### ISSUE TITLE
Publisher initialization with wrong videoSource/audioSource in Safari

### ISSUE THREAD

**Issue by soarer1004** [OpenVidu/openvidu#100]
In Safari `OpenVidu.initPublisher()` doesn't return any error if call it with wrong `videoSource`/`audioSource`.

This is due to the fact that `error.name` in Safari is always has value `Error`, and when in `Publisher.initialize`  [in switch/case block](https://github.com/OpenVidu/openvidu/blob/master/openvidu-browser/src/OpenVidu/Publisher.ts#L447) `error.name`  is no match any `case`, `errorCallback ` doesn't trigger.

**Comment by pabloFuente** [comment]
Already fixed in master branch (a75c3c194b4dc807726543dd795ca1ed9993a738)
