### ISSUE TITLE
The import org.kurento.client.GenericMediaElement cannot be resolved

### ISSUE THREAD

**Issue by ricardosnery** [OpenVidu/openvidu#101]
Hello, I'm trying to use the openvidu server and its code has the following error in some files The import org.kurento.client.GenericMediaElement can not be resolved.

I already tried to change the version of Kurento but none of them have this class, what can I do?

**Comment by pabloFuente** [comment]
Hi. You will have to use the development version of kurento-client dependency if you want to compile openvidu-server in the master branch right now.

Clone https://github.com/Kurento/kurento-java repository, compile and install locally every artifact of that repository and use it to compile openvidu-server.

**Comment by ricardosnery** [comment]
I got it here, the problem was that some repositories had not been downloaded completely, probably because of some internet connection problem.

I removed the .m2 / repository and forced the download of everything again, now it's no problem

Thank you!
