### ISSUE TITLE
Allow Fullscreen Sharing on Firefox

### ISSUE THREAD

**Issue by mserve** [OpenVidu/openvidu#103]
I am working on a desktop sharing only solution based on OpenVidu for BYOD scenarios in education. Application is following the NodeJS/MVC approach based on the openvidu-mvc-node example. I noticed that OpenVidu enforces use of the '**window**' mode in Firefox, while Chrome Extension also allows full screen. Some applications (as e.g. Visual Studio Code) are not properly shared in '**window**' mode, though.

It seems that the transformation of videoSource : '_screen_' => videoSource: '_window_' is hardcoded:  https://github.com/OpenVidu/openvidu/blob/b55faf831b769ea32599188f1e4169d9a0cd1c13/openvidu-browser/src/OpenViduInternal/ScreenSharing/Screen-Capturing.js#L112-L114
Changing this property gives full screen in Firefox (tested on FFx 62.0b16 x64 Win)

* One might expect that videoSource: 'screen' means 'screen' in terms of getUserMedia() - this could be stated somewhere in the docs more clearly
* IMHO, there could be the option to set both 'window' and 'screen' and transform the Chrome constraints as the user picks the source lateron anywhy. I noticed that this would require some more changes as the constraints are checked against 'screen' on some points

**Comment by mserve** [comment]
BTW: same in https://github.com/OpenVidu/openvidu/blob/b55faf831b769ea32599188f1e4169d9a0cd1c13/openvidu-browser/src/OpenViduInternal/ScreenSharing/Screen-Capturing-Auto.js#L40-L43 but those lines did not affect the behavior in my environment

**Comment by micaelgallego** [comment]
Hi @mserve, 
Good catch, can you provide a PR fixing the issue? Thanks!

**Comment by pabloFuente** [comment]
Hi,

Thanks for the PR, you are totally right. In the current version Firefox users cannot select the entire screen as a video source when screen-sharing. You're also right about the possibility of deciding wheter to share the entire screen or certain application window. We should discuss how this might fit in OpenVidu Browser API, as for Chrome this is much simpler as it allows to select any possible screen source from the same popup. Probably a quick fix would be adding a new value to `videoSource` property (https://openvidu.io/api/openvidu-browser/interfaces/publisherproperties.html#videosource), such as `"entire-screen-firefox"` or something like that. Not a very elegant solution, anyway.

**Comment by mserve** [comment]
Hi,

maybe using `videSource` values as proposed in the W3C draft would be the most consistent way (https://w3c.github.io/mediacapture-screen-share/) , esp. regarding Safari and Edge support of `getDisplayMedia`:


> * A **monitor** display surface represents a physical display. Some systems have multiple monitors, which can be identified separately. Multiple monitors might also be aggregated into as a single logical monitor. An aggregated display surface is captured as a single MediaStreamTrack.
> * A **window** display surface is a single contiguous surface that is used by a single application.
> * A single application might have several windows available to it, and those can be aggregated into a single **application** surface, representing all the windows available to that application and therefore presented as a single MediaStreamTrack.
> * A **browser** display surface is the rendered form of a single document. This is not strictly limited to HTML5 documents, though the discussion in this document will address some specific concerns with the capture of HTML.

Meanwhile, those values could be mapped to the values current browser understand.

**Comment by pabloFuente** [comment]
We will follow a similar approach to what you said. OpenVidu Browser will behave the same way it does now with Chrome, but if running on a different platform we will pass directly the string provided by the developer to the final media constraints applied to `getUserMedia`.

This will be available in the next release.

**Comment by pabloFuente** [comment]
This is already included in the development 'master' branch of OpenVidu/openvidu (openvidu-browser folder) with commit a52c4feb7123d991c32e79054527bde12718fe8a. After testing the different strings accepted by latest stable release of Firefox browser when asking for screen sharing permissions, you can now set as [`PublisherProperties.videoSource`](https://openvidu.io/api/openvidu-browser/interfaces/publisherproperties.html#videosource):
- `"screen"`: asks for entire screen permissions if browser detected is desktop Firefox. For Chrome the permission dialog allows selecting any application/tab/entire-screen as video source.
- `"window"`: asks for specific application window permissions if browser detected is desktop Firefox. For Chrome this string is treated as "deviceId" (https://openvidu.io/api/openvidu-browser/interfaces/device.html#deviceid)
- Other strings: treated as "deviceId" (https://openvidu.io/api/openvidu-browser/interfaces/device.html#deviceid)
