### ISSUE TITLE
Allow check for screensharing prerequisites

### ISSUE THREAD

**Issue by mserve** [OpenVidu/openvidu#104]
It would be good to have an API call similar to OpenVidu.checkSystemRequirements() to check if screen sharing is available, e.g. OpenVidu.chechScreensharingCapabilities() to know beforehand wether I can offer screen sharing in an app or not

I found that  window.getChromeExtensionStatus() is available globally as `window.getChromeExtensionStatus(function(cb) {console.log(cb)})`works when OpenVidu is loaded but that's rather an undocumented feature

**Comment by pabloFuente** [comment]
Already fixed in development 'master' branch of OpenVidu/openvidu (openvidu-browser folder) with commit e567d9c69a9d1060ce99ed296de149eb0f64fb0b
