### ISSUE TITLE
can't got kurento-6.7.2-SNAPSHOT jar

### ISSUE THREAD

**Issue by ancin** [OpenVidu/openvidu#106]
I cant got kurento jar, Is there  openvidu server to downlaod?
Thanks.

**Comment by DiegoSobarzo** [comment]
Same Here.
[ERROR] Failed to execute goal on project openvidu-server: Could not resolve dependencies for project io.openvidu:openvidu-server:jar:2.4.0: Failed to collect dependencies at org.kurento:kurento-jsonrpc-server:jar:6.7.2-SNAPSHOT: Failed to read artifact descriptor for org.kurento:kurento-jsonrpc-server:jar:6.7.2-SNAPSHOT: Could not transfer artifact org.kurento:kurento-jsonrpc-server:pom:6.7.2-SNAPSHOT from/to kurento-snapshots (https://maven.openvidu.io/archiva/repository/snapshots/): Failed to transfer file: https://maven.openvidu.io/archiva/repository/snapshots/org/kurento/kurento-jsonrpc-server/6.7.2-SNAPSHOT/kurento-jsonrpc-server-6.7.2-SNAPSHOT.pom. Return code is: 503 , ReasonPhrase:Service Unavailable.

**Comment by micaelgallego** [comment]
Right now master branch depends on the development branch of KurentoClient.

You can clone KurentoJava repository and compile yourself following these
instructions:

https://doc-kurento.readthedocs.io/en/6.6.2/mastering/kurento_development.html#kurento-java-client

But we recommend to you to use the latest stable OpenVidu tag to avoid
problems while the next OpenVidu version is in development.

**Comment by ancin** [comment]
I got the master branch code from Openvidu.

**Comment by DiegoSobarzo** [comment]
i'm working now with the lastest tag. 
Gracias Micael.

**Comment by cruizba** [comment]
See https://github.com/OpenVidu/openvidu/issues/677#issuecomment-1023229068 if you still facing issues on fetching SNAPSHOTS dependencies from maven.openvidu.io.
