### ISSUE TITLE
Issue in importing 'OpenVidu' from 'openvidu-browser' in a react-redux isomorphic app

### ISSUE THREAD

**Issue by talentedandrew** [OpenVidu/openvidu#11]
I'm getting this error 

> ReferenceError: window is not defined
    at Object.<anonymous> (/mern-starter/node_modules/openvidu-browser/ts/KurentoUtils/kurento-utils-js/WebRtcPeer.js:26:27)

I'm using v1.1.1

**Comment by micaelgallego** [comment]
You can't use openvidu-browser in a node app because it depends on libs
only available in browser.

If you want to use openvidu-browser in a isomorphic app, then you have to
disable it when you are in node environment and only use it in browser.

**Comment by talentedandrew** [comment]
Ok..but are you planning to provide a CDN for it in the near future?
