### ISSUE TITLE
Question about current openvidu-recording implementation

### ISSUE THREAD

**Issue by alexlapa** [OpenVidu/openvidu#113]
Current openvidu-recording seems to have some significant downsides:
1. Huge resource usage: since it creates separate ubuntu container+chrome+x11+ffmpeg for every recording.
2. Quality issues: network instability between Kurento and recording server will cause video quality degradation.

Why this implementation was chosen instead of using Kurento RecorderEndpoint API?

**Comment by micaelgallego** [comment]
We have implemented in that way because we can have a composite of all videocall streams with custom layouts.

But we have in our roadmap allow recording of individual streams using RecorderEndpoint. But we have a more issues/features in the roadmap...

**Comment by alexlapa** [comment]
@micaelgallego ,

That totally makes sense. 

Thank you for your answer.
