### ISSUE TITLE
openvidu-node-client(v2.4.0) - Error while Generate Token for existing session after disconnect.

### ISSUE THREAD

**Issue by maxifjaved** [OpenVidu/openvidu#115]
openvidu-node-client(v2.4.0) is throwing error while generating a new token for an existing session.  I re-installed the v2.3.0 and it is working fine.

**Comment by pabloFuente** [comment]
I have just tested openvidu-js-node tutorial doing so and cannot reproduce the problem.

Connected one user to a session called "Session 8", connected another user to the same session, disconnect the first user and rejoin the same session again. Works fine.

How can I reproduce this issue?

**Comment by oisnot** [comment]
To me it happens if you restart openvidu while not restarting node js while you are connected to the webserver and openvidu server. The problem is the node js internal session map, causeing you to join instead of creating a channel. 

Possible fixes are: 
A POST call when starting openvidu to Node JS. 
A POST call when videoconnection times out from openvidu to Node JS (not directly related but would be nice).

**Comment by pabloFuente** [comment]
Of course: developers are responsible of properly updating their collections on the application-server layer. REST API and Java/Node clients provide methods to retrieve the actual state of sessions in openvidu-server at any time.

If you restart openvidu-server, then of course any session in openvidu-server will be no longer available. And any information stored in your server-side application-layer will no longer be true. So:

a. If you plan to "support" in some way openvidu-server restart, then you'll have to clean up any session information in your app server when doing so.
b. You should always code your server side taking into account the possible abrupt disconnections of your clients. openvidu-server will automatically update its status after not receiving the expected ping from the user, but you must also update this info in your application server.

**Comment by oisnot** [comment]
I'm adding a session check every few seconds myself, as well as "if join fails try create before sending error". But it is a bug in the standard example code. 

And adding a callback to Node Js on events such as "openvidu server shutting down", "openvidu server started", "user timed out" would be helpfull.

**Comment by pabloFuente** [comment]
What sample code are you specifically refereing to when saying `But it is a bug in the standard example code.` ? Maybe one of node tutorials?

- https://github.com/OpenVidu/openvidu-tutorials/tree/master/openvidu-mvc-node
- https://github.com/OpenVidu/openvidu-tutorials/tree/master/openvidu-js-node

**Comment by oisnot** [comment]
Here: https://github.com/OpenVidu/openvidu-tutorials/blob/cb6c469ef93606ee52c7166c130c4b01c1a36cf1/openvidu-js-node/server.js#L135

This will fail if the only user times out of a channel on openvidu or openvidu is restarted but not node js, then you try to reconnect to the same channel name.

**Comment by pabloFuente** [comment]
This issue should be opened in openvidu-tutorials if as it seems it belongs to one of the node tutorials. Can be opened there if someone notices a similar issue with latest versions of OpenVidu
