### ISSUE TITLE
Problems about reconnecting.

### ISSUE THREAD

**Issue by willylee007** [OpenVidu/openvidu#118]
Hello, I'm back again.

Probelems: I found a problem is in the process of test, openvidu can restore the reconnection in disconnecting for 10 seconds and successful show, but cannot restore the reconnection after more than 10s and session can receive "networkDisconnect" event in about 15s, so we plan to accept by networkDisconnect events manually to attempt to rejoin. But there is a problem is, when users connected to the network in 10 seconds to 15 seconds again(It was disconnected at first), we can't get the networkDisconnect event, so it's embarrassing. We can't reconnect in this period and we can't get the disconnected event.(I tested it by plugging and unplugging the cable😄)

Expect: Able to restore video between 10 and 15 seconds, able to receive network disconnection events in 15 seconds.

Thanks. Best regards!

**Comment by tibinvpaul** [comment]
Hey @pabloFuente - I am having a similar issue and came across this thread. Could you please explain the desired functionality after a network glitch (disconnect and connect) in between a video session? I observed that the JS client successfully restores the connection if the internet comes back in a few seconds. But sometimes, I get the below log in the console.

![image](https://user-images.githubusercontent.com/2771721/65821043-06beba00-e24e-11e9-89c7-53b31b1d64b8.png)

There is a text `Recovered connection in Session osg7eynmsjc4fb9p` in the console, but the videos are not restored and stuck. There are no `sessionDisconnected` or `connectionDestroyed` events too. 

Could you help me understand this scenario?

Thanks.

**Comment by perk11** [comment]
Also experiencing this The existing videos are stuck after reconnection. New videos work. Expected scenario would be for existing videos to work as well.

**Comment by micaelgallego** [comment]
In the current OpenVidu version reconnection in case of network problem should be managed by the application. We plan to implement more automated recovery in the future in openvidu-browser and openvidu-server.

**Comment by perk11** [comment]
Do you have a suggestion on how can the application manage the reconnection? `connectionRecovered` event that happens automatically when openvidu-browser recovers the connection and which leads to this issue is commented out in openvidu-browser currently. How could the application listen to connection errors?

**Comment by pabloFuente** [comment]
https://docs.openvidu.io/en/stable/advanced-features/automatic-reconnection/
