### ISSUE TITLE
Remote audio is not recording within KURENTO composite recorder 

### ISSUE THREAD

**Issue by ajay01994** [OpenVidu/openvidu#119]
Hi all
i was trying to implement Kurento composite recorder to achieve one to one video call where each of the client sees own video and the remote video and not as the combination of both videos as in case of composite recorder .Can you please tell us how open vidu has done recording using Kurento 
Thank you ..

**Comment by pabloFuente** [comment]
Exactly. Lately seems like a pretty common approach for other SFU technologies. For example, Jitsi recording also works like this: https://github.com/jitsi/jibri

**Comment by pabloFuente** [comment]
The container in charge of recording can be found here: https://github.com/OpenVidu/openvidu/tree/master/openvidu-server/docker/openvidu-recording

**Comment by ajay01994** [comment]
I have executed the below code with ffmpeg to create an output with two input videos side by side and their audio combined.

ffmpeg -i video1.mp4 -i video2.mp4 -filter_complex "[0:v][1:v] hstack=inputs=2[v]; [0:a][1:a] amerge [a]" -map "[v]" -map "[a]" -ac 2 -shortest output.mp4
Can you please tell me what is it's equivalent code in fluent-ffmpeg used in nodejs?

**Comment by pabloFuente** [comment]
I'm sorry, I'm not an expert in fluent-ffmpeg.
