### ISSUE TITLE
one way broadcasting 

### ISSUE THREAD

**Issue by quickstreamingmedia** [OpenVidu/openvidu#12]
one2many forward stream to wowza

**Comment by pabloFuente** [comment]
I'll need more info. What behaviour do you want/expect in your one2many scenario?

**Comment by quickstreamingmedia** [comment]
1 broadcaster and n number of viewers so to make it scale I want to create sdp and stream that to wowza or any media server

**Comment by micaelgallego** [comment]
This is not possible right now with OpenVidu. To have this fine control it
is necessary to fork OpenVidu project or create a custom application based
on Kurento Media Server.

Un saludo.

Micael Gallego
ElasTest Project Technical Coordinator - http://elastest.io
Profesor en la Escuela Técnica Superior de Ingeniería Informática URJC

**Comment by quickstreamingmedia** [comment]
i have a application based on kurento already and its working fine i want to implement that on openvidu

**Comment by micaelgallego** [comment]
Cool!
OpenVidu codebase is a bit mesh right now. We plan to refactor it shortly and create a good developer documentation. Maybe you can wait some weeks for that refactoring and dev documentation to integrate your working code on OpenVidu. 

Or, if you are hurry, you can start digging into OpenVidu code right know to integrate your working code.

I am woing to repoing the issue again to track your progress

**Comment by quickstreamingmedia** [comment]
https://github.com/godka/kurento-rtmp

here is the repo that i contribute code to openvidu tutorials made easy to make rooms etc i want to implement above senario in openvidu. just i want to know how to get sdp from openvidu session so i can implement rest

**Comment by micaelgallego** [comment]
I've see that your code is node.js. OpenVidu server is implemented in Java. Can you document your code in a high level way? I think that we can port your code to OpenVidu very easily.

**Comment by quickstreamingmedia** [comment]
i have dont have any high level document but i can explain you flow
after loading video it will create a sdp offer that sdp file will be stored in root
and then socket io triggers there is a file 
then start ffmpeg child process to stream to media server

i hope above is useful

**Comment by quickstreamingmedia** [comment]
@pabloFuente @micaelgallego @nordri @gortazar @j1elo  need help in getting sdp from session please let me know

**Comment by quickstreamingmedia** [comment]
[Browser] -> WebrtcEndpoint -> [Kurento] -> RtpEndpoint -> 
[FFmpeg] -> RTMP -> [Node_Media_Server(srs)] -> RTMP -> [Browser]

**Comment by quickstreamingmedia** [comment]
am waiting for update from your team

**Comment by micaelgallego** [comment]
Hi @quickstreamingmedia, 
as you know, OpenVidu allows to create rooms with several members sending and receiving media. Do you plan to send to RTMP the media of all members publishing media? In that case, you will need to create one RtpEndpoint per member in addition to all WebRtpEndpoints created right now. 

For that reason, it is not only to know "how to get the session SDP". It is needed to modify the OpenVidu server source code.

We don't have time right now to implement that feature, but if you want, we can help you to develop it.

**Comment by quickstreamingmedia** [comment]
i need only single broadcaster in room and rest all viewers. so help me for same

**Comment by quickstreamingmedia** [comment]
1 month finished no update from team

**Comment by micaelgallego** [comment]
If you want to implement that feature, please feel free to fork the project and make the needed modifications. We are focused in other things right now and we can't implement this feature for you right now.

**Comment by pavelmena** [comment]
Is there any good new about this?

**Comment by micaelgallego** [comment]
You can implement it by yourself forking OpenVidu or implementing a new app from scratch based on Kurento
