### ISSUE TITLE
Integrate with react-native

### ISSUE THREAD

**Issue by randymuhroji** [OpenVidu/openvidu#120]
HI. 
is it possible openvidu to integrated with react-native?

**Comment by pabloFuente** [comment]
Hi. Next release, coming in a few days, will bring react support, including a very simple React tutorial.

Stay tuned.

**Comment by micaelgallego** [comment]
We plan to add react-native support in the following weeks, just after ionic support.

Regards


[cid:82add23a-83e6-4e47-93b8-c1d531192939]

Micael Gallego Carrillo
Escuela Técnica Superior de Ingeniería Informática (ETSII)
Universidad Rey Juan Carlos
Campus de Móstoles, Madrid (España)
Teléfono: +34 91 488 8065

micael.gallego@urjc.es<mailto:micael.gallego@urjc.es> | https://gestion2.urjc.es/pdi/ver/micael.gallego | @Micael_Gallego<https://twitter.com/Micael_Gallego>






On Sun, Sep 23, 2018 at 1:55 PM Pablo Fuente Pérez <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi. Next release, coming in a few days, will bring react support, including a very simple React tutorial.

Stay tuned.

**Comment by randymuhroji** [comment]
I can publish video from react native using [react native webrtc](https://github.com/oney/react-native-webrtc) but I failed to receive videos from the web using openvidu.

https://github.com/randymuhroji/react-native-webrtc-openvidu

**Comment by zipPeak** [comment]
Hello
we are waiting for it 👍 
Thank you

**Comment by pabloFuente** [comment]
React Native is now supported by OpenVidu 2.10.0. It is not part of OpenVidu open source stack though, so developers interested in React Native support should contact OpenVidu team through official [Commercial page](https://openvidu.io/commercial)
