### ISSUE TITLE
docker openvidu 2.4.0

### ISSUE THREAD

**Issue by DiegoSobarzo** [OpenVidu/openvidu#124]
Hello
is it possible to  work with docker openvidu-server-kms 2.4.0 after the update to 2.5.0?
![image](https://user-images.githubusercontent.com/27924849/46295051-78125100-c597-11e8-8b01-0de708d1eec6.png)

**Comment by pabloFuente** [comment]
Hi,

We are still in the middle of the release. We will be offically publishing the release notes and the offical post for the new version today.

Regarding your question, I don't quite understand what you mean. That output you have attached corresponds to OpenVidu Server 2.5.0. The only update you must perform after updating OpenVidu Server is upgrading **openvidu-browser** library to version 2.5.0.

**Comment by DiegoSobarzo** [comment]
i was working with OV java client and i got errors with docker OV server kms  because of the different versions. i was asking if its posible to work with docker OV server 2.4.0.
if you are in the middle of the release i'll wait till is complete.
thank you for your quick response.
issue closed.
