### ISSUE TITLE
Filters not working

### ISSUE THREAD

**Issue by miguelrcDEV** [OpenVidu/openvidu#125]
Hi! I'm trying the new filters feature that you added recently to openvidu.
First of all, I have a node server with a react client. So I updated openvidu-browser and openvidu-node-client, both to 2.5.0 . Also y updated the openvidu-server+kms docker image to 2.5.0.

I try to apply filter in two ways, but both failed. I attach error screenshots.

- Apply filters to initPublisher options like:
```
filter: {
    type: "GStreamerFilter",
    options: "videoflip method=vertical-flip"
}
```
Error in client console:
![error1](https://user-images.githubusercontent.com/17248343/46417543-3239c200-c72a-11e8-87b6-647c5924d17b.png)

        
- Apply filters dinamically:
```
publisher.stream.applyFilter("FaceOverlayFilter").then(filter => {
                    filter.execMethod(
                        "setOverlayedImage",
                        {
                            "uri":"https://cdn.pixabay.com/photo/2013/07/12/14/14/derby-148046_960_720.png",
                            "offsetXPercent":"-0.2F",
                            "offsetYPercent":"-0.8F",
                            "widthPercent":"1.3F",
                            "heightPercent":"1.0F"
                        });
});
```
Error in client console:
![error2](https://user-images.githubusercontent.com/17248343/46417592-50072700-c72a-11e8-8ea2-2b3e32e1ed11.png)

        
Any idea?

**Comment by pabloFuente** [comment]
Hi!

First of all, you can use as a starting sample application our openvidu-filters tutorial: https://github.com/OpenVidu/openvidu-tutorials/tree/master/openvidu-filters

Instructions to run it are available at the README.md file in that location

Also, second browser log error is telling me that your openvidu-server and openvidu-browser versions are not really 2.5.0. Remember to force the `pull` of openvidu-server container like this before launching it:

`docker pull openvidu/openvidu-server-kms`

And if you are sure you have already version 2.5.0 of openvidu-server-kms docker container, the force a cache cleaned up in your browser, since previous static files could be still serving a lower version of openvidu-brwoser library.

**Comment by miguelrcDEV** [comment]
I force pull of docker image, and checked that the openvidu-server-kms is in v2.5.0. Also checked that the openvidu-browser and openvidu-node-client was in v2.5.0. Opened my client from private navigation tab for avoid cache, and still getting same error. Maybe is the openvidu-browser npm package not built correctly? I have donwloaded openviodu main repo and did `npm run build` on openvidu-browser dir, giving a lot of typescript errors:

![image](https://user-images.githubusercontent.com/17248343/46458079-df591c80-c7b4-11e8-930d-0da49c96252e.png)

¿Could you check this?

**Comment by pabloFuente** [comment]
Hi,

First of all, which version of `npm` do you have installed? OpenVidu NPM libraries are using **node v8.12.0** and the latest release **npm 6.4.1**.

That said, if you run:

```
git clone https://github.com/OpenVidu/openvidu.git
cd openvidu/openvidu-browser
npm install
npm run build
```

openvidu-browser should build OK. Have you tried running  openvidu-filters tutorial?

Regards

**Comment by miguelrcDEV** [comment]
Yep, I try again to build openvidu-browser, but this time I removed first the /lib dir. Then run `npm run build` and this time works. Sorry, was my fault.

I tried openvidu-filters tutorial, and it works, but my project still giving the same errors.
I'll try the openvidu-filters tutorial pointing to my production openvidu-server-kms docker image to check if it fails.I'll keep you informed.

Thanks Pablo.

**Comment by miguelrcDEV** [comment]
Point your openvidu-filter tutorial to my openvidu-server-kms docker image works. So the problem is in openvidu-node-client or in openvidu-browser of my project. But, I'm sure the version is 2.5.0 in both. It's frustrating...

Thank you again Pablo

**Comment by pabloFuente** [comment]
Try deleting any node-modules folder and package-lock.json file of your tutorial.

The run again `npm install` and relaunch the app.

**Comment by miguelrcDEV** [comment]
Thanks, solved removing *-lock.json files.
