### ISSUE TITLE
NullPointer FetchAll

### ISSUE THREAD

**Issue by DiegoSobarzo** [OpenVidu/openvidu#126]
Hello i'm having an issue fetching session info.
response from openvidu server is ok (200).
![image](https://user-images.githubusercontent.com/27924849/46462091-bc346a00-c7c0-11e8-9183-a5cf072a9470.png)

i was able to debug till line 543 in OpenVidu.class fails inside "OpenVidu.activeSessions.computeIfAbsent".
![image](https://user-images.githubusercontent.com/27924849/46462029-94dd9d00-c7c0-11e8-94c7-8bf43da4fb6a.png)

console error in tutorial is this.
![image](https://user-images.githubusercontent.com/27924849/46462103-cb1b1c80-c7c0-11e8-90f3-f2a26f1dcd72.png)

**Comment by pabloFuente** [comment]
Hi. Can you please execute these exact commands to run **openvidu-recording-java** tutorial? (Note that the Docker container launched will not work for actual recording feature. See the end of this message to a complete `docker run` command that includes every necessary property to get this tutorial working with recording feature)

```
docker pull openvidu/openvidu-server-kms:2.5.0
docker run --rm -d -p 4443:4443 -e openvidu.secret=MY_SECRET openvidu/openvidu-server-kms:2.5.0
git clone https://github.com/OpenVidu/openvidu-tutorials.git
cd openvidu-tutorials/openvidu-recording-java/
mvn package exec:java
```

At [https://localhost:5000](https://localhost:5000) you should be able to join a session and fetch info without a problem. This issue could be caused by a bug in a first version of the openvidu-server-kms that was overwritten a few minutes later in DockerHub.

PS: to launch `openvidu/openvidu-server-kms:2.5.0` container with recording capabilities, do it like this:

```
docker run -p 4443:4443 --rm \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /PATH/TO/VIDEO/FILES:/PATH/TO/VIDEO/FILES \
    -e openvidu.recording=true \
    -e MY_UID=$(id -u $USER) \
    -e openvidu.recording.path=/PATH/TO/VIDEO/FILES \
    -e openvidu.recording.public-access=true \
    -e openvidu.secret=MY_SECRET \
openvidu/openvidu-server-kms:2.5.0
```

**Comment by DiegoSobarzo** [comment]
Hi Pablo.
I'm runnin the latest tutorial version.

> mvn package exec:java

 i'm running docker with my own self-signed certificate like this:
> docker run -p 4443:4443 --rm -v /var/run/docker.sock:/var/run/docker.sock -v /D/videos:/D/videos -v 
 /D/dasobarzo.jks:/D/dasobarzo.jks:ro -e openvidu.recording=true -e openvidu.recording.path=/D/videos -e openvidu.recording.public-access=true -e openvidu.publicurl=https://dasobarzo:4443 -e openvidu.secret=MY_SECRET -e server.ssl.key-store=/D/dasobarzo.jks -e server.ssl.key-store-password=XXXX-e server.ssl.key-alias=dasobarzo openvidu/openvidu-server-kms

 i'm able to join a session and start a recording.
![image](https://user-images.githubusercontent.com/27924849/46466182-df641700-c7ca-11e8-8158-fe4d5393f154.png)

the problem comes when i try to fetch info from all sessions.
here is the trace from tutorial console.

>  Fetching all session info
> 2018-10-04 11:44:44.860 ERROR 15624 --- [io-5000-exec-10] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.NullPointerException] with root cause
> 
> java.lang.NullPointerException: null
>         at io.openvidu.java.client.Session.lambda$null$1(Session.java:532) ~[openvidu-java-client-2.5.0.jar:na]
>         at java.util.ArrayList.forEach(ArrayList.java:1257) ~[na:1.8.0_161]
>         at io.openvidu.java.client.Session.lambda$resetSessionWithJson$3(Session.java:529) ~[openvidu-java-client-2.5.0.jar:na]
>         at java.util.ArrayList.forEach(ArrayList.java:1257) ~[na:1.8.0_161]
>         at io.openvidu.java.client.Session.resetSessionWithJson(Session.java:524) ~[openvidu-java-client-2.5.0.jar:na]
>         at io.openvidu.java.client.OpenVidu.lambda$null$1(OpenVidu.java:536) ~[openvidu-java-client-2.5.0.jar:na]
>         at java.util.concurrent.ConcurrentHashMap.computeIfPresent(ConcurrentHashMap.java:1769) ~[na:1.8.0_161]
>         at io.openvidu.java.client.OpenVidu.lambda$fetch$3(OpenVidu.java:534) ~[openvidu-java-client-2.5.0.jar:na]
>         at java.util.ArrayList.forEach(ArrayList.java:1257) ~[na:1.8.0_161]
>         at io.openvidu.java.client.OpenVidu.fetch(OpenVidu.java:531) ~[openvidu-java-client-2.5.0.jar:na]
>         at io.openvidu.recording.java.MyRestController.fetchAll(MyRestController.java:216) ~[classes/:na]
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_161]
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_161]
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_161]
>         at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_161]
>         at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221) ~[spring-web-4.3.3.RELEASE.jar:4.3.3.RELEASE]
>         at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136) ~[spring-web-4.3.3.RELEASE.jar:4.3.3.RELEASE]
>         at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:114) ~[spring-webmvc-4.3.3.RELEASE.jar:4.3.3.RELEASE]
>         at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827) ~[spring-webmvc-4.3.3.RELEASE.jar:4.3.3.RELEASE]
>         at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738) ~[spring-webmvc-4.3.3.RELEASE.jar:4.3.3.RELEASE]
>         at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85) ~[spring-webmvc-4.3.3.RELEASE.jar:4.3.3.RELEASE]
>         at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963) ~[spring-webmvc-4.3.3.RELEASE.jar:4.3.3.RELEASE]
>         at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897) ~[spring-webmvc-4.3.3.RELEASE.jar:4.3.3.RELEASE]
>         at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) ~[spring-webmvc-4.3.3.RELEASE.jar:4.3.3.RELEASE]
>         at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861) ~[spring-webmvc-4.3.3.RELEASE.jar:4.3.3.RELEASE]
>         at javax.servlet.http.HttpServlet.service(HttpServlet.java:622) ~[tomcat-embed-core-8.5.5.jar:8.5.5]
>         at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846) ~[spring-webmvc-4.3.3.RELEASE.jar:4.3.3.RELEASE]
>         at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) ~[tomcat-embed-core-8.5.5.jar:8.5.5]
>         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230) ~[tomcat-embed-core-8.5.5.jar:8.5.5]
>         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) ~[tomcat-embed-core-8.5.5.jar:8.5.5]
>         at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) ~[tomcat-embed-websocket-8.5.5.jar:8.5.5]
>         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) ~[tomcat-embed-core-8.5.5.jar:8.5.5]
>         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) ~[tomcat-embed-core-8.5.5.jar:8.5.5]
>         at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99) ~[spring-web-4.3.3.RELEASE.jar:4.3.3.RELEASE]
>         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.3.RELEASE.jar:4.3.3.RELEASE]
>         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) ~[tomcat-embed-core-8.5.5.jar:8.5.5]
>         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) ~[tomcat-embed-core-8.5.5.jar:8.5.5]
>         at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:89) ~[spring-web-4.3.3.RELEASE.jar:4.3.3.RELEASE]
>         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.3.RELEASE.jar:4.3.3.RELEASE]
>         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) ~[tomcat-embed-core-8.5.5.jar:8.5.5]
>         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) ~[tomcat-embed-core-8.5.5.jar:8.5.5]
>         at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:77) ~[spring-web-4.3.3.RELEASE.jar:4.3.3.RELEASE]
>         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.3.RELEASE.jar:4.3.3.RELEASE]
>         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) ~[tomcat-embed-core-8.5.5.jar:8.5.5]
>         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) ~[tomcat-embed-core-8.5.5.jar:8.5.5]
>         at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197) ~[spring-web-4.3.3.RELEASE.jar:4.3.3.RELEASE]
>         at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-4.3.3.RELEASE.jar:4.3.3.RELEASE]
>         at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192) ~[tomcat-embed-core-8.5.5.jar:8.5.5]
>         at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165) ~[tomcat-embed-core-8.5.5.jar:8.5.5]
>         at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198) ~[tomcat-embed-core-8.5.5.jar:8.5.5]
>         at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:108) [tomcat-embed-core-8.5.5.jar:8.5.5]
>         at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472) [tomcat-embed-core-8.5.5.jar:8.5.5]
>         at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140) [tomcat-embed-core-8.5.5.jar:8.5.5]
>         at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [tomcat-embed-core-8.5.5.jar:8.5.5]
>         at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) [tomcat-embed-core-8.5.5.jar:8.5.5]
>         at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349) [tomcat-embed-core-8.5.5.jar:8.5.5]
>         at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:784) [tomcat-embed-core-8.5.5.jar:8.5.5]
>         at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-8.5.5.jar:8.5.5]
>         at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:802) [tomcat-embed-core-8.5.5.jar:8.5.5]
>         at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1410) [tomcat-embed-core-8.5.5.jar:8.5.5]
>         at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-8.5.5.jar:8.5.5]
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_161]
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_161]
>         at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-8.5.5.jar:8.5.5]
>         at java.lang.Thread.run(Thread.java:748) [na:1.8.0_161]

thanks yor your quick response.

**Comment by pabloFuente** [comment]
Do this: `docker pull openvidu/openvidu-server-kms:2.5.0`

**Comment by DiegoSobarzo** [comment]
the image is up to date.
![image](https://user-images.githubusercontent.com/27924849/46467016-0a4f6a80-c7cd-11e8-996d-2737bb044c9a.png)

**Comment by DiegoSobarzo** [comment]
Hi, the problem was solved resetting docker to factory defaults.
now works well.
thank you.
