### ISSUE TITLE
Is there any ways for my backend to know whether a user has leave the session from OpenVidu Server?

### ISSUE THREAD

**Issue by zzzykf** [OpenVidu/openvidu#128]
I'm implementing an android app with openvidu server and my own backend. 
My situation is that, if the user kills the app without proper exit, my backend wouldn't know the user already exits the session (If the user exits the app in a proper way, the app will send a http request to my backend on leaving session). 
So my question is, how can my backend knows the user already exit the session without the app sending a http request to my backend?

**Comment by pabloFuente** [comment]
Right now OpenVidu doesn't have a proper backend event dispatcher. This is a feature already present in our roadmap. What you can do right now is to consult the session status whenever you want by calling REST API or by using openvidu-java-client or openvidu-node-client. Check https://openvidu.io/docs/reference-docs/REST-API/#get-apisessionssession_id

**Comment by zzzykf** [comment]
Thank you for your reply sir.
