### ISSUE TITLE
Test connection doesnot work for installation done with cloudformation on ec2

### ISSUE THREAD

**Issue by philajay** [OpenVidu/openvidu#130]
I followed the steps from [here](https://openvidu.io/docs/deployment/deploying-aws/). However when I run the test connection on the frontend(chrome) the spinner keeps on looping and server events tab has following enteries

`ICE CANDIDATE SELECTED (mjoce493yzlgmdeq_CAMERA_VLYWB): LOCAL CANDIDATE: candidate:13 1 UDP 1677722111 34.214.73.82 7737 typ srflx raddr 172.31.45.61 rport 7737 | REMOTE CANDIDATE: candidate:remote-1 1 UDP 1853824767 204.193.63.11 33588 typ prflx | TIMESTAMP: 1540370391627

ICE CANDIDATE SELECTED (mjoce493yzlgmdeq_CAMERA_VLYWB): LOCAL CANDIDATE: candidate:4 1 UDP 2013266431 172.17.0.1 39175 typ host | REMOTE CANDIDATE: candidate:remote-1 1 UDP 1853824767 204.193.63.11 33588 typ prflx | TIMESTAMP: 1540370391676`

Inside chrome://webrtc-Internals icegatheringstatechage shows "complete". I can see the active connection with following details
`

timestamp | 10/24/2018, 2:13:15 PM
-- | --
googActiveConnection | true
bytesReceived | 0
bytesSent | 0
packetsSent | 0
googReadable | true
requestsSent | 85
consentRequestsSent | 1
responsesSent | 4
requestsReceived | 4
responsesReceived | 85
googChannelId | Channel-audio-1
googLocalAddress | 204.193.63.11:33588
localCandidateId | Cand-iH6xvwC0
googLocalCandidateType | prflx
googRemoteAddress | 34.214.73.82:7737
remoteCandidateId | Cand-1M6wcWx1
googRemoteCandidateType | stun
googRtt | 347
packetsDiscardedOnSend | 0
googTransportType | udp
googWritable | true
`

There are no bytes being sent.   Any suggestion as to why this might be happening?

Thanks in advance.

**Comment by pabloFuente** [comment]
This can be related to an issue recently discovered and manifested, that is causing some troubles for clients behind certain types of firewalls when installing Docker in the same machine as OpenVidu (an AWS deployment does for the purpose of recording).

Today or tomorrow we'll be releasing a new version with this issue in mind, so you will be able to test if it does in fact fix the problem.

**Comment by philajay** [comment]
@pabloFuente Thank you very much for the replay. I was wondering how would I come to know about the fix?

**Comment by pabloFuente** [comment]
Will be available in a a few minutes/hours. I will comment and close every GitHub issue or Google Group message related to it.

**Comment by pabloFuente** [comment]
Okey, the fix has been integrated.

You can redeploy OpenVidu exactly the same way, following this guide: https://openvidu.io/docs/deployment/deploying-aws/

Tell us if your problem has been solved when you do so, please.

Regards

**Comment by philajay** [comment]
I tried it twice and now it works
