### ISSUE TITLE
Is it possible to get a LAN - INTERNET video ROOM  where KURENTO Media Server serves as gateway ?

### ISSUE THREAD

**Issue by cuban0** [OpenVidu/openvidu#133]
Hello, i'm new to OpenVIDU and my special needing is to create a Video ROOM (2 participants only) where first client is on the internet, and the other is on a LAN without internet access, as far as i know CHROME + PROXY  will not work for the media streaming as it is UDP, my OpenVIDU version is 2.4 and the host server Ubuntu 16 has 2 eth cards (1 internet + 1 LAN)

Any ideas on this setup ?

Thanks

**Comment by micaelgallego** [comment]
It is difficult to say without spending time tweaking things and testing ideas... 

Definitely is not a tested scenario.
