### ISSUE TITLE
The recorder shows the mouse cursor in the middle of the recorded screen

### ISSUE THREAD

**Issue by slabajo** [OpenVidu/openvidu#138]
When you use the recorder functionality, the mouse cursor is shown in the center of the recorded video.

According to this https://superuser.com/questions/1194076/xvfb-with-nocursor-shows-cursor-anyway/1195409 it seems to be a problem of the X11grab that ffmpeg uses and it should be easily solved by adding the -draw_mouse 0 parameter to the ffmpeg command before the -i parameter.

It is not a big problem, but for some production functionality it may be a Little annoying

**Comment by pabloFuente** [comment]
Hi,

Are you making use of custom recordong layout functionality? Time ago we solved this problem by simply setting a css class in the default recording layout that hid the cursor.

But the solution you linked is a lot better. We'll try to incoporate it.

Best regards

**Comment by pabloFuente** [comment]
I've tried the solution you posted and it actually works. Next OpenVidu release will bring this fix to recording container.

**Comment by pabloFuente** [comment]
2.7.0 fixes this problem
