### ISSUE TITLE
I encountered some problems during the test recording process.

### ISSUE THREAD

**Issue by WhitePi** [OpenVidu/openvidu#140]
When I called star recording API（'api/recording/start',）, it returned 400 error.  
    Has sessionId changed? Here are some logs I have recorded.

![login](https://user-images.githubusercontent.com/26297347/48110783-12e20780-e289-11e8-947b-5261b41f1bf4.png)

![join-session](https://user-images.githubusercontent.com/26297347/48110787-1b3a4280-e289-11e8-89a8-55866ed5a078.png)

![record-log](https://user-images.githubusercontent.com/26297347/48110793-1f666000-e289-11e8-8c19-7d0482e4e749.png)

**Comment by pabloFuente** [comment]
Check HTTPResponses section of this POST operation in docs: 
https://openvidu.io/docs/reference-docs/REST-API/#post-apirecordingsstart

`400: the session has no connected participants`

You can only start the recording of a session when at least one participant is connected to it.

**Comment by WhitePi** [comment]
There are three participants in SessionA, but I still have 400 error.

![image](https://user-images.githubusercontent.com/26297347/48117037-d7543700-e2a2-11e8-8188-d660a1d44e38.png)

**Comment by pabloFuente** [comment]
Okey, you are using openvidu-recording-java tutorial. So the 400 error is the one returned by the Java app, not by OpenVidu server.

I see a `409` warning in your browser's console. That means your session is already being recorded. Try `docker ps` to see the recording containers you have actually up and running.

**Comment by pabloFuente** [comment]
In fact you can see in the session information JSON of the tutorial that property `recording` is true. That's in your image above.

You cannot start twice the recording of a session at the same time.

**Comment by WhitePi** [comment]
Yes, it is already recording.

![image](https://user-images.githubusercontent.com/26297347/48117474-4f6f2c80-e2a4-11e8-89f8-b73ccf466da7.png)

Because of the first 400 errors, it did not return recordingId, so I could not stop it directly through the api. Also, I stopped the container manually, but there were no files under the original directory / opt / openvidu / recordings, which were in the recorded container.

![image](https://user-images.githubusercontent.com/26297347/48117758-2602d080-e2a5-11e8-967f-ae450447f419.png)

![image](https://user-images.githubusercontent.com/26297347/48117801-416ddb80-e2a5-11e8-9ae6-b4dd92da3c6f.png)

**Comment by pabloFuente** [comment]
So you are using container openvidu/openvidu-server-kms. What's the specific command you used to run it?

**Comment by WhitePi** [comment]
docker run -p 4443:4443 -d --rm \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /var/docker_data/openvidu/video:/opt/openvidu/recordings \
    -e openvidu.recording=true \
    -e openvidu.recording.public-access=true \
	-e MY_UID=$(id -u $USER) \
	-e openvidu.secret=MY_SECRET \
	-e openvidu.publicurl=https://192.168.0.92:4443/ \
	--name openvidu-kms \
openvidu/openvidu-server-kms

**Comment by pabloFuente** [comment]
I have tried your command exactly the way you run it and the problem I see is option
`-v /var/docker_data/openvidu/video:/opt/openvidu/recordings`

First of all, try setting the same path in both your host and your recording containers:

`-v /var/docker_data/openvidu/video:/var/docker_data/openvidu/video`

And secondly, you missed property `-e openvidu.recording.path=/var/docker_data/openvidu/video` (see https://openvidu.io/docs/advanced-features/recording/#for-openvidu-server-docker-image)

Should work OK then. Be sure to remove any remaining recording container before running openvidu/openvidu-server-kms again.

**Comment by WhitePi** [comment]
Thanks very much！It can work！

![image](https://user-images.githubusercontent.com/26297347/48122375-556c0a00-e2b2-11e8-8644-54a74c427c53.png)

![image](https://user-images.githubusercontent.com/26297347/48122459-8fd5a700-e2b2-11e8-9a1a-6efa8125abe1.png)

I was careless.

Thank you again.

**Comment by adyasasingh5** [comment]
Can this code be run for ionic app and please help to set this path -v /PATH/TO/VIDEO/FILES:/PATH/TO/VIDEO/FILES
