### ISSUE TITLE
Problems with openvidu-browser in own development

### ISSUE THREAD

**Issue by AlexStreaming** [OpenVidu/openvidu#141]
I'm trying to make some changes in openvidu-browser. For this I downloaded the complete openvidu project in local and I have included the openvidu-browser directory in my project. Once in my project I have executed "npm install" and "npm build", this second command gives me errors. To solve this problem, I modified the "package.json" file by editing the line "@ types / node": "10.12.0" to "@ types / node": "10.1.4". Once solved, I have tried several things, to execute my project directly, to execute "npm link" and then launch the project, but in all cases, and once I launch my project, I get errors. The first of them 

> ./src/vendor/openvidu-browser/lib/OpenViduInternal/ScreenSharing/Screen-Capturing-Auto.js Line 104: 'getScreenId' is not defined no-undef
>   Line 157: 'getScreenId' is not defined no-undef
> Search for the keywords to learn more about each error. 

Modifying the file I can solve the problem, and when launching again, I get another problem, and so problem after problem.

Is there something I'm doing wrong?

**Comment by micaelgallego** [comment]
As openvidu-browser is implemented in TypeScript you need to have TS configured in your project exactly as it is configured in openvidu-browser (version, tsconfig, etc...).

Maybe is easier to put your own code in openvidu-browser project or use npmlink against cloned openvidu-browser project.

**Comment by pabloFuente** [comment]
To clone, modify and compile openvidu-browser library in your development machine you should simply follow steps here stated: https://openvidu.io/docs/developing/
