### ISSUE TITLE
Can I change the audio quality of the recording?

### ISSUE THREAD

**Issue by bullsEye1** [OpenVidu/openvidu#143]
From the server side these are the parameters which we can specify for configuration when recording
	envs.add("URL=" + layoutUrl);
	envs.add("RESOLUTION=1920x1080");
	envs.add("FRAMERATE=30");
	envs.add("VIDEO_ID=" + recordingId);
	envs.add("VIDEO_NAME=" + properties.name());
	envs.add("VIDEO_FORMAT=mp4");
	envs.add("USER_ID=" + uid);
        envs.add("RECORDING_JSON=" + recording.toJson().toString())

Can I set the audio quality as well for the recording. (eg  : 44KHz) ?
If not in theses params where should I look into to customize the audio quality

**Comment by pabloFuente** [comment]
To do so you would need to modify [this line](https://github.com/OpenVidu/openvidu/blob/master/openvidu-server/docker/openvidu-recording/entrypoint.sh#L104) of openvidu-recording entrypoint script, adding something like:

```
-b:a 44k
```

to specify other audio bitrate than default. This will require you to build `openvidu/openvidu-recording` image, of course, and setting openvidu-server to use it (you can simply tag your own container with a custom TAG, and then launch openvidu-server with option `-Dopenvidu.recording.version=YOUR_TAG`

Default current options when recording a session are the following:

![selection_422](https://user-images.githubusercontent.com/15049534/48427819-ec7d0a00-e769-11e8-8d36-c8045daccba9.png)
