### ISSUE TITLE
Open Vidu remote streaming does not work on Safari

### ISSUE THREAD

**Issue by bullsEye1** [OpenVidu/openvidu#144]
I think Safari has support for WebRtc but still
I can not get the remote stream on Safari.
Working fine in Chrome
There are no error logs on the console as well when using Safari.

**Comment by micaelgallego** [comment]
Safari is not still supported in OpenVidu. 

We will work on it soon. We expect full support in the following weeks.

**Comment by bullsEye1** [comment]
Okay thanks a lot :)

**Comment by pabloFuente** [comment]
Safari is now supported
