### ISSUE TITLE
openvidu-webcomponent-2.6.0.js ilegible code

### ISSUE THREAD

**Issue by cuban0** [OpenVidu/openvidu#145]
Hello, is it possible to get a fully legible source Code for the asset openvidu-webcomponent-2.6.0.js ?? As in previous versions the content is obfuscated javascript  code. 

Thanks !

**Comment by pabloFuente** [comment]
Hi,

OpenVidu WebComponent is obtained from OpenVidu Call Angular application: https://github.com/OpenVidu/openvidu-call

To compile the webcomponent you must run in OpenVidu Call command `npm run build:openvidu-webcomponent -- X.Y.Z`
