### ISSUE TITLE
Remote video not playing

### ISSUE THREAD

**Issue by toxtox7** [OpenVidu/openvidu#147]
I am very new to this. Currently trying out Openvidu in my local network only. It is all set up via a docker container on a seperate Linux VM in the local network.
I can start the demos like Hello World and the local camera gets displayed. However not the "remote" camera.
Testing via the server dashboard gives me an endless animationbut no video in both Firefox and Chrome.
So something is very wrong and I have no clue what it is.
So my question is how do I get this running locally only. There is no such thing like publically accessible IP all of them have 192.x.x.x and are accessible in the local lan only.
From my Firefox console I can see that streams and events get created, btut I also so
`CE failed, add a TURN server and see about:webrtc for more details`

I have added a coturn server on the Linux machine and started the docker with option KMS_STUN_IP and  KMS_STUN_PORT but this did not help either.

So I really need a hint how to get this up and running. Thanks.

**Comment by pabloFuente** [comment]
If you have run OpenVidu docker container in a Linux VM in your local network, and the virtual machine has no firewall restrictions, then it shouldn't be a problem to establish remote connections within your network. You just have to be clear about the IP where your OpenVidu Server is listening. And that's the IP you should provide OpenVidu Server when launching it (that's [configuration property](https://openvidu.io/docs/reference-docs/openvidu-server-params/) `openvidu.publicurl`)

So, being your VM in your local network, I guess that will be something like `https://192.168.0.XYZ:4443/`. So the docker run command should include an option like this:

```
-e openvidu.publicurl=https://192.168.0.XYZ:4443/
```

 You can check if it is correct by connecting to it from within your network: you should be able to see OpenVidu Server dashboard.

**Comment by toxtox7** [comment]
Thanks for your answer. Yes the Linux machine has 192.x.x.x and I am using -e openvidu.publicurl=https://192.168.0.XYZ:4443/ to start the container.
I can reach the dashboard but when I click test, and give permission to use the camera, there is only the endless loading animation. And nothing else is happening.
Same goes for the demos. I tried the Hello World demo and the Get A Room demo. I can start them and I get prompted for the local cam which is getting displayed after I gave permission. But the remote camera does not getting displayed. I can see the app adding a container for the remote video but it remains empty.
I tried with firewall on and off  but this did not make a difference.

**Comment by toxtox7** [comment]
2 more findings: First of all my overall setup seems to be ok. Tested with https://apprtc.appspot.com my clients can send and receive video via internet. So the issue must be local.
What I came across is that the local WebRTC trying to involve a private 172.x.x.x address which is not even configured on my network. It seems that this comes from the docker container configuration.
So what I am wondering now if this config shouldn't also be on the 192.x.x.x network. I mean how is the client to suppose to connect to 172.x.x.x for ICE if there is no route to it?

**Comment by toxtox7** [comment]
And finally got it working. If anybody is having a similar issue, check the network config of the docker container. In my case switching to default host network solved the problem.

**Comment by yunhai2009** [comment]
> And finally got it working. If anybody is having a similar issue, check the network config of the docker container. In my case switching to default host network solved the problem.

How do you solve this problem？  do i need set   those config?  thank you .
