### ISSUE TITLE
How do I stop recording after a fixed time when using manual mode of recording ?

### ISSUE THREAD

**Issue by bullsEye1** [OpenVidu/openvidu#149]
I am using the manual mode of recording.
All is fine except when i start recording and I close the session without stopping the recording the ffpmeg process keeps running in background which makes it very heavy for the server. Also i can never start recording again for that room (I am using room name as my session id which is a custom session id ) until i stop the previous recording.

What should be the best way to handle this since i want the user to have control over starting the recording but if by chance he doesn't stop the recording it should automatically stop after a fixed interval of time say 5 minute.

Or can I implement in such a way that I start recording manually but recording should be stopped automatically when the user who started the recording leaves the room.

**Comment by pabloFuente** [comment]
This is actually a good idea. We will implement the automatic stop of any recording for an empty session after a fixed timeout.

**Comment by pabloFuente** [comment]
WIth OpenVidu 2.7.0 sessions configured with `Recording.MANUAL` property now automatically stop their recording if last participant left the session and no user published to the same session in 2 minutes.
