### ISSUE TITLE
Add custom stun and turn server

### ISSUE THREAD

**Issue by Stopka** [OpenVidu/openvidu#15]
We wanted to add turn server to openvidu browser, but there seems to be no other way to do it without modifying the hardcoded list of stun/turn servers in included freeice module. Or is there better way?

**Comment by micaelgallego** [comment]
I think the best idea is to configure OpenVidu COTURN server by default. 

Or do you think another STUN/TURN server should be needed?

**Comment by Stopka** [comment]
I think we misuderstood each other. We configured our coturn server, but the only way to add this custom conturn server to be used by openvidu_browser is to modify freeice module hardcoded into openvidu_browser. And it's not a clean solution. Better way would be to pass our list of servers to Openvidu browser object during inicialization.

**Comment by pabloFuente** [comment]
Hi,
OpenVidu 2.0.0 now allows setting custom STUN and TURN servers in the client-side. Check out new [OpenVidu.setAdvancedConfiguration](https://openvidu.io/api/openvidu-browser/classes/openvidu.html#setadvancedconfiguration) method.
