### ISSUE TITLE
Record publisher's video only

### ISSUE THREAD

**Issue by devamit123** [OpenVidu/openvidu#152]
Hi,
I want to record only publisher's stream, I tried this type of example but could not get anything.
session.on("streamCreated", (event) => {
    var stream = event.stream;
    if (stream.connection.data === 'userBigVideo') {
        session.subscribe(stream, 'big-video-div');
    } else if (stream.connection.data === 'userSmallVideo') {
        session.subscribe(stream, 'small-video-div');
    }
});

Can anyone please provide a working example/demo/code I am unable to debug on server, I have written console.log in custom layout file but still nothing comes out. 
I am using ubuntu server.

Thanks in advance.

**Comment by pabloFuente** [comment]
By default every Publisher being published to the Session is recorded. Can you further explain what is the exact type of recording you want to perform?
