### ISSUE TITLE
ionic android app production release build not working

### ISSUE THREAD

**Issue by devamit123** [OpenVidu/openvidu#153]
Hi,

in my debug build it is working fine but with --prod --release build it gives blank white screen while creating stream.

I am using IONIC.

Please help what should I change/update.

Thanks.

**Comment by pabloFuente** [comment]
In production stages you must deploy OpenVidu as stated in the docs: whether Amazon deployment (https://openvidu.io/docs/deployment/deploying-aws/) or Ubuntu deployment (https://openvidu.io/docs/deployment/deploying-ubuntu/)

**Comment by pabloFuente** [comment]
@devamit123 I have tried `--prod --release build` in our openvidu-ionic tutorial following official Ionic v4 instructions: https://beta.ionicframework.com/docs/publishing/play-store

And it works just fine in an Android device. No difference at all with the debug version of the app. Streams are succesfully published and subscribed.
