### ISSUE TITLE
Remote video not shown

### ISSUE THREAD

**Issue by Wildhansatriady** [OpenVidu/openvidu#158]
![image](https://user-images.githubusercontent.com/9446843/50010977-6a446780-ffed-11e8-8cbb-5b0979a19a78.png)

I'm always getting error like that. I'm using ubuntu for implement openvidu and kms. And I was implement custom turn server in coding but still not working.
My coturn server i running well, when I check with trickle ICE. This is my result.
![image](https://user-images.githubusercontent.com/9446843/50011032-919b3480-ffed-11e8-8b4c-f1912cbcae45.png)

I was unblock the port from firewall. And I was check my TURN server with simple webrtc implementation, it running well. But, when I try using my TURN server with openvidu and kms i have that error.

I'm using this source code https://openvidu.io/docs/tutorials/openvidu-js-node/ 
this is the result 
![80707](https://user-images.githubusercontent.com/9446843/50011418-a5936600-ffee-11e8-9e75-e08c94400a15.jpg)
![image](https://user-images.githubusercontent.com/9446843/50011506-dd9aa900-ffee-11e8-9a95-47abd8d1e9f2.png)

**Comment by pabloFuente** [comment]
You didn't provide enough information. I only know you are deploying OpenVidu on Ubuntu and that you have a TURN server that you are using... where exactly?
OpenVidu deployment in Ubuntu machines is well described here: https://openvidu.io/docs/deployment/deploying-ubuntu/

If you don't follow those steps I cannot assure your deployment will work fine. The Ubuntu machine neeeds to be publicly accessible and meeting [these network requirements](https://openvidu.io/docs/deployment/deploying-ubuntu/#server-network-requirements). And as you can see in the docs, the TURN server (a coturn server in this case) should be deployed alongside OpenVidu Server and KMS. Of course you can use your own TURN server in the client side by configuring it with property _iceServers_ in method [OpenVidu.setAdvancedConfiguration](https://openvidu.io/api/openvidu-browser/classes/openvidu.html#setadvancedconfiguration), but if OpenVidu Server and KMS in your server side are not configured and deployed ok your connections will fail.

**Comment by Wildhansatriady** [comment]
Thank you very much :D . It's work when I'm use  OpenVidu.setAdvancedConfiguration. But I'm still curious, I need your advice, which part I should change if I won't using setAdvancedConfiguratioin? Because I'm following your guidance before.

Oh yeah about the Coturn server, because I have the server before I try using my old coturn  server and I'm following this link to install it.
https://www.webrtc-experiment.com/docs/TURN-server-installation-guide.html#coturn

thank you.
