### ISSUE TITLE
Media stream error notifications

### ISSUE THREAD

**Issue by Stopka** [OpenVidu/openvidu#16]
During our tests clients are freezing out. Accourding to our research it seems it could happen when client is using some kind of unstable network connection, like LTE. When the client disconnects even for a second, the media stream freezes. The problem is, that I don't get any notification from video element or openvidu about this incident. The websocket connection is going on, but video is frozen. And I can't react to this by reconnecting back, becaouse I am not notified about it. Is there any chance to detect that the media stream is broken?

**Comment by micaelgallego** [comment]
We should expose browser events regarding to media. Or maybe, we should send to browser Kurento Media Server events related to media.

**Comment by mgd-php** [comment]
Any updates for this? We have the same issue with openvidu 2.11.0. In our case it happens quite often: we are starting session with 3 participants, after some time one of the participant became "frozen" for the others, but on his side he still can see and hear other members, and own video for him is still active. No errors or events are shown in browser console. Checking session status through OpenVidu REST api gives us an info that everything is OK, session has 3 active connections with 2 subscribers each.

Is there a way to catch such issues on client side to add reconnection logic? Or maybe we can do something to improve overall stability for video session?

**Comment by micaelgallego** [comment]
We have improved reconnection strategies in OpenVidu. They will be released In the next version 2.12  (in two weeks).
