### ISSUE TITLE
Ionic 3 manual install required of dependency of openvidu-browser.

### ISSUE THREAD

**Issue by krish-dev** [OpenVidu/openvidu#160]
I create a fresh ionic 3 application using ionic cli 4.5.0

ionic (Ionic CLI)  : 4.5.0 (/usr/local/lib/node_modules/ionic)
Ionic Framework    : ionic-angular 3.9.2

and then run `npm install openvidu-browser --save` (2.7.0) 

then run the application in `serve` mode. its given error of `freeice` `platform` etc js not found which is dependency of `openvidu-browser`

after that I run this command `npm i freeice platform uuid ..... --save` like all the dependency of openvidu-browser then only it works. However, it not required for only Angular 7 application.

**Comment by pabloFuente** [comment]
Hi,

Be aware that only Ionic v4 is offically supported (still in beta, but first stable version will be officialy released in a few weeks)

**Comment by krish-dev** [comment]
Hi @pabloFuente 

I tested openvidu in ionic 3 and its fully working. except the above-mentioned configuration issue.

**Comment by Caldarelli** [comment]
Hello, I wanted to know if the Ionic 3 tutorials are still planned or not, Thank you

(also @krish-dev , if possible, would you be willing to explain how did you manage to make openvidu work in ionic 3 ? that would be a really big help, my app stops working when I import hark from the dependencies... Thank you very much in advance )

**Comment by krish-dev** [comment]
Hi @Caldarelli 

For Ionic 3, only you need to install all dependency of "openvidu-browser" along with the openvidu-browser with proper version. No need to import those dependencies into the application except openvidu-browser. you can see the dependencies [here](https://github.com/OpenVidu/openvidu/blob/master/openvidu-browser/package.json#L6-L10).

So, only you need run like

`npm i freeice@2.2.2 --save`
`npm i hark@1.2.3 --save` and so on

then `ionic serve` or build

**Comment by Caldarelli** [comment]
So you mean I have to place myself into the openvidu-browser module itself and there install the dependencies ?

**Comment by pabloFuente** [comment]
Hi,

[openvidu-ionic](https://openvidu.io/docs/tutorials/openvidu-ionic/) tutorial is now officially using **Ionic 5**. We still support Ionic 4, but no official support will be given for Ionic 3. That doesn't mean it won't work (in fact it should work just fine), but if you are using Ionic 3 version, we strongly recommend to update to a more recent version.

Regards.
