### ISSUE TITLE
Openvidu version 2.7 not work Safari on IOS 12.1.2

### ISSUE THREAD

**Issue by johndeep2109** [OpenVidu/openvidu#161]
I run this example [ https://demos.openvidu.io/classroom/](url) . Teacher is on android device as publisher, and disable audio. Student is on safari (IOS 12.1.2) but can't display video.

**Comment by pabloFuente** [comment]
Hi,

Classroom demo has to be in fact updated to support Safari. Please, checkout any other demo at demos.openvidu.io and see if they work fine.
