### ISSUE TITLE
Issue with remote stream in ionic ios

### ISSUE THREAD

**Issue by abhi0476** [OpenVidu/openvidu#163]
In ionic ios app remote stream is not playing. Only blank screen is displayed, however local streams are playing fine.

**Comment by micaelgallego** [comment]
Can you reproduce the issue with official tutorial?

Please indicate exact iOS version and how other users are connected to the
session (browser? Other iOS? Etc...)

**Comment by abhi0476** [comment]
Issue is reproducible with official tutorial.
iOS version: 11.3
Tested Device: iphone SE
Tested Emulator: iphone 5s

Other users are connected through browser. 
Publisher video is streamed through browser.

**Comment by abhi0476** [comment]
Just noticed issue is not coming when I am using the demo user i.e demos.openvidu.io:4443
I am running openvidu-server-2.7.0.jar on server side

**Comment by micaelgallego** [comment]
How are you deployed your server?

Remember that you need TURN server if you want to connect to a server from
mobile network.

Regards

**Comment by abhi0476** [comment]
[turnserver.txt](https://github.com/OpenVidu/openvidu/files/2705830/turnserver.txt)
Here is the turn configuration file.
Do I need to add kms url to my openvidu server ?

**Comment by pabloFuente** [comment]
You just have to follow srep by step these instructions https://openvidu.io/docs/deployment/deploying-ubuntu/

(Or using AWS if you want)

**Comment by abhi0476** [comment]
> You just have to follow srep by step these instructions https://openvidu.io/docs/deployment/deploying-ubuntu/
> 
> (Or using AWS if you want)

Followed the same steps.
AWS installation is working fine though, but I want custom installation on other server
