### ISSUE TITLE
global is not defined at Object../node_modules/openvidu-browser/lib/OpenViduInternal/KurentoUtils/kurento-jsonrpc/clients/transports/webSocketWithReconnection.js

### ISSUE THREAD

**Issue by Wildhansatriady** [OpenVidu/openvidu#165]
Hi, I need help to resolve this error. When I try to new Instance OpenVidu() I've got an error like a picture below. I using ionic 4 and lastest Openvidu library. Thank you.
![image](https://user-images.githubusercontent.com/9446843/50478428-9acfcc80-0a03-11e9-90bc-b44df18eaba2.png)

**Comment by micaelgallego** [comment]
Please test official Ionic tutorial to see if it works well. If it does, use is as base of your own development or compare it with your own version looking for differences.

**Comment by Wildhansatriady** [comment]
Thank you very much. I used base ionic from OpenVidu it works properly.  :)
