### ISSUE TITLE
Is openvidu scalable at the moment?

### ISSUE THREAD

**Issue by abondar** [OpenVidu/openvidu#166]
Hi

I walked through the docs, but couldn't find any information on it.
Is openvidu horizontally scalable at the moment? 
Is it possible to build it so it can handle big rooms for broadcasting? (1-2 people broadcast, 100+ people watching)

**Comment by abondar** [comment]
After some finding https://medium.com/@openvidu/openvidu-load-testing-a-systematic-study-of-openvidu-platform-performance-b1aa3c475ba9 and reading more examples I believe that answer to my question is `No, it's not horizontally scalable`.

But is it somehow possible to implement workaround, that will restream broadcast from one openvidu server to another, making it read-only server, that lifts load off main server?

**Comment by flexconstructor** [comment]
@abondar ,

There is no special need for horizontal scaling of the openvidu server because it is just a signaling mechanism. Another thing is the Kurento media server, which will have to be horizontally scaled to solve your problem. There is a project designed to solve the problem of horizontal scaling of media broadcasts - this is a [kurentot-tree](https://github.com/Kurento/kurento-tree). Despite the fact that the kurento-tree has not been updated for a long time, it is quite efficient, I checked. But, unfortunately, the openvidu project is going its own way and to implement this solution you will have to seriously modify the openvidu server.

**Comment by micaelgallego** [comment]
Hi @abondar, as @flexconstructor said, OpenVidu can not scale horizontally right now. 

You could adapt OpenVidu Server to use several Kurento Media Servers deployed in several machines. Every KMS can manage one media session. You could go further and split media management of one media session in several KMSs. As the extreme use case, you can chain several KMSs to serve hundred of users in the same media session. 

The OpenVidu development team is working right now in a professional version of OpenVidu, called OpenVidu Pro, that will contain these advanced features such as scalability, monitoring and fault tolerance. We will publish more information in the following weeks.

**Comment by llan-bw** [comment]
Hello @micaelgallego, do you have an update on the current status of scalability in a production setting for OpenVidu Pro?

If we're trying to use OpenVidu now, would you recommend we look into an architecture where it's [n]front-end OpenVidu client => [1]back-end OpenVidu server => [n]KMS?  Is this how OpenVidu pro will handle scaling?

**Comment by pabloFuente** [comment]
Release 2.11.0 brings first version of scalable OpenVidu, available in OpenVidu Pro tier. Further details in OpenVidu Docs: https://openvidu.io/docs/openvidu-pro/scalability/

**Comment by jinshuai7777** [comment]
Hello. @pabloFuente 
I am creating OpenVidu Pro stack.
But when I create the stack, I am getting error.

`WaitCondition | CREATE_FAILED | Failed to receive 1 resource signal(s) within the specified duration`

Is there any solution?

And template URL is "https://s3-eu-west-1.amazonaws.com/aws.openvidu.io/CF-OpenVidu-latest.yaml" right?
Please let me know.
Thanks.

**Comment by umarF** [comment]
I am having the same issue @jinshuai7777 @pabloFuente 
why does it fail at  **WaitCondition** ?

![Screenshot 2020-05-04 at 16 31 28](https://user-images.githubusercontent.com/6275920/80978366-3d813200-8e26-11ea-9733-db2df7328740.png)

**Comment by pabloFuente** [comment]
Because OpenVidu Server has not been able to sucessfully run. Follow this troublishooting instructions: https://docs.openvidu.io/en/2.13.0/openvidu-pro/deployment/aws/#troubleshooting (even thwy are for OpenVidu Pro, they will work fine for OpenVidu CE)

Basically you want to tell AWS not to rollback your stack so you can SSH in the OpenVidu instance and get OpenVidu Server logs. There you will probably have the reason why it failed to start.

**Comment by umarF** [comment]
@pabloFuente 
I've attached the log files for a quick view, can't seem to understand the failure point.

[cloud-init-output.log](https://github.com/OpenVidu/openvidu/files/4575458/cloud-init-output.log)
[cloud-init.log](https://github.com/OpenVidu/openvidu/files/4575460/cloud-init.log)

**Comment by pabloFuente** [comment]
Those are not all the logs asked in the troubleshooting guide. It clearly also asks for these ones: `docker-compose logs -f`

**Comment by umarF** [comment]
> Those are not all the logs asked in the troubleshooting guide. It clearly also asks for these ones: `docker-compose logs -f`

How do we get that log from docker ?
There is no docker installation in the ec2 instance !

> _docker-compose: command not found_

**Comment by pabloFuente** [comment]
Oh, ok. You are not deploying OpenVidu 2.13.0.

Please, try deploying OpenVidu 2.13.0 instead of 2.12.0. Following these instructions will deploy latest 2.13.0: https://docs.openvidu.io/en/2.13.0/deployment/deploying-aws/

**Comment by umarF** [comment]
I have followed exactly these guidelines for openvidu pro 2.13 only.
The one I used for non-pro version works (v2.13.0) but not the pro.

maybe you mean should I replace the cloudformation url from 

**_https://s3-eu-west-1.amazonaws.com/aws.openvidu.io/CF-OpenVidu-latest.yaml_**

to 

**_https://s3-eu-west-1.amazonaws.com/aws.openvidu.io/CF-OpenVidu-2.13.0.yaml ??_**

**Comment by pabloFuente** [comment]
No, because the latest version is the 2.13.0 version. Let me understand this right: you are saying that installing OpenVidu Pron AWS by using this cloudformation template: https://s3-eu-west-1.amazonaws.com/aws.openvidu.io/CF-OpenVidu-Pro-latest.yaml

Is not installing Docker and Docker Compose in your EC2 instances?

**Comment by umarF** [comment]
>  installing OpenVidu Pron AWS by using this cloudformation template: https://s3-eu-west-1.amazonaws.com/aws.openvidu.io/CF-OpenVidu-Pro-latest.yaml
> 
> Is not installing Docker and Docker Compose in your EC2 instances?

Yes, it does not install docker and docker-compose in my ec2.

I am now just trying to set up with explicitly mentioning the cloudformation template.
**https://s3-eu-west-1.amazonaws.com/aws.openvidu.io/CF-OpenVidu-Pro-2.13.0.yaml**

**Comment by umarF** [comment]
I tried again doesn't work even by specifying the version. i.e. 

https://s3-eu-west-1.amazonaws.com/aws.openvidu.io/CF-OpenVidu-Pro-2.13.0.yaml

Installed docker and docker-compose manually but yet not able to execute that command with success result.

> 
> ERROR: 
>         Can't find a suitable configuration file in this directory or any
>         parent. Are you in the right directory?
> 
>         Supported filenames: docker-compose.yml, docker-compose.yaml

**Comment by pabloFuente** [comment]
Paste here the values you are setting in the cloudformation template. Something must be wrong

**Comment by umarF** [comment]
AwsInstanceTypeKMS | c5.2xlarge | -
-- | -- | --
AwsInstanceTypeOV | c5.xlarge | -
KeyName | vidutest | -
KibanaPassword | **** | -
KibanaUser | kibanaadmin | -
LetsEncryptEmail | info@penguinpass.it | -
MediaNodesStartNumber | 2 | -
MyDomainName | ov2.penguinpass.it | -
OpenViduLicense | **** | -
OpenViduSecret | **** | -
OpenViduSubnet | subnet-0610ec113d1d50470 | -
OpenViduVPC | vpc-0809edce4cf876c08 | -
OwnCertCRT | - | -
OwnCertKEY | - | -
PublicElasticIP | 108.128.248.160 | -
WantToDeployDemos | true | -
WhichCert | letsencrypt |

**Comment by micaelgallego** [comment]
We are not able to reproduce your issue. Cloud Formation uses AMIs with docker-compose already installed. 

Do you have any files in /opt/openvidu?

**Comment by umarF** [comment]
Thanks a lot for the help. The issue is resolved now. I changed the VPC network and EC2 machine configs. Now it is able to function.

**Comment by micaelgallego** [comment]
You are welcome.

**Comment by umarF** [comment]
> We are not able to reproduce your issue. Cloud Formation uses AMIs with docker-compose already installed.
> 
> Do you have any files in /opt/openvidu?

Ok I have another issue. After the deployment, I needed to make some configuration changes. following the documentation, i ssh into my ec2 machine but again i cant find the  /opt/openvidu

I am running version 2.13.0  :/

> [ec2-user@ip-192-168-0-203 ~]$ ls
> config  redis-shake.pem
> [ec2-user@ip-192-168-0-203 ~]$ cd ..
> [ec2-user@ip-192-168-0-203 home]$ ls
> ec2-user
> [ec2-user@ip-192-168-0-203 home]$  cd ..
> [ec2-user@ip-192-168-0-203 /]$ ls
> bin  boot  dev  etc  home  lib  lib64  local  media  mnt  opt  proc  root  run  sbin  srv  sys  tmp  usr  var
> [ec2-user@ip-192-168-0-203 /]$ cd opt
> [ec2-user@ip-192-168-0-203 opt]$ ls
> aws  rh
> [ec2-user@ip-192-168-0-203 opt]$

**Comment by umarF** [comment]
I tried to update the configs using the inspector but it didn't work and now I get 502 Bad Gateway .

**Comment by micaelgallego** [comment]
Definitely you have something wrong with your installation or you are connecting to another machine
