### ISSUE TITLE
Re-Publish

### ISSUE THREAD

**Issue by GNUConsultores** [OpenVidu/openvidu#17]
Hi,

i wrote a application extrapoled from openvidu-insecure-js. In that application, there is a principal publisher (main speaker) and many subscribers. But sometime, any subcriber (client) can publish his own stream to interact with the speaker, so all the rest can view (receive) two stream; the main and the other one.

All work perfect, but when that client call unpublish method from session (without disconnect), and want to publish more late again, there are problems. The OpenVidu-KMS send log "Publisher succesfully published to session", but Stream.ts (line 632) show "Error setting SDP to the peer connection", and the other clients, show "jsonrpcclient.js:157 Exception processing request: {"method":"participantPublished","params":{"id":"bp917ok7b99pquf3m92au73elb","streams":[{"id":"webcam","audioActive":true,"videoActive":true}]}}" ... and the stream not showing. These problem only exploid when the same client has published, unpublished and then want to publish again. What can i do to solved?

Thank you very much for your awesome work.

Regards,
Heri

**Comment by pabloFuente** [comment]
Hi

We are aware of this problem. This is related to SDP renegotiation, which is no fully supprted by Kurento Media Server. We are doing some heavy refactoring work on OpenVidu server and this issue will  be fixed one way or another in following updates.

Thanks

**Comment by pabloFuente** [comment]
This issue is now solved on version 1.4.0.
Check [Publish/Unpublish](http://openvidu.io/docs/how-do-i/publish-unpublish/) docs to learn how it works
