### ISSUE TITLE
Cannot read property 'send' of undefined

### ISSUE THREAD

**Issue by Wildhansatriady** [OpenVidu/openvidu#171]
Hi, I need help to solve this problem :).  I'm using Ionic, I've got the problem when trying to use send text feature.  Thank you.
![image](https://user-images.githubusercontent.com/9446843/50763743-3b937700-12a3-11e9-90b4-d96ceb61488e.png)

this is my code : 
`      this.session.signal({
        data: this.chatInput,  // Any string (optional)
        to: [],                     // Array of Connection objects (optional. Broadcast to everyone if empty)
        type: "global-chat"             // The type of message (optional)
      })
      .then(() => {
        console.log("Message successfully sent");
       
      })
      .catch(error => {
          console.error(error);
      });`

**Comment by micaelgallego** [comment]
Are you joined to a session before using send method? It seems something is not properly initialized in OpenVidu object.

In any case, we need to improve error message ;)

**Comment by Wildhansatriady** [comment]
Yes, it's solved. Seems like I have a connection problem. Thank you very much :D
