### ISSUE TITLE
Recording resolution issue

### ISSUE THREAD

**Issue by sanket044** [OpenVidu/openvidu#175]
Hello,

I have done basic coding of recording and it works well. But issue is i am sending video stream of 1280x720 resolution but it records in 1920x1080. I checked some other issues and found below code in [io/openvidu/server/recording/ComposedRecordingService.java ](https://github.com/OpenVidu/openvidu/blob/ccd8d7a8b9254638bc1aba48c14fa57920b5e254/openvidu-server/src/main/java/io/openvidu/server/recording/ComposedRecordingService.java#L103) class:

`public Recording startRecording(Session session, RecordingProperties properties) {

    // some code here...

    envs.add("URL=" + layoutUrl);
    envs.add("RESOLUTION=1920x1080");
    envs.add("FRAMERATE=30");
    envs.add("VIDEO_ID=" + recordingId);
    envs.add("VIDEO_NAME=" + properties.name());
    envs.add("VIDEO_FORMAT=mp4");
    envs.add("USER_ID=" + uid);
    envs.add("RECORDING_JSON=" + recording.toJson().toJSONString());

    String containerId = this.runRecordingContainer(envs, "recording_" + recordingId);

    this.waitForVideoFileNotEmpty(properties.name());

    // some code here....

    return recording;
}`

Resolution is fixed, 1920x1080. Is there any way i can change this resolution?

Thank you.

**Comment by pabloFuente** [comment]
Hi,

Not right now, but it will be included in next release. We are heavily working right now in OpenVidu recording service, fixing some issues and adding a new mode for individual stream recording.
We will add a new property "resolution" for composite recording. 

Stat tuned

**Comment by sanket044** [comment]
Okay thank you for quick response.

Also is there anyway we can tell name of the recording file? I see there is line properties.name(); but how can i set it?

**Comment by pabloFuente** [comment]
Depending on how you are communicating with OpenVidu Server

- REST API: https://openvidu.io/docs/reference-docs/REST-API/#post-apirecordingsstart
- openvidu-java-client: with [RecordingProperties.Builder().name()](https://openvidu.io/docs/reference-docs/openvidu-java-client/#manage-recordings)
- openvidu-node-client: passing a property `name` in [RecordingProperties](https://openvidu.io/api/openvidu-node-client/interfaces/recordingproperties.html) when calling [OpenVidu.startRecording](https://openvidu.io/api/openvidu-node-client/classes/openvidu.html#startrecording)

**Comment by sanket044** [comment]
Thanks for reply. 

But i am using automated recording. So i dont know how to use RecordingProperties.

```
OpenVidu openvidu = new OpenVidu(OPENVIDU_URL, OPENVIDU_SECRET);
SessionProperties properties = new SessionProperties.Builder()
    .recordingMode(RecordingMode.MANUAL) // RecordingMode.ALWAYS for automatic recording
    .defaultRecordingLayout(RecordingLayout.BEST_FIT)
    .mediaMode(MediaMode.ROUTED)
    .build();
Session session = openVidu.createSession(properties);
```

Can you help me in this?

**Comment by pabloFuente** [comment]
Customizing Recording properties like `name` is only available when manually starting and stopping recordings. For automatic recordings they will always be named after the sessionId. If you want you can specify a `customSessionId` when creating a session:

[API REST](https://openvidu.io/docs/reference-docs/REST-API#post-apisessions)
[openvidu-java-client](https://openvidu.io/docs/reference-docs/openvidu-java-client#create-a-session)
[openvidu-node-client](https://openvidu.io/docs/reference-docs/openvidu-node-client#create-a-session)

This way your recording will also have that property as name.

**Comment by sanket044** [comment]
Okay got it. Thank you very much.

One last question, can you suggest me what system should i use? When i will have 50 clients and max 3 streams running with recording.

**Comment by pabloFuente** [comment]
Just a couple of weeks ago we published this post, talking about performance: https://link.medium.com/CImEXoBAzT

I hope that answers your question!

**Comment by sanket044** [comment]
Ok, i tried to do manual recording. But i am getting 400 error. I checked everything and everything seems fine. One person is hosting the video, still it says 400.

When i do automatic recording everything works fine. Any idea what can i do next?

**Comment by sanket044** [comment]
`@RequestMapping(value = "/start-recording", method = RequestMethod.POST)
	public ResponseEntity<JSONObject> startHosting() {
		try {
			Recording recordingStarted = this.openVidu.startRecording(this.sessionId);
			this.recordingId = recordingStarted.getId();
			System.out.println("Recording Started, id is " + this.recordingId);
			return new ResponseEntity<>(HttpStatus.OK);
		} catch (Exception e) {
			System.out.println("Error in recording start: " + e.toString());
			return getErrorResponse(e);
		}
	}

	@RequestMapping(value = "/stop-recording", method = RequestMethod.POST)
	public ResponseEntity<JSONObject> stopHosting() {
		try {
			Recording recordingStopped = this.openVidu.stopRecording(this.recordingId);
			System.out.println("Recording stopped.");
			return new ResponseEntity<>(HttpStatus.OK);
		} catch (Exception e) {
			System.out.println("Error in recording stop: " + e.toString());
			return getErrorResponse(e);
		}
	}`

**Comment by pabloFuente** [comment]
Are you using openvidu-java-client SDK?

**Comment by pabloFuente** [comment]
Please, post below:

- How did you run OpenVidu Server
- OpenVidu Server version
- openvidu-java-client version in your app
- All the information available in object `Exception e` in the `catch` section of your `startRecording` code

**Comment by sanket044** [comment]
Run using following :

`sudo docker run -p 4443:4443 --rm -v /var/run/docker.sock:/var/run/docker.sock -v /home/thirty/recording/:/home/thirty/recording/ -e openvidu.recording=true -e MY_UID=$(id -u $USER) -e openvidu.recording.path=/home/thirty/recording/ -e openvidu.recording.public-access=true -e openvidu.secret=MY_SECRET -e openvidu.publicurl=https://192.168.0.1:4443 openvidu/openvidu-server-kms:2.7.0`

OpenVidu server version : 2.7.0
OpenVidu java client version : How can i find that?

I dont get any other information than OpenVidu.HTTPException and 400 as error

**Comment by pabloFuente** [comment]
You are working with a Java app as I can see in your comment above. I don't know if it is openvidu-recording-tutorial, but I'm guessing the app is making use of openvidu-java-client dependency. The version of that dependency is what I'm asking about.

**Comment by pabloFuente** [comment]
By the way, new version 2.8.0 has been just released, brining lots of improvements regarding recording service. Try running your Docker container as explained here: https://openvidu.io/docs/advanced-features/recording/#for-openvidu-server-docker-image-development-environment

And post the output of the Docker container here

**Comment by sanket044** [comment]
I am using openvidu js java app and implementing recording inside that. Its the same time i installed openvidu server and cloned the tutorials. So it should be 2.7.0 of tutorials.

**Comment by sanket044** [comment]
I am using openvidu js java app and implementing recording inside that. Its the same time i installed openvidu server and cloned the tutorials. So it should be 2.7.0 of tutorials.

**Comment by sanket044** [comment]
Oh thats great. Is there anyway to directly update from 2.7.0 to 2.8.0?
Also can you share change log link?

**Comment by pabloFuente** [comment]
These are the Release Notes for 2.8.0: https://medium.com/@openvidu/openvidu-2-8-0-individual-stream-recording-and-audio-video-only-recording-2de58f3d167b

Update should be as easy as running container 2.8.0 instead of 2.7.0, and updating in your application dependencies `openvidu-browser-2.7.0.js` to `openvidu-browser-2.8.0.js` and `openvidu-java-client` from 2.7.0 to 2.8.0 in the `pom.xml` file of your Java application

 There are only a couple of breaking changes, explained in the release notes, but your application's code will not probably need any change.

**Comment by sanket044** [comment]
okay, i read the change log and many features were already required. Good job team.

Can we set the name of recording now in automatic record? And also is there any direct way to stop automatic recording without forcing user to leave the session?

**Comment by sanket044** [comment]
And i am using java client 2.7.0 version.

**Comment by pabloFuente** [comment]
We have just discovered a pretty awful bug in OpenVidu Java Client that is causing this 400 error in certain cases. In a few hours a new patched version 2.8.1 will be released, hopefully fixing your problem

**Comment by sanket044** [comment]
Okay thanks. Also please can you drop changes required in code. As, i have not yet shifted from 2.7.0 to 2.8.0

**Comment by pabloFuente** [comment]
OpenVidu Java Client patch is already available. No changes needed in the code. You just need to update your dependencies:

- openvidu-server to **2.8.0**
- openvidu-java-client to **2.8.1**

**Comment by sanket044** [comment]
I downloaded that, and everything worked perfectly. Also, used name and resolution properties and that are also working great.

Thank you very much for your help.
