### ISSUE TITLE
Send data between session

### ISSUE THREAD

**Issue by Wildhansatriady** [OpenVidu/openvidu#177]
Hi, is possible to send data between session? for example, I  joined in session A, and I want to send text data from Session A to session B?

**Comment by pabloFuente** [comment]
No, not by using OpenVidu API. That would directly violate the encapsulation of sessions.
But you can always send your own messages on top of OpenVidu, of course, by using the framework of choice for your application.

**Comment by Wildhansatriady** [comment]
Ok thank you :D

**Comment by micaelgallego** [comment]
@Wildhansatriady remember that you can use signal method (https://openvidu.io/api/openvidu-browser/classes/session.html#signal) to send any kind of information from SessionA to SessionB
