### ISSUE TITLE
Recorded video error

### ISSUE THREAD

**Issue by datnt55** [OpenVidu/openvidu#179]
Hi.
When i play recorded video, my video show only "  This site can't be reached https://OPENVIDUAPP:secret @ host /#/layout-best-fit/ session_id/ secret "
How can i record normally?thanks.

**Comment by pabloFuente** [comment]
What version of OpenVidu are you using?

**Comment by datnt55** [comment]
im using  v2.7.0

**Comment by pabloFuente** [comment]
Okey, I'll need further info:

- What kind of setup are you using? Developing setup (openvidu-server-kms docker container) or production setup (AWS or Ubuntu deployment)
- Are you starting the recording with API REST, openvidu-java-client or openvidu-node-client? How are you performing the `start` operation, whichever is the SDK you are using?

**Comment by agergec** [comment]
Hello @pabloFuente,

We have a production grade installation on ubuntu 16.04.5 LTS. 
As described in "deploy openvidu on ubuntu" documentation coturn and kms are installed on the server and openvidu 2.8.0 server is started from jar file with recording enable. 

We have the same error. The produced mp4 files show a web page, which says it couldn't reach our server's url.

What do you need exactly to examine the issue.

Kind regards
Gökalp

**Comment by pabloFuente** [comment]
OpenVidu module will try to connect to your sessions through the public IP of your openvidu-server. Make sure that inside of your server you are able to reach `https;//YOUR_OPENVIDU_SERVER_PUBLIC_IP:4443/` with a ping command or something similar.

**Comment by agergec** [comment]
Thank you,

my /etc/hosts file had a wrong ip address for the host itself.

Kind regards
Gökalp
