### ISSUE TITLE
 whiteboard function in openvidu

### ISSUE THREAD

**Issue by yoyomule** [OpenVidu/openvidu#181]
I would like to ask how to implement the whiteboard function in openvidu, as well as PPT playback and writing on it.

**Comment by micaelgallego** [comment]
WebRTC allows you to "stream" a canvas element in the webpage (https://openvidu.io/api/openvidu-browser/classes/openvidu.html#getusermedia)

To share a whiteboard or PPT playback you will have to manage the streamed canvas as a whiteboard or PPT playback. For example using some libraries like:
* https://www.drawerjs.com/canvas-editor
* https://mozilla.github.io/pdf.js/

**Comment by zw12579** [comment]
Hello：
I encountered a problem during the process of using canvas-editor. I try to get changes to the canvas content through these two events for “EVENT_CANVAS_MODIFIED” and “EVENT_OBJECT_ADDED”. Into an infinite loop when sending websocket messages。Can you hlep me ? thanks

![image](https://user-images.githubusercontent.com/33717789/51885616-3bc8f300-23c7-11e9-81c3-3c261405720a.png)

![image](https://user-images.githubusercontent.com/33717789/51885627-4e432c80-23c7-11e9-8b98-0b2adf29e4c1.png)

**Comment by micaelgallego** [comment]
It seems that the original change event perfome some action in remote canvas. This action in remote canvas is notified with a new event that come back... And the cycle starts again.

**Comment by zw12579** [comment]
Do you have any good way to solve this problem? No related methods are available on his documentation.

**Comment by pabloFuente** [comment]
This isn't now an issue related to OpenVidu. To ask about other repos, please refer to them.

**Comment by Bigben83** [comment]
@zw12579  did you ever get the whiteboard canvas to stream ?
