### ISSUE TITLE
ICE issue in firefox

### ISSUE THREAD

**Issue by sanket044** [OpenVidu/openvidu#182]
Hello, 

I am running basic openvidu project js java in my LAN. But issue is, the chrome works fine, but the firefox gives error "ICE Failed, see about:webrtc for more details."

I tried almost everything to find the issue, but cant find anything. Also there is no internet in LAN, so it can not go out side. Can anyone help?

**Comment by desmat92** [comment]
Same problem.
The demo works on Chrome and not on Firefox, remote video is empty.

**Comment by sanket044** [comment]
I just found later that, it works on Firefox developer edition and nightly edition perfectly.

Not sure the reason.

**Comment by pabloFuente** [comment]
Do demos at https://demos.openvidu.io work fine in your Firefox instances?

**Comment by NisargPawar** [comment]
Same here, the participants connect to the session but cant get each other's feed.
The same code works fine on chrome.
My firefox version is 60.5.1
Chrome version is 70.+

**Comment by pabloFuente** [comment]
Do demos at https://demos.openvidu.io work fine in your Firefox instances?

**Comment by NisargPawar** [comment]
Yes demos work fine

**Comment by pabloFuente** [comment]
Tell me your dev setup then:

- In which OS are you running OpenVidu Server?
- What OpenVidu Server artifact are you running (docker container, JAR file)
- The exact command you are using to launch openvidu-server
- What tutorial are you running and the exact command you are using to serve it
- How are your clients connecting to the session? Same LAN with different devices?
- If you update Firefox to latest stable version recommended by Mozzila (65.0) does it work fine?

**Comment by NisargPawar** [comment]
1) AWS
2) AWS
3) AWS panel
4) integrated the insecure js demo, on interference in any openvidu code
5) Connection is between either wifi or LTE network and private LAN. But openvidu server is public

**Comment by pabloFuente** [comment]
Let's perform a quick test. I'm deploying right now an AWS openvidu-server. I'll post here the address when it is up and running so you can test the connection with the Firefox instance that is causing trouble.

**Comment by pabloFuente** [comment]
Ok, so:
- URL: https://ec2-34-244-154-135.eu-west-1.compute.amazonaws.com:4443
- USER: `OPENVIDUAPP`
- SECRET: `MY_SECRET`

Try the test connection that you will have available in OpenVidu Server dashboard with your Firefox instance and post here the results

**Comment by pabloFuente** [comment]
The AWS zone is Ireland, so you can expect some latency in the communications if you are not in Western Europe

**Comment by NisargPawar** [comment]
Works great... Is this a code issue then? Or a connectivity issue?

**Comment by NisargPawar** [comment]
What aws configurations did you use? Maybe im missing something on deployment perspective...?

**Comment by pabloFuente** [comment]
Well, if it works fine then I'm pretty confused. I've just followed this instructions: https://openvidu.io/docs/deployment/deploying-aws/, using selfsigned certificate option.

Maybe is something related to AWS availability zone? Try deploying OpenVidu in any other region and see if it works fine in your Firefox instance. But, either way, that behavior is so weird.

**Comment by pabloFuente** [comment]
In which AWS Zone were you deploying OpenVidu?

**Comment by NisargPawar** [comment]
Cant tell, but thanks for the help. Atleast now i know its something to do with the openvidu server.

**Comment by pabloFuente** [comment]
Not really. It is somthing related to your specific deployment of openvidu-server. Don't you know the AWS availability zone where you were deploying the openvidu-server CloudFormation?

**Comment by sanket044** [comment]
no, the issue is not with single system. But issue comes when two user comes and try to access each other's video.

**Comment by NisargPawar** [comment]
Sorry for a late response, but it worked out. I dont know what was done with the server but they handled it and now it works (they being the ones I work for). Thanks for the help!
