### ISSUE TITLE
I can't create dock file from src

### ISSUE THREAD

**Issue by zlatnaspirala** [OpenVidu/openvidu#183]
**What i done :**

I take git clone openvidu project from this address : https://github.com/OpenVidu/openvidu
I am special interest in : https://github.com/OpenVidu/openvidu/tree/master/openvidu-server

Now i goto src folder i for example i edit file : 

> openvidu/openvidu-server/src/main/java/io/openvidu/server/OpenViduServer.java

I put simple log line like : log.info("OpenVidu server edited !!!");

Now i want to build docker file and make docker image from edited source :

i goto :

> openvidu/openvidu-server/docker/openvidu-server/create_image.sh

And i always got error msg like :

`Step 6/9 : COPY openvidu-server.jar / COPY failed: stat /var/lib/docker/tmp/docker-builder085675371/openvidu-server.jar: no such file or directory rm: ./openvidu-server.jar: No such file or directory
`

I can download jar from git release but it is not what i want ...

Any suggestion how to build jar from src.

This is also stack with other parts in this project.

**Comment by pabloFuente** [comment]
You have to first build openvidu-server JAR

```bash
git clone https://github.com/OpenVidu/openvidu.git
cd openvidu
mvn -DskipTests=true compile && mvn -DskipTests=true install # Only needed first time
cd openvidu-server
mvn clean compile package # Needed every time you want to rebuild Docker container with some changes
```

Now you will have in path `openvidu/openvidu-server/target` the JAR file `openvidu-server-2.7.0.jar`
You can now build the Docker image like this:

```bash
./create-image.sh 2.7.0 # Change 2.7.0 for the version of your compiled openvidu-server
```

**Comment by zlatnaspirala** [comment]
Thank you for answer, i never build java project.
 
 On first command : 

```
[INFO] Reactor Summary:
[INFO]
[INFO] OpenVidu 1.9.0-beta-1 .............................. SUCCESS [  0.532 s]
[INFO] OpenVidu Client 1.1.0 .............................. SUCCESS [  1.180 s]
[INFO] OpenVidu Java Client 2.5.0 ......................... SUCCESS [  0.163 s]
[INFO] OpenVidu Test 1.1.0 ................................ SUCCESS [ 32.555 s]
[INFO] OpenVidu Server 2.7.0 .............................. SUCCESS [ 41.181 s]
[INFO] OpenVidu Test e2e 1.1.1 ............................ FAILURE [  2.377 s]

```

On second i got some problems : 

Nikolas-iMac:openvidu-server nikola$ mvn clean compile package
[INFO] Scanning for projects...
[INFO]
[INFO] --------------------< io.openvidu:openvidu-server >---------------------
[INFO] Building OpenVidu Server 2.7.0
[INFO] --------------------------------[ jar ]---------------------------------
[WARNING] The POM for io.openvidu:openvidu-client:jar:1.1.0 is missing, no dependency information available
[WARNING] The POM for io.openvidu:openvidu-test:jar:1.1.0 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.110 s
[INFO] Finished at: 2019-01-28T10:56:08+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project openvidu-server: Could not resolve dependencies for project io.openvidu:openvidu-server:jar:2.7.0: The following artifacts could not be resolved: io.openvidu:openvidu-client:jar:1.1.0, io.openvidu:openvidu-test:jar:1.1.0: Failure to find io.openvidu:openvidu-client:jar:1.1.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]

Any suggest.

**Comment by pabloFuente** [comment]
I don't really know what's casuing this issue in your case. Maybe it is something related to your OS/Java/Maven version. Can you include these information?

- OS where you are compiling OpenVidu repo
- Java version (`java -version`)
- Maven version (`mvn -v`)

**Comment by pabloFuente** [comment]
I'm sure this is related to your Java version. You will need `openjdk-8-jdk`

**Comment by Piousangel** [comment]
Java 11 JDK | java -version | sudo apt-get install -y openjdk-11-jdk
-- | -- | --
Maven | mvn -v | sudo apt-get install -y maven
Node | node -v | sudo curl -sL https://deb.nodesource.com/setup_16.x \| sudo bash -sudo apt-get install -y nodejs

and then 
git clone https://github.com/OpenVidu/openvidu.git
cd openvidu
mvn -DskipTests=true clean install
and then 

[ERROR] Failed to execute goal on project openvidu-client: Could not resolve dependencies for project io.openvidu:openvidu-client:jar:1.1.0: The following artifacts could not be resolved: org.kurento:kurento-jsonrpc-client:jar:6.18.0-SNAPSHOT, org.kurento:kurento-jsonrpc-client-jetty:jar:6.18.0-SNAPSHOT: Could not find artifact org.kurento:kurento-jsonrpc-client:jar:6.18.0-SNAPSHOT -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :openvidu-client

plz why,,,?

**Comment by cruizba** [comment]
We are at master branch migrating to a new Kurento version, which is currently as SNAPSHOT. As we are using Github Packages as a Snapshot repository, you are not being able to build the server.

Configure the snapshot repository for Kurento in `~/.m2/settings` of `/etc/maven/settings`:

```
<?xml version="1.0" encoding="UTF-8"?>
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">
  <pluginGroups></pluginGroups>
  <proxies></proxies>
  <servers></servers>
  <mirrors></mirrors>
  <profiles>
    <profile>
      <id>dev</id>
      <repositories>
        <repository>
          <id>kurento-github-public</id>
          <name>Kurento GitHub Maven packages (public access)</name>
          <url>https://public:&#103;hp_tFHDdd4Nh9GqKSaoPjnFIXrb0PFsUh258gzV@maven.pkg.github.com/kurento/*</url>
          <releases>
            <enabled>false</enabled>
          </releases>
          <snapshots>
            <enabled>true</enabled>
          </snapshots>
        </repository>
      </repositories>
      <pluginRepositories>
        <pluginRepository>
          <id>kurento-github-public</id>
          <name>Kurento GitHub Maven packages (public access)</name>
          <url>https://public:&#103;hp_tFHDdd4Nh9GqKSaoPjnFIXrb0PFsUh258gzV@maven.pkg.github.com/kurento/*</url>
          <releases>
            <enabled>false</enabled>
          </releases>
          <snapshots>
            <enabled>true</enabled>
          </snapshots>
        </pluginRepository>
      </pluginRepositories>
      <activation>
        <activeByDefault>true</activeByDefault>
      </activation>
    </profile>
  </profiles>
</settings>
```

Execute:

```
mvn -Dmaven.artifact.threads=1 -DskipTests=true clean install
```

More info here: https://doc-kurento.readthedocs.io/en/latest/user/installation_dev.html?highlight=nightly#per-user-config
