### ISSUE TITLE
Server Side Adaptive Bitrate

### ISSUE THREAD

**Issue by tibinvpaul** [OpenVidu/openvidu#186]
I am building a live broadcast solution on top of openvidu and came across a requirement of adaptive bitrate. The publisher broadcasts the stream with 720p resolution. If the internet speed of the subscribers is fair enough, they will get 720p resolution video otherwise they will get 480p OR 360p based on the internet speed. 

Is this doable with the current version of openvidu?

**Comment by micaelgallego** [comment]
Kurento Media Server doesn't support simulcast. That is, KMS is not able to receive different resolutions from source browser. Then, users are not able to select the most suitable resolution depending on Internet speed.

**Comment by tibinvpaul** [comment]
Thanks, @micaelgallego for the answer.

Does it mean that the resolution and framerate set in the publisher object will directly be transferred to the subscriber without any processing?

I have seen some media servers encode a single source media at multiple bit rates in the server and the client gets it based on the internet speed.

Do you have any plans to implement this in the future?
