### ISSUE TITLE
Screensharing stop event

### ISSUE THREAD

**Issue by sanket044** [OpenVidu/openvidu#187]
Hello, 

I have implemented screensharing and works great in ubuntu. But it doesnt work on windows. It doesnt show any error or screen sharing selection popup.

Also, when i share screen, firefox shows its native stop screen sharing button. User can stop screen sharing using stop button. Is there any event using which i can know this button clicked?

Thanks.

**Comment by pabloFuente** [comment]
Hi

There's a native WebAPI event that might help you: https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack/onended

So, you simply need to add this event to the MediaStreamTracks objects you want to be able to monitor for this particular behavior. How do you access MediaStreamTracks through openvidu-browser API?

Easy. Being `Stream` the [Stream class](https://openvidu.io/api/openvidu-browser/classes/stream.html) provided by openvidu-browser that you get on `streamCreated` event:

To get the video track (if available):
`Stream.mediaStream.getVideoTracks()[0]`

To get the audio track (if available):
`Stream.mediaStream.getAudioTracks()[0]`

**Comment by pabloFuente** [comment]
By the way, in Windows screen sharing works just fine. Try https://demos.openvidu.io/openvidu-call

**Comment by oisnot** [comment]
> By the way, in Windows screen sharing works just fine. Try https://demos.openvidu.io/openvidu-call

I tried that webpage in ubuntu 18.10, google chrome, openvidu screenshare extension and screenshare  doesn't work? 

![skjermdump fra 2019-02-05 10-31-59](https://user-images.githubusercontent.com/2698541/52264766-af708000-2932-11e9-918e-96b579e32c33.png)
![skjermdump fra 2019-02-05 10-32-55](https://user-images.githubusercontent.com/2698541/52264798-c0b98c80-2932-11e9-96fb-83393e7fa07e.png)
![skjermdump fra 2019-02-05 10-43-02](https://user-images.githubusercontent.com/2698541/52264839-db8c0100-2932-11e9-818f-639f5afc64c5.png)

**Comment by heymatias** [comment]
I have the same problem in Chrome 80 with Ubuntu, can anyone find a solution?

**Comment by pabloFuente** [comment]
https://github.com/OpenVidu/openvidu/issues/319#issuecomment-604717683
