### ISSUE TITLE
Is java session object necessary?

### ISSUE THREAD

**Issue by NisargPawar** [OpenVidu/openvidu#190]
As the title says. We create a session object in java and generate a token from it. That being said is that the only importance of the session object? What if i could generate two tokens and destroy the session object. Would that work?

**Comment by pabloFuente** [comment]
What do you mean about "destroying" the Session object? In Java you cannot destroy an object _per se_, you just lose the reference to it. There's no problem if you lose the reference of the Session object,  you simply won't be able to call its methods: https://openvidu.io/api/openvidu-java-client/

And you can always retrieve all active sessions and recover a reference to them using OpenVidu  _getActiveSessions_ and _fetch_ methods: https://openvidu.io/api/openvidu-java-client/

**Comment by NisargPawar** [comment]
Thats all i needed to know! Thanks for clarifying!!
