### ISSUE TITLE
When plan to support RTSP?

### ISSUE THREAD

**Issue by nickname110** [OpenVidu/openvidu#191]
When plan to support the RTSP streams? When do you think it could be done?

**Comment by micaelgallego** [comment]
It is in our mid term roadmap. 

We hope it will be added before the end of Q1

**Comment by farshidbakh** [comment]
Hello I am working on a project which I need to show rtsp streams from IP cameras on my web app. Does OpenVidu support that?

**Comment by yoyomule** [comment]
> It is in our mid term roadmap.
> 
> We hope it will be added before the end of Q1
Hi,
Is it already implemented, support rtsp and rtmp? There are a lot of motion cameras (gopro) and panoramic cameras (insta one x), etc. are all pushed by rtmp protocol, I hope openvidu can support.

**Comment by micaelgallego** [comment]
Rtsp and rtmp are very different protocols. 

We are focused right now in implementing other features in OpenVidu like webhooks. We will evaluate RTSP support when we come back from vacations

**Comment by hiperpat** [comment]
Any updates on this?

**Comment by micaelgallego** [comment]
It is already implemented in master. It will be announced and documented when we publish the next OpenVidu release.

**Comment by kkddeerr** [comment]
When is the scheduled next release date?

**Comment by paivaric** [comment]
Any news?

**Comment by micaelgallego** [comment]
We plan to publish the new release in two or three weeks

**Comment by geekloper** [comment]
Any news ? 🙏 😃

**Comment by micaelgallego** [comment]
New release is taking longer than expect 
We are with documentation right now... two weeks max (I hope) ;)

**Comment by yoyomule** [comment]
Any news ? 🙏 😃

**Comment by pabloFuente** [comment]
Monday 16th

**Comment by saadqc** [comment]
@micaelgallego : update please!

**Comment by micaelgallego** [comment]
OpenVidu already provides RTSP support!
