### ISSUE TITLE
Start opnevidu and docker on system start

### ISSUE THREAD

**Issue by sanket044** [OpenVidu/openvidu#193]
Hello, 

I want to start openvidu and docker when system starts. Tried to make service of both and added in startup. But docker command is making lots of issues in that, some times takes a lot time to start and some times doesnt start at all.

Can anyone help?

**Comment by pabloFuente** [comment]
Please, avoid posting this kind of system configuration questions on issues section. It is not a problem related to OpenVidu platform itself and it is extremely dependant on your system and administration config. Use GoogleGroup better for this type of threads:  https://groups.google.com/forum/m/#!forum/openvidu
