### ISSUE TITLE
Unable to get audio when screensharing

### ISSUE THREAD

**Issue by zeshan321** [OpenVidu/openvidu#194]
Hi,

It seems that when you screenshare it does not send audio from the desktop. For example, if you screenshare on youtube, video audio will not be sent. Is there a way to do this?

**Comment by pabloFuente** [comment]
I do not know if this is possible. Native screen capture api may not support getting as video track the audio ouput of the captured window/application/tab. Do a quick search on google to see if someone has faced the same problem when using JavaScript API `getUserMedia`.

With a little research, I can see that newest `getDisplayMedia` API that will allow Chrome to screen capture without an extension does not really support audio:
https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getDisplayMedia#Browser_compatibility

Even though the Web API standard does state it is possible: https://developer.mozilla.org/en-US/docs/Web/API/Screen_Capture_API/Using_Screen_Capture#Capturing_shared_audio

**Comment by zeshan321** [comment]
I'm using the chrome extension and have updated it to share audio. So, when they share tab or screen the option "share audio" appears.  Just never sent or used I think. Thanks for the help.

**Comment by pabloFuente** [comment]
Hi,

Could you share how you modified OpenVidu extension to allow screen audio capture?

Appreciate it, thanks.

**Comment by zeshan321** [comment]
Yup. I haven't really changed much in the extension. I just only added audio to screenOptions. 

I removed the if statements and just have it as the following in the method portOnMessageHanlder:

`screenOptions = ['screen', 'window', 'audio', 'tab'];
chrome.desktopCapture.chooseDesktopMedia(screenOptions, port.sender.tab, onAccessApproved);`

When I changed it to that, a checkbox appears when select which tab or window to share.

**Comment by desmat92** [comment]
@pabloFuente 
Is that possible to add the support of `getDisplayMedia` ?

**Comment by pabloFuente** [comment]
We will add it soon to openvidu-browser. You can always add it yourself to your app and then initialize a Publisher with the retrieved MediaStreamTrack:

```javascript
OpenVidu.initPublisher(targetElement, {
  videoSource: MEDIA_STREAM_TRACK // a MediaStreamTrack object
})
```

**Comment by willylee007** [comment]
> @pabloFuente
> Is that possible to add the support of `getDisplayMedia` ?

Chrome 72 has supported 'getDisplayMedia', but only supported { video: true }, not supported { video: true, audio: true } yet, it will throw 
`Failed to execute 'getDisplayMedia' on 'MediaDevices': Audio capture is not supported`

I will make a PR to support 'getDisplayMedia' later.  ✨

**Comment by zeshan321** [comment]
It's possible if you create a extension or possibly only available in tab capture? This shares audio and video using:

https://github.com/muaz-khan/Chrome-Extensions/tree/master/tabCapture

**Comment by zeshan321** [comment]
I was able to get audio and video working. Got streamid from chooseDesktopMedia with audio screen option included. Passed the streamid to the webpage. From there used getUserMedia with streamid constraint added to audio and video. This gets you the stream which includes the audio and video track which you can initialize with OV.

**Comment by netamity** [comment]
I realise this is closed, but I can't get this working. I've modified the extension and installed it in my browser, but it's not being used when I call
```
	function coachShareAudio(itok)
	{
		var OV = new OpenVidu();
		OV.setAdvancedConfiguration( { screenShareChromeExtension: "https://chrome.google.com/webstore/detail/NO_MATTER/oepfjjienbhamdaojclkddcknibnikmi" } );
		var sessionScreen = OV.initSession();

		sessionScreen.connect(itok).then(() => {
        var publisher = OV.initPublisher("coachSound", { videoSource: "screen" });

        publisher.once('accessAllowed', (event) => {
            publisher.stream.getMediaStream().getVideoTracks()[0].addEventListener('ended', () => {
                console.log('User pressed the "Stop sharing" button');
            });
            sessionScreen.publish(publisher);

        });

        publisher.once('accessDenied', (event) => {
            console.warn('ScreenShare: Access Denied');
        });

		}).catch((error => {
			console.warn('There was an error connecting to the session:', error.code, error.message);

		}));

	}
```
It just opens the same screenshare pop-up that has no audio checkbox. Any clues?

**Comment by scl2589** [comment]
> I realise this is closed, but I can't get this working. I've modified the extension and installed it in my browser, but it's not being used when I call
> 
> ```
> 	function coachShareAudio(itok)
> 	{
> 		var OV = new OpenVidu();
> 		OV.setAdvancedConfiguration( { screenShareChromeExtension: "https://chrome.google.com/webstore/detail/NO_MATTER/oepfjjienbhamdaojclkddcknibnikmi" } );
> 		var sessionScreen = OV.initSession();
> 
> 		sessionScreen.connect(itok).then(() => {
>         var publisher = OV.initPublisher("coachSound", { videoSource: "screen" });
> 
>         publisher.once('accessAllowed', (event) => {
>             publisher.stream.getMediaStream().getVideoTracks()[0].addEventListener('ended', () => {
>                 console.log('User pressed the "Stop sharing" button');
>             });
>             sessionScreen.publish(publisher);
> 
>         });
> 
>         publisher.once('accessDenied', (event) => {
>             console.warn('ScreenShare: Access Denied');
>         });
> 
> 		}).catch((error => {
> 			console.warn('There was an error connecting to the session:', error.code, error.message);
> 
> 		}));
> 
> 	}
> ```
> 
> It just opens the same screenshare pop-up that has no audio checkbox. Any clues?

For me, the screenshare option pops up, but it doesn't actually show the shared screen.
Anyone have ideas to it??
