### ISSUE TITLE
When will be a new article on medium about testing topology 1 to N?

### ISSUE THREAD

**Issue by t3mnikov** [OpenVidu/openvidu#197]
In conclusion of this [article](https://medium.com/@openvidu/openvidu-load-testing-a-systematic-study-of-openvidu-platform-performance-b1aa3c475ba9) you write that there will be a continuation. Can I know when?

I am interested in topology 1 to N

**Comment by micaelgallego** [comment]
We don't know yet... We are right focused in other fancy features...

**Comment by t3mnikov** [comment]
OK
