### ISSUE TITLE
When is the mcu architecture supported?

### ISSUE THREAD

**Issue by lyfunny** [OpenVidu/openvidu#198]
Now the multiplayer video consumes a lot of ports on the server side.

**Comment by micaelgallego** [comment]
MCU will consume a lot of CPU power in server side because all videos have to be decoded, mixed and re-encoded... 

It is in our mid term roadmap...

**Comment by lybest** [comment]
> MCU will consume a lot of CPU power in server side because all videos have to be decoded, mixed and re-encoded...
> 
> It is in our mid term roadmap...

If all are audio streams, will the CPU not become a bottleneck?

**Comment by pabloFuente** [comment]
For audio-only sessions MCU with track mixing is for sure the best solution. It will be taken into account for the future.

**Comment by deepinder10** [comment]
Is this still in the roadmap? When can we expect an MCU based architecture?

**Comment by micaelgallego** [comment]
Yep... but not in the short term roadmap.
