### ISSUE TITLE
Differents apps to Publisher and Subscriber

### ISSUE THREAD

**Issue by caioschristino** [OpenVidu/openvidu#199]
Its possible build a app just for Publisher and not open the Subscriber in same struct?

architecture sketch

<img width="584" alt="screen shot 2019-02-15 at 13 24 50" src="https://user-images.githubusercontent.com/15656147/52866332-8ff10880-3125-11e9-8398-664dd0c3e42d.png">

**Comment by pabloFuente** [comment]
Cannot see the image linked.

**Comment by pabloFuente** [comment]
Of course. You just have to connect the Publisher and the Subscriber to the same session. Code in the client side can be any way you want, total freedom to implement as many apps as you want.

Users connecting to the same session in OpenVidu Server (using a token for that session) will be able to communicate between them. That's the only rule.

**Comment by caioschristino** [comment]
the idea is scale the Subscriber.. 
i think i have two options of architecture

if i choose the architecture that app Subscriber register the session in the Publisher, but this limit the number of users
<img width="683" alt="screen shot 2019-02-15 at 13 52 57" src="https://user-images.githubusercontent.com/15656147/52867868-0d6a4800-3129-11e9-99b0-7c0b8e2327b5.png">

![1_odrtn_bpa3qs2o4a994nuq](https://user-images.githubusercontent.com/15656147/52867379-f7a85300-3127-11e9-8e70-bd7b49879076.png)
article [https://medium.com/@openvidu/openvidu-load-testing-a-systematic-study-of-openvidu-platform-performance-b1aa3c475ba9](url)

if i choose the architecture that app Subscriber register the session in the other struct with just KMS and OpenVidu (mirror), i can scale the Subscriber to N
<img width="466" alt="screen shot 2019-02-15 at 14 07 39" src="https://user-images.githubusercontent.com/15656147/52868679-2247db00-312b-11e9-9f21-0f2a05b7a5bb.png">

The question is: 
Its possible make a mirror from Publisher server? 
Or execute the steps of encode, transcode e decode in deferents servers? 

i accept ideas and hints about the architecture

ps: full-teaching <3

**Comment by pabloFuente** [comment]
Hi, sorry for the delay answering your question:

Communicating different Kurento Media Servers is possible. Long time ago Kurento team actually designed a pretty cool tree-shaped architecture that allowed to multiply the load supported by the system.

But this is not currently supported by OpenVidu platform. OpenVidu Server being the master node in charge of managing different video sessions and building their internal media pipelines, it does not currently contemplate the possibility of directly communicating two different Kurento servers. You will have to lower the level of abstraction to achieve this kind of behavior, working directly with Kurento.
