### ISSUE TITLE
openvidu-browser 0.1.0 is broken

### ISSUE THREAD

**Issue by alxhotel** [OpenVidu/openvidu#2]
Hey,

Since version `0.1.0`, this module is broken. I believe this is because the files needed to use it, such as `lib/index.js` does not exist.

Please let me know when this is fixed.

Thanks

**Comment by pabloFuente** [comment]
New version 0.1.1 already available in NPM should fix that. I tried to install again the package from NPM with 0.1.0 and it was indeed broken. After this patch update, I've been able to do so without any problem.

We are making major changes to this library in the incoming weeks, so it is possible that some issues appear.

Please, if 0.1.1 fixes your problem, proceed to close this issue. Thanks.

**Comment by alxhotel** [comment]
Nice. Thanks.
