### ISSUE TITLE
Docker image include Kurento media server?

### ISSUE THREAD

**Issue by TemoxaGreenMoney** [OpenVidu/openvidu#201]
Hello! I'm run docker image 

docker run -p 4443:4443 --rm -e openvidu.secret=MY_SECRET -e openvidu.publicurl=https://192.168.0.242:4443/  openvidu/openvidu-server-kms:2.8.0

after run example "openvidu-webcomponent" and video stream not play, but User1 and User2 can write message in chat, it's ok. 

For play video steam must install Kurento server?

**Comment by pabloFuente** [comment]
Of course. But video streams will only work fine when using the docker container for devices connected in the same network. To properly deploy OpenVidu and make it working in all cases, you must do it as Documentation states: with Amazon (https://openvidu.io/docs/deployment/deploying-aws/) or in Ubuntu (https://openvidu.io/docs/deployment/deploying-ubuntu/)
