### ISSUE TITLE
Updating Openvidu on a previous AWS cloudformation

### ISSUE THREAD

**Issue by jammer99** [OpenVidu/openvidu#205]
Hello, This may seem a very trivial question but how do i update openvidu server which was deployed via a AWS cloudformation script.
 
Is downloading and replacing openvidu-server.jar the preferred method or is it required to re-deploy the entire AWS stack?

Thanks.

**Comment by pabloFuente** [comment]
We will provide an automated mechanism to upgrade AWS OpenVidu deployment. Right now, the easiest way is to just launch a brand new CloudFormation, that will always use latest release of OpenVidu.

**Comment by jammer99** [comment]
But what about the earlier recorded videos? how do i migrate them automatically?

**Comment by pabloFuente** [comment]
You can now take advantage of Automatic upgrading capabilities of AWS deployments. Take a look at https://openvidu.io/docs/deployment/upgrading/
