### ISSUE TITLE
In Chrome 72+ screen sharing should work without extension

### ISSUE THREAD

**Issue by pacoloco71** [OpenVidu/openvidu#207]
Chrome72+ finally supports screen sharing without setting flags via an extension.

See [https://www.chromestatus.com/feature/6744724455030784](url)

openvidu-browser-2.8.0.js logs out the following error if trying to use screen sharing without chrome extension:

`OpenViduError {name: "SCREEN_EXTENSION_NOT_INSTALLED", message: "https://chrome.google.com/webstore/detail/openvidu-screensharing/lfcgfepafnobdloecchnfaclibenjold"}`

**Comment by pabloFuente** [comment]
This is already included in master branch. Will be available in next release.

**Comment by pabloFuente** [comment]
This is the commit updating openvidu-browser: https://github.com/OpenVidu/openvidu/commit/4f3cce732f26ce4c58827e6a9f3bffb018e8e5ce

**Comment by pacoloco71** [comment]
Great! Thanks for the info!
