### ISSUE TITLE
How to force the disconnection by token ?

### ISSUE THREAD

**Issue by johndeep2109** [OpenVidu/openvidu#211]
This api  `DELETE /api/sessions/<SESSION_ID>/connection/<CONNECTION_ID>` to force disconnection, but i don't know to get `CONNECTION_ID`. Can you make it easier by replacing CONNECTION_ID with TOKEN from api `POST /api/tokens`

**Comment by pabloFuente** [comment]
Token and connectionId are different concepts. Any user needs a valid token to connect to a session (and as result he will get a connectionId associated to that specific session). Currently tokens are single-use only, so one token will only generate one connectionId, but in the future this could change. We could have tokens that are valid during certain time span, and a user could use the same token to connect to the same session several times, for example to reconnect to it.

You have every `connectionId` associated to a session in both client-side and server-side. Every client will trigger `connectionCreated` event once it successfully calls `Session.connect` method (you just have to add a listener such as `Session.on('connectionCreated', connectionEvent => {})`), and also for every new user that connects to the session once he is connected to it.
In your server side, you can retrieve Session information just by calling methods `GET /api/sessions` or `GET /api/sessions/SESSION_ID`. The response brings any connection established to the session, with the proper `connectionId` parameter, so you can call any method that requires the connectionId.
