### ISSUE TITLE
Will Chroma Key video filter works with 2.8.0 openvidu

### ISSUE THREAD

**Issue by vattisampath** [OpenVidu/openvidu#213]
Hi, 
Thanks for great library . It makes our job very easy. Its all working good but not filters.

I m trying to apply "FaceOverlayFilter" and "ChromaFilter" with below code respectively.

publisher.stream.applyFilter("FaceOverlayFilter")
              .then(filter => {
                filter.execMethod(
                  "setOverlayedImage", {
                    "uri": "https://cdn.pixabay.com/photo/2013/07/12/14/14/derby-148046_960_720.png",
                    "offsetXPercent": "-0.2F",
                    "offsetYPercent": "-0.8F",
                    "widthPercent": "1.3F",
                    "heightPercent": "1.0F"
                  });
              });

            publisher.stream.applyFilter(
              "ChromaFilter", {
                "window": {
                  "topRightCornerX": 0,
                  "topRightCornerY": 0,
                  "width": 50,
                  "height": 50
                },
                "backgroundImage": "https://www.maxpixel.net/static/photo/1x/Cool-Blue-Liquid-Lake-Abstract-Background-Clear-316144.jpg"
              });

But none of them are working and also no errors both in  browser console and also on server log.

May I know what I was missing and why its not getting applied ... ? Is these filters functional , if not production ready, any plans of making them functional in future releases ... ?

**Comment by pabloFuente** [comment]
Sure, it works fine.
Take a look to this sample application: https://github.com/OpenVidu/openvidu-tutorials/tree/master/openvidu-filters

Just serve folder `/web`like this: `http-server openvidu-tutorials/openvidu-filters/web`
And run openvidu-server like with any other tutorial: `docker run -p 4443:4443 --rm -e openvidu.secret=MY_SECRET openvidu/openvidu-server-kms:2.8.0`

You will see that Faceoverlay filter works fine. Use this app as a starting point if you want.
