### ISSUE TITLE
Windows UWP Client

### ISSUE THREAD

**Issue by ghost** [OpenVidu/openvidu#214]
I am trying to implement a Windows UWP Client to work with openvidu-server, and I was wondering if there was any documentation available in regards to how the whole websocket process is setup?

For now, I've tried "reverse-engineering" the TypeScript code, but it would be very helpful if there was any documentation on the websocket api, messages etc.

Other than that I just want to say thank you for an amazing job.

**Comment by willylee007** [comment]
You can open Chrome Browser then open the chrome devtools by pressing F12 to check how the websocket works in OpenVidu.
<img width="931" alt="WX20190315-114016@2x" src="https://user-images.githubusercontent.com/16423055/54407110-8a341600-4717-11e9-9948-45ca343f5c27.png">

I use this way for developing or debugging quickly. 

But also you can search some requsts in the Session.ts file.

For documentation... I have no ideas, ha ha..

**Comment by stianbakken** [comment]
@willylee007 that is the way I have been doing it until now, but seeing as we're developing a client from scratch, it would be good to have a list of all possible events etc :) But thank you!

**Comment by pabloFuente** [comment]
Right now we don't have an offical list with all RPC methods available in openvidu-server. But we can do so if developers are interested in contributing other clients to the project, such as Windows UWP or native Android/iOS SDKs.

**Comment by pabloFuente** [comment]
Hi,
OpenVidu 2.10.0 supports building native desktop applications for Windows, OSX and Linux with Electron. You can check out [openvidu-electron]() tutorial.
We will still document openvidu-server RPC protocol so any dev may implement their own custom clients for other platforms. Closing this issue for now.
