### ISSUE TITLE
Support for electron in OSX??

### ISSUE THREAD

**Issue by Mhsanjib** [OpenVidu/openvidu#215]
Hi,
I am trying to implement openvidu in an electron app. But I am getting the error 

> There was an error connecting to the session: **somesession** Browser Electron for OS X is not supported in OpenVidu

Is there any workaround for this? 

Edit:
I managed to make it work by adding custom code to support Electron as browser ie 

> (browser !== 'Electron') 

 inside **checkSystemRequirements** function. Will this change give issues in the later phases?

**Comment by pabloFuente** [comment]
Did you managed to get it working on an Electron app for OSX?

**Comment by blgo** [comment]
I got it working by editing the useragent string in the webview:

```html
<webview 
id="webview" 
autosize="on" 
src="VIDEOSERVICE" 
data-home="VIDEOSERVICE" 
useragent="Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36">
</webview>
```

I also enabled webtools for debugging the webview:
```Javascript
<script>
const webview = document.querySelector('webview')
webview.openDevTools()
</script>
```

**Comment by blgo** [comment]
> I managed to make it work by adding custom code to support Electron as browser ie
> 
> > (browser !== 'Electron')
> 
> inside **checkSystemRequirements** function. Will this change give issues in the later phases?

@pabloFuente : is this solution good enough to create a pull request?

**Comment by pabloFuente** [comment]
Sure! Please create a PR and we will give it a try.

**Comment by pabloFuente** [comment]
Any update on that PR?

**Comment by Mhsanjib** [comment]
@pabloFuente I have opened a pull request for this fix. Please have a look into it #263 .

**Comment by pabloFuente** [comment]
Mhsanjib, could you provide us a sample application built with electron so we can give it a try? With just the minimum features to see that sending and receiving video with OpenVidu works fine. I have no Electron experience at all, but it would be awesome to see it working with this platform and maybe documenting an official Electron tutorial in OpenVidu Docs.

If you don't feel like publicly posting the application here, you can directly mail me (pablofuenteperez@gmail.com) so I can give it a try.

**Comment by Mhsanjib** [comment]
Sure, Here is the link to the app with the minimal features for macos.   @pabloFuente 
[https://s3.amazonaws.com/test-app007/testapp-openvidu.dmg](https://s3.amazonaws.com/test-app007/testapp-openvidu.dmg)
Username: testuser@fortest.com
Password: (anything more than 6 digits)

Note: Only 2 users can join a room at a time

**Comment by Mhsanjib** [comment]
closing this issue..  #263 fix has been merged.
