### ISSUE TITLE
Chat dissapears in mobile phones

### ISSUE THREAD

**Issue by ngertrudiz** [OpenVidu/openvidu#216]
I tested openvidu in android mobile phones, chat messages are not showing. I used in different web navigators.

**Comment by pabloFuente** [comment]
What are you talking about? A specific tutorial? A demo?

**Comment by ngertrudiz** [comment]
In demo openvidu-call, available at https://demos.openvidu.io/openvidu-call/#/

**Comment by pabloFuente** [comment]
Yes, you are right. Though that version of the demo is pretty old, and some bugs in mobile browsers may be present. New version being released really soon will fix this problem.

Regards
