### ISSUE TITLE
Support for 4k resolution

### ISSUE THREAD

**Issue by Mhsanjib** [OpenVidu/openvidu#217]
Hi, I am trying to record the videos having 4k resolution. I tried changing the resolution parameter as 
```
const recordingProperties = {
      outputMode: "COMPOSED",
      hasAudio: true,
      hasVideo: true,
      recordingLayout: "CUSTOM",
      resolution: "4096x2048"
    };
```
but its giving the 422 error(meaning **resolution parameter exceeds acceptable values** according to the openvidu docs, only supports up to 1999px*1999px).
Is there any way for recording the 4k videos? I am using the node version, server is hosted in aws. Can I increase the capacity of server to be able to record 4k videos?

**Comment by pabloFuente** [comment]
As you already noticed, resolution is limited to 1999 pixels for both width and height, so you won't be able to record with COMPOSED option in 4K. That said, I don't think it really matters, because 4K media transmission is not supported by OpenVidu, so the recorded file would have a resolution that would not match the received video in any case.

**Comment by Tushant** [comment]
Since, I too have the requirement for 4k resolution recording, i would like to know if there is a support for 4k resolution in `individual` recording. If the support is not yet available, could you tell if there is any plan to support it in near future, please?

**Comment by Mhsanjib** [comment]
I have tried with individual recordings as well and it failed with same issue. Can we atleast tweak the server to support 4k recordings (INDIVIDUAL will do as well). @pabloFuente as you have mentioned 

> you won't be able to record with COMPOSED option in 4K

maybe we are doing something wrong here. Please can you suggest some ways or else we will have to change the complete implementation. Thanks.

**Comment by pabloFuente** [comment]
Individual recordings don't support changing its resolution. The recorded resolution will be the one of the native video being published in this case.

Resolution is limitted in this method: https://github.com/OpenVidu/openvidu/blob/master/openvidu-server/src/main/java/io/openvidu/server/utils/FormatChecker.java#L22-L26

It is a regex expresion that allows resolutions from 100px to 1999px, for both width and height. You could tweak that method as you want, but we cannot assure you that it will work ok if you exceed recommend resolution.
