### ISSUE TITLE
Browser Package: Video controls not showing up

### ISSUE THREAD

**Issue by tibinvpaul** [OpenVidu/openvidu#218]
I am using version 2.8.0 of OpenVidu Server and Browser. The video is coming blank in Safari (Version 12.0.2 and OS Mojave) but works fine when I manually play it. I am trying to use `controls` attribute of HTML5 `video` tag to display the controls by default but seems like the [browser code](https://github.com/OpenVidu/openvidu/blob/master/openvidu-browser/src/OpenVidu/StreamManager.ts#L346) is removing it. How can I display player `controls` by default in all the browsers? Thank you!

**Comment by pabloFuente** [comment]
This must be related to the Safari policy of not allowing autoplay on videos with audio tracks. Here you have a FAQ talking about it: https://openvidu.io/docs/troubleshooting/#11-my-safari-users-with-role-subscriber-are-not-able-to-receive-any-remote-video

As you will see in the FAQ, this should only happen for those users that do not publish audio or video. As soon as they grant access to the camera, rest of videos will start playing automatically.

You can easily show video controls thanks to event [videoElementCreated](https://openvidu.io/api/openvidu-browser/classes/videoelementevent.html). This event is triggered by a Publisher or Subscriber once OpenVidu has inserted a video in the DOM.

```javascript
publisherOrSubscriber.on('videoElementCreated', event => {
  event.element.controls = true;
});
```

**Comment by tibinvpaul** [comment]
The solution under the `troubleshooting` page resolved the issue. Thanks, @pabloFuente.
