### ISSUE TITLE
unable to launch new aws cloudformation

### ISSUE THREAD

**Issue by rush86999** [OpenVidu/openvidu#219]
the error i get is related to the WaitCondition

```
Failed to receive 1 resource signal(s) within the specified duration
```
I am trying to use let's encrypt process to get the stack launched. I tried many combinations but I am not sure why it keeps failing. Is there something else I need to do for the Let's encrypt approach to launch a stack? The only thing I keep changing is the type of ec2 instance, ebs size and iops to see if something works but nothing did. I also don't need 100 gb. 

my second question is: Am I able to use a t2.medium?

**Comment by pabloFuente** [comment]
You must pair your domain name with the AWS Elastic IP of your choice, usually through your DNS provider. Only after you are able to reach your Elastic IP through your domain name Let's Encrypt deployment will work.

Yes, you can use a t2.medium. Here you have some information about OpenVidu performance: https://openvidu.io/docs/troubleshooting#9-which-is-the-current-status-of-openvidu-on-scalability-and-fault-tolerance

**Comment by rush86999** [comment]
I am only looking for 1:1 sessions with two way communication. thanks . I think this is resolved.
