### ISSUE TITLE
Flutter Package

### ISSUE THREAD

**Issue by abinvp** [OpenVidu/openvidu#220]
Is there any plans to release a flutter package? We just finished our web integration which is going live in a few weeks. Would like to know if there is a plan to release a flutter package in the near future.

**Comment by micaelgallego** [comment]
We aren't flutter developers, and we don't have plans to create a Flutter client for OpenVidu. 

If you implement it, it would be glad if you share it with the community

**Comment by abinvp** [comment]
Sounds good. Wanted to make sure this isn't in your roadmap before we start developing.

**Comment by andrisole92** [comment]
I would gently add flutter and iOS support. I like OpenVidu, but it needs more work.

**Comment by robin3317** [comment]
@andrisole92 do you start working on it(flutter support of openvidu) ?
