### ISSUE TITLE
aw snap when compositing video

### ISSUE THREAD

**Issue by Tushant** [OpenVidu/openvidu#221]
Before going over issue, i would like to tell the use case of the application first.

There can only be two party in the specific room for video calling along with screen sharing. The recording starts when both the party joins in the room. There can be three stream(two webcam feed and screen sharing). The screen sharing will be the background of the video and two webcam feeds are on the right and left according to the layout designed in html. When those streams are composited using custom layout, we get `aw snap` issue in between most of the times after playing the video correctly for short interval. 

Here is the screen shot of what issue we are getting 
![Image of issue](https://i.imgur.com/sQQTCko.png)

What might be the reason for this? Is this related to server or its an issue in openvidu side or probably we did the wrong way?

**Comment by pabloFuente** [comment]
Hi,

I think this is a bug we encountered and fixed just a few days ago. It was a really challenging bug, related to the recording of screen share streams in the composed mode. To sum up, the specific nature of these streams seems to require more shared memory to be played inside the Docker container. We have already fixed it in the master branch, and will be available in next release 2.9.0. Hopefully launched very soon.

Regards.

**Comment by Tushant** [comment]
Thanks for your prompt reply. Its great to hear the bug is resolved, however, i have one confusion as you have told `inside the Docker container`. Does that means the issue occurs only inside a docker container? But I am running it in the server as 

> java -jar -Dopenvidu.recording=true openvidu-server.jar

I don't suppose the openvidu server will run inside a docker container in this case. Can you also suggest the optimal server configuration for this type of setup(composite recordings of two or more sessions running simultaneously)? 
Will be waiting for the 2.9.0 release, Thanks.

**Comment by pabloFuente** [comment]
Sorry for the confusion, I was refering to the Docker container used by the composed recording service.

OpenVidu will always use a Docker container to perform COMPOSED recordings with video. For INDIVIDUAL recordings or composed audio-only recordings, no container is used and streams are directly stored in the host machine (this is, on the other hand, a much more efficient process. It is recommended to use INDIVIDUAL recording when possible).

This container for COMPOSED recording is the one failing with the snap! error.

Regards

**Comment by Tushant** [comment]
Thank you for clearing the confusion and also for the suggestion. I am closing this one as the bug has been already resolved. Hoping for 2.9.0 release to happen very soon. :)

Thanks
