### ISSUE TITLE
kurento cannot make webrtc call on chrome 74.0.3729.28 beta

### ISSUE THREAD

**Issue by MiaSanMia** [OpenVidu/openvidu#222]
https://groups.google.com/forum/#!searchin/discuss-webrtc/Removing$20TLS$201.0$2C$20TLS$201.1$20and$20DTLS$201.0$20support$20from$20WebRTC|sort:date/discuss-webrtc/OhMcXQOA_wE/vaWApOE4AwAJ

so how to specify dtls 1.2 on kurento?

**Comment by pabloFuente** [comment]
Refering to https://github.com/Kurento/bugtracker/issues/355#issuecomment-478970008
