### ISSUE TITLE
ICE failed in Firefox with many requests, worked for Safari, Opera, Chrome

### ISSUE THREAD

**Issue by ZhiliangGong** [OpenVidu/openvidu#224]
Deployed the server on Linux 16.04 on Google Cloud compute engine, set up DNS for custom domain name, the test app worked for Opera, Safari, Chrome, but does not work for Firefox and Chrome Canary.

Safari (also worked for Chrome and Opera):
<img width="1119" alt="image" src="https://user-images.githubusercontent.com/15947070/55270966-d2a11700-5273-11e9-9298-801b8700d8e1.png">

Firefox reports ICE failed:
<img width="1134" alt="image" src="https://user-images.githubusercontent.com/15947070/55270989-2dd30980-5274-11e9-81bc-df73efdeb694.png">
As you can see, Firefox sent many ICE requests:
![image](https://user-images.githubusercontent.com/15947070/55277835-673a6200-52d2-11e9-8b3e-afef6fbd2e5e.png)

Chrome Canary won't show video:
<img width="1123" alt="image" src="https://user-images.githubusercontent.com/15947070/55271008-55c26d00-5274-11e9-9096-f5c23b55b9e7.png">

**Comment by ZhiliangGong** [comment]
The problem persists with Google Cloud instances, but the cloud formation stack on AWS worked.

**Comment by anidotnet** [comment]
I am seeing the same issue with firefox. I am running this demo - https://openvidu.io/demos#4 via docker compose. Simple setup, nothing to go wrong. The example works perfectly with Chrome (both desktop and mobile). But firefox (both desktop and mobile) showing me blank screen.

![image](https://user-images.githubusercontent.com/696662/58752319-77391280-84ca-11e9-855f-47c55e9be0bd.png)

I am running the demo from a virtualbox image of ubuntu

```
Ubuntu 18.04.2 LTS (GNU/Linux 4.15.0-50-generic x86_64)

System information as of Sat Jun  1 18:39:44 UTC 2019

System load:  0.11              Users logged in:                1
Usage of /:   70.2% of 9.78GB   IP address for enp0s3:          192.168.31.26
Memory usage: 85%               IP address for enp0s8:          10.0.3.15
Swap usage:   29%               IP address for docker0:         172.17.0.1
Processes:    112               IP address for br-6e882df0acc2: 172.18.0.1
```
Accessing the demo from host browser which is also ubuntu

```
Ubuntu 19.04 (GNU/Linux 5.0.0-15-generic x86_64)
Chrome: Version 74.0.3729.169 (Official Build) (64-bit)
Firefox: Quantum 67.0 (64-bit)
Firefox (Android): 67.0
```

**Comment by pabloFuente** [comment]
Do demos.openvidu.io work fine in your Firefox browser?

**Comment by anidotnet** [comment]
@pabloFuente yes it works perfectly. Then why don't the docker images?

**Comment by pabloFuente** [comment]
Then it must be something related to your specific setup. You have an Ubuntu 19.04 machine, where you have launched an Ubuntu 18.04 in a VirtualBox to run the docker-compose, and you are accessing the demo from a Firefox instance installed in the Ubuntu 19.04 machine. Is that right?

**Comment by pabloFuente** [comment]
If so, then I don't really understand why are you doing that. Why don't you just launch docker in your Ubuntu 19.04 host machine? OpenVidu being supported only in Ubuntu 16.04 and 18.04 is just a thing for production environments. It needs Ubuntu 16.04 or 18.04 to run as a _native service_, but if you are running it as a Docker container for development purposes, you can launch it in any OS you like: Linux, Windows, OSX...

**Comment by anidotnet** [comment]
Your assumption is right. Actually my aim is to run openvidu on digital ocean droplet. So I tried to create such environment using virtualbox in my ubuntu host machine. Anyway in my host machine I ran the docker image directly by `docker run -p 4443:4443 -e openvidu.publicurl=https://192.168.31.162:4443/ openvidu/basic-videoconference-demo
`, here also same result. Firefox can't open the session. Where as in chrome I can do that without hiccups in my host ubuntu.

![image](https://user-images.githubusercontent.com/696662/59060681-391f6280-88bf-11e9-818e-615ca2af98e4.png)

**Comment by silmood** [comment]
@anidotnet I got the same problem in firefox when i used self signed certificates in AWS deployment. Apparently Firefox doesn't allow WS connections with a server which has a self signed certificate. [More infor](https://bugzilla.mozilla.org/show_bug.cgi?id=1187666)

**Comment by anidotnet** [comment]
@silmood I resolved it by going to https://ip-address:4443 and adding an exception in Firefox. 

But for production using self signed certificates is not recommended, I did it inly for development.
