### ISSUE TITLE
Is there any automation tool to test the performance of openvidu server?

### ISSUE THREAD

**Issue by Prasanna223** [OpenVidu/openvidu#226]
we are working on webRTC and using OpenVidu as a media server.As we are new to OpenVidu,need some guidance about testing and fine-tuning the openVidu server.

**Comment by pabloFuente** [comment]
What are you looking for exactly? We published a few months ago a post explaining our load testing environment: https://medium.com/@openvidu/openvidu-load-testing-a-systematic-study-of-openvidu-platform-performance-b1aa3c475ba9

It is open source, so any one can replicate it: https://github.com/OpenVidu/openvidu-loadtest. It is meant to be executed on AWS. But I don't know if that's what you are asking for :)
