### ISSUE TITLE
Please fix StreamManager.createVideoElement by id (openvidu-browser js)

### ISSUE THREAD

**Issue by githb-user** [OpenVidu/openvidu#227]
https://github.com/OpenVidu/openvidu/blob/3ad698f6d57c8e5b45b4b37856775dd721b5e44d/openvidu-browser/src/OpenVidu/StreamManager.ts#L286

I am not typescript coder. But it seems that at this place "targEl" must be replaced with "targetElement". Сonsequently always rises error "The provided 'targetElement' couldn't be resolved to any HTML element".

**Comment by pabloFuente** [comment]
You are totally right. Already fIxed in 3abf26d8ca7d352ab5797191153b27d5e607651e
