### ISSUE TITLE
Does OpenVidu Support 1080p resolution?

### ISSUE THREAD

**Issue by pavankuppa** [OpenVidu/openvidu#228]
Need to stream 1920x1080 resolution of video

**Comment by j1elo** [comment]
Does OpenVidu Support 1080p resolution?
-> Maybe but you should test and see if it works for you
https://doc-kurento.readthedocs.io/en/latest/user/troubleshooting.html#cpu-usage-grows-too-high

> Currently Kurento has performance issues with source videos bigger or equal to 720p. 1080p is not recommended (although it might work but the Kurento team hasn’t done any factual analysis to prove it).
