### ISSUE TITLE
OpenVidu Pro

### ISSUE THREAD

**Issue by bolgi19** [OpenVidu/openvidu#229]
Hi,

what are the news on the pro version? Any plans to release it?

A related question. I need 20,30 channels with 1-10 people inside. Would it be able to solve this problem?

Thanks a lot,
Blago

**Comment by micaelgallego** [comment]
We are working on OpenVidu Pro right now. It will be released very soon.

We plan to develop OpenVidu Pro in several phases. Scalability is planned to be available in a few months from now.

**Comment by DustinnBel** [comment]
@micaelgallego What kind of features does the pro version have in advantage of the normal version?

**Comment by pabloFuente** [comment]
We will release OpenVidu Pro later today if everything goes as expected. OpenVidu docs will be updated with all necessary information about it.

Stay tuned

**Comment by DustinnBel** [comment]
And I read everything about auto scalability etc, so that takes a few months from now?

**Comment by micaelgallego** [comment]
We are working very hard on scalability and fault tolerance... we will release as soon as it is available.

**Comment by pabloFuente** [comment]
OpenVidu Pro is available now for free while it is a preview version. Check out release 2.9.0 for further info

**Comment by jinshuai7777** [comment]
I have created OpenVidu Pro but can't call APIs using URL:4443.
I am using letsencrypt.
