### ISSUE TITLE
recording sessions

### ISSUE THREAD

**Issue by SusanaCastela** [OpenVidu/openvidu#23]
Hi,
I'm considering diverse technologies to start a video call based project. I would like to know if recording video calls is already implemented or which is the state of its implementation (since this is crucial to the project). Thank you very much

**Comment by pabloFuente** [comment]
Hi:

Session recording is the next feature we are adding to the platform. A first working version should be available in the following weeks.

Thanks.

**Comment by pabloFuente** [comment]
Our first recording service prototype is available now under release 1.7.0. Check our updated Docs to learn more: [http://openvidu.io/docs/advanced-features/recording/](http://openvidu.io/docs/advanced-features/recording/)
