### ISSUE TITLE
Recording both output mode ie INDIVIDUAL and COMPOSED at the same time

### ISSUE THREAD

**Issue by Mhsanjib** [OpenVidu/openvidu#231]
Can we record the session with both **INDIVIDUAL** and **COMPOSED** mode at the same time resulting into 2 separate recording parts? I tried calling the the record function(api) one with "INDIVIDUAL" mode and another with "COMPOSED" mode simultaneously, but the result I am getting is different. Sometimes I would get "409" error on the second api call and sometimes both call would run without error, but the final output video is broken in that case.
So the question is `Is it possible to record both output mode simultaneously`?

**Comment by pabloFuente** [comment]
You can only start one recording at a time for each session right now. So starting a COMPOSED and a INDIVIDUAL recording is not possible. As you can see here https://openvidu.io/docs/reference-docs/REST-API/#post-apirecordingsstart in HTTPResponses section, a `409` is sent if the session is already being recorded
