### ISSUE TITLE
what's the issue with p2p?

### ISSUE THREAD

**Issue by rush86999** [OpenVidu/openvidu#235]
Is there a reason why p2p is not supported? Getting the load off extra server bandwidth would be a big win and there might be more interest in openvidu as well

**Comment by micaelgallego** [comment]
There is no technical reasons to not have p2p in OpenVidu. We are focused
implementing other features and p2p is below in the roadmap...

**Comment by rush86999** [comment]
ok thanks, any eta for this implementation?

**Comment by micaelgallego** [comment]
Not yet sorry...
