### ISSUE TITLE
Miss a "catch" event in the Publisher.ts

### ISSUE THREAD

**Issue by willylee007** [OpenVidu/openvidu#236]
Hi, I'm back~
I found missing a "catch" event in the Publisher.ts(line: 522) after codeview.
Best regards~

**Comment by ZhiliangGong** [comment]
Do you mean this line?

https://github.com/OpenVidu/openvidu/blob/39ccdc19f22d07d27ae5aca395206c8f965ff615/openvidu-browser/src/OpenVidu/Publisher.ts#L522

**Comment by willylee007** [comment]
navigator.mediaDevices['getDisplayMedia']({ video: true })
                                .then(mediaStream => {
                                    afterGetMedia(mediaStream, definedAudioConstraint);
                                });
This promise miss a catch.
[openvidu/openvidu-browser/src/OpenVidu/Publisher.ts](https://github.com/OpenVidu/openvidu/blob/39ccdc19f22d07d27ae5aca395206c8f965ff615/openvidu-browser/src/OpenVidu/Publisher.ts#L551)
You can commit a PR.
感谢.
Thx.

**Comment by pabloFuente** [comment]
Already fixed in commit 70605976904bc522f65f510b3153a880544a911b
