### ISSUE TITLE
v2.9.0 ICE Candidate bug

### ISSUE THREAD

**Issue by ifed3** [OpenVidu/openvidu#237]
Hey folks, thanks for pouring your heart into this project. It's been a blast using the software. 

I was able to succesfully deploy v2.9.0 on AWS. I could also start a stream via my Chrome browser on the server. However whenever other clients would connect, I can't see their videos. I also get this error: https://github.com/OpenVidu/openvidu/blob/e3a25748528b3067e77bb846cefea303094002c5/openvidu-browser/src/OpenVidu/Session.ts#L882

Any thoughts?

**Comment by davidkumru** [comment]
It is possibly caused by a mismatch between the server and client versions (2.9.0 vs 2.8.0). Try updating the client packages.

**Comment by ifed3** [comment]
@davidkumru, that worked! thanks for your prompt response
