### ISSUE TITLE
Openvidu Pro - Deploy on AWS

### ISSUE THREAD

**Issue by gabber49** [OpenVidu/openvidu#238]
I'm following the steps in this url but i encountered issues trying to create the application on AWS Cloudformation stack....

Is there anyone who can point me to a solution? thank you.

https://openvidu.io/docs/openvidu-pro/deploying-openvidu-pro/ 

The specified instance type can only be used in a VPC. A subnet ID or network interface ID is required to carry out the request. (Service: AmazonEC2; Status Code: 400; Error Code: VPCResourceNotSpecified; Request ID: b5d036eb-ab3e-47e8-89cd-62ba96f81f75)

**Comment by micaelgallego** [comment]
Thank you for reporting. 

We will take a look on Monday 22nd when we come back from holidays

**Comment by pabloFuente** [comment]
Please check that this is not happening to you:
https://openvidu.io/docs/troubleshooting/#13-deploying-openvidu-in-aws-is-failing
