### ISSUE TITLE
preview of all live videos sessions

### ISSUE THREAD

**Issue by MyNameIsAlaa** [OpenVidu/openvidu#239]
Hello,

is it possible to get a preview of all live videos sessions?

**Comment by micaelgallego** [comment]
Can you describe exactly what do you mean by "preview"? In the inspector? In your app? For all publishers individually? Only for a mix between all of them?

**Comment by MyNameIsAlaa** [comment]
Thank you for your quick reply @micaelgallego 
I want to view all active videos sessions in one place, like inspector's Recording management but instead of viewing recorded videos i want to view live videos from all active sessions in the server, for administrative purposes

**Comment by micaelgallego** [comment]
This is not possible right now, but you can implement it if you want. You only have to create an special user "moderator" that subscribes to all presenters in sessions.

**Comment by melvingilberto** [comment]
You can save all tokens generated on a stack, the problem is when the users unsubscribe to session on some moment, somtimes do not close session, so you will see some session active when really is closed

**Comment by pabloFuente** [comment]
If the moderator user is connected to the session to subscribe to every Publisher of it and that way have your "all streams view", then it will have to be managed as any other user too. So, for example, session won't be close until this user also leaves the session. Remember you can use openvidu-server REST API (or Java/Node client) to manually manage your sessions.
