### ISSUE TITLE
 sessionid return `null/1biftlug3q11p9hbrps6i2kvs2`

### ISSUE THREAD

**Issue by hexiao-o** [OpenVidu/openvidu#24]
Hi,
I just updated the 1.5.0, but returned after call getSessionId is `null/1biftlug3q11p9hbrps6i2kvs2`,

openvidu-browser: 1.5.0
openvidu/openvidu-server-kms: 1.5.0 
openvidu-node-client: 1.1.0

Can you help me see what the problem is? Thank you very much

**Comment by pabloFuente** [comment]
Are you using OpenVidu locally or are you deploying it? If you are deploying it manually, what command are you using for launching OpenVidu Server?

Manual deployment and automatic deployment with Amazon CloudFormation have been tested several times and it works OK in 1.5.0, so this must be a problem with your setup. You can try to deploy everything from scratch and see if it works OK.
