### ISSUE TITLE
Cordova example

### ISSUE THREAD

**Issue by fabianpie** [OpenVidu/openvidu#240]
I was trying to use openvidu with cordova iosrtc plugin, but I couldn't make it work. Does anybody have a working example ?

**Comment by micaelgallego** [comment]
We have tested only with Ionic 4. Behind the scenes is algo Cordova... Then, it should work.

If you manage to make it working, please share with the community.

**Comment by pabloFuente** [comment]
openvidu-ionic tutorial (https://openvidu.io/docs/tutorials/openvidu-ionic/) works fine with cordova iosrtc plugin. It is built with latest Ionic 4 release.
