### ISSUE TITLE
Openvidu for live-streaming product

### ISSUE THREAD

**Issue by aliuadepoju** [OpenVidu/openvidu#244]
My team is looking at building a live-stream platform similar to periscope with Openvidu. 

Example:
One To Many Broadcast
User A broadcast to User B - Z
User B - Z only view broadcast from User A

We're curious to have foreknowledge of using Openvidu for such project,
What do  we need to know? 
Thanks. Regards

**Comment by melvingilberto** [comment]
Check OpnviduRole https://openvidu.io/api/openvidu-node-client/enums/openvidurole.html

**Comment by pabloFuente** [comment]
Hi,

Please, do not use GitHub issues fot this kind of questions. Better use Google Group for this kind of support: https://groups.google.com/forum/#!forum/openvidu. There we can further discuss any doubts you may have.

**Comment by aliuadepoju** [comment]
Alright
