### ISSUE TITLE
RTSP IP camera => Safari IOS

### ISSUE THREAD

**Issue by bertcoenen** [OpenVidu/openvidu#245]
Hi,

I've read the thread about the RTSP support not being implemented before Q1 (https://github.com/OpenVidu/openvidu/issues/191)  

Is it plannend to have it in Q2? or is it already possible to convert a RTSP stream from an IP camera to webRTC, to be displayed on safari IOS?
Is it advised to make a webapp to be supported for multiple devices? 
Or should we follow the ionic tutorial for displayed RTSP streams on a Ipad/Iphone?

Thanks in advance

**Comment by yoyomule** [comment]
Hi，did you do it later?

**Comment by micaelgallego** [comment]
RTSP will be available in 2.12 version (due to 16th of March)
