### ISSUE TITLE
Openvidu Recording  Error 500

### ISSUE THREAD

**Issue by zzdd1558** [OpenVidu/openvidu#249]
Hi
I have a question about the issue and wrote something like this.
First, thank you for providing open source platform for media server.

What I would like to ask you is implementing the direct recording function in Java. If I click on Stop and click the Record button again while recording, I get an error. I was worried about how to handle this part.

나는 현재 Recording을 Java 로 구현하여 사용하고있습니다 .

`
Recording saveRecording = openVidu.stopRecording(recordings.get(confUuid).getId());
`

Current 
`
private ConcurrentHashMap <String, Recording> recordings = new ConcurrentHashMap <> ();
`
The code stores the Recording object and stops the saved Recording object.

openvidu server Error log 

`
java.lang.NullPointerException: null
114658         at io.openvidu.server.recording.RecordingInfoUtils.videoWidth(RecordingInfoUtils.java:98)
114659         at io.openvidu.server.recording.service.ComposedRecordingService.stopRecordingWithVideo(ComposedRecordingService.java:308)
114660         at io.openvidu.server.recording.service.ComposedRecordingService.stopRecording(ComposedRecordingService.java:104)
114661         at io.openvidu.server.recording.service.RecordingManager.stopRecording(RecordingManager.java:212)
114662         at io.openvidu.server.rest.SessionRestController.stopRecordingSession(SessionRestController.java:490)
114663         at sun.reflect.GeneratedMethodAccessor143.invoke(Unknown Source)
114664         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
114665         at java.lang.reflect.Method.invoke(Method.java:498)

`

**Comment by zzdd1558** [comment]
OMG , 2.9.0 bugfix checked.

**Comment by pabloFuente** [comment]
Is it fixed, then?

**Comment by zzdd1558** [comment]
I could not solve the error directly, and gave the user 3 seconds to count and give him time to prepare for the recording. It seems to be solved by a shortcut rather than a solution.
