### ISSUE TITLE
Open files leak

### ISSUE THREAD

**Issue by steelden** [OpenVidu/openvidu#250]
OpenVidu server 2.8.0, running under systemd.

We ran into open files errors last night, and video server was not responding.
Logs were filled with this:
May 14 08:23:46 video java[17485]: [ERROR] 2019-05-14 08:23:46,821 [3-Acceptor-0] org.apache.tomcat.util.net.NioEndpoint (log) - Socket accept failed
May 14 08:23:46 video java[17485]: java.io.IOException: Too many open files
May 14 08:23:46 video java[17485]:         at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
May 14 08:23:46 video java[17485]:         at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422)
May 14 08:23:46 video java[17485]:         at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
May 14 08:23:46 video java[17485]:         at org.apache.tomcat.util.net.NioEndpoint$Acceptor.run(NioEndpoint.java:456)
May 14 08:23:46 video java[17485]:         at java.lang.Thread.run(Thread.java:748)

After some investigation I narrowed the problem down to GET /recordings call we do every 10 minutes. After every call I checked `lsof 17134 | wc -l` and it was steadily increasing. In the list of open files (`lsof -p 17134 | sort -k 9`) were lots of duplicate references to .recording files, like this:
java    17134 root  231r      REG               8,17      329 540660218 /mnt/video/archive/61801f6c455d4fbcb836ec9b2de58efb/.recording.61801f6c455d4fbcb836ec9b2de58efb
java    17134 root  253r      REG               8,17      329 540660218 /mnt/video/archive/61801f6c455d4fbcb836ec9b2de58efb/.recording.61801f6c455d4fbcb836ec9b2de58efb
java    17134 root  273r      REG               8,17      329 540660218 /mnt/video/archive/61801f6c455d4fbcb836ec9b2de58efb/.recording.61801f6c455d4fbcb836ec9b2de58efb
java    17134 root  296r      REG               8,17      329 540660218 /mnt/video/archive/61801f6c455d4fbcb836ec9b2de58efb/.recording.61801f6c455d4fbcb836ec9b2de58efb

Looks like openvidu process hit open files limit (default limit for systemd is 4096).
So I looked at the code and it seems the issue is at [RecordingManager line 362](https://github.com/OpenVidu/openvidu/blob/4e1a080232e3d3eb646e79e1c40b4cec52c87f33/openvidu-server/src/main/java/io/openvidu/server/recording/service/RecordingManager.java#L362)

Can some one look at this problem?

**Comment by pabloFuente** [comment]
Sure, we will take a look. Maybe there's some reader that is not properly closed.

**Comment by pabloFuente** [comment]
Okey, this commit should fix the problem: https://github.com/OpenVidu/openvidu/commit/fb41e6c19312d76ad0dabefd616b07d9115f746d

Next release will bring this fix. If you want to try the master version of openvidu-server, you can compile it with these commands:

```
git clone https://github.com/OpenVidu/openvidu.git
cd openvidu
mvn -DskipTests=true clean install
cd openvidu-server
mvn clean package
```

**Comment by steelden** [comment]
Thanks a lot for help 👍
Will try this fix asap.
