### ISSUE TITLE
Default recording resolution

### ISSUE THREAD

**Issue by steelden** [OpenVidu/openvidu#251]
Hello,

I'm using `POST /api/sessions` to start a session and recording at the same time.
With this API one can set defaultOutputMode or defaultRecordingLayout.
But there is no way to specify resolution the conference is going to be recorded with.
And it will record it using default resolution 1920x1080 which puts quite a load on the server's CPU.
While I managed to fix this by building my own version of recording docker container I don't think thats a good solution.

So I thought it would be great if you could simply specify "defaultResolution" in `POST /api/sessions` and set recording resolution the same way as in `POST /api/recordings/start`.

Thanks!

**Comment by pabloFuente** [comment]
We can study this proposal. Sessions configured with ALWAYS recording mode can set the following properties: 
`defaultCustomLayout, defaultOutputMode, defaultRecordingLayout`

But they will always record both audio and video (while MANUAL recordings allow audio-only and video-only recordings) and resolution is fixed to 1080p.

This decission was made as a compromise between API simplicity and freedom of recording customization. As ALWAYS recordings is just a shortcut (you can just pass to MANUAL recording, that would simply require you to programatically start the recording just after the session starts and stop it when it is closed, as ALWYAS recording does), this is not a limiting condition at all.

But I will save this proposal in the roadmap so we can reconsider it in the future. Closing this issue for now.
