### ISSUE TITLE
Chromium crash while recording

### ISSUE THREAD

**Issue by steelden** [OpenVidu/openvidu#252]
Hello,

OpenVidu 2.8.0, running on ubuntu 16.4, under systemd.
Conferences started by `POST /api/sessions` with `recordingMode=ALWAYS`, `defaultOutputMode=COMPOSED` and `defaultRecordingLayout=BEST_FIT`.
Any session has 2 clients at most.

Sometimes chromium page just crashes while being recorded.
Ffmpeg continues its work and record empty screen with error.
This error happens from time to time, mostly when one of the clients on a mobile and unstable connection. It can happen everywhere in the middle of a session.
Sadly there are no chromium logs and no errors in openvidu logs.

Right now I can't find logs from a session with crashed chromium, but I'll try to find some.

Error screen:
![chromium_error](https://user-images.githubusercontent.com/1427114/57709626-15784c00-7674-11e9-8843-96a430a896f5.png)

Video with error at 0:24.
[9d7fc050c5434749918e9d1a87f843e0.zip](https://github.com/OpenVidu/openvidu/files/3178548/9d7fc050c5434749918e9d1a87f843e0.zip)

For us this problem is critical because we are required by law to keep records of every conversation.
Is there any way we can debug it further or fix it somehow?

Thanks!

**Comment by pabloFuente** [comment]
Hi,

There was a shared memory problem in the recording container in release 2.8.0
Maybe this is what's happening to you. Try upgrading to 2.9.0

**Comment by steelden** [comment]
Thanks!
I'll give it a try when I have time.

**Comment by pabloFuente** [comment]
Ok, I'll close this issue in the meantime. If you still have this problem after upgrading to 2.9.0, please reopen it then.
