### ISSUE TITLE
Error when saving the recordings

### ISSUE THREAD

**Issue by BritoMatheus** [OpenVidu/openvidu#253]
Hi,

I tried to record but when I saved the videos the only thing saved was a black screen so I tried to custom the layout and it also didn't work.

What can I do to save videos correctly? or someone has a layout example? (https://openvidu.io/docs/advanced-features/recording/#how-to-record-sessions this doesn't wok) is there some way to debug custom layout?

**Comment by inqz** [comment]
Hi! I have same problem with 2.9.0 version on ubuntu 18.04, previous version(2.8.0) worked fine.

**Comment by pabloFuente** [comment]
Hi,

Default recording layout for COMPOSED recordings should work fine out of the box. Our recording end2end tests pass ok, for both Ubuntu 16.04 and 18.04. So you might have a version incompatibility issue. You need to comply with these version numbers: https://openvidu.io/docs/releases/#290

So, openvidu-server and openvidu-browser must be 2.9.0, and KMS 6.10.0

**Comment by inqz** [comment]
@pabloFuente thanks for response!

`
root@vm137198:~# kurento-media-server --version
Kurento Media Server version: 6.10.0
Found modules:
	'core' version 6.10.0
	'elements' version 6.10.0
	'filters' version 6.10.0
`

Running jar file server with next command
`
command = /bin/bash -c "java -jar -Dopenvidu.secret=13jce1jSAKOFAWMFA0jq29j1ed203ce21 -Dopenvidu.publicurl=https://ov.easy-bizzi.com -Dserver.port=80 -Dserver.ssl.enabled=false -Dopenvidu.recording=true -Dopenvidu.record.autostop-timeout=30 -Dopenvidu.recording.path=/opt/openvidu/recordings /root/openvidu-server-2.9.0.jar"
`

**Comment by inqz** [comment]
@pabloFuente  thanks for response!
`
root@vm137198:~# kurento-media-server --version 
`
`
Kurento Media Server version: 6.10.0 Found modules: 'core' version 6.10.0 'elements' version 6.10.0 'filters' version 6.10.0
`
Running jar file server with next command(under cloundflare ssl), from root
`
command = /bin/bash -c "java -jar -Dopenvidu.secret=imalreadychangethat -Dopenvidu.publicurl=https://mydomain.com -Dserver.port=80 -Dserver.ssl.enabled=false -Dopenvidu.recording=true -Dopenvidu.record.autostop-timeout=30 -Dopenvidu.recording.path=/opt/openvidu/recordings /root/openvidu-server-2.9.0.jar"
`

**Comment by pabloFuente** [comment]
Do you have a proxy around openvidu-server? I guess so, as you are changing its default port and removing ssl protection.

**Comment by inqz** [comment]
> Do you have a proxy around openvidu-server? I guess so, as you are changing its default port and removing ssl protection.

ye, cloudflare, but i have been installed openvidu with letsencrypt cert with 443 and ssl in command, its works, but recording still have black screen

**Comment by inqz** [comment]
@pabloFuente 
docker logs contains next records:
`
[mp4 @ 0x562ad3e7b4c0] Non-monotonous DTS in output stream 0:1; previous: 162607, current: 162095; changing to 162608. This may result in incorrect timestamps in the output file.
`

and

`
[mp4 @ 0x562ad3e7b4c0] Non-monotonous DTS in output stream 0:1; previous: 91559, current: 84122; changing to 91560. This may result in incorrect timestamps in the output file.
[aac @ 0x562ad3e7de00] Queue input is backward in time
`

**Comment by pabloFuente** [comment]
Hi,

There is a log in openvidu-server that possibly will help fixing this issue. When starting a COMPOSED recording with video, there will be a log like this:

```
[INFO] 2019-05-29 10:15:20,595 [-4443-exec-4] io.openvidu.server.recording.service.ComposedRecordingService (startRecordingWithVideo) - Recorder connecting to url https://OPENVIDUAPP:MY_SECRET@127.0.0.1:4443/#/layout-best-fit/TestSession/MY_SECRET/4443/false
```

That URL is the one used by the recording  container to connect to the session and receive all the streams. So, it needs to be accesible from inside your openvidu-server host, where recording container runs. If you are seeing a black screen, then it probably means that the URL is correct but WebRTC connections are not able to be established between the container and Kurento. That would be a behavior I have not encountered yet.

I'll make some further tests of composed recording on Ubuntu 18.04, to rule out any possibility of a bug.

**Comment by inqz** [comment]
> Hi,
> 
> There is a log in openvidu-server that possibly will help fixing this issue. When starting a COMPOSED recording with video, there will be a log like this:
> 
> ```
> [INFO] 2019-05-29 10:15:20,595 [-4443-exec-4] io.openvidu.server.recording.service.ComposedRecordingService (startRecordingWithVideo) - Recorder connecting to url https://OPENVIDUAPP:MY_SECRET@127.0.0.1:4443/#/layout-best-fit/TestSession/MY_SECRET/4443/false
> ```
> 
> That URL is the one used by the recording container to connect to the session and receive all the streams. So, it needs to be accesible from inside your openvidu-server host, where recording container runs. If you are seeing a black screen, then it probably means that the URL is correct but WebRTC connections are not able to be established between the container and Kurento. That would be a behavior I have not encountered yet.
> 
> I'll make some further tests of composed recording on Ubuntu 18.04, to rule out any possibility of a bug.

Thanks! I can give you access to my VPS with this problem, if needed, or any other information.

**Comment by pabloFuente** [comment]
I have been testing OpenVidu 2.9.0 deployed on a clean Ubuntu 18.04 machine in Amazon, following [these steps](https://openvidu.io/docs/deployment/deploying-ubuntu/), and recording works perfectly for both INDIVIDUAL and COMPOSED modes. There must be a configuration problem in your setup that is preventing the recording container to properly establish WebRTC connections with Kurento Media Server.

**Comment by pabloFuente** [comment]
Following your first comment in this issue, do recordings work fine in the exact same setup you are using with OpenVidu 2.9.0 if you use OpenVidu 2.8.0? (same host machine, same installation, same networking, only changing [OpenVidu/KMS] from [2.8.0/6.9.0] to [2.9.0/6.10.0]) )

**Comment by inqz** [comment]
> Following your first comment in this issue, do recordings work fine in the exact same setup you are using with OpenVidu 2.9.0 if you use OpenVidu 2.8.0? (same host machine, same installation, same networking, only changing [OpenVidu/KMS] from [2.8.0/6.9.0] to [2.9.0/6.10.0]) )

On 16.04 and 2.8.0 recording works fine. I have been installed 2.9.0 version(also update kurento to 6.10.0) on this machine near 2.8.0 and similarly clean 18.04 installation recordings file has black screen and many records like "Non-monotonous DTS in output stream" in docker logs. 

I use steps from doc, but in file /etc/kurento/modules/kurento/WebRtcEndpoint.conf.ini im added turnURL for testing webrtc connect works normally.

**Comment by inqz** [comment]
Got in browser console while i tried connect to recorder url(like https://domain/#/layout-best-fit/123/123/-1/false)

`
'OpenVidu' initialized
main.006da98b71eca69e3d09.js:1 TypeError: Failed to construct 'URL': Invalid URL
    at e.processToken (main.006da98b71eca69e3d09.js:1)
    at main.006da98b71eca69e3d09.js:1
    at new t (polyfills.ce99a1000137fc7c463e.js:1)
    at e.connect (main.006da98b71eca69e3d09.js:1)
    at t.e.ngOnInit (main.006da98b71eca69e3d09.js:1)
    at main.006da98b71eca69e3d09.js:1
    at main.006da98b71eca69e3d09.js:1
    at ds (main.006da98b71eca69e3d09.js:1)
    at Ls (main.006da98b71eca69e3d09.js:1)
    at Object.updateDirectives (main.006da98b71eca69e3d09.js:1)
`

**Comment by inqz** [comment]
@pabloFuente found something interesting, can you explain -1 in port?

<img width="390" alt="Снимок экрана 2019-06-03 в 1 14 47" src="https://user-images.githubusercontent.com/11858103/58768022-0a427d00-859d-11e9-874e-30e7b971c2fe.png">

**Comment by pabloFuente** [comment]
Can you show me the complete `processToken` method to which that line belongs to? And can you also check the complete value of the token in that method?
Also, it would still be very useful to retrieve the log I stated here: https://github.com/OpenVidu/openvidu/issues/253#issuecomment-496836373

**Comment by BritoMatheus** [comment]
I'm using OpenVidu 2.9.0 and I created my custom layout but the black screen is still showing. 

![bloggif_5cf51d50cad12](https://user-images.githubusercontent.com/33379549/58804805-1b18e000-85e9-11e9-9560-9b0bcc772872.gif)

First it shows black screen before white screen and finally my template starts.

How can I resolve it?

**Comment by pabloFuente** [comment]
T

> I'm using OpenVidu 2.9.0 and I created my custom layout but the black screen is still showing.
> 
> ![bloggif_5cf51d50cad12](https://user-images.githubusercontent.com/33379549/58804805-1b18e000-85e9-11e9-9560-9b0bcc772872.gif)
> 
> First it shows black screen before white screen and finally my template starts.
> 
> How can I resolve it?

That's a variable behavior the recorder container might have, but very difficult to manage. Let me explain: the recording module is a Chrome window that starts being recorded as soon as it is launched. For custom recordings, you design a layout with web technologies through which the Chrome connects to the session as any other subscriber. What you see at the beginning of the video file is the Chrome container conecting to your layout and loading it as a web page. So there's not really a good way of preventing the recording container to start the recordig process "too soon" when using a custom layout.  Sometimes, depending on the server load or other measures, the layout will be loaded faster and you won't see the black screen. But at other times, it can take a little bit longer and the result is what you appended.

We could study some solutions that would possibly involve storing the time when the page is completely loaded inside the container and crop that amount of time from the beginning of the video after recording has stopped, or something similar to this. But this is not an easy task, so it may take some time to be done.

**Comment by inqz** [comment]
I resolved my problem - strange configuration with cloudflare and its worked
`
-Dopenvidu.publicurl=https://my.domain.com:443 -Dserver.port=80
`
In result recording url works fine. OMG :).

**Comment by pabloFuente** [comment]
So, it was a matter of port configuration. Closing the issue.
