### ISSUE TITLE
Unable to record video and find path for openvidu.recording equals to path in ionic 

### ISSUE THREAD

**Issue by adyasasingh5** [OpenVidu/openvidu#254]
how to start video recording and find stream file in ionic and i am unable to get path for openvidu.recording equals to true  and find the streams for recording

**Comment by adyasasingh5** [comment]
where to write the below code for openvidu-ionic 
java -jar \
    -Dopenvidu.recording=true \
    -Dopenvidu.recording.path=/PATH/TO/VIDEO/FILES \
openvidu-server.jar

**Comment by micaelgallego** [comment]
You have to install OpenVidu Server in order to record videoconferences in the server

**Comment by adyasasingh5** [comment]
how to install openvidu server for windows?In openvidu document,there is solution for ubuntu and linux but not for windows

**Comment by micaelgallego** [comment]
OpenVidu Server is available only for Linux for production systems.

For development , in windows you can use a virtual machine (managed with Vagrant for example) or with a Docker container.

**Comment by adyasasingh5** [comment]
thank you but where we can find  OpenVidu Server JAR

**Comment by pabloFuente** [comment]
https://github.com/OpenVidu/openvidu/releases
