### ISSUE TITLE
how and where to set path

### ISSUE THREAD

**Issue by adyasasingh5** [OpenVidu/openvidu#259]
where to run this command and after running in docker i am getting error
 run -p 4443:4443 --rm \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /PATH/TO/VIDEO/FILES:/PATH/TO/VIDEO/FILES \
    -e openvidu.recording=true \
    -e openvidu.recording.path=/PATH/TO/VIDEO/FILES \
openvidu/openvidu-server-kms:2.9.0

**Comment by pabloFuente** [comment]
I do not understand. What error are you getting?

**Comment by adyasasingh5** [comment]
i am unable to set path
docker run -p 4443:4443 --rm \ -v /var/run/docker.sock:/var/run/docker.sock
\ -v /PATH/TO/VIDEO/FILES:/PATH/TO/VIDEO/FILES \ -e openvidu.recording=true
\ -e openvidu.recording.path=/PATH/TO/VIDEO/FILES \
openvidu/openvidu-server-kms:2.9.0

In this  what is -v /PATH/TO/VIDEO/FILES:/PATH/TO/VIDEO/FILES and how to
run this this in docker

**Comment by pabloFuente** [comment]
You must first understand how Docker works in terms of those flags.
Flag `-e openvidu.recording.path=/PATH/TO/VIDEO/FILES` is telling the container where to store the recorded files **inside** the container, and flag `-v /PATH/TO/VIDEO/FILES:/PATH/TO/VIDEO/FILES` is mounting that path inside the container to a path of the *host machine*. For simplicity, we recommend to give them the same value. But the path in your host machine must be properly created and have enough permissions so Docker can write into it.

Anf finally flag `-v /var/run/docker.sock:/var/run/docker.sock` is just giving the Docker container acces to the Docker daemon of your host machine, so it can manage other recording containers itself (the COMPOSED recording service of OpenVidu requires launching a Docker container).

So, if your host machine has a path like `/opt/openvidu/recordings`, you can launch the Docker container like this:

docker run -p 4443:4443 --rm \ -v /var/run/docker.sock:/var/run/docker.sock
\ -v /opt/openvidu/recordings:/opt/openvidu/recordings \ -e openvidu.recording=true
\ -e openvidu.recording.path=/opt/openvidu/recordings \
openvidu/openvidu-server-kms:2.9.0

**Comment by adyasasingh5** [comment]
i am using openvidu-ionic,for that where i have to create this path /opt/openvidu/recordings?

**Comment by adyasasingh5** [comment]
on running docker run -p 4443:4443 --rm
-v /var/run/docker.sock:/var/run/docker.sock
-v /opt/openvidu/recordings:/opt/openvidu/recordings 
-e openvidu.recording=true
-e openvidu.recording.path=/opt/openvidu/recordings
openvidu/openvidu-server-kms:2.9.0 
in docker i am getting error
"docker run" requires at least 1 argument.
See 'docker run --help'.

Usage:  docker run [OPTIONS] IMAGE [COMMAND] [ARG...]

Run a command in a new container
-v : The term '-v' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:2 char:1
+ -v /var/run/docker.sock:/var/run/docker.sock
+ ~~
    + CategoryInfo          : ObjectNotFound: (-v:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

-v : The term '-v' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:3 char:1
+ -v /opt/openvidu/recordings:/opt/openvidu/recordings
+ ~~
    + CategoryInfo          : ObjectNotFound: (-v:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

-e : The term '-e' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:4 char:1
+ -e openvidu.recording=true
+ ~~
    + CategoryInfo          : ObjectNotFound: (-e:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

-e : The term '-e' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:5 char:1
+ -e openvidu.recording.path=/opt/openvidu/recordings
+ ~~
    + CategoryInfo          : ObjectNotFound: (-e:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

openvidu/openvidu-server-kms:2.9.0 : The term 'openvidu/openvidu-server-kms:2.9.0' is not recognized as the name of a
cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify
that the path is correct and try again.
At line:6 char:1
+ openvidu/openvidu-server-kms:2.9.0
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (openvidu/openvidu-server-kms:2.9.0:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by pabloFuente** [comment]
One line command:

```
docker run -p 4443:4443 --rm -v /var/run/docker.sock:/var/run/docker.sock -v /opt/openvidu/recordings:/opt/openvidu/recordings -e openvidu.recording=true -e openvidu.recording.path=/opt/openvidu/recordings openvidu/openvidu-server-kms:2.9.0
```

**Comment by adyasasingh5** [comment]
already i am running docker run -p 4443:4443 --rm -e openvidu.secret=MY_SECRET -e openvidu.publicurl=https://IP:4443/ openvidu/openvidu-server-kms:2.9.0
so while running docker run -p 4443:4443 --rm -v /var/run/docker.sock:/var/run/docker.sock -v /opt/openvidu/recordings:/opt/openvidu/recordings -e openvidu.recording=true -e openvidu.recording.path=/opt/openvidu/recordings openvidu/openvidu-server-kms:2.9.0

i am getting that port already in use,should i use same port or different?

**Comment by pabloFuente** [comment]
Just remove older containers. You have them in background

**Comment by adyasasingh5** [comment]
thank you pabloFuente ,for your support till now but i am facing this error
driver failed programming external connectivity on endpoint serene_ellis (89e199715ce52f66ec7d9edd9e0ab3838e53beb9ce761b17d7798c317c9f1e88): Bind for 0.0.0.0:4443 failed: port is already allocated.

**Comment by adyasasingh5** [comment]
I want to record in android mobile but i am getting error
WebSocket connection to 'wss://localhost:4443/openvidu' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

**Comment by adyasasingh5** [comment]
how to solve 406 error after running in android mobile
