### ISSUE TITLE
Can OpenVidu supported iOS11 now?

### ISSUE THREAD

**Issue by willylee007** [OpenVidu/openvidu#26]
Hello. Can OpenVidu supported iOS11 now?
Thx!

**Comment by willylee007** [comment]
Sorry. Can OpenVidu supported iOS11 on Safari now?
Thx!

**Comment by micaelgallego** [comment]
We are working on that right now, but it is not available at the moment.

**Comment by pabloFuente** [comment]
We will be hopefully releasing in the incoming weeks a new version that will support Safari 11. It is being a complex process because some incompatibility issues have arisen in both the client side and the Media Server.
But we are expecting good results relatively soon. Stay tunned.

**Comment by willylee007** [comment]
Thx!
I found some links about the solutions:
1.[Hello, WebRTC on Safari 11](https://medium.com/@leemartin/hello-webrtc-on-safari-11-e8bcb5335295)
2.[Safari 11 support? #685](https://github.com/webrtc/adapter/issues/685)
Hope it's helpful for the supports  on Safari 11!

In addition, I want to know how to complie openvidu-browser SDK by myself. I had installed Typescript(version: 2.6.1) and Node(9.2.0). And  run

> npm install
npm run updatetsc
sudo npm link

I found "updatetsc" is a script in the package.json. So I tried to run

> npm run browserify

But it shows: 

>  VERSION=${VERSION:-}; cd ts/OpenVidu && browserify Main.ts -p [ tsify ] --exclude kurento-browser-extensions --debug -o ../../static/js/openvidu-browser-$VERSION.js -v

> TypeScript error: ../kurentoutils/kurento-jsonrpc/clients/transports/index.js(18,42): Error TS1149: File name '/users/mac/downloads/openvidu-master/openvidu-browser/ts/kurentoutils/kurento-jsonrpc/clients/transports/webSocketWithReconnection.js' differs from already included file name '../kurentoutils/kurento-jsonrpc/clients/transports/websocketwithreconnection.js' only in casing.

It is correctly above ? Thx!

**Comment by willylee007** [comment]
Oohs...It must developed on Ubuntu. [Developing OpenVidu](https://github.com/OpenVidu/openvidu.io-docs/blob/master/docs/developing/index.md) But I'm developing on macOS10.13.2. ..

**Comment by willylee007** [comment]
I solve this problem after setting in two tsconfig.json files. Which in /openvidu-browser/ts/OpenVidu/tsconfig.json and /openvidu-browser/ts/OpenViduInternal/tsconfig.json, following this changing:

> "forceConsistentCasingInFileNames": false,

I can compile opvidu-browser SDK on my mac now!And success both on CentOS7 too.

**Comment by pabloFuente** [comment]
Glad to here it. Yes, probably those compile errors can appear depending on Typescript version, but usually they can be resolved through `tsconfig` files.

**Comment by pabloFuente** [comment]
Glad to here it. Yes, probably those compile errors can appear depending on Typescript version, but usually they can be resolved through `tsconfig` files.
