### ISSUE TITLE
how to solve 406 error after connecting with android app

### ISSUE THREAD

**Issue by adyasasingh5** [OpenVidu/openvidu#262]
i am getting [406: the session has no connected participants] after starting video recording in android phone using openvidu-ionic

**Comment by tandel007** [comment]
Hi @adyasasingh5,
I am getting [406: the session has no connected participants] after starting video recording in the android 10 phone using openvidu-ionic.

Could you help us to solve the issue?

Thank you in advance.

**Comment by pabloFuente** [comment]
What is your doubt? The message is very clear, as the API documentation: https://docs.openvidu.io/en/2.13.0/reference-docs/REST-API/#post-apirecordingsstart

You cannot manually start the recording of a session with no connected participants.

**Comment by tandel007** [comment]
Thanks, @pabloFuente,

I thought the issue has occurred while starting the recording.  Currently, I have disabled the recording feature.

In android 10, a **white blank page** has occurred while connecting to the session in the ionic 4 apps.
example : this.session.connect(token, { clientData: myUserName })
Always I got an updated token from a server but still showing a white blank screen.

Nodejs : 8.16.0
openvidu-node-client: 2.10.0

Ionic version 4
openvidu-browser: 2.10.0

I have attached the screenshot for your reference.

![WhatsApp Image 2020-04-29 at 1 59 50 PM](https://user-images.githubusercontent.com/35524634/80575928-f2c87a00-8a21-11ea-92aa-a00a529bac57.jpeg)

Please help us.
 Thanks.

**Comment by micaelgallego** [comment]
Hello @tandel007,

Have you followed this tutorial step by step?

https://docs.openvidu.io/en/2.13.0/demos/openvidu-call-ionic/

If so, can you share with use ionic app logs and openvidu logs?

**Comment by pabloFuente** [comment]
How have you deployed OpenVidu? And which version? It is VERY important for us to have the issues on the issue tracker of OpenVidu GitHub use the default template that is presented to the user when opening an issue (in fact issues without the template are issues for which the user has manually and purposely deleted all of the template content). The template asks for all the information we need to help users. If not, issues are always like this: "This doesn't work" "How have you deployed OpenVidu?" "Like this" "Which version did you deployed?" "This one" ......

Which is a complete waste of time. I'm taking some time to write this down in the hope that the next person who reads this message and wants to open an issue respects the mandatory template.

Regards.

**Comment by tandel007** [comment]
Thanks, @micaelgallego,
One more thing, when we build the release final build(ionic 4) with debuggable true in android manifest file then we have faced the issue.  Otherwise, It is working fine.

**Comment by tandel007** [comment]
> How have you deployed OpenVidu? And which version? It is VERY important for us to have the issues on the issue tracker of OpenVidu GitHub use the default template that is presented to the user when opening an issue (in fact issues without the template are issues for which the user has manually and purposely deleted all of the template content). The template asks for all the information we need to help users. If not, issues are always like this: "This doesn't work" "How have you deployed OpenVidu?" "Like this" "Which version did you deployed?" "This one" ......
> 
> Which is a complete waste of time. I'm taking some time to write this down in the hope that the next person who reads this message and wants to open an issue respects the mandatory template.
> 
> Regards.

Yes, I have deployed on ubuntu 16.04.  The openvidu server version is 2.10.0.

**Comment by micaelgallego** [comment]
Please update to latest OpenVidu version and follow in detail the tutorial.

**Comment by tandel007** [comment]
> Please update to latest OpenVidu version and follow in detail the tutorial.

Thanks, I Will check and let you know.
