### ISSUE TITLE
Publishing on demand selectively

### ISSUE THREAD

**Issue by anidotnet** [OpenVidu/openvidu#264]
I want to create a webiner/classroom setup like this:

1. There will be 1 publisher of a session
2. There will be n subscribers to that session
3. Publisher 1 can make one subscriber the publisher 2, so other subscribers can see stream from both publisher 1 & 2
4. Later publisher 1 again can make publisher 2 as subscriber by stopping publisher 2 from streaming

Is it possible to implement the above scenario with OpenVidu? If possible can anybody give me some pointer?

**Comment by pabloFuente** [comment]
Yes, of course you can implement it. You must take into account the available roles users may have inside an OpenVidu session. Here you have them properly documented in openvidu-node-client API: https://openvidu.io/api/openvidu-node-client/enums/openvidurole.html

So, any user you want to be able to publish a stream must have at least PUBLISHER role. So your Publisher 1 should be MODERATOR, and any subscriber user should be PUBLISHER, but they won't initialize and publish a Publisher object after joining the session. You can use `Session.signal` method to communicate your publisher and subscriber users. The publisher may send a signal to certain subscriber user, that upon that signal will initialize and publish a Publisher.

Whenever the publisher user wants that subscriber user to stop publishing, he can send a new signal to make the subscriber user unpublish, or as a MODERATOR, he can directly force the unpublishing of the subscriber's stream (https://openvidu.io/api/openvidu-browser/classes/session.html#forceunpublish)

**Comment by pabloFuente** [comment]
Closing issue as already answered. For this kind of support questions, please refer to OpenVidu Mailing list: https://groups.google.com/forum/#!forum/openvidu
