### ISSUE TITLE
how to save recorded video in aws using ionic app

### ISSUE THREAD

**Issue by adyasasingh5** [OpenVidu/openvidu#268]
I have created ionic app by using openvidu,now i want to store the recorded video in aws  and i am using window server,can you please recommend how to save video in  aws after recording from local system

**Comment by micaelgallego** [comment]
If you are using OpenVidu in an ionic application, then you have installed OpenVidu Server in a linux server in AWS, right? 

If you want to record the entire video conference (with all participants together), then you need to record in the linux box where OpenVidu server is installed.

If you only want to record one participant, you can also record that participant in the linux box where OpenVidu server is installed. On the other hand, you can record the local media on the mobile... and then send it to any server you want using http POST request, for example.

PD: Use mailing list for questions like this.

**Comment by adyasasingh5** [comment]
should i follow same link https://openvidu.io/docs/deployment/deploying-ubuntu/ for linux also?

**Comment by pabloFuente** [comment]
Yes, those are the instructions to deploy OpenVidu on premise.
