### ISSUE TITLE
Recording docker container not disposed properly

### ISSUE THREAD

**Issue by miguelrcDEV** [OpenVidu/openvidu#27]
I run a container of the image "openvidu/openvidu-server-kms" as mentioned in http://openvidu.io/docs/advanced-features/recording/ . Then I create a session with a publisher and record image (openvidu/openvidu-recording) starts automatically, but when leave the session the record image dont stop, that cause the mkv record keep recording.

I tested locally, launching openvidu-server with intellij. I follow the same previous steps, create a session with a published, openvidu-record starts automatically, but when leave the session, the record image stops.

It's possible that the problem be the  "openvidu/openvidu-server-kms" image, that don't dispose the "openvidu-recording" image when leave the session?

**Comment by pabloFuente** [comment]
I suppose you are testing a front-end only application (I mean, you are creating your sessions as stated in the first point of [this FAQ](http://openvidu.io/docs/troubleshooting/#5-what-are-the-differences-related-to-openvidu-between-an-app-without-a-server-side-and-an-app-with-a-server-side) and not as in the second point).

If openvidu-recording container is succesfully started but it is not properly disposed, this usually means that the property `openvidu.publicurl` with which you started your OpenVidu Server (in this case, the openvidu-server-kms container) and the URL that you are using in `OpenVidu.initSession` method in your Javascript code are not the same.

Make sure that, if your OpenVidu Server is hosted in 

`https://YOUR_IP:8443/`

you init your container with property 

`-e openvidu.publicurl=https://YOUR_IP:8443/`

and that in your JS code you init your session like 

`OpenVidu.initSession("wss:///YOUR_IP:8443/" + SESSION_ID + "?secret=" + OPENVIDU_SECRET)`

**Comment by miguelrcDEV** [comment]
It works if I add the --net="host"  parameter, in addition to the suggestions that you have given me @pabloFuente
