### ISSUE TITLE
Android: how to include module openvidu-client?

### ISSUE THREAD

**Issue by szkodnik25** [OpenVidu/openvidu#270]
Hello there,

In openvidu-client module README says: _Can be used to implement an Android client._ 
How can I include only this module in my native Android app?

**Comment by micaelgallego** [comment]
We don't have an official client for native android development. We have an ionic client for hybrid mobile apps and also a react-native client (not open source).

There is an Android demo application https://github.com/OpenVidu/openvidu-android-app. But it is a bit outdated right now and it is possible that doesn't work.

If you can contribute, you can fix the demo project or implement the native client.

**Comment by szkodnik25** [comment]
Yes, I found that sample project. I can confirm that it doesn't work. 
I am willing to implement native client, but are there any official resources/tutorials to guide me how to build connection in "lower level" rather than ready components? E.g. which request call after another, how to build request JSON etc...

**Comment by micaelgallego** [comment]
We plan to document the client-server protocol as soon as we have some time... But until then, the only way to know it is doing some reverse engineering on the openvidu-browser client. As websocket messages can be seen in Chrome dev tools, it is easy to understand the messages exchanges between client and server.

If you have any doubt, please ask for help/support.

**Comment by szkodnik25** [comment]
Ok, thank you.

So, just for clarification: if I will figure out connecting/signaling with browser client, the rest of streaming is WebRTC magic that I can handle with prebuild native libraries https://webrtc.org/native-code/android/?

**Comment by micaelgallego** [comment]
Yes! In fact, the android sample app was working several months ago. Then, it has the protocol implemented... Maybe some message has changed and doesn't work because that small protocol change.

You can use that sample Android app as a base to understand protocol and how to use webrtc prebuilt binaries.

If you fix it, please share with us with a PR ;)

**Comment by szkodnik25** [comment]
Thank you for your response.

I will take a look to sample app. I probably won't work on, nor modify your sample project, as the prebuild WebRTC is outdated aswell. I will let you know If I'm goona fix it, and if I find some spare time, contribute new sample native app. 

Closing this ticket for now, thanks.
