### ISSUE TITLE
Low quality video recorded

### ISSUE THREAD

**Issue by loveisalie92** [OpenVidu/openvidu#271]
Hi,

Thanks for making this awesome opensource,
I have successfully making a video call feature, including recording the video call. But i can not get openvidu to record high quality videos. 
I know that there are some options in the API to measure, this is what i tried:

**/api/tokens**

'kurentoOptions' => [
      'videoMaxRecvBandwidth' => 0, // unconstrained
      'videoMaxSendBandwidth' => 0, // unconstrained
      'videoMinRecvBandwidth' => 1500,
      'videoMinSendBandwidth' => 1500
]

I have played around with these values but i still get the same low quality videos recorded.
(I'm using an iphoneX as a publisher with high speed wifi)
Please suggest me a proper way to do this if i am going the wrong way

Thanks in advance

**Comment by pabloFuente** [comment]
Hi,

Try using INDIVIDUAL recording mode. This way OpenVidu Server will save the published video just as it reaches the server, with no other processing in the middle.
