### ISSUE TITLE
What is the username and password of the docker image(openvidu-kms) dashboard password?

### ISSUE THREAD

**Issue by tonyho** [OpenVidu/openvidu#273]
When I open the https://ip:4443, it requires the username and password to enter. What is it?

**Comment by pabloFuente** [comment]
User: OPENVIDUAPP
Password: property `openvidu.secret` (MY_SECRET by default)

**Comment by ftntming** [comment]
I really hope this goes into some document with "IMPORTANT!IMPORTANT!IMPORTANT!IMPORTANT!"

**Comment by Rush** [comment]
I also missed this. Please add it to some documentation.

**Comment by mihaicoli** [comment]
empty

**Comment by Thaina** [comment]
Also can we change it?

**Comment by prajith-nair** [comment]
https://docs.openvidu.io/en/2.14.0/deployment/deploying-on-premises/#available-services

Consume [OpenVidu REST API](https://docs.openvidu.io/en/2.14.0/reference-docs/REST-API/) through https://DOMAIN_OR_PUBLIC_IP/
If the [application](https://docs.openvidu.io/en/2.14.0/deployment/deploying-on-premises/#videoconference-application) is enabled, it will also be available at https://DOMAIN_OR_PUBLIC_IP/
You can open OpenVidu Dashboard to verify everything is working as expected at https://DOMAIN_OR_PUBLIC_IP/dashboard/ with credentials:
user: OPENVIDUAPP
pass: the value of OPENVIDU_SECRET in .env file
