### ISSUE TITLE
kms 2.8.0 => 2.10.0 question

### ISSUE THREAD

**Issue by zzdd1558** [OpenVidu/openvidu#275]
kms The version was upgraded from 2.8.0 to 2.10.0 and I noticed that the connectionId was added to the connection part of browser.js.

**Comment by pabloFuente** [comment]
I'm sorry, but what is the question?

**Comment by micaelgallego** [comment]
Please use the forum for questions.

Yes, we implement changes in several parts of the platform in every new version.
