### ISSUE TITLE
Data Channel Messaging

### ISSUE THREAD

**Issue by suraj-pai** [OpenVidu/openvidu#277]
From my understanding of the signal messages sent between different peers, it seems to be through JSON-RPC. Is there no implementation of data channels using RTCDataChannels for openvidu? I'm sure I must be missing something. 
Context: Was using Kurento earlier and had access to data channel messaging between peers, switched to OpenVidu to better handle support across Safari.

**Comment by wardhanster** [comment]
@pabloFuente any news on this ?

**Comment by pabloFuente** [comment]
Hi,

OpenVidu does not have data channel support yet. It implements a simple messaging system based on websocket (see [Send text messages between users](https://openvidu.io/docs/cheatsheet/send-messages/)).
