### ISSUE TITLE
git  contributor Question

### ISSUE THREAD

**Issue by zzdd1558** [OpenVidu/openvidu#281]
Hi there, I do not think there is an example where Node Express and React are interlocked. I am making it myself. If it is neatly organized, can I participate as a contributor?

If you want to participate, how can you participate?

**Comment by micaelgallego** [comment]
Hi zzdd1558,
We are open to contributors. We don't have a written policy on how to contribute. At the moment, you can publish your complete demo project on a repository on your own github account with a documentation in the main README. 

We will add this project to a web page in OpenVidu main site as community demo projects.

Then, we can work together in creating a reposirory (or account) with external contributed OpenVidu demos.

What do you think?

**Comment by zzdd1558** [comment]
I created it by referring to the existing openvidu-mvc-node + openvidu-insecure-react.

I will clean up the source and tell you again.

**Comment by zzdd1558** [comment]
Hello micaelgallego 

https://github.com/zzdd1558/openvidu-react-node

I uploaded the source code to my github.

The source is not structured by making sense of the action.

I would like to ask you for your answers.

**Comment by pabloFuente** [comment]
Hi,

Thanks for your project. Whenever we add a "Related projects" section to our documentation, we will perform a search of the most important open-source projects built with OpenVidu and add them to it.

I'm closing this issue for now, as it is not really an issue.
