### ISSUE TITLE
Problems with conection:Undefined

### ISSUE THREAD

**Issue by augustocristian** [OpenVidu/openvidu#282]
Hi, i've having problems with the connection between fullteaching and the openvidu server. I've tried with several configurations(i.e. accepting the SSL certificate of the server in the URL:4443, deploying the non contenerized version,using different browsers with different versions)  and  in different enviroments(HyperV  Ubuntu 18, Ubuntu 16 , windows 10 , Ubuntu into a bare metal machine)  having the same output:
![imagen](https://user-images.githubusercontent.com/49859508/60513015-67ce0480-9cd6-11e9-860d-726737fffb03.png)

I am not sure what is happening due to a month ago i remember that the video streaming work, and now that i am performing several tests over the video session y can not do it.

Many Thanks
Cristian

**Comment by pabloFuente** [comment]
Please, open this issue in the full-teaching application repository.
