### ISSUE TITLE
Can't mute Video after changing Camera stream

### ISSUE THREAD

**Issue by wardhanster** [OpenVidu/openvidu#283]
**What happened:**
After changing the camera video stream, i.e: switching the camera, following fails
>this.localFeed.publishVideo(false); 

This was observed on an iOS device.

**Expected Result**
I should still be able to mute the video.
PS: My implementation only has the need of having two users in a room.

**Code Snippet**

```devices = devices.filter((i) => i.kind === 'videoinput');
    const selectedDevice = devices[deviceIndex];
    var constraints = { videoSource: selectedDevice.deviceId };

    var stream = await this.OV.getUserMedia(constraints);
    localVideo.srcObject = stream;
    stream.getVideoTracks().forEach(function(track) {
      var peerConnCallee = call.session.streamManagers[1].stream.getWebRtcPeer().pc;
      var sender = peerConnCallee.getSenders().find(function(s) {
        return s.track.kind === track.kind;
      });
      sender.replaceTrack(track);
    });``

**Comment by pabloFuente** [comment]
You are not using the official openvidu-browser API to initialize your Publisher, so using the official way to mute the tracks may perfectly fail. We cannot ensure that everything developers do internally will work just fine when mixing browser-native and OpenVidu APIs.

Try accessing the video tracks on your own and muting them with native Web API instead of using OpenVidu way.

**Comment by wardhanster** [comment]
@pabloFuente I am using the browser API to mute and unmute the video.
the snippet I provided is only to showcase how I am changing the video tracks.

if this still is non-openvidu-browser API implementation, can you point me in the right direction?

**Comment by pabloFuente** [comment]
What I meant is that accessing the PeerConnection object and changing video tracks on the fly as you do in your code is not officially supported.
To change the camera you should initialize a new Publisher with the new `videoSource`. Once you have it, you should unpublish the old one and immediately after publish the new one. Here you have an example: openvidu-call-ionic app does it like this (https://github.com/OpenVidu/openvidu-call-ionic/blob/master/src/app/video-room/video-room.page.ts#L248-L276)

**Comment by wardhanster** [comment]
@pabloFuente thanks a lot, I think that will help a lot.
