### ISSUE TITLE
Deploy OpenVidu Pro in Private Cloud Server

### ISSUE THREAD

**Issue by kamlesh0606** [OpenVidu/openvidu#285]
Hi,

I use OpenVidu As Private Cloud Server. My company plan for move to pro version . But i did not get help document for this. So Please provide it

Thanks
kamlesh

**Comment by micaelgallego** [comment]
Hi @kamlesh0606, 

Please use Google Forum to ask questions like this. 

We are working in a new version of OpenVidu Pro with instructions on how to deploy it on premises and new features (mainly related to scalability). We plan to release it in the following weeks. Please stay tuned.
