### ISSUE TITLE
Change log levels on OpenVidu Server output

### ISSUE THREAD

**Issue by eiriholh** [OpenVidu/openvidu#286]
Hi, I've installed the OpenVidu server on a VM running Ubuntu 18.04, and was wondering if there is a setting for changing the log levels of the output? In default state, it logs pretty much everything, but I would rather have it just log the warnings and above. Is that possible?

**Comment by pabloFuente** [comment]
Sure. Just launch openvidu-server with property:

`logging.level.root=warn`
