### ISSUE TITLE
can openvidu use in iframe page?

### ISSUE THREAD

**Issue by z-lionel** [OpenVidu/openvidu#287]
Hello,
    i wonder can openvidu use in iframe page?

**Comment by micaelgallego** [comment]
Yes... It works

**Comment by mads2** [comment]
Since this is the first result for "openvidu iframe" I would like to add that you should use the `allow` parameter.
```
<iframe src="https://coolvidu.com/room" allow="camera;microphone">
</iframe>

```
[Ref](https://groups.google.com/d/msg/discuss-webrtc/32natnrbP6U/wd1-m3crAwAJ)

**Comment by micaelgallego** [comment]
Thank you for the information. We will include it in the official documentation
