### ISSUE TITLE
CDR  SendMessage Event

### ISSUE THREAD

**Issue by cirinoe** [OpenVidu/openvidu#288]
We would be interested in registering the sendMessage event (signal: chat and signal: xxx) for tracking all the messages exchanged between the various clients. Is the activation of this event also foreseen?
If not, could we implement it and make it available as a feature for openvidu by becoming a contributor?

**Comment by pabloFuente** [comment]
Hi,

Signals are not stored right now in OpenVidu CDR, but they could be. If you want to implement it, you are free to do so. And of course if you want to contribute it, just do a PR and we will review it. We will perform any necessary changes for it to properly fit into the existing CDR module.

**Comment by banagale** [comment]
@cirinoe curious if you ended up implementing this, or how you're exfiltrating the content of sendMessage events.

**Comment by banagale** [comment]
I see now that this has an open PR, #402

**Comment by pabloFuente** [comment]
In master branch a new event called `signalEvent` is now available for the Webhook and CDR (see commit e8dd9bd8f4c739a83f26d9d9f6b59393e17337eb). This PR has not been merged becasue some minor changes were required, but the functionality is the expected one. Will be officially available in 2.17.0.

**Comment by banagale** [comment]
@pabloFuente Thank you for adding this. I have been working on other parts of my project this past week but saw this when you posted it and am very appreciative of you getting it in. I'll try to make time to post feedback / info from my implementation.
