### ISSUE TITLE
Sending files by broadcast

### ISSUE THREAD

**Issue by L-BuenoSRP** [OpenVidu/openvidu#289]
Hi guys,
I am trying to make the application with OpenVidu for video calls with sending files and text messages by socket connection, but I was unable to use session.signal method for sending files, do you have any suggestions on how could broadcast files and whether this can be converted into a pull request in the future.
Thanks.

**Comment by L-BuenoSRP** [comment]
Hello guys,
I got a solution working in conjunction with my backend structure, I'm saving the files on the server and generating a record in the database with the file name and path where it was saved, then after upload, send a message to the other users informing me that the file of a given ID is available, so I find the file via ajax and show it to it through an <a> element.
Although not a file send by socket, it is enough. But if I ever have a form of file sharing through Openvidu's own connection, I will migrate to use it.
Thank you.

**Comment by micaelgallego** [comment]
Hi @L-BuenoSRP,

We try to maintain OpenVidu focused on videoconference features to maintain it simple. Maybe in the future we decide to implement other high level features like that you are sugesting

**Comment by L-BuenoSRP** [comment]
Thanks @micaelgallego 
Great work with Opevidu, I will continue to follow the updates.

**Comment by guiljs** [comment]
Great work guys. For now, I'll try to implement it without using OpenVidu. Thank you.
