### ISSUE TITLE
录制问题

### ISSUE THREAD

**Issue by dengwuqiang19899** [OpenVidu/openvidu#290]
使用kurento-room-client-android连接kurento, 服务端录制的视频,播放时只显示了一帧画面,但有声音,00:00时长, 大神帮忙看看,谢谢啊

**Comment by pabloFuente** [comment]
I'm sorry, but we only attend issues in English.

**Comment by willylee007** [comment]
@dengwuqiang19899 [提问的智慧](https://github.com/tvvocold/How-To-Ask-Questions-The-Smart-Way)
