### ISSUE TITLE
Can I dynamically subscribe to any publisher in the room? Not at the moment of connecting to the room for the first time

### ISSUE THREAD

**Issue by Ray-Sir-Like** [OpenVidu/openvidu#291]
Hi,
At the beginning, I just subscribed to a publisher. Later, I needed to subscribe to another publisher who was already in the room. Is there any way to complete it?
Regards

**Comment by pabloFuente** [comment]
Sure. Just store the Stream object of the 'streamCreated' event. You can then call Session.subscribe(stream) whenever you want.

**Comment by Ray-Sir-Like** [comment]
Thank you !
