### ISSUE TITLE
Can I adjust the resolution in a fixed size element?

### ISSUE THREAD

**Issue by Ray-Sir-Like** [OpenVidu/openvidu#292]
Hi,
When I use the parameter resolution: "1280x720" to publish the video stream, my browser will generate a 1280x720 video element.  Is there any way to make the video element created by openvidu width*height is 522*298, but the resolution is 1280*720 ?
Regards

**Comment by pabloFuente** [comment]
Of course. Just set the width and height of the HTMLVideoElement. This is just a simple CSS task.

**Comment by Ray-Sir-Like** [comment]
Do I need to manually change the size of this video?
Is there a way to configure it directly  likes  to configurate the  resolution?
          e.g.
              publishAudio: true,
              publishVideo: true,
              resolution: "1280x720",
              frameRate: 60,
              insertMode: "APPEND",

**Comment by pabloFuente** [comment]
Just sytle it however you want. If you are letting OpenVidu insert the video for you, just style the element with CSS according to its location in the DOM. If you are using your own video players, it is even more simple to style the video element. More info here: https://openvidu.io/docs/cheatsheet/manage-videos/

**Comment by Ray-Sir-Like** [comment]
Thank you very much.Best wishes.
