### ISSUE TITLE
Recordings are always publicly accessible

### ISSUE THREAD

**Issue by cstip** [OpenVidu/openvidu#294]
Hi,

It seems the recordings are always publicly accessible, even if `openvidu.recording.public-access` is `false`. It think it may be related to the new folder structure introduced in version 2.8.0.

For example, if I try to access a video at **https://[host]:[port]/recordings/[streamId].mp4** (old folder structure), OpenVidu asks for credentials. But if I try to access a video at **https://[host]:[port]/recordings/[recordingId]/[streamId].mp4** (new folder structure), it doesn't.

I'm getting this behavior with version 2.8.0 installed on Ubuntu Server 16.04 using your docs (https://openvidu.io/docs/deployment/deploying-ubuntu/) and with the latest (2.10.0) Docker image.

Thank you!

**Comment by pabloFuente** [comment]
Hi,

Recordings path is secured in this way:

https://github.com/OpenVidu/openvidu/blob/master/openvidu-server/src/main/java/io/openvidu/server/config/SecurityConfig.java#L65-L69

So, that security configuration is enough for covering both cases. Be sure that you didn't had a valid cookie in your HTTP GET petition when accessing the recordings. Sometimes the browser or HTTP client will not ask for Basic Auth credentials if it has already access the domain name with valid credentials.

**Comment by cstip** [comment]
Hi,

I didn't have a valid cookie. I made sure I cleared everything during my tests.

I'm not familiar with Spring, but shoudn't it be "/recordings/**" instead of "/recordings/*" to secure everything?

Thank you again!

**Comment by pabloFuente** [comment]
You might be right, that could be a bug. Tomorrow we will take a look to it. I'm reopening the issue meanwhile.

**Comment by pabloFuente** [comment]
Commit c242bea08a5cb7bf632c1f4e756a2639a913e9b2 fixes this issue.
Thanks for the bug report!
