### ISSUE TITLE
React Native Build ~ Error

### ISSUE THREAD

**Issue by zzdd1558** [OpenVidu/openvidu#297]
# react-native run-ios 

 fatal error: 'React/RCTBridge.h' file not found
#import <React/RCTBridge.h>
        ^~~~~~~~~~~~~~~~~~~

fatal error: 'React/RCTBridge.h' file not found
#import <React/RCTBridge.h>
        ^~~~~~~~~~~~~~~~~~~
fatal error: 'React/RCTBridge.h' file not found
#import <React/RCTBridge.h>

Example I followed the following error.

Is there any corrective action?

**Comment by CSantosM** [comment]
Hello @zzdd1558 ,
**React Native support is a paid feature**. A special version of openvidu-browser library is needed for openvidu-react-native tutorial to work. Contact us through openvidu@gmail.com to get it please.
Thank you.
