### ISSUE TITLE
Unable to launch new aws cloudformation for openvidu pro

### ISSUE THREAD

**Issue by philajay** [OpenVidu/openvidu#300]
Hi All,
I'm getting below error while deploying on aws 

> Failed to receive 1 resource signal(s) within the specified duration

> 
Below is the stack as shown on aws 
> RouteTable	DELETE_COMPLETE	-
RouteTable	DELETE_IN_PROGRESS	-
AttachInternetGateway	DELETE_IN_PROGRESS	-
PublicSubnet1RouteTableAssociation	DELETE_COMPLETE	-
InternetRoute	DELETE_COMPLETE	-
WaitCondition	DELETE_COMPLETE	-
PublicSubnet1RouteTableAssociation	DELETE_IN_PROGRESS	-
InternetRoute	DELETE_IN_PROGRESS	-   
OpenViduServer	DELETE_IN_PROGRESS	-
WaitCondition	DELETE_IN_PROGRESS	-
KurentoAutoScalingGroup	DELETE_IN_PROGRESS	-
**openvidu	ROLLBACK_IN_PROGRESS	The following resource(s) failed to create: [WaitCondition]. . Rollback requested by user.
WaitCondition	CREATE_FAILED	Failed to receive 1 resource signal(s) within the specified duration
KurentoAut**oScalingGroup	CREATE_COMPLETE	-
OpenViduServer	CREATE_COMPLETE	-
KurentoAutoScalingGroup	CREATE_IN_PROGRESS	Resource creation Initiated
KurentoAutoScalingGroup	CREATE_IN_PROGRESS	-
OpenViduServer	CREATE_IN_PROGRESS	Resource creation Initiated
OpenViduServer	CREATE_IN_PROGRESS	-
KurentoLaunchConfiguration	CREATE_COMPLETE	-
KurentoLaunchConfiguration	CREATE_IN_PROGRESS	Resource creation Initiated
KurentoLaunchConfiguration	CREATE_IN_PROGRESS	-
OpenviduInstancesProfile	CREATE_COMPLETE	-
PublicSubnet1RouteTableAssociation	
CREATE_COMPLETE	-InternetRoute	
CREATE_COMPLETE	-PublicSubnet1RouteTableAssociation	
CREATE_IN_PROGRESS	Resource creation Initiated
PublicSubnet1RouteTableAssociation	CREATE_IN_PROGRESS	-
InternetRoute	CREATE_IN_PROGRESS	Resource creation Initiated
InternetRoute	CREATE_IN_PROGRESS	-
OpenViduSubnet1	CREATE_COMPLETE	-
AttachInternetGateway	CREATE_COMPLETE	-
OpenViduSecurityGroup	CREATE_COMPLETE	-
KMSSecurityGroup	CREATE_COMPLETE	-
OpenViduSecurityGroup	CREATE_IN_PROGRESS	Resource creation Initiated
KMSSecurityGroup	CREATE_IN_PROGRESS	Resource creation Initiated
OpenViduSubnet1	CREATE_IN_PROGRESS	Resource creation Initiated
RouteTable	CREATE_COMPLETE	-
OpenViduSubnet1	CREATE_IN_PROGRESS	-
RouteTable	CREATE_IN_PROGRESS	Resource creation Initiated
RouteTable	CREATE_IN_PROGRESS	-
AttachInternetGateway	CREATE_IN_PROGRESS	Resource creation Initiated
AttachInternetGateway	CREATE_IN_PROGRESS	-
OpenViduSecurityGroup	CREATE_IN_PROGRESS	-
KMSSecurityGroup	CREATE_IN_PROGRESS	-
OpenViduVPC	CREATE_COMPLETE	-
OpenviduInstancesProfile	CREATE_IN_PROGRESS	Resource creation Initiated
OpenviduInstancesProfile	CREATE_IN_PROGRESS	-
InternetGateway	CREATE_COMPLETE	-
DescribeInstancesRole	CREATE_COMPLETE	-
OpenViduVPC	CREATE_IN_PROGRESS	Resource creation Initiated
OpenViduVPC	CREATE_IN_PROGRESS	-
DescribeInstancesRole	CREATE_IN_PROGRESS	Resource creation Initiated
DescribeInstancesRole	CREATE_IN_PROGRESS	-
WaitCondition	CREATE_IN_PROGRESS	Resource creation Initiated
WaitCondition	CREATE_IN_PROGRESS	-
InternetGateway	CREATE_IN_PROGRESS	Resource creation Initiated
InternetGateway	CREATE_IN_PROGRESS	-
openvidu	CREATE_IN_PROGRESS	User Initiated

> 
Any help will be appreciated. 
Thanks

**Comment by micaelgallego** [comment]
As several applications have to be downloaded and installed, it is possible that in some circumstances, the timeout we have jumps too early. Can you test with more powerful machines please?

**Comment by philajay** [comment]
I have been trying since yestarday and have not been able to do it .I'm attaching the values used to create stack below. 
`AwsInstanceTypeKMS` | c5.2xlarge | -
-- | -- | --
AwsInstanceTypeOV | c5.2xlarge | -
CoturnPort | 0.0.0.0/0 | -
FreeHTTPAccesToRecordingVideos | true | -
HTTPAccess | 0.0.0.0/0 | -
HTTPSAccess | 0.0.0.0/0 | -
KeyName | tms | -
KibanaPassword | **** | -
KibanaUser | kibana | -
KurentoAsgSize | 1 | -
KurentoAvailabilityZone | us-west-2c | -
LetsEncryptEmail | - | -
MaxOpenPort | 65535 | -
MinOpenPort | 1024 | -
MyDomainName | openvidu.mycompany.com | -
OpenViduCidrBlock | 172.31.0.0/16 | -
OpenViduProPassword | **** | -
OpenViduProUsername | mgarbers | -
OpenViduSecret | **** | -
OpenViduSubnet | 172.31.0.0/20 | -
OpenViduWebhook | false | -
OpenViduWebhookEndpoint | http://my.endpoint.com | -
OpenViduWebhookEvents | sessionCreated,sessionDestroyed,participantJoined,participantLeft,webrtcConnectionCreated,webrtcConnectionDestroyed,recordingStatusChanged | -
OpenViduWebhookHeaders | - | -
OpenviduCDREnable | true | -
OpenviduClusterLoadStrategy | streams | -
OpenviduRecordingNotification | publisher_moderator | -
OpenviduStreamsVideoMaxRecvBandwidth | 0 | -
OpenviduStreamsVideoMaxSendBandwidth | 0 | -
OpenviduStreamsVideoMinRecvBandwidth | 0 | -
OpenviduStreamsVideoMinSendBandwidth | 0 | -
OwnCertCRT | - | -
OwnCertKEY | - | -
PublicElasticIP | 1.0.2.0 | -
SSHCidr | 0.0.0.0/0 | -
TCPRange | 0.0.0.0/0 | -
UDPRange | 0.0.0.0/0 | -
WebUICidr | 0.0.0.0/0 | -
WhichCert | selfsigned
`
Thanks

**Comment by micaelgallego** [comment]
Please check if service is running as some times service_checker is not working properly. Look to this thread: https://github.com/OpenVidu/openvidu/issues/135

You can disable rollback of instances and look for cloud-init-output.log and cloud-init.log to see if there is something wrong.

**Comment by philajay** [comment]
There seems to be something with c5.2xlarge instance. I tried with t2.2xlarge and it worked. Thanks for help
