### ISSUE TITLE
Issue in intenet connection is lost

### ISSUE THREAD

**Issue by dhavalsolanki** [OpenVidu/openvidu#301]
Hello,

I have a scenario where two users are in conference and when internet connection is lost for a particular user  and once it gets reconnected then user is not added to conference again.
I am attaching the log when internet connection is lost and connection is achieved back.
![Capture1](https://user-images.githubusercontent.com/5657449/63350118-7487e400-c37a-11e9-9540-3b4a670a5888.png)

**Comment by micaelgallego** [comment]
Such feature is not yet implemented in OpenVidu. It has to be implemented by the application.

**Comment by pabloFuente** [comment]
You can implement the reconnection process on your own. That's why events have `reason` property, so you can identify the cases where some user has lost its network connection.

**Comment by dhavalsolanki** [comment]
Actually when network gets connected and **streamDestroyed** is called we are getting reason **networkDisconnect**, but it is also closing the video stream. So is there any way to open stream again.

![Capture](https://user-images.githubusercontent.com/5657449/63415620-a56c2580-c41b-11e9-8f23-fee5139613bb.PNG)

**Comment by pabloFuente** [comment]
Event `streamDestroyed` means that the stream is closed. After reconnection. you have to publish again the user's Publisher object by calling `Session.publish(publisher)`
