### ISSUE TITLE
ICE_ADD_CANDIDATE_ERROR in Firefox

### ISSUE THREAD

**Issue by silmood** [OpenVidu/openvidu#302]
Hi there!

I've  been experiencing issues from a specific user who is using Firefox 68.0.2 (Last version)

- We used AWS cloudformation for our deployment
- We checked all the network requirements and they are all set up. Also we opened all UDP ports as Kurento [docs](https://doc-kurento.readthedocs.io/en/6.11.0/user/faq.html#when-is-stun-needed) recommends
- We tested this scenario in the dashboard test, the basic videoconference demo and in our application and the result is the same.
- As you can see the dashboard log seems pretty normal:

![image](https://user-images.githubusercontent.com/7158683/63364500-53ec6980-c33b-11e9-9caf-02295c8269a2.png)

- Here is the browser console log
![image](https://user-images.githubusercontent.com/7158683/63364557-741c2880-c33b-11e9-8aa3-68cdf42e250c.png)

- And `about:webrtc` report in firefox
![image](https://user-images.githubusercontent.com/7158683/63364997-4f748080-c33c-11e9-9740-ee5db61f3985.png)

- Then i checked the supervisor  logs of the server, and here i found the next error:

```
[WARN] 2019-08-20 15:51:55,752 [ntExec-e2-t2113] io.openvidu.server.kurento.endpoint.PublisherEndpoint (onError) - EP 2yvtercy6rrqu4zy_CAMERA_BSBGH: Failed to add ice candidate to the internal endpoint
org.kurento.jsonrpc.JsonRpcErrorException: Error adding candidate. Code: 40401. Data: {"type":"ICE_ADD_CANDIDATE_ERROR"}
	at org.kurento.jsonrpc.internal.JsonRpcRequestSenderHelper$1.onSuccess(JsonRpcRequestSenderHelper.java:128)
	at org.kurento.jsonrpc.internal.JsonRpcRequestSenderHelper$1.onSuccess(JsonRpcRequestSenderHelper.java:113)
	at org.kurento.jsonrpc.client.AbstractJsonRpcClientWebSocket$14.onSuccess(AbstractJsonRpcClientWebSocket.java:452)
	at org.kurento.jsonrpc.client.AbstractJsonRpcClientWebSocket$14.onSuccess(AbstractJsonRpcClientWebSocket.java:433)
	at com.google.common.util.concurrent.Futures$6.run(Futures.java:1773)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

I read that could be a problem related with `libnice` library but the version installed seems to be correct:
```
$ dpkg -l | grep nice
ii  gstreamer1.5-nice:amd64              0.1.15-1kurento3.16.04                     amd64        ICE library (GStreamer 1.5 plugin)
ii  libnice10:amd64                      0.1.15-1kurento3.16.04                     amd64        ICE library (shared library)
```

Tell me if you need more info. Thank you for your support :)

**Comment by micaelgallego** [comment]
Can you test with OpenVidu service in demos?

https://demos.openvidu.io:4443
user: OPENVIDUAPP
pass: MY_SECRET

**Comment by silmood** [comment]
We've just done the test and the result was the same. Here are some snapshots:

![image](https://user-images.githubusercontent.com/7158683/63375966-5c03d380-c352-11e9-94da-b3271634ea51.png)

![image](https://user-images.githubusercontent.com/7158683/63375987-66be6880-c352-11e9-923d-9c451bca4dde.png)

**Comment by micaelgallego** [comment]
It seems there are something estrange with your system. In my system I have candidates different than 10.1.1.25 and 193.147.51.58. 

I have Docker installed, for that reason I have a lot of Docker IPs in candidates. But I also have my public IP and my local network IP 

![image](https://user-images.githubusercontent.com/1072424/63379543-cf2e3980-c394-11e9-9dd7-d3bfff07bade.png)

Can you check what candidates are generated in Chrome in your system? Just to compare them. Do you have some special in your network? Do you have some privacy related configuration in Firefox? It is possible that some configurations avoid showing some local IPs...

**Comment by silmood** [comment]
Here are the results in chrome. 

![image](https://user-images.githubusercontent.com/7158683/63381396-31b81300-c35e-11e9-9770-dfe46531cec8.png)

Remote candidates in webrtc-internals

![image](https://user-images.githubusercontent.com/7158683/63382351-2534ba00-c360-11e9-9916-9de334e0c2cc.png)

![image](https://user-images.githubusercontent.com/7158683/63382360-2e258b80-c360-11e9-8534-27d90403ed3f.png)

![image](https://user-images.githubusercontent.com/7158683/63382412-4a292d00-c360-11e9-9b62-9cc277f4946a.png)

![image](https://user-images.githubusercontent.com/7158683/63382492-70e76380-c360-11e9-8f52-ff690237f257.png)


Local candidates

![image](https://user-images.githubusercontent.com/7158683/63382539-8a88ab00-c360-11e9-93a5-24e92f19b9da.png)

![image](https://user-images.githubusercontent.com/7158683/63382558-94121300-c360-11e9-9d65-0bde5c4fc0d0.png)

![image](https://user-images.githubusercontent.com/7158683/63382581-9d02e480-c360-11e9-8030-f390b2d2d2ac.png)

![image](https://user-images.githubusercontent.com/7158683/63382602-a8561000-c360-11e9-8017-721d9b0c657b.png)

![image](https://user-images.githubusercontent.com/7158683/63382611-ae4bf100-c360-11e9-9510-1d2099a23aa2.png)

Apparently nothing strange with privacy configuration in Firefox. In chrome everything is working fine. In firefox there is a warning indicating that client is using more than one STUN/TURN servers,  maybe that could be a clue, however we've tested with other users that present the same warning and everything works fine.

**Comment by silmood** [comment]
Checking the WebRTC configuration of the client browser, we found the attribute `rely_only` was set on true. We changed this value and now we haven't had problems with that user.

![image](https://user-images.githubusercontent.com/7158683/64731842-85be9f00-d4a7-11e9-9b5d-84d70ac423ec.png)
