### ISSUE TITLE
WebRTC stats 

### ISSUE THREAD

**Issue by LaphazeMC** [OpenVidu/openvidu#308]
Hi,

Is it possible to get bandwidth speed, latency, packets loss and bitrate information in openvidu ? I didn't find anything in the docs.
If possible, how can I implement this using Angular for example ?

Something like this could be perfect : https://www.webrtc-experiment.com/getStats/

Thanks a lot

**Comment by micaelgallego** [comment]
You can use getRTCPeerConnection() method in Session object.

**Comment by mandaputtra** [comment]
@micaelgallego how to do that? like this?

```js
var session = OV.initSession();

session.getRTCPeerConnection()
```

**Comment by micaelgallego** [comment]
This method is this one:

myPublisher.stream.getRTCPeerConnection()

There is a typo in my last comment.

**Comment by mandaputtra** [comment]
Thanks,
