### ISSUE TITLE
Change the ip address after installation.

### ISSUE THREAD

**Issue by philajay** [OpenVidu/openvidu#309]
Hi All,
I installed the openvidu server using the amazon stack. Leter I tried to assign the elastic IP to the openvidu server. I updated the application.properties and restarted the server. Now when I browse to dashboard I get the following error Access to 

> XMLHttpRequest at 'https://xxxx:4443/api-login/login' from origin 'https://xxxx.compute.amazonaws.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Do I need to change some other settings or need to install it again?
Thanks
Ajay Pal Singh

**Comment by nordri** [comment]
Hi @philajay 

When one deploy this stack with regular IP configuration, a script is responsible to check changes in network configuration.

When one stop an instance in AWS the IPs change on the next boot, so there's a script which will update all config files needed by OpenVidu (nginx, media server, openvidu itself and coturn).

Once you've change the IP by hand my advice is you can **stop** the instance and **start** it again. **No reboot**.

The script will spread the new IP across all the config files.

Please Let me know if you need any help.

Cheers!

**Comment by pabloFuente** [comment]
Closing this for now. If you have any other question, feel free to reopen the issue.
