### ISSUE TITLE
Cannot create AWS Cloudformation stack !!

### ISSUE THREAD

**Issue by talentedandrew** [OpenVidu/openvidu#31]
Getting the below error.

![screenshot from 2018-03-06 23_33_57l](https://user-images.githubusercontent.com/15646138/37049682-aadb15da-2197-11e8-9cfa-64d75a891cce.png)

**Comment by pabloFuente** [comment]
Problem solved (it was an issue with the permissions)

**Comment by talentedandrew** [comment]
@pabloFuente  thanks
