### ISSUE TITLE
Openvidu recording file shows blank page

### ISSUE THREAD

**Issue by VJPranay** [OpenVidu/openvidu#311]
Openvideo recording file shows blank page chrome page

![32533](https://user-images.githubusercontent.com/9312169/64241152-c60aa400-cf20-11e9-8789-35be7bb12cd3.jpg)

**Comment by pabloFuente** [comment]
You must have some missconfiguration in openvidu-server if composed video recordings show this result. Please, provide all the details of your setup.

**Comment by VJPranay** [comment]
Used this link https://openvidu.io/docs/deployment/deploying-ubuntu/ to do the setup also using domain instead of IP with SSL

**Comment by VJPranay** [comment]
The duration of recording file is exactly same as the duration of the session

**Comment by pabloFuente** [comment]
First of all, which openvidu-server JAR artifact are you using in your deployment?

Composed video recording requires a Chrome instance automatically launched by OpenVidu Server in the same host to connect to the recording layout, which is a web page served by OpenVidu Server itself.

Please, find in OpenVidu Server logs the line stating:

```
io.openvidu.server.recording.service.ComposedRecordingService (startRecordingWithVideo) - Recorder connecting to url [....]
```

And see what URL is being passed to the Chrome instance to connect to the recording layout.
That URL must be accessible from inside the same host. By default is the public IP configured in openvidu-server (the same IP your clients will use to connect to it), but there's a configuration parameter you can set in OpenVidu Server to customize the URL passed to the recording Chrome instances.

**Comment by VJPranay** [comment]
thank you it helped me

**Comment by sreedharbukya** [comment]
I was having same issue. 

I found an issue with credentials set to string starting with "y" as port number for the URL which is being generated for recording the video. 

All I did is to fix is change password and restart the server.
