### ISSUE TITLE
OpenVidu returns recording with url: null

### ISSUE THREAD

**Issue by Antarus66** [OpenVidu/openvidu#312]
OpenVidu returns recording with url: null.
Option openvidu.recording.public-access is set to 'true'. Recording's status is 'ready'. A recording file is available by a link "https://YOUR_OPENVIDUSERVER_IP/recordings/<RECORDING_ID>/<RECORDING_NAME>.<EXTENSION>". 
OpenVidu version (and nodes sdk version) is 2.11.0

**Comment by pabloFuente** [comment]
Hi,

This may be related to a bug recently found in the recording metadata. Next release will change the way `url` property works on recording entities: it will always be defined, even when openvidu.recording.public-access is set to false. It really makes no sense to return null when recordings are protected: they will be secured with openvidu credentials, so unless you know them they won't be accesible.

**Comment by pabloFuente** [comment]
Closing this for now. Waiting till next release

**Comment by Antarus66** [comment]
> Next release will change the way `url` property works on recording entities

Thank you a lot. Appreciate this!
