### ISSUE TITLE
No openvidu dashboard shown

### ISSUE THREAD

**Issue by MarkoMarkani** [OpenVidu/openvidu#313]
I want to deploy OpenVidu server on my Ubuntu machine.I followed the official guide:
Deploying OpenVidu on Ubuntu.
The log does not throw any errors,but Openvidu server does not seem to be working.
After running it,no self-signed default certificate is shown.
All I get is a ,,This site can’t be reached'-ERR_CONNECTION_TIMED_OUT" blank page on port 4443.
Here is my log when I run it:

` java -jar -Dopenvidu.secret=YOUR_SECRET -Dopenvidu.publicurl=https://mypublicipaddress:4443/ openvidu-server-2.11.0.jar
10:11:59.218 [main] INFO io.openvidu.server.OpenViduServer - Using /dev/urandom for secure random generation

______________________________________________
   ____               __      ___     _       
  / __ \              \ \    / (_)   | |      
 | |  | |_ __   ___ _ _\ \  / / _  __| |_   _
 | |  | | '_ \ / _ \ '_ \ \/ / | |/ _` | | | |
 | |__| | |_) |  __/ | | \  /  | | (_| | |_| |
  \____/| .__/ \___|_| |_|\/   |_|\__,_|\__,_|
        | |
        |_|             version 2.11.0
______________________________________________                                          

[INFO] 2019-09-09 10:12:00,274 [main] io.openvidu.server.OpenViduServer (logStarting) - Starting OpenViduServer on connexions with PID 29100 (/home/ubuntu/iot/openvidu-server-2.11.0.jar started by ubuntu in /home/ubuntu/iot)
[INFO] 2019-09-09 10:12:00,275 [main] io.openvidu.server.OpenViduServer (logStartupProfileInfo) - No active profile set, falling back to default profiles: defaultWARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (jar:file:/home/ubuntu/iot/openvidu-server-2.11.0.jar!/BOOT-INF/lib/groovy-2.4.13.jar!/) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[INFO] 2019-09-09 10:12:01,819 [main] io.openvidu.server.OpenViduServer (init) - OpenVidu Server using custom URL: [wss://mypublicipaddress:4443]
[INFO] 2019-09-09 10:12:02,149 [main] org.springframework.boot.web.embedded.tomcat.TomcatWebServer (initialize) - Tomcat initialized with port(s): 4443 (https)
[INFO] 2019-09-09 10:12:02,175 [main] org.apache.coyote.http11.Http11NioProtocol (log) - Initializing ProtocolHandler ["https-jsse-nio-0.0.0.0-4443"]
[INFO] 2019-09-09 10:12:02,194 [main] org.apache.catalina.core.StandardService (log) - Starting service [Tomcat]
[INFO] 2019-09-09 10:12:02,194 [main] org.apache.catalina.core.StandardEngine (log) - Starting Servlet engine: [Apache Tomcat/9.0.19]
[INFO] 2019-09-09 10:12:02,305 [main] org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] (log) - Initializing Spring embedded WebApplicationContext
[INFO] 2019-09-09 10:12:02,306 [main] org.springframework.web.context.ContextLoader (prepareWebApplicationContext) - Root WebApplicationContext: initialization completed in 1760 ms
[INFO] 2019-09-09 10:12:02,437 [main] io.openvidu.server.OpenViduServer (kmsManager) - OpenVidu Server using one KMS: ws://localhost:8888/kurento
[INFO] 2019-09-09 10:12:02,463 [rbeatExec-e1-t0] org.kurento.jsonrpc.client.JsonRpcClientNettyWebSocket (connectNativeClient) - [KurentoClient]  Connecting native client
[INFO] 2019-09-09 10:12:02,464 [rbeatExec-e1-t0] org.kurento.jsonrpc.client.JsonRpcClientNettyWebSocket (connectNativeClient) - [KurentoClient]  Creating new NioEventLoopGroup
[INFO] 2019-09-09 10:12:02,700 [ntLoopGroup-2-1] org.kurento.jsonrpc.client.JsonRpcClientNettyWebSocket (initChannel) - [KurentoClient]  Initiating new Netty channel. Will create new handler too!
[WARN] 2019-09-09 10:12:02,906 [EventExec-e2-t0] io.openvidu.server.kurento.kms.KmsManager (connected) - Kurento Client is now connected to KMS KMS-4JHU3I with uri ws://localhost:8888/kurento
[INFO] 2019-09-09 10:12:02,939 [main] io.openvidu.server.coturn.CoturnCredentialsService (initialize) - COTURN Redis DB accessible with string "ip=127.0.0.1 dbname=0 password=turn connect_timeout=30"
[INFO] 2019-09-09 10:12:02,940 [main] io.openvidu.server.coturn.CoturnCredentialsService (initialize) - Cleaning COTURN DB...
[INFO] 2019-09-09 10:12:02,940 [main] io.openvidu.server.coturn.CoturnCredentialsService (initialize) - Path of COTURN log files: /var/tmp/
[INFO] 2019-09-09 10:12:02,950 [main] io.openvidu.server.coturn.CoturnCredentialsService (initialize) - COTURN DB is now empty
[INFO] 2019-09-09 10:12:02,950 [main] io.openvidu.server.coturn.CoturnCredentialsService (initialize) - Using COTURN credentials service for BASH environment
[INFO] 2019-09-09 10:12:03,156 [main] org.springframework.scheduling.concurrent.ThreadPoolTaskScheduler (initialize) - Initializing ExecutorService 'jsonrpcTaskScheduler'
[INFO] 2019-09-09 10:12:03,401 [main] org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor (initialize) - Initializing ExecutorService 'applicationTaskExecutor'
[INFO] 2019-09-09 10:12:03,571 [main] org.springframework.boot.autoconfigure.web.servlet.WelcomePageHandlerMapping (<init>) - Adding welcome page: class path resource [static/index.html]
[INFO] 2019-09-09 10:12:03,797 [main] org.springframework.security.web.DefaultSecurityFilterChain (<init>) - Creating filter chain: any request, [org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter@7b7b3edb, org.springframework.security.web.context.SecurityContextPersistenceFilter@77bd7fe7, org.springframework.security.web.header.HeaderWriterFilter@52b6319f, org.springframework.web.filter.CorsFilter@6b474074, org.springframework.security.web.authentication.logout.LogoutFilter@5631962, org.springframework.security.web.authentication.www.BasicAuthenticationFilter@3104351d, org.springframework.security.web.savedrequest.RequestCacheAwareFilter@10876a6, org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter@706cb08, org.springframework.security.web.authentication.AnonymousAuthenticationFilter@108531c2, org.springframework.security.web.session.SessionManagementFilter@5bcde458, org.springframework.security.web.access.ExceptionTranslationFilter@40d10481, org.springframework.security.web.access.intercept.FilterSecurityInterceptor@7ec58feb]
[INFO] 2019-09-09 10:12:03,869 [main] org.apache.coyote.http11.Http11NioProtocol (log) - Starting ProtocolHandler ["https-jsse-nio-0.0.0.0-4443"]
[INFO] 2019-09-09 10:12:04,129 [main] org.springframework.boot.web.embedded.tomcat.TomcatWebServer (start) - Tomcat started on port(s): 4443 (https) with context path ''
[INFO] 2019-09-09 10:12:04,134 [main] io.openvidu.server.OpenViduServer (logStarted) - Started OpenViduServer in 4.795 seconds (JVM running for 5.548)
[INFO] 2019-09-09 10:12:04,136 [main] io.openvidu.server.OpenViduServer (whenReady) - 

    ACCESS IP            
-------------------------
https://mypublicipaddress:4443/
-------------------------
`
No dispatcher servlet is initialized after this,neither is 
"REST API: GET /config/openvidu-publicurl".

Note-instead of "mypublicipaddress" is used my real public address,of course.

Could you help me to solve this?
Thank you in advance.

**Comment by pabloFuente** [comment]
Are you sure your domain name is properly paired with your sever's public IP, and that port 4443 is opened to the public?

That error is usually caused by a missconfiguration in the host's network. Not a problem with OpenVidu itself.

Regards.
