### ISSUE TITLE
Please create a security advisory

### ISSUE THREAD

**Issue by JLLeitschuh** [OpenVidu/openvidu#317]
I would like to report a security vulnerability.
Please open a security advisory and add me.
https://github.com/OpenVidu/openvidu/security/advisories

**Comment by micaelgallego** [comment]
Done. I suppose a notification has been sent to you. 

Honestly, it is my first time using "security advisory" in GitHub and I don't really know how it works.

**Comment by JLLeitschuh** [comment]
I've commented there. This can be closed.
