### ISSUE TITLE
Chrome's "Stop Sharing Screen" button handler

### ISSUE THREAD

**Issue by oalexgg** [OpenVidu/openvidu#319]
Whenever an user clicks on chrome's stop sharing button the screen turns black, is there a way to handle that event?
![issue](https://user-images.githubusercontent.com/25076022/65552132-39348400-dee9-11e9-8cee-3743f8344c1e.PNG)

**Comment by pabloFuente** [comment]
We will look into the possibility of adding an event to warn about this. Should be possible with Web native MediaStream API.

**Comment by pabloFuente** [comment]
But you can easily implement it on your own.

You just have to add an event listener to the **MediaStream** object. You can try with `"ended"` event or even better, `"inactive"` event. Those events should be triggered whenever the user clicks on that button. Do whatever you want when they trigger (you may send a `Session.signal` warning about it to the rest of participants of the session).

You can access MediaStream object by calling `Stream.getMediaStream()`

**Comment by pabloFuente** [comment]
A new section has been added to offical Documentation explaining this:

https://openvidu.io/docs/advanced-features/screen-share/#how-to-know-when-the-user-stops-sharing-the-screen

**Comment by oalexgg** [comment]
It's not working for me, i will search on my code for errors, it may be that I'm not implementing the screen share the proper way.

**Comment by heymatias** [comment]
It's not working at all 🤦‍♂ 

I'm trying to get any property to check if the video is still playing, and if not just close the connection, but didn't found that either.

**Comment by pabloFuente** [comment]
It works fine in latest Chrome and Firefox with 'ended' event as explained in the documentation note.

![Selection_429](https://user-images.githubusercontent.com/15049534/77702302-7cff6780-6fb8-11ea-81c1-f8186bed9f48.png)
