### ISSUE TITLE
How create screenshot video?

### ISSUE THREAD

**Issue by TemoxaGreenMoney** [OpenVidu/openvidu#322]
Hi

How i can create screenshot video in active session?

**Comment by pabloFuente** [comment]
In the server side or the client side? There's no method yet to generate a screenshot of a video stream in the server side. To do it on the client side, Google is your friend:

https://stackoverflow.com/a/13765373/6943134
https://www.tutorialspoint.com/How-to-take-a-snapshot-of-HTML5-JavaScript-based-video-player
https://github.com/ilkkao/capture-video-frame
