### ISSUE TITLE
GENERIC_ERROR

### ISSUE THREAD

**Issue by santoshsaven** [OpenVidu/openvidu#323]
OpenViduError {name: "GENERIC_ERROR", message: "Connection not found for endpoint q3tldvo6gntqquhj…H. Ice candidate will be ignored: [object Object]"}
message: "Connection not found for endpoint q3tldvo6gntqquhj_CAMERA_JAMPH. Ice candidate will be ignored: [object Object]"
name: "GENERIC_ERROR"

**Comment by pabloFuente** [comment]
Again @santoshsaven, without context this is useless. I'm going to close the issue until you provide more details about the error.

Regards
