### ISSUE TITLE
Need Assistance

### ISSUE THREAD

**Issue by mateenQureshi** [OpenVidu/openvidu#325]
Hi Guys,

I have a REST API developed in Nodejs. We developed it in microservices style, hence one dedicated service (plain node process without HTTP server) is responsible for openvidu utils. 

I wanna know how should I provide certificate & keys when generating token from node-client package? I am bypassing TLS (`NODE_TLS_REJECT_UNAUTHORIZED="0"`) in development. But in production, I am stuck from the last three days. Even bypassing TLS in production is also not working for me. 

Please help!

Let me know if you need further details on the following scenario.

**Comment by pabloFuente** [comment]
Please, do not fill bug reports when asking for assistance or suport. Use the google-group mailing list: https://groups.google.com/forum/#!forum/openvidu
