### ISSUE TITLE
Unable to record sessions with canvas stream

### ISSUE THREAD

**Issue by markgarbers** [OpenVidu/openvidu#326]
I've enabled streaming a canvas and this works fine and can be viewed by other subscribers.

However, when I try to record sessions set up in this way, I get a 500 error saying "error starting recording". Recording works perfectly when I disable the canvas streaming and use a video source from a webcam.

This is the code I'm using to initialise the canvas stream:

```
var canvasStream = document.getElementById('whiteboardcanvas').captureStream(5).getVideoTracks()[0];

publisher = OV.initPublisher(undefined, { hasAudio:false, hasVideo:true, videoSource:canvasStream, resolution:'300x300' });
```

**Comment by markgarbers** [comment]
Further clarification to the above, composed recordings do work, individual recordings don't.

**Comment by pabloFuente** [comment]
We'll have to do some testing about this particular case. Individual recording of publishers initialize with a canvas video MediaStreamTrack. The moment we have some results, I'll post here a new message.

**Comment by markgarbers** [comment]
Any news or progress on this?

**Comment by pabloFuente** [comment]
Yes,

I've performed some tests and INDIVIDUAL recording is working fine for published streams built with a custom MediaStreamTrack got from a canvas.

I've used a very similar code to this (https://openvidu.io/api/openvidu-browser/classes/openvidu.html#getusermedia) to publish a webcam black-and-white video at 10 fps and HD resolution to a Session. I joined a subscriber user to confirm everything was working fine. Then started INDIVIDUAL recording (which recorded just a single stream with audio and video).

After stopping the recording, the generated video file was perfectly ok, and no errors were shown on openvidu-server log.

I've performed this test by using official [openvidu-recording-node tutorial](https://github.com/OpenVidu/openvidu-tutorials/tree/master/openvidu-recording-node) and openvidu-server-kms:2.11.0 docker container, modifying it a little bit right here to get the publisher like this:

```javascript
const FRAME_RATE = 10;
OV.getUserMedia({
    audioSource: false,
    videoSource: undefined,
    resolution: '1280x720',
    frameRate: FRAME_RATE
})
.then(mediaStream => {

    var videoTrack = mediaStream.getVideoTracks()[0];
    var video = document.createElement('video');
    video.srcObject = new MediaStream([videoTrack]);

    var canvas = document.createElement('canvas');
    var ctx = canvas.getContext('2d');
    ctx.filter = 'grayscale(100%)';

    video.addEventListener('play', () => {
        var loop = () => {
            if (!video.paused && !video.ended) {
                ctx.drawImage(video, 0, 0, 300, 170);
                setTimeout(loop, 1000/ FRAME_RATE); // Drawing at 10 fps
            }};
        loop();
    });
    video.play();

    var grayVideoTrack = canvas.captureStream(FRAME_RATE).getVideoTracks()[0];
    var publisher = this.OV.initPublisher(
        'video-container',
        {
            audioSource: false,
            videoSource: grayVideoTrack
        });

        ...
```

Any other useful information you could give us?
