### ISSUE TITLE
Filters not work in Ionic 

### ISSUE THREAD

**Issue by gomez34** [OpenVidu/openvidu#327]
Filters do not work in the Ionic app. For example the barcode reader. What could be the problem?

Thank you.

**Comment by pabloFuente** [comment]
Filters are applied on the server side. They do not depend on the client-side in any way: the video stream could be sent by any device to which Kurento can connect.

**Comment by gomez34** [comment]
Buenas noches,
Esta congelación solo es sufrida cuando el presentador es un terminal con Ionic y no en todos los dispositivos, por lo que descartamos servidor y Red. ¿Podemos realizar algún cambio o investigar en alguna parte del código el problema para evitar estas congelaciones?

Gracias.

Saludos.
________________________________
