### ISSUE TITLE
Ionic small freezes

### ISSUE THREAD

**Issue by gomez34** [OpenVidu/openvidu#328]
In calls with Ionic from Android, the video has small freezes on other subscribers. The connection quality is good. what is the problem?

**Comment by pabloFuente** [comment]
So many factors can come into play regarding these small freezes: client's network performance on the sender side, client's network performance on the receiver side, server's network performance, device capabilities, quality of the video stream... There's no a single answer to your question. For example, I sometimes experience video freezing  in my own private Wifi network if I connect through my router repeater, even on Skype or any other video streaming service.

What I can recommend to you is making sure your server side is properly deployed in a healthy and publicly accessible network, and then exploring in which kind of client-side conditions you see these freezes. If in your particular deployment every other client (Chrome, Firefox, a native Android app...) work just fine, then we could assume that there may indeed be some particular problem with Ionic, and do some further research.

Regards.

**Comment by gomez34** [comment]
Buenas Noches,

Usamos el mismo código que en la web para implementar los filtros pero en ionic nos muestra que no reconoce el método applyFilter.
________________________________
