### ISSUE TITLE
openvidu-browser: double-asking consent when using OpenVidu.getUserMedia

### ISSUE THREAD

**Issue by mserve** [OpenVidu/openvidu#330]
There is a double-consent request to the user when using OpenVidu.getUserMedia as eg in 

```
var OV = new OpenVidu();
OV.getUserMedia({
    audioSource: false, // No audio source - not supported in screen share
    videoSource: 'screen', // The source of video. 
}).then( ... );
```

I guess there should be a return statement in https://github.com/OpenVidu/openvidu/blob/master/openvidu-browser/src/OpenVidu/OpenVidu.ts#L569 as getUserMedia() should not be called at all if the videoSource is screen and there is no audio

**Comment by mserve** [comment]
See PR  #331

**Comment by pabloFuente** [comment]
See https://github.com/OpenVidu/openvidu/pull/331#discussion_r331924396

**Comment by pabloFuente** [comment]
PR has been merged
