### ISSUE TITLE
About  Recording Configuration

### ISSUE THREAD

**Issue by Ray-Sir-Like** [OpenVidu/openvidu#332]
Hi ,
  If I can't use docker to configurate recording in Openvidu-Server 2.11.0,just use openvidu-server-2.11.0.jar, can I configurate it?
![image](https://user-images.githubusercontent.com/25659192/66379440-01990200-e9e8-11e9-981e-fb60ab9f2846.png)

**Comment by pabloFuente** [comment]
Hi,

If you are running OpenVidu Server JAR, then it means you are doing so in an Ubuntu machine. Why can't you install Docker in it?

Docker is mandatory to enable OpenVidu Recording module. It is true that we could make configurable whether users want recording module to work except for composed video recording (that is, it could work without Docker for composed audio recording or indivudal (audio and video) recording).

But for now we consider Docker mandatory to enable recording module.
