### ISSUE TITLE
Check if publisher is joining session

### ISSUE THREAD

**Issue by Anytram** [OpenVidu/openvidu#333]
Hello,
is there any way to check if publisher is joining session?
I have separate subscriber and publisher app and I need to know if/when publisher is joining session in my subscriber app.

**Comment by pabloFuente** [comment]
Please, avoid asking this kind of questions about the platform in the GitHub Issues section (which is reserved for issues/bugs/problems). To get support you can write on OpenVidu's Google Group: https://groups.google.com/forum/#!forum/openvidu
