### ISSUE TITLE
Screen Sharing on Chrome broken after macOS Catalina 10.15 update

### ISSUE THREAD

**Issue by drlatham** [OpenVidu/openvidu#336]
Note: These steps work fine in latest Firefox

Repro steps:

1. Upgrade macOS to Catalina 10.15 (19A583)
1. Assert latest Chrome Version or upgrade to 77.0.3865.90 (Official Build) (64-bit) is installed
1. Assert Chrome has been added to the list of allowed apps that can use ScreenSharing, see picture below
    
    <img width="666" alt="Screen Shot 2019-10-09 at 3 53 20 PM" src="https://user-images.githubusercontent.com/6742826/66519613-3e7afc80-eaad-11e9-8cf0-60c4bf525f19.png">

1. git clone the `openvidu-tutorials` project
1. Follow the setup instructions for the `openvidu-hello-world` tutorial, [link here](https://openvidu.io/docs/tutorials/openvidu-hello-world/)
1. Edit `openvidu-hello-world/web/app.js:23`, you should add `, { videoSource: "screen" }` to the initPublisher function so that the line looks like the following:
    ```
    				var publisher = OV.initPublisher("publisher", { videoSource: "screen" });
    ```
1. Run the tutorial with `http-server`
1. Assert `http-server` is serving `openvidu-hellow-world/web` to `localhost:8080`
1. Go to `http://localhost:8080/` in Chrome
1. Click the Join button
1. Assert you click "Your Entire Screen" and click "Share"

    <img width="677" alt="Screen Shot 2019-10-09 at 3 54 25 PM" src="https://user-images.githubusercontent.com/6742826/66519697-69fde700-eaad-11e9-9d71-b37bf5c0a2d7.png">

1. Your screen and console will look like this

    
<img width="1295" alt="Screen Shot 2019-10-09 at 3 46 08 PM" src="https://user-images.githubusercontent.com/6742826/66519801-974a9500-eaad-11e9-9846-2c94dbc04b49.png">

**Comment by pabloFuente** [comment]
Works fine for me:

<img width="1440" alt="Captura de pantalla 2019-10-10 a las 15 12 57" src="https://user-images.githubusercontent.com/15049534/66572297-ff15e400-eb70-11e9-9ddf-dae8446b0a76.png">

That is OpenVidu Call Demo (https://demos.openvidu.io/openvidu-call) sending a webcam stream and a screen share screen (this is the About MacOS window, showing the latest Catalina version). You can also see in bottom left corner Chrome's version.

**Comment by pabloFuente** [comment]
Works fine for me: 

![Captura de pantalla 2019-10-10 a las 15 12 57](https://user-images.githubusercontent.com/15049534/66572610-8f542900-eb71-11e9-819b-b7580df5268c.png)

There you have OpenVidu Call Demo (https://demos.openvidu.io/openvidu-call) sending a webcam stream and a screenshare stream. This is the About MacOS window, showing latest Catalina version. On the bottom left corner you can see the latest offical version of the running Chrome.

**Comment by pabloFuente** [comment]
As performing the exact steps described in the comment above couldn't help reproducing the issue (using the exact same OS and browser versions), we will be closing the issue for now. If somebody else  expermient similar problems, we will open it again.
