### ISSUE TITLE
why  Recorder connecting to : /inspector/#/layout-best-fit

### ISSUE THREAD

**Issue by assiomatica** [OpenVidu/openvidu#337]
I am testing the recording in version 11
it's doesn't work because the layout url is fixed and even changing the properties files no result 
I get a 404 page of course because that path doesn't exist.

**Comment by pabloFuente** [comment]
What do you mean when you say...

1) Because the layout url is fixed ?
2) Changing the properties file no result ?

Please, explain that in detail.

**Comment by assiomatica** [comment]
Hi
even if I change the properties file /opt/openvidu/application.properties
to 
openvidu.recording.composed-url=https://openvidu.xxxx.zzz/

after reboot this is the value I found, seems the file is modified by some process/script

openvidu.recording.composed-url=https://openvidu.xxxx.zzz/inspector/

**Comment by pabloFuente** [comment]
Hi,

There was a bug related to this issue that was fixed some days ago. It affected OpenVidu Pro deployment. Should be fixed now, please give it a try with a new deployment.

Cheers.
