### ISSUE TITLE
Can not show video after switch share-screen to video talk or video switch to share-creen?

### ISSUE THREAD

**Issue by willylee007** [OpenVidu/openvidu#34]
Hi! Best regards!
I had tested video talk and screen sharing respectively, they both work! But I wanted to switch share-screen to video talk, it can't show video.I used the following method to switch:
[publish-unpublish](https://github.com/willylee007/openvidu.io-docs/blob/master/docs/how-do-i/publish-unpublish.md)

**Comment by pabloFuente** [comment]
Hi,

Can you please test this behaviour in our Test App and check if that is what you want?
You can run it with a simple docker command:

`docker run -p 8443:8443 openvidu/testapp`

Connect to [https://localhost:8443](https://localhost:8443) and add a Publisher and a Subscriber to the session (just to the right of _JOIN_ button, uncheck _Subscribe_ option in the first one and _Publish_ option in the second one respectively, and press _JOIN_ button in both of them).

When the Subscriber starts receiving the webcam of the Publisher, change dinamically the Publisher stream by pressing this button in the Publisher view:

![selection_166](https://user-images.githubusercontent.com/15049534/38021338-d4251b34-327c-11e8-82d8-038b7caaacdb.png)

After pressing that button, the Publisher will start publishing the screen if the webcam was the previous option.

**Comment by willylee007** [comment]
Cool! The above method has been tested, it works! 
But I'm using React to develop not Angular, I have to test for it.
Waiting for my good news~!
Thx! @_@

**Comment by willylee007** [comment]
Cool! It works!

Thx!

**Comment by willylee007** [comment]
Hey hey hey~
There is something wrong when user want to cancel screen-share, we should do our work after user confirming share his screen...So I think the control flow is:
1. request screen share, and wait for the callback.
2. if click confirm, unpublish oldPublisher and publish new screenPublisher 
3. if click cancel, return error callback.
4. In addition, client should detect when the user stoping screen-share.
I'm learning TS and trying to make my first contribution for OpenVidu.(⁎⁍̴̛ᴗ⁍̴̛⁎)
