### ISSUE TITLE
Certificate CN invalid error

### ISSUE THREAD

**Issue by bebekar** [OpenVidu/openvidu#340]
what is the cause of this error, it appears sometimes, other times it works well

webSocketWithReconnection.js:71 WebSocket connection to 'wss://192.168.1.42:4443/openvidu' failed: Error in connection establishment: net::ERR_CERT_COMMON_NAME_INVALID

**Comment by pabloFuente** [comment]
You client does not like your certificate. In a production environment you should use a domain name instead of IP 192.168.1.42 and your OpenVidu Server should be well protected with the appropriate certificates for that domain name.

**Comment by bebekar** [comment]
This is setup on the localhost environment with valid self signed certificates. 
the self signed CA certificates is also available on all clients. 

I understand that SSL is necessary, Wish to know the reason
