### ISSUE TITLE
react-native demo project can't run-android  [Could not open settings remapped class]

### ISSUE THREAD

**Issue by shipcake** [OpenVidu/openvidu#341]
I follow doc. but can't run in android 
I try to remove .gradle cache and anything in solution at stackoverflow :(

![image](https://user-images.githubusercontent.com/30076862/67362048-6cc00800-f594-11e9-8500-56aa626b8b2c.png)

>

**Comment by micaelgallego** [comment]
You need to purchase a version of openvidu-browser with react-native support.

If you are interested, please contact with me at openvidu@gmail.com
