### ISSUE TITLE
RCTFatalException: Unhandled JS Exception: TypeError: undefined is not an object (evaluating 'navigator.userAgent.indexOf')

### ISSUE THREAD

**Issue by ChinaJson** [OpenVidu/openvidu#342]
Running openvidu-react-native-59.9 crashes, creating a new project also crashes, I noticed that
```
 import { OpenVidu } from 'openvidu-browser';
```

**Comment by micaelgallego** [comment]
You need to purchase a license to get an updated openvidu-browser version to use react-native.
