### ISSUE TITLE
publishAudio eventually stops working

### ISSUE THREAD

**Issue by maxmclarentaylor** [OpenVidu/openvidu#345]
Hi there,

I am having an issue with my publishAudio when using safari IOS.

Problem: I enter muted and then when I unmute the call I have audio, however when I then mute and unmute again I can't hear my audio.

I am using publishAudio and then passing in true/false.

The error is NOT occurring when using the Chrome browser.

 If I change camera, which results in me un-publishing then publishing a stream with a new video stream, the unmute/mute function can be toggled on or off three or four times in a row, pressing every second, before it stops working and I am left without an audio being published. 

safari version - "Mozilla/5.0 (iPad; CPU OS 13_1_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.1 Mobile/15E148 Safari/604.1" 

openvidu-browser: "^2.11.0",

Here is my mute function:

![image](https://user-images.githubusercontent.com/42745017/67685261-a88c1080-f98c-11e9-85a6-4a5c9840234a.png)

This is where I call my function for ios:

![image](https://user-images.githubusercontent.com/42745017/67686193-403e2e80-f98e-11e9-9ad1-250843874a0a.png)

Thanks,

Max

**Comment by maxmclarentaylor** [comment]
the error was also occurring on the iphone

**Comment by blazeag** [comment]
I have a very similar problem with publishAudio, but with OpenVidu v2.12.0. Did you manage to solve in some way?

**Comment by micaelgallego** [comment]
It seems Safari is a bit more fragile than Google Chrome managing WebRTC media. 

We will take a look to the issue.

**Comment by blazeag** [comment]
Thank you very much @micaelgallego and @CSantosM 
It must be very frustrating having to write and test different code for different browsers. Sometime I suddently wake up in the night still scared by the old good IE6 times...

**Comment by micaelgallego** [comment]
As you have identified, it seems the issues are due to problems in Safari iOS, not if OpenVidu itself (https://openvidu.discourse.group/t/troubles-with-safari-on-ios/367/5).

Closing this for now. Open again if we can do something.
