### ISSUE TITLE
Exceptions on Session.js line 436

### ISSUE THREAD

**Issue by yosietserga** [OpenVidu/openvidu#346]
Hi, 

I found an error handler exception missing on /lib/OpenVidu/Session.js

I put this to fix my own app

```javascript
for (let i in signal.to) {
    let connection = signal.to[i]; if (connection === null || connection === false || typeof connection == 'undefined') continue;
    if (typeof connection.connectionId != 'undefined') 
        connectionIds_1.push(connection.connectionId); 
    else 
        connectionIds_1.push(connection);
}
```

Maybe someone can do it better, regards

**Comment by yosietserga** [comment]
```javascriptfor (let i in signal.to) {
                	let connection = signal.to[i];
                	if (connection === null || connection === false || typeof connection == 'undefined') continue;

            		if (typeof connection.connectionId != 'undefined')
                		connectionIds_1.push(connection.connectionId);
                	else
                		connectionIds_1.push(connection);
                }```

**Comment by yosietserga** [comment]
`javascript
for (let i in signal.to) {
    let connection = signal.to[i];
    if (connection === null || connection === false || typeof connection == 'undefined') continue;
    if (typeof connection.connectionId != 'undefined')
        connectionIds_1.push(connection.connectionId);
    else
        connectionIds_1.push(connection);
}
`

**Comment by yosietserga** [comment]
```javascript
for (let i in signal.to) {
    let connection = signal.to[i]; if (connection === null || connection === false || typeof connection == 'undefined') continue;
    if (typeof connection.connectionId != 'undefined') 
        connectionIds_1.push(connection.connectionId); 
    else 
        connectionIds_1.push(connection);
}
```

**Comment by pabloFuente** [comment]
Hi,

Thanks for the comment, but `.js` files are the compilation of the actual source files of openvidu-browser library. Changes/PRs must be performed on TypeScript files, not on JS files. In this case, that is here: https://github.com/OpenVidu/openvidu/blob/master/openvidu-browser/src/OpenVidu/Session.ts

I'm closing the issue for now. If you are able to locate the presumed error in that file, please reopen it indicating changes that you think may fix it.

**Comment by yosietserga** [comment]
Would be here [https://github.com/OpenVidu/openvidu/blob/7507569c9fc5fefa407687258a545af4eef57ffa/openvidu-browser/src/OpenVidu/Session.ts#L525](https://github.com/OpenVidu/openvidu/blob/7507569c9fc5fefa407687258a545af4eef57ffa/openvidu-browser/src/OpenVidu/Session.ts#L525)

**Comment by yosietserga** [comment]
```typescript

for (let i in signal.to) {
    let connection = signal.to[i]; 
    if (connection === null || connection === false || typeof connection == 'undefined') continue;
    if (typeof connection.connectionId != 'undefined') 
        connectionIds_1.push(connection.connectionId); 
    else 
        connectionIds_1.push(connection);
}
```

**Comment by pabloFuente** [comment]
Okey, but this what does exactly fix? Please, fill a bug report indicating the error you're getting and a way to replicate it, so we can understand the problem. Thank you.

**Comment by yosietserga** [comment]
If I pass an array with incorrect values, this will create an undefined index into connectionIds array, that when the signal is sent, it will return an invalid format value error for connections that crashes the whole app, instead of handle the exception before sending the signal

on my streamer.js
```typescript
import { OpenVidu } from "openvidu-browser";
[ ... ]

let ov = new OpenVidu();
let ovSession = ov.initSession();

let to = [false, null]; //connection's array

ovSession .signal({
    data:'something to say',
    to,
    type:'chat'
})
.then( ()=>{ ... })
.catch( (error)=>{ 
    //my custom error handler
});
```

on [Session.ts line 525](https://github.com/OpenVidu/openvidu/blob/7507569c9fc5fefa407687258a545af4eef57ffa/openvidu-browser/src/OpenVidu/Session.ts#L525)

prepare the signal message data 

```typescript
if (signal.to && signal.to.length > 0) {
    const connectionIds: string[] = [];

    signal.to.forEach(connection => {
        // if ${connection} is not an object or has not connectionId index, it will
        // push an undefined value into the connectionIds array
        connectionIds.push(connection.connectionId);
    });
    signalMessage['to'] = connectionIds;
} else {
    signalMessage['to'] = [];
}
```

on [OpenVidu.ts line 838](https://github.com/OpenVidu/openvidu/blob/7507569c9fc5fefa407687258a545af4eef57ffa/openvidu-browser/src/OpenVidu/OpenVidu.ts#L838)

send the signal data using kurento client
```typescript
    this.jsonRpcClient.send(method, params, callback);
```

on [openvidu/openvidu-browser/src/OpenViduInternal/KurentoUtils/kurento-jsonrpc/clients/jsonrpcclient.js line 174](https://github.com/OpenVidu/openvidu/blob/7507569c9fc5fefa407687258a545af4eef57ffa/openvidu-browser/src/OpenViduInternal/KurentoUtils/kurento-jsonrpc/clients/jsonrpcclient.js#L174)

if the connection's array is not a right connections array or a least an empty array, throw an error that crashes my calls stack and doesn't allow me to call my error handler to reset the calls stack

**Comment by pabloFuente** [comment]
Okey, this commit 91daa9aa44e999a04fc598ba706ca5be7ab71dfb should fix the error. Will be available on next release.
