### ISSUE TITLE
[QUESTION] Docker OpenVidu deployment, use nginx as reverse proxy?

### ISSUE THREAD

**Issue by mandaputtra** [OpenVidu/openvidu#348]
Hi I use OpenVidu docker for deployment, and I want to use nginx as reverse proxy. Can I do that?

My docker command:

```bash
docker run -d --name kms -p 4443:4443 --rm -e openvidu.secret=MY_SECRET openvidu/openvidu-server-kms:2.11.0
```

When I tested it using this `curl` command

```bash
$ curl -i -N \
    -H "Connection: Upgrade" \
    -H "Upgrade: websocket" \
    -H "Host: 127.0.0.1:8888" \
    -H "Origin: 127.0.0.1" \
    http://127.0.0.1:8888/kurento
```

it returns bad request, not same as the guide on kurento docker hub
```bash
HTTP/1.1 400
Content-Type: text/plain;charset=ISO-8859-1
Connection: close

Bad Request
This combination of host and port requires TLS.
```

Someone [said](https://github.com/OpenVidu/openvidu/issues/55#issuecomment-390209251) that I can pass options when starting openvidu server to disable ssl. how to do that with docker.

nginx configuration:

```perl
server {
  server_name www.example.com;
  root /srv/openvidu-tutorials/openvidu-insecure-js/web;

  location /mediaserver {
    rewrite /mediaserver(.*) /$1 break;
    proxy_pass https://www.example.com:4443;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
  }

  listen 443 ssl;
  ssl_certificate /root/fullchain.pem;
  ssl_certificate_key /root/privkey.pem;
}

server {
  if ($host = www.example.com) {
    return 301 https://$host$request_uri;
  }

  listen 80;
  server_name www.example.com;
  return 404;
}
```

**Comment by nordri** [comment]
Hi @mandaputtra 

The curl command won't work because this is a openvidu container and that command is intended for KMS container. 

If you want to disable SSL try this `docker run` instead.

`docker run -d --name kms -p 4443:4443 --rm -e openvidu.secret=MY_SECRET -e server.ssl.enabled=false openvidu/openvidu-server-kms:2.11.0`

Let me know if you need any further help.

Cheers!

**Comment by mandaputtra** [comment]
Hi thanks @nordri 

Now I just wonder how to sign in. I get what is the default username?

![username](https://user-images.githubusercontent.com/23342943/68206801-96534780-0008-11ea-80b1-41864b471a13.png)

**Comment by mandaputtra** [comment]
Seems like I got `409` errors on when using openvidu-insecure-js now. seems like I must confgure the stun server like this one #157 ?

**Comment by mandaputtra** [comment]
Seems like deployment on docker aren't possible to be accessed on another browser? If yes then you can close this issue @nordri

Thanks a lot, just solved the issue by [deploying on ubuntu tutorials](https://openvidu.io/docs/deployment/deploying-ubuntu/) run the all the command, but I'm still cant get it work with `nginx` reverse proxy, but thats another story.

**Comment by nordri** [comment]
OK
Glad you finally can make it.

**Comment by mandaputtra** [comment]
I actually want to understand how the server works. Glad if you point me where are the source code for that server

**Comment by Afondevi** [comment]
Hello,
`server.ssl.enabled=false` do the camera Failed...
and when pass to `true`, have this error : 
```
Bad Request
This combination of host and port requires TLS.
```

Very bad documentation about this

**Comment by micaelgallego** [comment]
OpenVidu service provides WebRTC features. WebRTC is complex to configure because networking for realtime communications is very complex. Also, OpenVidu depends on Kurento Media Server and COTURN software to provide its features.

For those reasons, we do not support officially production deployments of OpenVidu with docker. Please use ubuntu deployment (https://openvidu.io/docs/deployment/deploying-ubuntu/).

**Comment by derek-adair** [comment]
Has anyone found a concerted "non-official" effort for this?

**Comment by pabloFuente** [comment]
We are actually working on migrating the default version of OpenVidu CE production deployments to Docker. Stay tuned for the next few weeks.

**Comment by derek-adair** [comment]
Is there any way I can contribute and/or otherwise play around with this?

Could you clarify what those efforts entail?

**Comment by pabloFuente** [comment]
Basically building a docker-compose setup that works out of the box in a production environment. This includes setting up an nginx server, a let's encrypt process for managing custom domain names, a properly configured coturn server for providing STUN/TURN services, a redis database for storing TURN users, an openvidu-server instance and kurento-media-server instance. All of this services being containerized in Docker images and configured through docker-compose.

**Comment by derek-adair** [comment]
That could be interesting.  I'm using [caprover](https://github.com/caprover/caprover), which takes care of the nginx/lets encrypt.  I wonder what an integration with that would look like.

At a minimum it would be interesting to borrow / learn from a thorough compose example.

Can i view this code anywhere?
