### ISSUE TITLE
Unable to see other participants in a session call

### ISSUE THREAD

**Issue by jlcorcuera** [OpenVidu/openvidu#349]
Hello,

I already setup OpenVidu in an Amazon EC2 instance by running there a docker image (openvidu/openvidu-server-kms:2.11.0) and a coturn instance (nazarpc/coturn). The fact is that some users, after joining a call, they can not see other participants in the video session call (we did a test with two different users and they cannot see each other). We tried with a lot of devices, sometimes it worked (different networks, an iOS device and an Android one), sometimes not. They can just see the name of the other device but neither the video or the audio was coming. Bellow the configuration of how I ran the containers and all the ports specified below were opened on the Amazon AWS EC2 Instance. Could someone please address me in the path to solve this issue? 

Thank you in advance.

OpenVidu:

sudo docker run -p 4443:4443 -p 8888:8888 -p 9091:9091 -d --rm -v /home/ec2-user/keystore-openvidu.jks:/keystore-openvidu.jks -e openvidu.publicurl=https://my_server:4443 -e openvidu.secret=MY_SECRET_MODIFIED -e server.ssl.key-store=/keystore-openvidu.jks -e server.ssl.key-store-password=PASSWORD -e server.ssl.key-alias=openvidu-key -e KMS_STUN_IP=stun.l.google.com -e KMS_STUN_PORT=19302 -e KMS_TURN_URL=username:password@my_server:3478 openvidu/openvidu-server-kms:2.11.0

Coturn:

sudo docker run \
  -d \
  -p 3478:3478 \
  -p 3478:3478/udp \
  -p 65300-65535:65300-65535/udp \
  -e REALM=my_server \
  -v /home/ec2-user/cert/fullchain.pem:/etc/ssl/turn_server_cert.pem \
  -v privkey.pem:/etc/ssl/turn_server_pkey.pem \
  --restart=always \
  --name coturn \
  nazarpc/coturn

**Comment by micaelgallego** [comment]
Executing OpenVidu in production with docker is not supported. 

Please follow guides published in the web page.
