### ISSUE TITLE
How to create Subscriber?

### ISSUE THREAD

**Issue by aydn33** [OpenVidu/openvidu#351]
Hello i use your OpenVidu Ionic Demo . I can create a publisher but i couldn't be subscriber the publisher. I want the person who comes to session to be subscriber. Can you help me for this ?

**Comment by pabloFuente** [comment]
Hi,

Please, do not use GitHub issue tracker to post questions about the use of the platform. It is only meant for bugs.
Use OpenVidu's mailing list to get support: https://groups.google.com/forum/#!forum/openvidu
