### ISSUE TITLE
Video Quality not decreased when resolution lowered to resolution: '320x240'

### ISSUE THREAD

**Issue by dhavalsolanki** [OpenVidu/openvidu#352]
Hello,

I have lowered my video quality as shown in code 

![Capture1](https://user-images.githubusercontent.com/5657449/68386936-2c12e200-0183-11ea-9d70-5218e5116c34.PNG)

But my video quality is not lowered it is taking as per the video quality definition of my camera
As show in below image.

<img width="478" alt="Capture" src="https://user-images.githubusercontent.com/5657449/68387022-52d11880-0183-11ea-8c56-0411cf7d082f.PNG">

Can i change resolution as per my setting

**Comment by pabloFuente** [comment]
Hi,

Resolution of captured video depends on the client device. Chrome does in fact allow to change the resolution of the acquired video MediaStream. It does so through software, re-encoding the video to the desired resolution. But other platforms (for example Firefox) do require the hardware input device to natively support the provided resolution. So it won't change it unless your webcam supports it in at hardware level.

To sum it up: `resolution` parameter of `PublisherProperties` interface is just a simple wrapper around native Web API MediaStream constraints: https://developer.mozilla.org/en-US/docs/Web/API/Media_Streams_API/Constraints. openvidu-browser simply constructs that object with these properties, always using a range of value `ideal` according to Web API, so the request for getUserMedia does not fail in case the device does not support the provided constraints.

What browser/platform are you testing on the client side?

**Comment by dhavalsolanki** [comment]
We are testing on chrome browser. Chrome version is 78.0.3904.87.

**Comment by pabloFuente** [comment]
Do the frameRate  successfully change to 5 fps?

**Comment by dhavalsolankislk** [comment]
Yes

**Comment by pabloFuente** [comment]
Hi,

I'm going through some past issues that remained opened for now good reason. As said in my previous comment, setting the resolution on OpenVidu.initPublisher method is only a _best effort_ configuration, and successfully fulfilling it lies with the browser.

From our experiencie, Chrome should always honor frameRate and resolution settings. Firefox usually doesn't if the hardware does not specifically support it.

Closing this issue for now. Any other doubt about this, plaese comment below.
