### ISSUE TITLE
Any method to intercept video request from webRTC before send to user?

### ISSUE THREAD

**Issue by mandaputtra** [OpenVidu/openvidu#354]
So I want to compress video before it sends to the user, any method that I can use? I use `node.js` client server.

**Comment by micaelgallego** [comment]
Video is already sent to the user compressed.

Yo can "intercept" the vídeo implementing a custom video filter in Kurento
Media Server. But this requires deep knowledge in C/C++ programming and
OpenCV and/or GStreamer.

Regards

**Comment by mandaputtra** [comment]
Thanks! 👍
