### ISSUE TITLE
Black and white back camera

### ISSUE THREAD

**Issue by elenaveltroni** [OpenVidu/openvidu#355]
I have a problem with camera switch. The front camera works perfectly, but when I switch, the back camera is black and white. Is there a way to solve this problem?

**Comment by mandaputtra** [comment]
What tutorial you use? Can you give me your code here for me to run?

**Comment by elenaveltroni** [comment]
The tutorial used is openvidu-ionic.
The repository is private but below is the code used for the camera switch.

button to press to make the switch:

`<ion-fab vertical="bottom" horizontal="start" slot="fixed" style="margin-bottom:55px">
            <ion-fab-button size="small" color="light" (click)="toggleCamera()" id="toggleCamera">
                <ion-icon name="sync"></ion-icon>
            </ion-fab-button>
        </ion-fab>`

function used to make the switch:

toggleCamera(){ 

      this.OV.getDevices().then(devices => {

            // Getting only the video devices
            const videoDevices = devices.filter(device => device.kind === 'videoinput');

            if (videoDevices && videoDevices.length > 1){

                // Creating a new publisher with specific videoSource
                // In mobile devices the default and first camera is the front one
                const newPublisher = this.OV.initPublisher('element_publisher', {
                    insertMode: 'APPEND', // How the video is inserted in the target element 'video-container'
                    videoSource: this.isFrontCamera ? videoDevices[1].deviceId : videoDevices[0].deviceId,
                    publishAudio: true,
                    publishVideo: true,
                    resolution: '640x480', // The resolution of your video
                    frameRate: 30, // The frame rate of your video
                    mirror: !this.isFrontCamera, // Setting mirror enable if front camera is selected
                });
                // Changing isFrontCamera value
                this.isFrontCamera = !this.isFrontCamera;
                this.user = 'publisher';

                // Unpublishing the old publisher
                this.session.unpublish(this.publisher);

                // Assigning the new publisher to our global variable 'publisher'
                this.publisher = newPublisher;
                console.log(newPublisher);

                // Publishing the new publisher
                this.session.publish(this.publisher);
            }
        });
    }

**Comment by CSantosM** [comment]
Are you using Android or iOS? 
Which is the version? 
Could you test [openvidu-call-ionic](https://github.com/OpenVidu/openvidu-call-ionic) with the same device and check if the issue is still happening?

**Comment by elenaveltroni** [comment]
I use Android. 
I have test the same application with iOS and work well, but on android the problem remain.

**Comment by CSantosM** [comment]
Which is the Android version?
Could you test [openvidu-call-ionic](https://github.com/OpenVidu/openvidu-call-ionic) with the same device and check if the issue is still happening?

**Comment by elenaveltroni** [comment]
@CSantosM The version is 9. Yes, I have test and the result is the same.

**Comment by hoivikaj** [comment]
FYI, I was able to work around this by changing the resolution from the default 480p to 720p. So far Ive only seen this on the Pixel 4.
