### ISSUE TITLE
Does the OpenVidu server support multithreaded architecture?

### ISSUE THREAD

**Issue by t3mnikov** [OpenVidu/openvidu#356]
Hi.
Does the OpenVidu and Kurento media server support multithreaded architecture? What is the best processor to choose?

**Comment by pabloFuente** [comment]
Please, do not open issues if your question is not related to what you may consider to be a bug. Use OpenVidu public Google Group to do so: https://groups.google.com/forum/#!forum/openvidu

Thanks.

**Comment by t3mnikov** [comment]
I`m sorry.
