### ISSUE TITLE
Doesn't open camera on production on desktop

### ISSUE THREAD

**Issue by ilprima** [OpenVidu/openvidu#359]
**Describe the bug**
When i try to join a session (new or or not) on desktop running the ionic code in production (after the build, with or without --prod), so not on localhost, the code doesn't ask me for the camera permission. There is no the video in input from the pc, chrome for example doesn't show the red point or my MacBook doesn't have the camera green light on.
It works on mobile or on localhost.
I can get incoming video stream from other users but can't output mine.

**Expected behavior**
The browser must ask me for a permission to open the camera/mic or just open them if the permission is already enabled. It is shown just a black screen.

**Wrong current behavior**
Already mentioned.

**OpenVidu tutorial where to replicate the error**

I run the demo. What is wrong with my code?

`joinSession() {
        // --- 1) Get an OpenVidu object ---

        this.OV = new OpenVidu();

        // --- 2) Init a session ---

        this.session = this.OV.initSession();

        this.OV.getDevices().then(devices => {
            // 'devices' array contains all available media devices
            const videoDevices = devices.filter(device => device.kind === 'videoinput');
            console.log(videoDevices);
/*
            if (videoDevices && videoDevices.length <= 1) {
                document.getElementById('toggleCamera').setAttribute("hidden", 'true');
            }
            */
        });

        // --- 3) Specify the actions when events take place in the session ---

        // On every new Stream received...
        this.session.on('streamCreated', (event: StreamEvent) => {
            // Subscribe to the Stream to receive it. Second parameter is undefined
            // so OpenVidu doesn't create an HTML video on its own
            const subscriber: Subscriber = this.session.subscribe(event.stream, undefined);
            this.subscribers.push(subscriber);
        });

        // On every Stream destroyed...
        this.session.on('streamDestroyed', (event: StreamEvent) => {
            // Remove the stream from 'subscribers' array
            this.deleteSubscriber(event.stream.streamManager);
        });

        // --- 4) Connect to the session with a valid user token ---

        // 'getToken' method is simulating what your server-side should do.
        // 'token' parameter should be retrieved and returned by your own backend
        let id = 1;
        if (this.selectedVisit && this.selectedVisit.slots && this.selectedVisit.slots.length>0)
            id = this.selectedVisit.slots[0].id;
        this.getToken(id).then((token) => {
            // First param is the token got from OpenVidu Server. Second param will be used by every user on event
            // 'streamCreated' (property Stream.connection.data), and will be appended to DOM as the user's nickname
            this.session
                .connect(token, { clientData: this.myUserName })
                .then(() => {
                    // --- 5) Requesting and Checking Android Permissions
                    if (this.platform.is('cordova')) {
                        // Ionic platform
                        if (this.platform.is('android')) {
                            console.log('Android platform');
                            this.checkAndroidPermissions()
                                .then(() => this.initPublisher())
                                .catch(err => console.error(err));
                        } else if (this.platform.is('ios')) {
                            console.log('iOS platform');
                            this.initPublisher();
                        }
                    } else {
                        this.initPublisher();
                    }
                })
                .catch(error => {
                    console.log('There was an error connecting to the session:', error.code, error.message);
                });
        });
    }

    initPublisher() {
        // Init a publisher passing undefined as targetElement (we don't want OpenVidu to insert a video
        // element: we will manage it on our own) and with the desired properties
        const publisher: Publisher = this.OV.initPublisher(undefined, {
            audioSource: undefined, // The source of audio. If undefined default microphone
            videoSource: undefined, // The source of video. If undefined default webcam
            publishAudio: true, // Whether you want to start publishing with your audio unmuted or not
            publishVideo: true, // Whether you want to start publishing with your video enabled or not
            resolution: '640x480', // The resolution of your video
            frameRate: 30, // The frame rate of your video
            insertMode: 'APPEND', // How the video is inserted in the target element 'video-container'
            mirror: true // Whether to mirror your local video or not
        },
            (error) => {                // Function to be executed when the method finishes
                if (error) {
                    console.error('Error while initializing publisher: ', error);
                } else {
                    console.log('Publisher successfully initialized');
                }
            });

        // --- 6) Publish your stream ---

        this.session.publish(publisher).then(() => {
            // Store our Publisher
            this.publisher = publisher;
        });
    }

    toggleCamera() {
        this.OV.getDevices().then(devices => {

            // Getting only the video devices
            const videoDevices = devices.filter(device => device.kind === 'videoinput');

            if (videoDevices && videoDevices.length > 1){

                // Creating a new publisher with specific videoSource
                // In mobile devices the default and first camera is the front one
                const newPublisher = this.OV.initPublisher('element_publisher', {
                    insertMode: 'APPEND', // How the video is inserted in the target element 'video-container'
                    videoSource: this.isFrontCamera ? videoDevices[1].deviceId : videoDevices[0].deviceId,
                    publishAudio: true,
                    publishVideo: true,
                    resolution: '640x480', // The resolution of your video
                    frameRate: 30, // The frame rate of your video
                    mirror: !this.isFrontCamera, // Setting mirror enable if front camera is selected
                });
                // Changing isFrontCamera value
                this.isFrontCamera = !this.isFrontCamera;
                this.user = 'publisher';

                // Unpublishing the old publisher
                this.session.unpublish(this.publisher);

                // Assigning the new publisher to our global variable 'publisher'
                this.publisher = newPublisher;
                console.log(newPublisher);

                // Publishing the new publisher
                this.session.publish(this.publisher);
            }
        });
    }

    leaveSession() {
        // --- 7) Leave the session by calling 'disconnect' method over the Session object ---

        if (this.session) {
            this.session.disconnect();
        }

        // Empty all properties...
        this.user = '';
        this.subscribers = [];
        delete this.publisher;
        delete this.session;
        delete this.OV;
    }

    refreshVideos() {
        if (this.platform.is('ios') && this.platform.is('cordova')) {
            cordova.plugins.iosrtc.refreshVideos();
        }
    }

    private checkAndroidPermissions(): Promise<any> {
        return new Promise((resolve, reject) => {
            this.platform.ready().then(() => {
                this.androidPermissions
                    .requestPermissions(this.ANDROID_PERMISSIONS)
                    .then(() => {
                        this.androidPermissions
                            .checkPermission(this.androidPermissions.PERMISSION.CAMERA)
                            .then(camera => {
                                this.androidPermissions
                                    .checkPermission(this.androidPermissions.PERMISSION.RECORD_AUDIO)
                                    .then(audio => {
                                        this.androidPermissions
                                            .checkPermission(this.androidPermissions.PERMISSION.MODIFY_AUDIO_SETTINGS)
                                            .then(modifyAudio => {
                                                if (camera.hasPermission && audio.hasPermission && modifyAudio.hasPermission) {
                                                    resolve();
                                                } else {
                                                    reject(
                                                        new Error(
                                                            'Permissions denied: ' +
                                                            '\n' +
                                                            ' CAMERA = ' +
                                                            camera.hasPermission +
                                                            '\n' +
                                                            ' AUDIO = ' +
                                                            audio.hasPermission +
                                                            '\n' +
                                                            ' AUDIO_SETTINGS = ' +
                                                            modifyAudio.hasPermission,
                                                        ),
                                                    );
                                                }
                                            })
                                            .catch(err => {
                                                console.error(
                                                    'Checking permission ' +
                                                    this.androidPermissions.PERMISSION.MODIFY_AUDIO_SETTINGS +
                                                    ' failed',
                                                );
                                                reject(err);
                                            });
                                    })
                                    .catch(err => {
                                        console.error(
                                            'Checking permission ' + this.androidPermissions.PERMISSION.RECORD_AUDIO + ' failed',
                                        );
                                        reject(err);
                                    });
                            })
                            .catch(err => {
                                console.error('Checking permission ' + this.androidPermissions.PERMISSION.CAMERA + ' failed');
                                reject(err);
                            });
                    })
                    .catch(err => console.error('Error requesting permissions: ', err));
            });
        });
    }

    private generateParticipantInfo() {
        // Random user nickname and sessionId
        this.sessionId = 'Session'+ 1;
        this.clientUserName =  'Participant' + Math.floor(Math.random() * 100);
        this.myUserName = this.GlobalFields.currentUserInfo.firstName + ' ' + this.GlobalFields.currentUserInfo.lastName;
    }

    private deleteSubscriber(streamManager: StreamManager): void {
        const index = this.subscribers.indexOf(streamManager, 0);
        if (index > -1) {
            this.subscribers.splice(index, 1);
        }
    }

    /*
     * --------------------------
     * SERVER-SIDE RESPONSIBILITY
     * --------------------------
     * This method retrieve the mandatory user token from OpenVidu Server,
     * in this case making use Angular http API.
     * This behaviour MUST BE IN YOUR SERVER-SIDE IN PRODUCTION. In this case:
     *   1) Initialize a session in OpenVidu Server	 (POST /api/sessions)
     *   2) Generate a token in OpenVidu Server		   (POST /api/tokens)
     *   3) The token must be consumed in Session.connect() method of OpenVidu Browser
     */

    getToken(sessionId: number): Promise<string> {
    /*    if (this.platform.is('ios') && this.platform.is('cordova') && this.OPENVIDU_SERVER_URL === 'https://localhost:4445') {
            // To make easier first steps with iOS apps, use demos OpenVidu Sever if no custom valid server is configured
            this.OPENVIDU_SERVER_URL = 'https://demos.openvidu.io:4445';
        }*/
        return this.createSession(sessionId).then((id) => {
            return this.createToken(id);
        });
    }

    createSession(sessionId) {
        return new Promise((resolve, reject) => {
            const body = JSON.stringify({ customSessionId: "session" + sessionId });
            const options = {
                headers: new HttpHeaders({
                    Authorization: 'Basic ' + btoa('OPENVIDUAPP:' + this.OPENVIDU_SERVER_SECRET),
                    'Content-Type': 'application/json',
                }),
            };
            return this.httpClient
                .post(this.OPENVIDU_SERVER_URL + '/api/sessions', body, options)
                .pipe(
                    catchError((error) => {
                        if (error.status === 409) {
                            resolve(sessionId);
                        } else {
                            console.warn(
                                'No connection to OpenVidu Server. This may be a certificate error at ' +
                                this.OPENVIDU_SERVER_URL,
                            );
                            if (
                                window.confirm(
                                    'No connection to OpenVidu Server. This may be a certificate error at "' +
                                    this.OPENVIDU_SERVER_URL +
                                    // tslint:disable-next-line:max-line-length
                                    '"\n\nClick OK to navigate and accept it. If no certificate warning is shown, then check that your OpenVidu Server' +
                                    'is up and running at "' +
                                    this.OPENVIDU_SERVER_URL +
                                    '"',
                                )
                            ) {
                                location.assign(this.OPENVIDU_SERVER_URL + '/accept-certificate');
                            }
                        }
                        return observableThrowError(error);
                    }),
                )
                .subscribe((response) => {
                    console.log(response);
                    resolve(response['id']);
                });
        });
    }

    createToken(sessionId): Promise<string> {
        console.log(sessionId)
        if (!(sessionId + "").includes("session"))
            sessionId = "session" + sessionId;
        return new Promise((resolve, reject) => {
            const body = JSON.stringify({ session: sessionId });
            const options = {
                headers: new HttpHeaders({
                    Authorization: 'Basic ' + btoa('OPENVIDUAPP:' + this.OPENVIDU_SERVER_SECRET),
                    'Content-Type': 'application/json',
                }),
            };
            return this.httpClient
                .post(this.OPENVIDU_SERVER_URL + '/api/tokens', body, options)
                .pipe(
                    catchError((error) => {
                        reject(error);
                        return observableThrowError(error);
                    }),
                )
                .subscribe((response) => {
                    console.log(response);
                    resolve(response['token']);
                });
        });
    }
`

**OpenVidu deployment info**
How is your OpenVidu Server instance deployed when you get the bug. A couple of possible examples are listed below:
- Docker container as explained in OpenVidu tutorials, run with command `docker run ...` on macOS Catalina 10.15.1
- AWS deployment as explained in OpenVidu Docs (https://openvidu.io/docs/deployment/deploying-aws/)

> **IMPORTANT NOTE**: please, if you think the bug might be related to OpenVidu Server side, specify here if you are also getting the error by using OpenVidu Server Demos instance. This instance is publicly available (use it only for this test, because it is not secure!!!): **URL**: `https://demos.openvidu.io:4443`, **SECRET**: `MY_SECRET`

**Client device info (if applicable)**
Describe the client device(s) or platform(s) where you are able to replicate the error. For example:
- Chrome 78.0.3904.97 (Official Build) (64-bit) on Windows 10 (1903).
- Firefox Mobile 68.2.0 running on OnePlus 6 with Android 9.

**Screenshots**

**Additional context**
Add any other context about the problem here. For example, attach any useful logs related to the issue.

**Comment by arushgupta2007** [comment]
I having the same issue with OpenVidu version 2.14.0
Any updates?
Thanks

**Comment by micaelgallego** [comment]
@arushgupta2007 do you have same problem with any of the demos of https://demos.openvidu.io?

Can you share browser console log?

**Comment by arushgupta2007** [comment]
@micaelgallego It seems to working with the link you provided. There must be something wrong in my code then. I'll check it out.
Thanks

**Comment by arushgupta2007** [comment]
@micaelgallego  If i run my openvidu application (nodejs) on localhost than I do not  get any problems, but if I run my application on AWS ec2 instance than the site does not ask for permission for accessing the camera or the microphone. On both localhost and AWS I connect to a deployed openvidu server, [https://docs.openvidu.io/en/2.14.0/deployment/deploying-aws/](https://docs.openvidu.io/en/2.14.0/deployment/deploying-aws/). Weird! Does this behavior ring any bells?
Thanks

**Comment by arushgupta2007** [comment]
Here are logs copied from the firefox console
```
'OpenVidu' initialized OpenViduLogger.ts:31:19
openvidu-browser version: 2.14.0 OpenViduLogger.ts:31:19
STUN/TURN server IP: 3.17.189.175 OpenViduLogger.ts:19:19
TURN temp credentials [R7GTF9:bgysuk] OpenViduLogger.ts:19:19
openvidu-server version: 2.14.0 OpenViduLogger.ts:31:19
Connecting websocket to URI: wss://ec2-3-17-189-175.us-east-2.compute.amazonaws.com/openvidu jsonrpcclient.js:137:11
WebSocket connected to wss://ec2-3-17-189-175.us-east-2.compute.amazonaws.com/openvidu webSocketWithReconnection.js:47:15
--------- ONCONNECTED ----------- jsonrpcclient.js:108:15
Starting ping (if configured) jsonrpcclient.js:233:19
Sending request: {method:"joinRoom", params: {"token":"wss://ec2-3-17-189-175.us-east-2.compute.amazonaws.com?sessionId=ses_KfMxTeFw2k&token=tok_WxUakAOnsGMhdzf4&role=PUBLISHER&version=2.14.0&coturnIp=3.17.189.175&turnUsername=R7GTF9&turnCredential=bgysuk","session":"ses_KfMxTeFw2k","platform":"Firefox 76.0 on Linux 64-bit","metadata":"{\"clientData\":\"Arush Gupta\"}","secret":"","recorder":false}} OpenViduLogger.ts:25:19
Request: method:joinRoom params:{"token":"wss://ec2-3-17-189-175.us-east-2.compute.amazonaws.com?sessionId=ses_KfMxTeFw2k&token=tok_WxUakAOnsGMhdzf4&role=PUBLISHER&version=2.14.0&coturnIp=3.17.189.175&turnUsername=R7GTF9&turnCredential=bgysuk","session":"ses_KfMxTeFw2k","platform":"Firefox 76.0 on Linux 64-bit","metadata":"{\"clientData\":\"Arush Gupta\"}","secret":"","recorder":false} jsonrpcclient.js:165:19
Response: {"id":"con_Ulds4X4hw8","createdAt":1589617883079,"metadata":"{\"clientData\":\"Arush Gupta\"}%/%{\"serverData\":\"Arush Gupta\"}","value":[],"sessionId":"nrmhtjuirsuiv9b6da17hq78oh"} jsonrpcclient.js:184:27
'Connection' created (local) OpenViduLogger.ts:31:19
Event 'connectionCreated' triggered by 'Session' 
Object { hasBeenPrevented: false, cancelable: false, target: {…}, type: "connectionCreated", connection: {…}, reason: "" }
OpenViduLogger.ts:31:19
New video element associated to  
Object { userHandlerArrowHandler: WeakMap(0), ee: {}, videos: (1) […], lazyLaunchVideoElementCreatedEvent: false, stream: {…}, remote: false, canPlayListener: canPlayListener(), accessAllowed: false, isSubscribedToRemote: false, accessDenied: false, … }
OpenViduLogger.ts:31:19
```

**Comment by micaelgallego** [comment]
Maybe you have some kind of block to unsecure certificates? Because if it is working with localhost and working with demos, it is very estrange it is not working with your own deployed media server.

Have you tested with different browsers in different devices?

**Comment by arushgupta2007** [comment]
Hey @micaelgallego,
I have tried on different browsers and devices, it does not seem to work.
But weirdly, chat between users still works.
The problem lies in hardware initializing.
Thanks

**Comment by arushgupta2007** [comment]
Hey,
I have solved the problem.
To anybody who may need it: try creating https server instead of http server.
Thanks

**Comment by pabloFuente** [comment]
Of course, in production any real time WebRTC application needs a secure server. That's why the chat is working (doesn't need HTTP to work) but media is not (media needs HTTPS).
I'm closing this issue for now. @ilprima if you confirm that this is not your problem and that you are correclty serving your production server with HTTPS, then we will reopen it.
