### ISSUE TITLE
Openvidu streams are not getting deleted when the participant leave. 

### ISSUE THREAD

**Issue by aslamky** [OpenVidu/openvidu#36]
I am facing the same problem reported by **sandeep048** (Issue 35) `
![screenshot from 2018-03-29 18-40-18](https://user-images.githubusercontent.com/25210869/38090651-d8b3d938-3380-11e8-887d-deb332827ab5.png)

`OV.openvidu.session.streams`
When any of participant reload the browser all the streams are disappearing.

**Comment by micaelgallego** [comment]
Please add comments in issue #35.

I'm closing this issue.
