### ISSUE TITLE
Android 9 audio on input doesn't arrive

### ISSUE THREAD

**Issue by ilprima** [OpenVidu/openvidu#360]
Hi, i'm using ionic code and calling android version 9 video works but not audio, I can here it but it can't here me.
I'm using an iPhone or pc video calling an android 9.
Works with an android 7.
Do you know why?
I tried it using my code (little changes in the demo code) and the demo code

**Comment by micaelgallego** [comment]
Ionic code uses underlying browser through WebView. It seems Android 9 has some issue with audio. Can you test on more devices and Android versions to see what happend? Can you test other things related with audio? (recording it in local, for example).

**Comment by ilprima** [comment]
I found out the problem. It's not related to a particular android version.
If a phone call is on and you open the video call with open vidu and then you turn off the phone call, android doesn't set the output audio, so you can't ear the other user. On iOS this doesnt happen.

**Comment by pabloFuente** [comment]
Okey. Let me summarize the problem:

- A regular phone call is being attended by the Android device.
- The user joins an OpenVidu session *without hanging up the phone call*
- The user is able to hear the regular phone call *and* to see and hear the OpenVidu video call, at the same time.
- If the user then hangs up the regular phone call, then it is no longer able to hear the OpenVidu video call, but is is still able to see it.

Is this right?

**Comment by ilprima** [comment]
Yes totally true

**Comment by pabloFuente** [comment]
Okey, then I'm not really sure if this is a problem with OpenVidu. Seems like a priority issue regarding native audio management in Android. Maybe Ionic provides some plugin to manually manage this in the application.

I'm closing this issue for now, as 1) We don't think this can be fixed at openvidu-browser level and 2) We're not sure this is a "supported" scenario (maybe it is just impossible to properly manage a phone call and a webrtc call at the same time without having this kind of issues). But please, add any other relevant information about this if you find anything useful or you're able to solve the issue.

Cheers.
