### ISSUE TITLE
Recording not able to access layout page

### ISSUE THREAD

**Issue by JamesRoche** [OpenVidu/openvidu#362]
I have an issue that replicates #311, I have followed the advice of updating the url used by the video recorder but it seems unable to access the frontend service. I have confirmed that it can reach the internet by using googles url in place of the OpenVidu service url and the session correctly recorded Google home page.

My docker container is run like this

 docker run -d --privileged=true  --net="br0" --ip 10.10.1.166 \
-e server.port=4443 \
-e openvidu.recording.composed-url=https://mydomain.com:4443 \
--name vidu-br \
-e openvidu.secret=12345\
-e kms.uris=["ws://10.10.1.165:8888/kurento"] \
-e openvidu.recording=true \
-e openvidu.recording.path=/mnt/user/Software/VIDU \
-e openvidu.publicurl=https://mydomain.com:4443 \
-e server.ssl.key-store=/mnt/user/Software/VIDU/final.jks \
-e server.ssl.key-store-password=12345\
-e server.ssl.key-alias=server \
-v /mnt/user/Software/VIDU:/mnt/user/Software/VIDU \
--rm \
-v /var/run/docker.sock:/var/run/docker.sock \
--user 0 \
-e openvidu.recording.autostop-timeout=30 \
openvidu/openvidu-server

Everything else is working as expected. Could OpenVidu be creating an instance of recording container which cant access the rest of my network?

**Comment by pabloFuente** [comment]
Hi,

Sorry for the delay answering your issue report. I'd need more information to give you a good answer:

- Which OS are you using to launch openvidu-server Docker container?
- Which exact version of openvidu-server Docker container are you using? (It is a good practice to alwayys launch Docker containers providing a specific tag, not only the image name. So, that would be for example `openvidu/openvidu-server-kms:2.11.0`).  I see in the command you posted that you are using `openvidu-server` container, not `openvidu-server-kms`, which is the one recommended in OpenVidu Docs for development environments.

Thanks for the info
