### ISSUE TITLE
Can't see local video

### ISSUE THREAD

**Issue by Ray-Sir-Like** [OpenVidu/openvidu#365]
Hi,
when I use the Tutorial of https://openvidu.io/docs/deployment/deploying-ubuntu/ to deployed and started openvidu-server-2.11.0.jar,I can access the deployed network address, but I cannot see the local video when I click test.
My chrome version is 78.0.3904.108 after upgrading, the previous 76.xx version can see the local video
The server's logs are as follows:
![image](https://user-images.githubusercontent.com/25659192/70031793-009ae000-15e7-11ea-8397-72b76b4175a3.png),
Can you help me analyze the reason?

**Comment by pabloFuente** [comment]
You are not publishing the video. There's no log related to publishing process.

Check your camera access.
