### ISSUE TITLE
Unable to install Openvidu on Ubuntu 18.04

### ISSUE THREAD

**Issue by digitlimit** [OpenVidu/openvidu#371]
I tried following instruction on https://openvidu.io/docs/deployment/deploying-ubuntu/

I am getting the error below from the command below

```
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 5AFA7A83
```

Error
```
 sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 5AFA7A83
Executing: /tmp/apt-key-gpghome.fVyuQCEUAL/gpg.1.sh --keyserver keyserver.ubuntu.com --recv-keys 5AFA7A83
gpg: keyserver receive failed: Invalid argument

```

**Comment by pabloFuente** [comment]
Hi,

This is not a problem with Kurento keys. Installation command works fine for both Ubuntu 16.04 and 18.04. A quick search in Google returns that this error may happen when DNS was changed: https://stackoverflow.com/questions/51983144/error-installing-sbt-on-ubuntu-18-04-gpg-keyserver-receive-failed-invalid-ar

Eitherway, this is not an OpenVidu related error, but a networking missconfiguration.

**Comment by pabloFuente** [comment]
By the way, this Docker command works fine in our environments:

```
docker run --rm -i ubuntu:18.04 /bin/bash <<'EOL'
apt-get update && apt-get install --yes gnupg
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 5AFA7A83
EOL
```

So it must definitely be something with your server configuration.
