### ISSUE TITLE
hi. while creating the stack in AWS i used the openvidu password as YOUR_SECRET. i'm not sure but now i'm getting 401 error

### ISSUE THREAD

**Issue by designerprasan007** [OpenVidu/openvidu#373]
([https://stream.liveonline4u.com:5000](url).`)

this is the link of my website. when user says to join video he gets error of

Error: 401
    at /var/www/html/openvidu-tutorials/openvidu-js-node/node_modules/openvidu-node-client/lib/Session.js:413:32
    at process._tickCallback (internal/process/next_tick.js:68:7)
.

please let me know how to solve it.

**Comment by designerprasan007** [comment]
![Screenshot from 2020-01-07 17-28-31](https://user-images.githubusercontent.com/50103756/71894027-292c7180-3173-11ea-9448-f6585ab5b87b.png)

**Comment by pabloFuente** [comment]
Please, do not open this kind of questions in the issue tracker, as this is not a bug. For getting support, use OpenVidu Discourse forum: https://openvidu.discourse.group/
