### ISSUE TITLE
Speech and Audio Detection events do not fire on iOS

### ISSUE THREAD

**Issue by carter-dewey** [OpenVidu/openvidu#374]
**OpenVidu Version (Browser/Node/Server)**
2.11.0

**Describe the bug**
Speech and Audio Detection events do not fire on iOS.

**Expected behavior**
The publisherStartSpeaking, publisherStartSpeaking and streamAudioVolumeChange should fire on iOS.

I subscribe to the events as mentioned here. No error are thrown.
https://openvidu.io/docs/advanced-features/speech-detection/

**Wrong current behavior**
The events never fire on iOS. The same events are working as expected on Android and web.

**OpenVidu tutorial where to replicate the error**
No current tutorial demonstrates this feature but I have added them to the Ionic hello world here.
https://github.com/carter-dewey/openvidu-speech-and-audio-detection-fail-ios

**OpenVidu deployment info**
- Deployed in AWS on a custom Ubuntu server. Not via cloud formation.
(https://openvidu.io/docs/deployment/deploying-ubuntu/)

> **IMPORTANT NOTE**: please, if you think the bug might be related to OpenVidu Server side
-I believe this is only related to OpenVidu-Browser

**Client device info (if applicable)**
iPhone 11, iOS 13.3

**Screenshots**
None as nothing is happening to screenshot.

**Additional context**
Every other feature of OpenVidu is working as expected.

**Comment by pabloFuente** [comment]
Hi,

It is very possible that in Ionic speech events won't work. This is surely caused because of the use of cordova-plugin-iosrtc: https://openvidu.io/docs/tutorials/openvidu-ionic/#ios-specific-requirements

We will update the documentation to make this clear.

Regards

**Comment by carter-dewey** [comment]
Thank you for the quick reply. I guess iOS is just difficult.
