### ISSUE TITLE
windows10 Project started error in idea

### ISSUE THREAD

**Issue by qq122716072** [OpenVidu/openvidu#376]
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
[ERROR] 2020-01-14 15:01:34,844 [main] org.springframework.boot.diagnostics.LoggingFailureAnalysisReporter (report) - 

***************************
APPLICATION FAILED TO START
***************************

Description:

Field buildProperties in io.openvidu.server.config.OpenviduConfig required a bean of type 'org.springframework.boot.info.BuildProperties' that could not be found.

The injection point has the following annotations:
	- @org.springframework.beans.factory.annotation.Autowired(required=true)

The following candidates were found but could not be injected:
	- Bean method 'buildProperties' in 'ProjectInfoAutoConfiguration' not loaded because @ConditionalOnResource did not find resource '${spring.info.build.location:classpath:META-INF/build-info.properties}'

Action:

Consider revisiting the entries above or defining a bean of type 'org.springframework.boot.info.BuildProperties' in your configuration.

Process finished with exit code 1

**Comment by pabloFuente** [comment]
Hi,

Please, provide a detailed explanation of your problem: what are you exactly trying to do, what steps are you performing, what do you expect to achieve.
