### ISSUE TITLE
jsonrpcclient.js:174 ERROR:[KurentoClient]  Exception connecting to WebSocket server ws

### ISSUE THREAD

**Issue by designerprasan007** [OpenVidu/openvidu#377]
till afternoon it was working fine but i don't know suddenly what happend i'm getting error as i shown in title. 
![openviduerror](https://user-images.githubusercontent.com/50103756/72519538-9039dc80-387d-11ea-827e-c6691b3d493d.png)
![openviduterminal](https://user-images.githubusercontent.com/50103756/72519544-9203a000-387d-11ea-8465-cfdc34b6b08f.png)

in the image the terminal is working fine even i tried https://stream.liveonline4u.com:4443 here also getting error of [object object]. what is the issue for this?

**Comment by pabloFuente** [comment]
Can you attach the logs of openvidu-server?

**Comment by designerprasan007** [comment]
it's working now. i just restarted KMS server. and it started to work. but actually i want to ask you one more thing here. i'm implementing the recording option for getaroom. but getting an error of 400 bad request. i'm sure i have followed the steps as same in the openvidu-recording-node example. and the 1 plus point is that even though getting error of 400 bad request, in console i'm getting the sessionId  of recording. can you please help me to achieve this?

**Comment by pabloFuente** [comment]
Take a look to REST API docs: https://openvidu.io/docs/reference-docs/REST-API/#post-apirecordingsstart

See HTTP statuses to learn more about the recording start and stop operations. For example, in your logs I see you are receiving 422 and 405 statuses. Try to solve them with the help of the docs.

**Comment by designerprasan007** [comment]
okay pabloFuente let me try. thank you for response

**Comment by pabloFuente** [comment]
Okey, I'm closing the issue for now. As this is not really an issue but a support question, please if you have already any other doubt about the recording process, use OpenVidu support forum: https://openvidu.discourse.group/

**Comment by robin3317** [comment]
This also happens to me and here i asked for help in forum:  https://openvidu.discourse.group/t/exception-connecting-to-websocket-kurentoclient/225
