### ISSUE TITLE
Unable to hear participant voice when he reconnects after internet disconnection 

### ISSUE THREAD

**Issue by sravan41-elorce** [OpenVidu/openvidu#378]
Hello,
          There is a problem with participant reconnecting once he loses internet, Rest of the participants are unable to hear the reconnected participant voice, However the participant who Reconnects can hear other participants audio. 

Expected output: All the participants must be able to hear voices even when they reconnect.

Platform -  Android(Java).

Regards
Sravan V

**Comment by pabloFuente** [comment]
Hi,

If a user loses its connection, then you may possibly need to reset all media connections to the session, even if it successfully reconnects to it.
