### ISSUE TITLE
Whitelabel Error Page

### ISSUE THREAD

**Issue by qq122716072** [OpenVidu/openvidu#379]
Start only openvidu-server，Visit website[https://ip:4443], enter username[OPENVIDU] and password[MY_SECRET].Returns the result below
------
Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.

Mon Jan 20 14:01:37 CST 2020
There was an unexpected error (type=Not Found, status=404).
No message available
------

I use api to request interface, record video.The resulting video file shows no normal picture

**Comment by pabloFuente** [comment]
How are your running OpenVidu Server? Where have you deployed it? Have you opened the necessary ports? What do you mean with "I use api to request interface, record video.The resulting video file shows no normal picture" ? (I don't really know what are you talking about)

Please, be more specific when describing your problem.

**Comment by pabloFuente** [comment]
Closing by inactivity. If you want to further describe your problem, add a new message below.
