### ISSUE TITLE
Why ArchiveMode.MANUAL is also making a video record.

### ISSUE THREAD

**Issue by Wrufesh** [OpenVidu/openvidu#38]
Hi I am using kms server with openvidu-node-client.

I am trying to record video manually.

```
    let properties = new SessionProperties.Builder().archiveMode(ArchiveMode.MANUAL).archiveLayout(ArchiveLayout.BEST_FIT).mediaMode(MediaMode.ROUTED).build();


    // Create a new OpenVidu Session
    let mySession = OV.createSession(properties);
```

Still I can find mp4 file in recorded video folder.

**Comment by pabloFuente** [comment]
Can you please test our openvidu-recording-node tutorial?

Download, compile and serve the tutorial:

```
git clone https://github.com/OpenVidu/openvidu-tutorials.git
cd openvidu-tutorials/openvidu-recording-node
npm install
node server.js localhost:8443 MY_SECRET
```

Run openvidu-server-kms like this:
```
docker run -p 8443:8443 --rm \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /opt/openvidu/recordings:/opt/openvidu/recordings \
    -e openvidu.recording=true \
    -e MY_UID=$(id -u $USER) \
    -e openvidu.recording.path=/opt/openvidu/recordings \
    -e openvidu.recording.free-access=true \
openvidu/openvidu-server-kms:1.8.0
```

In the demo you can choose when to start and stop the recording making use of openvidu-node-client. The MP4 file will be generated inside `/opt/openvidu/recordings` folder from the time you press "Start recording" until you press "Finish recording".
