### ISSUE TITLE
getMediaError - Requested device not found

### ISSUE THREAD

**Issue by Bigben83** [OpenVidu/openvidu#382]
I don't know if this is an issue or not,
I have successfully got the openvidu getaroom demo working and have trialed it on several devices.

When trying it with a Logitech Group Conference System I get an error.

The error showing in chrome console is
`DOMException: Requested device not found
getMediaError @ Publisher.ts:484`

So I tried the test page in openvidu via the port but get an error too
[https://url.com.au:4443](https://url.com.au:4443)
when you do a test it says "Camera access denied"

Chrome does have access to the camera as when you go to the webRTC test the camera works.
[https://webrtc.github.io/samples/src/content/getusermedia/gum/](https://webrtc.github.io/samples/src/content/getusermedia/gum/)

**Comment by pabloFuente** [comment]
Hi,

That's a problem with the device itself. Try accessing its camera in other web pages, you should see some kind of similar error.
I myself have a laptop that always gives me the same error, but with the microphone instead.

The solution is to carefully list what audio and video inputs your device has available to call OpenVidu.initPublisher with the aproppriate values. You can do so with OpenVidu.getDevices method. That way you will avoid the unexpected error and at least if their mic works, your users will be able to speak in the session.

**Comment by Bigben83** [comment]
Thanks @pabloFuente how do I get a list of inputs  in the app.js file. ? I cant see any examples in the files.

**Comment by pabloFuente** [comment]
You just need to use [OpenVidu.getDevices](https://openvidu.io/api/openvidu-browser/classes/openvidu.html#getdevices). You can see an example of its use in OpenVidu Call Angular app right here: https://github.com/OpenVidu/openvidu-call/blob/master/front/openvidu-call/src/app/shared/components/dialog-choose-room/dialog-choose-room.component.ts#L216
