### ISSUE TITLE
Java API fetch/getActiveSessions vs getSession

### ISSUE THREAD

**Issue by EdiMel** [OpenVidu/openvidu#383]
Hi all

Forgive me if this is a silly question.  On the Java API, I understand that if I want to get the latest info from a active session, I need to call fetch() an then getActiveSessions() and iterate the list to find the session that I want...

What is the reason for the absence of a getSession(sessionId) method for the Java API ?

**Comment by pabloFuente** [comment]
Hi,

You can fetch the current information of any session by using Session.fetch() method.

Of course for that you need to have the Session object previously stored, to which is the usual behavior after calling OpenVidu.createSession.

Regards.

**Comment by EdiMel** [comment]
Ok, the thing is that I'm using a database to store status, and persisting only the session Id string.  For sanity check, before i use this string.. I need to check the real Session status... and there is no Session(sessionId) method either... so... I think I I will need to make this procedure every time...

**Comment by pabloFuente** [comment]
Well, it is a right approach to store in your DB session ids to keep safe the status of OpenVidu Server in case your app crashes, but that doesn't mean you can't store Session objects in a collection in memory. That way you'll safe tons of queries to your DB. In case of lost of that information, you can always consult your DB, or even better, you could simply ask the infromation to OpenVidu with getActiveSessions method.
