### ISSUE TITLE
Possible to prioritize video/audio codecs?

### ISSUE THREAD

**Issue by eirikhollis** [OpenVidu/openvidu#388]
On some devices with low CPU hardware, the default VP8 codec is quite harsh and leads to multiple framedrops and bad overall performance/quality. However, most of these devices that I'm working with has H264 hardware encoding/decoding.

Is it possible to prioritize specific codecs such as H264 within either the clients or the server?
If it's possible, are there any examples or guides available?
If not, what's the best solution for a workaround?

**Comment by pabloFuente** [comment]
Hi,

It is possible to force VP8 or H264 in Kurento Media Server by commenting lines in file 

`/etc/kurento/modules/kurento/SdpEndpoint.conf.json`

That way Kurento will only negotiate the video codec you indicate in such file:

```
"videoCodecs": [
//      { "name": "VP8/90000" },
        { "name": "H264/90000" }
]
```

But make sure to test your application after the change to be sure it still works fine.

**Comment by eirikhollis** [comment]
Thanks for the reply @pabloFuente 

Unfortunately, we use both VP8 and H264 (mostly H264), so we would still like the option of VP8 to be available if H264 is not supported on the device.

Will reorganizing them as 
```
"videoCodecs": [
        { "name": "H264/90000" },
        { "name": "VP8/90000" }
]
```
change the prioritizing to favor H264 when possible?

**Comment by eirikhollis** [comment]
I just tested with both commenting out VP8 and reorganizing the codecs.

As I suspected, the clients that don't support H264 couldn't connect when VP8 codec was commented out, and the reorganizing did not prioritize H264 over VP8.

Any other options?
Is it possible to restructure the `m=video` line in the SDP offer on client side to prioritize H264, e.g. if H264 codec is number 124:
```
Before:
m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 102 122 127 121 125 107 108 109 124 120 123 119 114 115 116

After:
m=video 9 UDP/TLS/RTP/SAVPF 124 96 97 98 99 100 101 102 122 127 121 125 107 108 109 120 123 119 114 115 116
```

This can be done in between `CreateOffer()` and `SetLocalDescription()` by modifying the `offer.Sdp` returned by `CreateOffer()`, but during our initial testing, the extra lines of code we added didn't seem to be compiled into the new client package.

**Comment by j1elo** [comment]
Hi,

the list of available codecs is read from `SdpEndpoint.conf.json` and each one ends up [appended in order](https://github.com/Kurento/kms-core/blob/cd9006f0072186f8e64892923608f5bfb5923ddb/src/server/implementation/objects/SdpEndpointImpl.cpp#L145) into an internal array.

Then these are used to **generate** SDP Offers, which is the only time at which a WebRTC participant is able to have any saying about the order of codecs.

With this config:
```
"videoCodecs": [
    { "name": "VP8/90000" },
    { "name": "H264/90000" }
]
```

SDP Offer from KMS:
```
m=video 1 RTP/SAVPF 100 101
a=rtpmap:100 VP8/90000
a=rtpmap:101 H264/90000
```

Meanwhile, with this config:
```
"videoCodecs": [
    { "name": "H264/90000" },
    { "name": "VP8/90000" }
]
```

SDP Offer from KMS:
```
m=video 1 RTP/SAVPF 100 101
a=rtpmap:100 H264/90000
a=rtpmap:101 VP8/90000
```

**Comment by j1elo** [comment]
> Is it possible to restructure the `m=video` line in the SDP offer on client side to prioritize H264

It is possible, but shouldn't be necessary. Note however if the SDP **Offer** is generated by Chrome, you don't have any saying in the order of codecs. Kurento should process the offer and generate its SDP **Answer** respecting the order of codecs that it was given by Chrome.

If you do the other way around, generating the Offer in KMS and processing it to generate an Answer in Chrome, *then* you can affect the codec ordering in the way I've showed

**Comment by pabloFuente** [comment]
By the way, **this is important**:

Since Kurento was updated to Xenial, you cannot comment JSON files like I posted. You need to do so like this (basically changing the name of the property so Kurento ignores it):
```
"videoCodecs": [
    { "//name": "VP8/90000" },
    { "name": "H264/90000" }
]
```

**Comment by eirikhollis** [comment]
OK, so for good measure, I commented out VP8 and reordered the codecs.
```
"videoCodecs": [
        { "name": "H264/9000" },
        { "//name": "VP8/90000" }
]
```
Rebooted the VM and KMS, and tried connecting through Chrome in React.

SDP offer (simplified) in the `joinRoom `message showed following codecs
```
m=audio 9 UDP/TLS/RTP/SAVPF 111 103 104 9 0 8 106 105 13 110 112 113 126

a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1

m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 102 122 127 121 125 107 108 109 124 120 123 119 114 115 116

a=rtpmap:96 VP8/90000
a=rtcp-fb:96 goog-remb
a=rtcp-fb:96 transport-cc
a=rtcp-fb:96 ccm fir
a=rtcp-fb:96 nack
a=rtcp-fb:96 nack pli

a=rtpmap:102 H264/90000
a=rtcp-fb:102 goog-remb
a=rtcp-fb:102 transport-cc
a=rtcp-fb:102 ccm fir
a=rtcp-fb:102 nack
a=rtcp-fb:102 nack pli
a=fmtp:102 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f
```

and the `sdpAnswer` returned (in its full) was
```
v=0
o=- 3790500092 3790500092 IN IP4 0.0.0.0
s=Kurento Media Server
c=IN IP4 0.0.0.0
t=0 0
a=msid-semantic: WMS mCRfNEJFC5fSb8DN8Jp8Hx8Ssw9tgcSzQ1FJ
a=group:BUNDLE 0
m=audio 1 UDP/TLS/RTP/SAVPF 111 0
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=recvonly
a=mid:0
a=rtcp:9 IN IP4 0.0.0.0
a=rtpmap:111 opus/48000/2
a=rtpmap:0 PCMU/8000
a=setup:active
a=rtcp-mux
a=fmtp:111 minptime=10;useinbandfec=1
a=ssrc:2306431994 cname:user2947887423@host-dafeb5c0
a=ice-ufrag:NCVZ
a=ice-pwd:uMM27Xf5TqSt0Vj1qBZI/s
a=fingerprint:sha-256 41:DF:A1:B8:94:8E:7A:23:84:6B:A5:0D:57:57:F7:C8:C5:5A:AF:3D:AF:5D:C0:15:4B:C3:2A:71:49:3F:9F:C5
m=video 0 UDP/TLS/RTP/SAVPF
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=recvonly
a=mid:1
a=rtcp:9 IN IP4 0.0.0.0
a=setup:active
a=rtcp-mux
a=ssrc:3954154796 cname:user2947887423@host-dafeb5c0
a=ice-ufrag:NCVZ
a=ice-pwd:uMM27Xf5TqSt0Vj1qBZI/s
a=fingerprint:sha-256 41:DF:A1:B8:94:8E:7A:23:84:6B:A5:0D:57:57:F7:C8:C5:5A:AF:3D:AF:5D:C0:15:4B:C3:2A:71:49:3F:9F:C5
```

When connecting with a second Chrome user into the call, the SDP offer in `receiveVideoFrom` message and the SDP answer in the accompanying `sdpAnswer` are equal (codec-wise) to the above ones.
Local video stream sets up fine, but we are unable to see each other since the server returns 0 matching video codecs.

**Comment by eirikhollis** [comment]
So if I understand correctly, since the offer is always (at least in my scenario?) generated by the client and not the KMS, the local offer would have to be modified by the client before it's sent to the KMS.

Therefore technically, I'm back to my original post, if there's any way to modify the offer in between `CreateOffer()` and `SetLocalDescription()`, right?

Weird that commenting out VP8 still doesn't allow H264 codec to be applied, is there anything wrong with how I set it up on the KMS?
```
"videoCodecs": [
        { "name": "H264/9000" },
        { "//name": "VP8/90000" }
]
```

**Comment by micaelgallego** [comment]
Right now I think it is not possible. We can consider to add it in the future. 

You will have to "hack" a bit openvidu-browser.

**Comment by eirikhollis** [comment]
Just an update, I had an error in my SdpEndpoint.conf.json where i wrote `H264/9000` instead of the correct `H264/90000`, forgetting the last zero. That's why it failed when I commented out the VP8 codec.

We modified the browser code to remove VP8 in the SDP offer and it finally managed to create a connection to the server using H264! It would be awesome if the same kind of prioritization of codecs that's on the KMS could be added to clients as well, as I'm sure many working with low performant devices with H264 HW encoding/decoding could benefit from this.

**Comment by micaelgallego** [comment]
Glad to hear you finally manage to get it working.

Good feature request. We take note!

**Comment by alexlapa** [comment]
You might want to take a look at [RTCRtpTransceiver.setCodecPreferences()](https://developer.mozilla.org/en-US/docs/Web/API/RTCRtpTransceiver/setCodecPreferences), but it is only implemented in Chrome, afaik.

**Comment by eirikhollis** [comment]
@micaelgallego

So maybe I spoke too soon about making it work with H264. What I managed to setup was a single connection to KMS where I observed that the sdpAnswer correctly returned a matching H264 codec.

The problems arised when I tried connecting with a second client using the same SDP modified code. Both set up as usual with no errors and both completed the SDP negotiation with no errors. However, no video is sent from one client to another, even though the SDP negotiated contains the correct H264 codec.

<details>
  <summary>Code for choosing SDP, inspired by @alexlapa</summary>

```
var rtpTransceivers = _this.pc.getTransceivers();
var rtpTransceiver = rtpTransceivers.find(function (t) { return t.sender.track.kind === 'video'; });
var codecParameters = [];
codecParameters.push({
	mimeType: 'video/H264',
	clockRate: 90000,
	sdpFmtpLine: 'level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f'
});
codecParameters.push({
	mimeType: 'video/H264',
	clockRate: 90000,
	sdpFmtpLine: 'level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f'
});
codecParameters.push({
	mimeType: 'video/H264',
	clockRate: 90000,
	sdpFmtpLine: 'level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42e01f'
});
codecParameters.push({
	mimeType: 'video/H264',
	clockRate: 90000,
	sdpFmtpLine: 'level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=4d0032'
});
codecParameters.push({
	mimeType: 'video/H264',
	clockRate: 90000,
	sdpFmtpLine: 'level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=640032'
});
rtpTransceiver.setCodecPreferences(codecParameters);
```
</details>

<details>
  <summary>SDP Offer</summary>

```
v=0
o=- 6449952133175893945 2 IN IP4 127.0.0.1
s=-
t=0 0
a=group:BUNDLE 0 1
a=msid-semantic: WMS okn0JROGSdP4N5DtVB6p7nliOQwuqkwYw8I2
m=audio 9 UDP/TLS/RTP/SAVPF 111 103 104 9 0 8 106 105 13 110 112 113 126
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:rXcR
a=ice-pwd:Cpg4R10xOZvug1Ou31iuRavc
a=ice-options:trickle
a=fingerprint:sha-256 7F:53:B4:AF:8F:CE:E4:CB:E0:1F:A0:6A:E0:E1:BE:8D:D9:F6:B2:B7:51:EE:17:30:CF:2B:55:E4:2C:D1:AF:6F
a=setup:actpass
a=mid:0
a=extmap:1 urn:ietf:params:rtp-hdrext:ssrc-audio-level
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:5 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
a=extmap:6 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
a=sendonly
a=msid:okn0JROGSdP4N5DtVB6p7nliOQwuqkwYw8I2 b8b0f768-1e41-4fc3-a7e8-4b5ea8a0e3ec
a=rtcp-mux
a=rtpmap:111 opus/48000/2
a=rtcp-fb:111 transport-cc
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:103 ISAC/16000
a=rtpmap:104 ISAC/32000
a=rtpmap:9 G722/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:106 CN/32000
a=rtpmap:105 CN/16000
a=rtpmap:13 CN/8000
a=rtpmap:110 telephone-event/48000
a=rtpmap:112 telephone-event/32000
a=rtpmap:113 telephone-event/16000
a=rtpmap:126 telephone-event/8000
a=ssrc:90098832 cname:/asv4JFJ2pMKAgqB
a=ssrc:90098832 msid:okn0JROGSdP4N5DtVB6p7nliOQwuqkwYw8I2 b8b0f768-1e41-4fc3-a7e8-4b5ea8a0e3ec
a=ssrc:90098832 mslabel:okn0JROGSdP4N5DtVB6p7nliOQwuqkwYw8I2
a=ssrc:90098832 label:b8b0f768-1e41-4fc3-a7e8-4b5ea8a0e3ec
m=video 9 UDP/TLS/RTP/SAVPF 102 106 108 110 112
c=IN IP4 0.0.0.0
a=rtcp:9 IN IP4 0.0.0.0
a=ice-ufrag:rXcR
a=ice-pwd:Cpg4R10xOZvug1Ou31iuRavc
a=ice-options:trickle
a=fingerprint:sha-256 7F:53:B4:AF:8F:CE:E4:CB:E0:1F:A0:6A:E0:E1:BE:8D:D9:F6:B2:B7:51:EE:17:30:CF:2B:55:E4:2C:D1:AF:6F
a=setup:actpass
a=mid:1
a=extmap:14 urn:ietf:params:rtp-hdrext:toffset
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=extmap:13 urn:3gpp:video-orientation
a=extmap:3 http://www.ietf.org/id/draft-holmer-rmcat-transport-wide-cc-extensions-01
a=extmap:12 http://www.webrtc.org/experiments/rtp-hdrext/playout-delay
a=extmap:11 http://www.webrtc.org/experiments/rtp-hdrext/video-content-type
a=extmap:7 http://www.webrtc.org/experiments/rtp-hdrext/video-timing
a=extmap:8 http://tools.ietf.org/html/draft-ietf-avtext-framemarking-07
a=extmap:9 http://www.webrtc.org/experiments/rtp-hdrext/color-space
a=extmap:4 urn:ietf:params:rtp-hdrext:sdes:mid
a=extmap:5 urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
a=extmap:6 urn:ietf:params:rtp-hdrext:sdes:repaired-rtp-stream-id
a=sendonly
a=msid:okn0JROGSdP4N5DtVB6p7nliOQwuqkwYw8I2 0a24b446-d166-4e94-a14e-cb8526ea9f2f
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:102 H264/90000
a=rtcp-fb:102 goog-remb
a=rtcp-fb:102 transport-cc
a=rtcp-fb:102 ccm fir
a=rtcp-fb:102 nack
a=rtcp-fb:102 nack pli
a=fmtp:102 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f
a=rtpmap:106 H264/90000
a=rtcp-fb:106 goog-remb
a=rtcp-fb:106 transport-cc
a=rtcp-fb:106 ccm fir
a=rtcp-fb:106 nack
a=rtcp-fb:106 nack pli
a=fmtp:106 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=rtpmap:108 H264/90000
a=rtcp-fb:108 goog-remb
a=rtcp-fb:108 transport-cc
a=rtcp-fb:108 ccm fir
a=rtcp-fb:108 nack
a=rtcp-fb:108 nack pli
a=fmtp:108 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42e01f
a=rtpmap:110 H264/90000
a=rtcp-fb:110 goog-remb
a=rtcp-fb:110 transport-cc
a=rtcp-fb:110 ccm fir
a=rtcp-fb:110 nack
a=rtcp-fb:110 nack pli
a=fmtp:110 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=4d0032
a=rtpmap:112 H264/90000
a=rtcp-fb:112 goog-remb
a=rtcp-fb:112 transport-cc
a=rtcp-fb:112 ccm fir
a=rtcp-fb:112 nack
a=rtcp-fb:112 nack pli
a=fmtp:112 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=640032
a=ssrc:3409024674 cname:/asv4JFJ2pMKAgqB
a=ssrc:3409024674 msid:okn0JROGSdP4N5DtVB6p7nliOQwuqkwYw8I2 0a24b446-d166-4e94-a14e-cb8526ea9f2f
a=ssrc:3409024674 mslabel:okn0JROGSdP4N5DtVB6p7nliOQwuqkwYw8I2
a=ssrc:3409024674 label:0a24b446-d166-4e94-a14e-cb8526ea9f2f
```
</details>

<details>
  <summary>SDP Answer</summary>

```
v=0
o=- 3791187122 3791187122 IN IP4 0.0.0.0
s=Kurento Media Server
c=IN IP4 0.0.0.0
t=0 0
a=msid-semantic: WMS okn0JROGSdP4N5DtVB6p7nliOQwuqkwYw8I2
a=group:BUNDLE 0 1
m=audio 1 UDP/TLS/RTP/SAVPF 111 0
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=recvonly
a=mid:0
a=rtcp:9 IN IP4 0.0.0.0
a=rtpmap:111 opus/48000/2
a=rtpmap:0 PCMU/8000
a=setup:active
a=rtcp-mux
a=fmtp:111 minptime=10;useinbandfec=1
a=ssrc:30602842 cname:user2701135324@host-c094c9c8
a=ice-ufrag:N1G5
a=ice-pwd:IxjqeJEA5wQaJICONENYPJ
a=fingerprint:sha-256 E7:3A:B5:50:A0:E7:83:F2:1B:F4:EE:1F:30:B6:98:26:6B:B0:9B:33:DE:D7:48:70:CD:EB:D6:F3:54:5E:53:15
m=video 1 UDP/TLS/RTP/SAVPF 102 106 108 110 112
a=extmap:2 http://www.webrtc.org/experiments/rtp-hdrext/abs-send-time
a=recvonly
a=mid:1
a=rtcp:9 IN IP4 0.0.0.0
a=rtpmap:102 H264/90000
a=rtpmap:106 H264/90000
a=rtpmap:108 H264/90000
a=rtpmap:110 H264/90000
a=rtpmap:112 H264/90000
a=rtcp-fb:102 goog-remb
a=rtcp-fb:102 ccm fir
a=rtcp-fb:102 nack
a=rtcp-fb:102 nack pli
a=rtcp-fb:106 goog-remb
a=rtcp-fb:106 ccm fir
a=rtcp-fb:106 nack
a=rtcp-fb:106 nack pli
a=rtcp-fb:108 goog-remb
a=rtcp-fb:108 ccm fir
a=rtcp-fb:108 nack
a=rtcp-fb:108 nack pli
a=rtcp-fb:110 goog-remb
a=rtcp-fb:110 ccm fir
a=rtcp-fb:110 nack
a=rtcp-fb:110 nack pli
a=rtcp-fb:112 goog-remb
a=rtcp-fb:112 ccm fir
a=rtcp-fb:112 nack
a=rtcp-fb:112 nack pli
a=setup:active
a=rtcp-mux
a=fmtp:102 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42001f
a=fmtp:106 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f
a=fmtp:108 level-asymmetry-allowed=1;packetization-mode=0;profile-level-id=42e01f
a=fmtp:110 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=4d0032
a=fmtp:112 level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=640032
a=ssrc:3405256768 cname:user2701135324@host-c094c9c8
a=ice-ufrag:N1G5
a=ice-pwd:IxjqeJEA5wQaJICONENYPJ
a=fingerprint:sha-256 E7:3A:B5:50:A0:E7:83:F2:1B:F4:EE:1F:30:B6:98:26:6B:B0:9B:33:DE:D7:48:70:CD:EB:D6:F3:54:5E:53:15
```
</details>

We also tried the aforementioned method of removing VP8 from the Offer before adding it to LocalDescription, and also just simply reordering the `m=video` line to place VP8 at the far back. Here we did not remove, nor add any codecs. We simply just reordered the prioritized codec list in between `CreateOffer()` and `SetLocalDescription()`.
```
Offer (Notice VP8 at the end):
m=video 9 UDP/TLS/RTP/SAVPF 97 98 99 100 101 102 122 127 121 125 107 108 109 124 120 123 119 114 115 116 96

Answer:
m=video 1 UDP/TLS/RTP/SAVPF 102 127 125 108 124 123 96
```

This also didn't work. We tried every variation of prioritization on the available H264 codecs `102 127 125 108 124 123`, but none of them resulted in a successful video<->video connection. Setting VP8 (96) first would always create a connection succesfully.

I'm observing that the IceConnectionState of the RTCPeerConnection stays at `checking` for a while, and then changes to `disconnected`.

Any ideas? Is this a bug on OpenVidu side? Have you ever been able to setup an H264 connection?

**Comment by micaelgallego** [comment]
@j1elo do you have any clue about this?

**Comment by eirikhollis** [comment]
Any updates on this?

**Comment by eirikhollis** [comment]
@micaelgallego Anything new here?
This is quite critical for our work, and would be nice to be resolved before moving to 2.12 and OpenVidu PRO.

**Comment by j1elo** [comment]
@micaelgallego sorry not really; this is not a feature of Kurento so I wouldn't know how to achieve the desired outcome without tinkering directly with the source code.

@eirikhollis if this is blocking you and it's critical I'd suggest contacting OpenVidu for explicit support

**Comment by micaelgallego** [comment]
We try to implement most useful features in Kurento and OpenVidu. Our resources are limited and we have to focus.

But if this feature is important for you, consider to use our commercial services to support it.

**Comment by danwize** [comment]
I installed the Openvidu server with docker following the instructions here: https://docs.openvidu.io/en/2.13.0/deployment/deploying-on-premises/

I don't see the /etc/kurento/modules/kurento/SdpEndpoint.conf.json file.  Where are the config settings by default?

**Comment by micaelgallego** [comment]
The best way to fine tune Kurento Media Server configuration is creating a new docker image for kms based on the official one.
