### ISSUE TITLE
Recording & share screen not able to hear sound from other side browser

### ISSUE THREAD

**Issue by HeroTran** [OpenVidu/openvidu#389]
Hi pabloFuente,
As issue #385 
I try to implemented recording during share screen my current browser (video call & microphone)
My application is class room and 2 user(user 1 & user 2) can video call and talk with each other.
My feature need to recording screen user 1 and able to hear the both user
![image](https://user-images.githubusercontent.com/10969446/74418612-34ae3f00-4e7b-11ea-8248-bdf168e17c22.png)

![image](https://user-images.githubusercontent.com/10969446/74418752-75a65380-4e7b-11ea-9389-c73eb44508c1.png)

This is my code
const publisher = OV.initPublisher(undefined, {
            audioSource: undefined, // The source of audio. If undefined default microphone
	    videoSource: 'screen', // The source of video. If undefined default webcam
            publishAudio: true, // Whether you want to start publishing with your audio unmuted or not
            publishVideo: true, // Whether you want to start publishing with your video enabled or not
            resolution: '1920x1080', // The resolution of your video
            frameRate: 30, // The frame rate of your video
            insertMode: 'APPEND', // How the video is inserted in the target element 'video-container'
            mirror: false // Whether to mirror your local video or not
          });

1/COMPOSED recording or INDIVIDUAL recording?
=> I using COMPOSED
2/Are you sure you are starting the recording with video and audio options set to true
=> Yes, I am, I setting options it true
3/Are you able to hear the remote audio, but the recording file does not have audio?
=>When recording done and create video on server, I just hear sound from my side, and can not hear from other side

How connect remote audio from other side browser ?
What should I implement code in Openvidu ?
How share screen able to hear sound from the both user?
This is my video : https://record.1on1english.vn:4443/recordings/81defa9b-2bf7-41d7-917b-e19bfbef79b9-3/81defa9b-2bf7-41d7-917b-e19bfbef79b9-3.mp4
Just hear from my side 
Thanks

**Comment by pabloFuente** [comment]
What I'm trying to understand is if this is a problem with the recording or is also a problem with the p2p connections. With this question `3/Are you able to hear the remote audio, but the recording file does not have audio?`  I mean if the lack of audio of the other participant is only found in the recording file or if you (your local browser) cannot hear the other participant during the session niether.

**Comment by HeroTran** [comment]
Hi pabloFuente,
Thanks for reply
if this is a problem with the recording or is also a problem with the p2p connections.
=>Yes, I think it problem the recording , during video call on browser I able to hear sound from audio of the other participant very clear,so when I recording & share screen in my local browser,
I check video recording has created on server , so I just able to hear sound from my side, cannot hear from remote audio.
Please help me check it
Thanks

**Comment by HeroTran** [comment]
Hi PabloFuete,
When I using other app recording video call on browser . It work good and able to hear sound from the both user
https://www.loom.com/share/ee1b0d4af95543bd8001fa4c64c54b3e
But when I recording by Openvidu I, Unfortunaly It just hear sound from my side.
How Openvidu connect remote audio when recording share screen,I really need
Please let me know
Thanks

**Comment by HeroTran** [comment]
Hi PabloFuete,
My application is video call on browser (user A & user B) using RTCMultiConnection
At UserA I want to recording void sound the both and screen browser by Openvidu
During video call I able to hear sound from the both user A & user B
But when I recording share screen in user B I able to hear sound from user A , can not hear sound from userB
I don't know what happend this issue
Please le me know,
Thanks

**Comment by HeroTran** [comment]
Hi PableFuete,
Fortunarly I have solve this issue, The right way allow the both use connect the same sessionID
and then It can hear voice sound the both user when recording.
But when create video recording , 
![image](https://user-images.githubusercontent.com/10969446/75133625-16afcc80-570e-11ea-810c-78c27261df0b.png)
This screen video split 2 place (one for screen recording & one for camera remote)
How setting hide camera remote and allow recording video full screen

**Comment by pabloFuente** [comment]
So you were connecting both users to different sessions? No doubt why they wouldn't hear each other 😅

If you want to record only the camera, then I suggest you try INDIVIDUAL recording: https://openvidu.io/docs/advanced-features/recording/#individual-stream-recording

You will record each video stream separately. Besides, this type of recording is *much more efficient and will maximise quality* than COMPOSED recording.

**Comment by HeroTran** [comment]
Hi pabloFuente , 
Thank you so much
Currently my issue, When I recording done and make new video, This video show 2 screen
1.Screen from recorder
2.Camera from remote user
That mean I want to display video just full screen from recorder and hide camera
From now, I can hide camera by properties  { videoSource: null, }
But It create space black on screen as image as you see 
![image](https://user-images.githubusercontent.com/10969446/75135157-34336500-5713-11ea-90c0-a1f38551c6cd.png)

===
1/If you want to record only the camera, then I suggest you try INDIVIDUAL recording: https://openvidu.io/docs/advanced-features/recording/#individual-stream-recording
==>I want to record screen from recorder and void sound the both. I try use INDIVIDUAL  but it not work correctly what I want


I really appreciate what you supported for me

**Comment by pabloFuente** [comment]
If you want audio from both of them and just a particular video, then you have 2 alternatives:
- Keep using INDIVDUAL recording and mix the resulting files after the sessions is done with some media post-processing tool. This would require you to implement it from scratch, but it can be done and it can be done in an automated way with a little effort.
- Use a custom recording layout. This allows you to design any layout you want. You can think of the custom recorder layout as an special participant of the session that will subscribe to any audio or video you want (and whenever you want). You implement it with HTML, CSS and JS: https://openvidu.io/docs/advanced-features/recording/#custom-recording-layouts

**Comment by HeroTran** [comment]
Hi @pabloFuente 
Thank you so much for reply
Currently I setting for recorder participant is
`const recorderOptions = {
          audioSource: undefined, // The source of audio. If undefined default microphone
          videoSource: 'screen', // The source of video. If undefined default webcam
          publishAudio: true, // Whether you want to start publishing with your audio unmuted or not
          publishVideo: true, // Whether you want to start publishing with your video enabled or not
          resolution: '1920x1080', // The resolution of your video
          mirror: false
        };`

and for otherparticipant
`const otherPublisher = {
          videoSource: null,
          mirror: true
        };`
Using condition for check 
`const publisher = OV.initPublisher(undefined, isCheckRole ? recorderOptions : otherPublisher);`
`if (isCheckRole) { // just recording if user is recorder participant
	startRecording();
  }`

Recorder participant will share screen & recording
Other participant just join the same sessionId with Recorder participant
Purpose: Recording full screen recorderparticipant & hear sound from Other participant 
Currently I have not  understant clearly custom recording layout yet. (Do you have any code or demo about it)
Custom recording layout could display full screen from Recorder participant and hear sound from the both.
Thank a lot,
