### ISSUE TITLE
Participant gets disconnected from the session when the app is in background in Android 10.

### ISSUE THREAD

**Issue by sravan41-elorce** [OpenVidu/openvidu#390]
Working with Openvidu.. We are facing an issue in the Oxygen OS in android devices, which is participant is getting disconnected from the call

Can you please help us with this

**Comment by micaelgallego** [comment]
We don't have any experience with Oxygen OS. 

I any case, if client is disconnected, Android system is closing the connection. In iPhone, this is the standard behavior. 

We don't know what to do in this case. If you have any suggestion...
