### ISSUE TITLE
Chrome - Device not found error but works with Firefox

### ISSUE THREAD

**Issue by jdaprato** [OpenVidu/openvidu#395]
**Describe the bug**
When trying openvidu js node tutorial (or One2One Kurento tuto with the same result) on differents OS (Linux and OSX) under Chrome Browser, when I enter a session by clicking on the "join" the error  "Device not found" appears. (same with kurento when hitting the "call" button).

**Expected behavior**
Getting the "allow camera and microphone" prompt into Chrome and the stream's display

**Wrong current behavior**
The error "Device not found" appears.

**OpenVidu tutorial where to replicate the error**
https://openvidu.io/docs/tutorials/openvidu-js-node/
https://doc-kurento.readthedocs.io/en/stable/tutorials/node/tutorial-one2one.html#for-the-impatient-running-this-example

**Comment by micaelgallego** [comment]
Have you tested with other WebRTC online services? It seems a problem with your system.

**Comment by jdaprato** [comment]
Thank you for your quick return. 
If I test via https://test.webrtc.org/ I do have an issue on Chrome too, same error but only for the audio input, I do have the prompt "Enable your camera" that shows. Another collegue has the same issue, with Chrome on OSX.

**Comment by micaelgallego** [comment]
Try reinstalling Chrome or connecting an external web cam.
