### ISSUE TITLE
Recording & share screen with Custom recording layouts

### ISSUE THREAD

**Issue by HeroTran** [OpenVidu/openvidu#396]
Hi @pabloFuente ! First of all I would like to many thank with you
This is my feature not bugs Openvidu
There are 3 guy join the same session Id (session Id get with classroom id)so I could call name with them
-Recorder
-Joiner A
-Joiner B
3 guys join the class room in this time, and Recorder guy will share screen and recording
Purporse: I want to record sound and all behavios from recorder => I have done
But my issue that video can not full screen from recorder ,it contain camera of (Joiner A & B)
as #389  You told me , using Custom recording layouts for fix it
I try read document and make demo, But This video just recording file index on server
`recordingLayout: RecordingLayout.CUSTOM` => Openvidu-Node
I have created index.html and deploy it on server AMZ
follow the same document on Openvidu

1/How customs layout record connect session Id from other web app (because session Id get from web app).
2/How index.html could recording screen from Recorder

Link record customs layout : https://record.1on1english.vn:4443/recordings/8mxcpw6ew22kwdgt/8mxcpw6ew22kwdgt.mp4

Thanks

**Comment by pabloFuente** [comment]
Please, do not use GitHub issue tracker for this kind of support questions. Use OpenVidu forum for that: https://openvidu.discourse.group/

**Comment by HeroTran** [comment]
Sorry @pabloFuente  I will delete it

**Comment by HeroTran** [comment]
I have done, close ticket.
