### ISSUE TITLE
before join the meeting, i want to change my camera, how can i get the stream from the camera

### ISSUE THREAD

**Issue by z-lionel** [OpenVidu/openvidu#397]
HI！

Before join the meeting, i want to change my camera, 
how can i get the stream from the camera?

I use the method like these:
var publisher = OV.initPublisher('video-container', { audioSource:  Audio One, videoSource: Video One, publishAudio: true, publishVideo: true }, (stream) => {
   // I can get Video One stream
});

When i use the method second time:
var publisher = OV.initPublisher('video-container', { audioSource:  Audio Two, videoSource: Video Two, publishAudio: true, publishVideo: true }, (stream) => {
   // I can get the stream, and there params is change, but stream still come from video  one
});

so i don't undstand, how can i do?

**Comment by pabloFuente** [comment]
This is not an issue or bug report. Please, use OpenVidu forum to ask for support: https://openvidu.discourse.group/
