### ISSUE TITLE
Anonymous video calling for testing

### ISSUE THREAD

**Issue by dhavalsolankislk** [OpenVidu/openvidu#398]
Hello,

We are using open vidu in our application. We need to implement Anonymous video calling in which on one side there will be actual user and on other side there will directly video played from the server for video call testing. Is is possible using open vidu

**Comment by micaelgallego** [comment]
If it is for testing, you can inject a video file as a "fake camera" in a browser managed using Selenium using a command like this: 

chrome.exe --use-fake-device-for-media-stream --use-file-for-fake-video-capture="D:\Test\Video\y4m.y4m"

More information here: https://cs.chromium.org/chromium/src/media/base/media_switches.cc?q=use-file-for-fake&sq=package:chromium&l=98

**Comment by dhavalsolankislk** [comment]
Hello,
Thanks for the reply.
Your solution works on GUI based server and we are using CLI based server. So is there any way to implement anonymous user calling using CLI based server.

**Comment by micaelgallego** [comment]
I understand. 

It can be implemented using Kurento, but not OpenVidu. 

If your commercial product depends on that feature you can consider given your support to implement it under our commercial services.
