### ISSUE TITLE
Encoding - OpenVidu Server Webhook

### ISSUE THREAD

**Issue by brunobottazzini** [OpenVidu/openvidu#399]
**Describe the bug**
When receiving an event from Webhook of type "messageSent", it arrives without a properly encoding.

So when we are sending special characters such as: è, ì, ò, ó, é our back-end cannot decode it properly and the character becomes: � or ?.

**Expected behaviour**
We expect that the charset should be passed through the call in the headers. Such as UTF-8.

**Wrong current behavior**
We have configure the flag "openvidu.webhook.headers" with the following flags:
* Content-type:application/json; charset=utf-8
* Accept-Charset: UTF-8

But these flags do not arrive in our server and the problem persists.

**OpenVidu tutorial where to replicate the error**
Unfortunately I could not find a tutorial that help us out.

**OpenVidu deployment info**
- Docker container, run with command 
```
docker run --name my-openvidu \
    --user 0:$GID \
    -d --network=myopenvidu \
    -p 4445:4445 \
    -v $LOGPATH/supervisor:/var/log/supervisor \
    -v $LOGPATH/cdr:/log \
    -v $VIDEOPATH:/opt/openvidu/recordings \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -e openvidu.secret=$THE_SECRET \
    -e openvidu.publicurl=$PUBLICURL \
    -e KMS_STUN_IP=$PUBLICIP -e KMS_STUN_PORT=19304 \
    -e KMS_TURN_URL=myproject:SOME_SECRET@$PUBLICIP:3490 \
    -e openvidu.recording=true \
    -e openvidu.recording.path=/opt/openvidu/recordings \
    -e server.ssl.enabled=false \
    -e openvidu.cdr=true \
    -e openvidu.webhook=true \
    -e openvidu.webhook.endpoint=http://localhost:8080/my-server/api/logs/webhook \
    -e openvidu.webhook.headers=["Content-type:application/json;\ charset=utf-8","Accept-Charset:\ UTF-8"] \                                                  
    -e openvidu.webhook.events=[messageSent,participantJoined,participantLeft] \
    -v $LIBS/openvidu-server-2.9.1-EM.jar:/openvidu-server.jar:ro \
    -v /usr/share/zoneinfo/Europe/Rome:/etc/localtime \
    openvidu/openvidu-server-kms:2.9.0
```

on Fedora 31 (replicable on Windows and others OS.)

**Screenshots**
![Schermata da 2020-03-03 11-45-51](https://user-images.githubusercontent.com/4460234/75768403-99efa480-5d44-11ea-8255-625159609f41.png)

![Schermata da 2020-03-03 11-45-33](https://user-images.githubusercontent.com/4460234/75768416-9e1bc200-5d44-11ea-9620-c3760487006f.png)

**Comment by MrCrayon** [comment]
@brunobottazzini  How did you get _messageSent_ Webhook?
I don't see that webhook implemented in OpenVidu code.

**Comment by brunobottazzini** [comment]
We have configured the webhook by following the openvidu server parameters: 
https://openvidu.io/docs/reference-docs/openvidu-server-params/#configuration-parameters-for-openvidu-server

As you can see our docker command in the section "OpenVidu deployment info" above.

We have our backend that receives the message from OpenVidu. 
We don't think the problem is with our backend because if we call it manually, the encoding works.

**Comment by MrCrayon** [comment]
@brunobottazzini yes, but as you can see from that page there is no _messageSent_ Event, that's why I asked.

You can also see here #288

Are you sure your webhook is not called somewhere by your app with that event?

**Comment by brunobottazzini** [comment]
@MrCrayon, I understand. I will double check on that and come back here

Thank you very much.

**Comment by brunobottazzini** [comment]
Hi @MrCrayon, 

You are right. We have implemented ourselves and I was not aware of it.

I will work with the team and create a PR to contribute with the project.

Since the issue does not exist here I am closing this issue.

**Comment by brunobottazzini** [comment]
@MrCrayon, I got the code and start debugging and I have noticed that the message does arrive encoded when handleRequest is called inside RpcHandler.

So I am guessing that the problema may be inside kurento-jsonrpc-server. I have stopped debugging since the problema is outside openvidu-server.

I am preparing the PR for the messageSent event. 

Best Regards,

**Comment by MrCrayon** [comment]
@brunobottazzini that's good to know, thanks for the update.
I think it's planned a release in a few days so that's going to be for the next one.

**Comment by brunobottazzini** [comment]
Hello @MrCrayon, 

We have created the PR: https://github.com/OpenVidu/openvidu/pull/402
