### ISSUE TITLE
How to room recording

### ISSUE THREAD

**Issue by mgochoa** [OpenVidu/openvidu#4]
In the Readme it says this project is a fork from Kurento Room I wanted to know, i f you guys have implemented room recording.

**Comment by micaelgallego** [comment]
We plan to implement recording in the near future, but it is not implemented yet.

What kind of recording do you need? 
* a) Record every user independently
* b) Composite all users in the same video file
* c) Record the application web interface as an invisible user

**Comment by mgochoa** [comment]
I need A) Record every user independently when entering a room.
I was trying to achieve this with this [KurentoRoomServerExample](https://github.com/kontonieaktywne1/KurentoRoomServerExample)

But then I read about OpenVidu

**Comment by micaelgallego** [comment]
Ok. We plan to implement that feature in the next months.

**Comment by mgochoa** [comment]
Oh, ok. So you should close this issue, while I also try to implement it.
