### ISSUE TITLE
 openvidu + react-native

### ISSUE THREAD

**Issue by hexiao-o** [OpenVidu/openvidu#40]
Hi,
I found an open source project [Echo](https://github.com/Jerameel/Echo)
WebRTC and Kurento Media Server Integration Demo for React-Native
Is it possible to integrate to openvidu ?

**Comment by pabloFuente** [comment]
If you're certain that this sample application works OK with KMS and its JavaScript client, you should be able to get it working with OpenVidu. Just adapt the client using openvidu-browser library and deploy OpenVidu Server as shown in the docs.

If you're willing to do it, let us know how it went when you've finished it. It would be very useful to confirm tha OpenVidu works in this particular case.

**Comment by hexiao-o** [comment]
I am doing a demo, and now I can see the video stream of mobile terminal (ios, android) on the web, but I don't know how to receive the remote video stream on the mobile terminal, hoping to get your help?  
demo: [https://github.com/hexiao-o/react-native-openvidu](https://github.com/hexiao-o/react-native-openvidu)

**Comment by hexiao-o** [comment]
It has been solved, thank you

**Comment by SahanXd** [comment]
Hi can you give me react native with kurento project
