### ISSUE TITLE
Switch camera causes the loss of the user’s personal streaming video and sees the player

### ISSUE THREAD

**Issue by giovannilezzi** [OpenVidu/openvidu#403]
Hello to all,
I’m trying to add the functionality of the Switch camera. But as soon as the user clicks on the button to make the switch he loses his streaming video and sees the player icons. has anyone already faced this problem?

**Comment by CSantosM** [comment]
Hello @giovannilezzi 

Which tutorial are you following?

**Comment by CSantosM** [comment]
Please, do not use GitHub issue tracker for this kind of support questions. Use OpenVidu forum for that: https://openvidu.discourse.group/
