### ISSUE TITLE
OpenVidu Pro Auto-Scaling doesn't work.

### ISSUE THREAD

**Issue by jinshuai7777** [OpenVidu/openvidu#404]
Hello. All.
How are you?
I have created OpenVidu Pro stack and tested the Auto-Scaling on the server.
But when I tested the Auto Scaling, it didn't work.
The KMS CPU Utilization was 100%.
In that case, new KMS instance should created if Auto-Scaling works fine.
Please check the following screenshot.

![image](https://user-images.githubusercontent.com/30215152/76329622-c8aee180-6327-11ea-91cb-bc243b1245b3.png)

Anyone can help me for this issue?
Thanks.

**Comment by pabloFuente** [comment]
I'm sorry, but there's no automating scale of OpenVIdu Pro clusters right now.
Version 2.12.0 releasing in the next few days will bring manual scalability though REST API. Next will work on automated scalability based on CPU load.

Regards
