### ISSUE TITLE
Can't change the default 4443 port

### ISSUE THREAD

**Issue by jinshuai7777** [OpenVidu/openvidu#406]
Hello. How are you?
I know OpenVidu Pro using 4443 port.
But the port is blocked for some company.
So I am going to change the 4443 port to common HTTPS port like 8443.

I have added another port (8443) on the OpenVidu Pro server. Especially nginx configuration.
But when I call REST API /api/sessions(POST), 409 error is occurring.

I think, we should be able to change the default port without any glithces for the OpenVidu Pro version.
Any suggestion?
Thank you.

**Comment by cruizba** [comment]
Hi jinshuai777, it does not seems like a configuration parameter. As the documentation says, this request can return 409: https://openvidu.io/docs/reference-docs/REST-API/#post-apisessions

If you have defined in your post request the parameter `sessionId`, it can return 409 if the session exists.

> customSessionId (optional string)
You can fix the sessionId that will be assigned to the session with this parameter. If you make another request with the exact same customSessionId while previous session already exists, no session will be created and a 409 http response will be returned. If this parameter is an empty string or not sent at all, OpenVidu Server will generate a random sessionId for you

If you don't define a sessionId, OpenVidu will generate a random sessionId.

Hope this helps.

If the problem persists and is related with the infrastructure or OpenVidu Pro, please contact via openvidu@gmail.com

**Comment by jinshuai7777** [comment]
Hi @cruizba 
Thanks for your kindly reply.

You mena the 409 error is normally when call the API?
I don't need to worry about the 409 error right?

**Comment by pabloFuente** [comment]
Documentation explains it: https://openvidu.io/docs/reference-docs/REST-API/#post-apisessions
