### ISSUE TITLE
OpenViduServer FAILED TO START(v2.12.0)

### ISSUE THREAD

**Issue by WesleyOne** [OpenVidu/openvidu#407]
**Describe the bug**
OpenViduServer FAILED TO START

**Expected behavior**
START SUCCESS

**Wrong current behavior**
START FAIL
CAN NOT FIND RESOURCE '${spring.info.build.location:classpath:META-INF/build-info.properties}'

**Additional context**

22:50:21.836 [main] INFO io.openvidu.server.OpenViduServer - Using /dev/urandom for secure random generation

______________________________________________
   ____               __      ___     _       
  / __ \              \ \    / (_)   | |      
 | |  | |_ __   ___ _ _\ \  / / _  __| |_   _
 | |  | | '_ \ / _ \ '_ \ \/ / | |/ _` | | | |
 | |__| | |_) |  __/ | | \  /  | | (_| | |_| |
  \____/| .__/ \___|_| |_|\/   |_|\__,_|\__,_|
        | |
        |_|             version 2.12.0
______________________________________________                                          

[INFO] 2020-03-13 22:50:22,851 [main] io.openvidu.server.OpenViduServer - Starting OpenViduServer on wangxiaoweideMacBook-Pro.local with PID 78348 (/Users/wesley/IdeaProjects/openvidu/openvidu-server/target/classes started by wesley in /Users/wesley/IdeaProjects/openvidu)
[INFO] 2020-03-13 22:50:22,852 [main] io.openvidu.server.OpenViduServer - No active profile set, falling back to default profiles: default
[INFO] 2020-03-13 22:50:24,075 [main] org.springframework.boot.web.embedded.tomcat.TomcatWebServer - Tomcat initialized with port(s): 4443 (https)
[INFO] 2020-03-13 22:50:24,087 [main] org.apache.coyote.http11.Http11NioProtocol - Initializing ProtocolHandler ["https-jsse-nio-0.0.0.0-4443"]
[INFO] 2020-03-13 22:50:24,088 [main] org.apache.catalina.core.StandardService - Starting service [Tomcat]
[INFO] 2020-03-13 22:50:24,089 [main] org.apache.catalina.core.StandardEngine - Starting Servlet engine: [Apache Tomcat/9.0.30]
[INFO] 2020-03-13 22:50:24,215 [main] org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] - Initializing Spring embedded WebApplicationContext
[INFO] 2020-03-13 22:50:24,216 [main] org.springframework.web.context.ContextLoader - Root WebApplicationContext: initialization completed in 1079 ms
[WARN] 2020-03-13 22:50:24,300 [main] org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'CDRHttpHandler': Unsatisfied dependency expressed through field 'openviduConfig'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'openviduConfig': Unsatisfied dependency expressed through field 'buildProperties'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.boot.info.BuildProperties' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
[INFO] 2020-03-13 22:50:24,303 [main] org.apache.catalina.core.StandardService - Stopping service [Tomcat]
[INFO] 2020-03-13 22:50:24,313 [main] org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener - 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
[ERROR] 2020-03-13 22:50:24,398 [main] org.springframework.boot.diagnostics.LoggingFailureAnalysisReporter - 

***************************
APPLICATION FAILED TO START
***************************

Description:

Field buildProperties in io.openvidu.server.config.OpenviduConfig required a bean of type 'org.springframework.boot.info.BuildProperties' that could not be found.

The injection point has the following annotations:
	- @org.springframework.beans.factory.annotation.Autowired(required=true)

The following candidates were found but could not be injected:
	- Bean method 'buildProperties' in 'ProjectInfoAutoConfiguration' not loaded because @ConditionalOnResource did not find resource '${spring.info.build.location:classpath:META-INF/build-info.properties}'

Action:

Consider revisiting the entries above or defining a bean of type 'org.springframework.boot.info.BuildProperties' in your configuration.

**Comment by pabloFuente** [comment]
Sorry, but until 2.12.0 is officially announced no support will be given

**Comment by micaelgallego** [comment]
2.12 version will be announced on Monday midday (CET time).
