### ISSUE TITLE
Can't see other participants

### ISSUE THREAD

**Issue by cmpscabral** [OpenVidu/openvidu#412]
**Describe the bug**
I'm running the demo docker files, I can't see the other participants in a call (and they can't see me)

**Expected behavior**
All participants should be able to see/ear eachother

**OpenVidu tutorial where to replicate the error**
`docker run -p 4443:4443 -e openvidu.publicurl=https://***MYIP***/ openvidu/getaroom-demo`
or
`docker run -p 4443:4443 -e openvidu.publicurl=https://***MYIP***/ openvidu/openvidu-call`

**Client device info (if applicable)**
- OSX Chrome Version 80.0.3987.132 (Official Build) (64-bit)
- OSX Firefox 74 (64-bit)
- Android Chrome

All demos work in your website, but I noticed the version is different.

Thank you!

**Comment by pabloFuente** [comment]
Those docker images are not ready for production environments. They will only work for local netowrk environments. So, if you try to connect with users outside of the newtork, it won't work.

You must deploy OpenVidu as stated in the [docs](https://openvidu.io/docs/home/) to properly work in a production environemnt:
