### ISSUE TITLE
Username and Password login server Deploy in Ubuntu 16.04 LTS ?

### ISSUE THREAD

**Issue by gatotteguhramadhan** [OpenVidu/openvidu#413]
hey please help me, this is why when I open a local openvidu server
https: // ip: 4443 /
deploy on ubuntu 16.04 does he ask for a username and password?
I followed the tutorial from here
https://openvidu.io/docs/deployment/deploying-ubuntu/

**Comment by pabloFuente** [comment]
Well, just finish the instructions 😉
https://openvidu.io/docs/deployment/deploying-ubuntu/#9-finally-check-your-server
