### ISSUE TITLE
In openvidu-browser, some time incoming audio come from media and other form audio call in android

### ISSUE THREAD

**Issue by rafaeljimenez** [OpenVidu/openvidu#415]
When I use Openvidu in my chrome browser of my Android mobile phone, some time the incoming audio call come from media and other time from audio call. 

The problem is that by default when we encrease the volume of the phone it increase only the "audio call" source. So when the incoming sound come from media, it is not easy to increase the sound.

**Comment by pabloFuente** [comment]
I'm sorry, but this doesn't qualify as a bug. This is not a direct problem of openvidu-browser, but a native Android thing. If you want some help with this, try opening an entry in [OpenVidu post](https://openvidu.discourse.group/).
