### ISSUE TITLE
Can't hear some others.

### ISSUE THREAD

**Issue by jinshuai7777** [OpenVidu/openvidu#416]
Hello.
I use OpenVidu Pro 2.12.0 on AWS.
When have a meeting, someone couldn't hear.
Some hear and some not.

Any suggesstiongs?
Thank you.

**Comment by beyondlevi** [comment]
It is happening to me. Have U found a fix?

**Comment by micaelgallego** [comment]
Hello @beyondlevi, can you create a new issue and describe how have you deployed OpenVidu? Also, the problem appears in any browser/device? or only in some specific ones?
