### ISSUE TITLE
Openvidu 2.12.0 audio iOS to chrome not working.

### ISSUE THREAD

**Issue by wardhanster** [OpenVidu/openvidu#417]
**Describe the bug**
We are trying to update our system from 2.11.0 to 2.12.0 and have encountered a roadblock.
In our tests - When chrome is the call initiator and an iOS device establishes a connection the audio is missing on the chrome side.

**Expected behavior**
Both sides should have audio

**Wrong current behavior**
The call initiator does not have remote audio from an iOS device (iOS 13.3.1)
iPhone 6s (tested with two devices)

**OpenVidu tutorial where to replicate the error**
can be replicated on https://demos.openvidu.io/openvidu-call 

**Client device info (if applicable)**
Describe the client device(s) or platform(s) where you are able to replicate the error. For example:
- Chrome 78.0.3904.97 (Official Build) (64-bit) on Windows 10 (1903).
- Safari  running on iPhone 6s with iOS 13.3.1.
"Mozilla/5.0 (iPhone; CPU iPhone OS 13_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.5 Mobile/15E148 Safari/604.1"

**Comment by wardhanster** [comment]
tagging you @micaelgallego for visibility

**Comment by micaelgallego** [comment]
Thank you for reporting. We are working on it

**Comment by ekurdesov** [comment]
I built an android sample + spring server on my local. running docker all is well but the rooms I create on web are not visible on the android or otherwise. I assume it's the latest master of openvidu-mvc-java
 and android. Tx! I assume those could be separate bugs but since you are working on it anyway :)

**Comment by wardhanster** [comment]
Hi @micaelgallego & @CSantosM 
I just saw that OV 2.13.0 was out, and hence I wanted to tune in and check if this issue has been resolved or not.
We are currently running OV2.11.0 as of now in prod.
and was hoping to migrate to PRO given all our tests comes out positive.
Any hints on the above issue would be really helpful.

**Comment by micaelgallego** [comment]
Please check with 2.13 and let us know

**Comment by hmassad** [comment]
The problem is related to Chrome on iOS and WebRTC, it happens outside OpenVidu.
Google is tracking the bug here https://bugs.chromium.org/p/chromium/issues/detail?id=752458

**Comment by wardhanster** [comment]
@hmassad thanks for mentioning that info 
but in my case it was not the webview as the bug mentioned. 
On another note - I still have to validate it with 2.13 .
Which I will be doing next week .

**Comment by Vichp** [comment]
@hmassad From what I read and what @wardhanster stated is that he is using Safari on iOS when testing, and Chrome on Windows 10. Therefore the problem has nothing to do with Chrome on iOS.

**Comment by CSantosM** [comment]
Hello @wardhanster 

I just tested your scenary and everything is working as expected. Chrome user receive the audio from Safari user.

The test I made was:

1. Go to [openvidu-call](https://demos.openvidu.io/openvidu-call/#/) demo and join to session with Chrome browser desktop (v 81.0.4044.129)
2. Do the same in iPhone 7 Plus (iOS 13.1.3) with Safari browser.

Could you test with the current demos environment please? Recently we released the 2.14.0 OpenVidu version. 

Let us know. 
Regards

**Comment by wardhanster** [comment]
@CSantosM Thanks for doing that.
I will be doing that test later today and update this issue ticket accordingly.

**Comment by wardhanster** [comment]
@CSantosM 
It seems to be working well for me with 2.14
I am going to close this ticket for now. I'll re-open if it comes back!
I Still, wonder what was causing that? 
On top of my head - Codecs ?
