### ISSUE TITLE
Set resolution in initialize a session endpoint

### ISSUE THREAD

**Issue by BritoMatheus** [OpenVidu/openvidu#418]
Hi,

I'm using  recordingMode  ALWAYS and I have a problem with resolution of recordings.

If we can set resolution in POST /api/sessions. It will help us a lot of.

Thanks!

**Comment by pabloFuente** [comment]
Sessions don't support setting a default resolution different than 1920x1080 for COMPOSED ALWAYS recordings. If you really need to change the resolution of your recordings, you will have to go to MANUAL mode and start the recording through REST API or Java/Node SDK.
