### ISSUE TITLE
How can I force other user in a session to unpublish or disconnect as MODERATOR role?

### ISSUE THREAD

**Issue by Wrufesh** [OpenVidu/openvidu#42]
Hi, I have a problem forcing other user in a session to disconnect or unpublish as role MODERATOR.

According to openvidu-node-client API reference:

```
OpenViduRole
MODERATOR :  They can subscribe to published streams of other users, publish their own streams and force unpublish() and disconnect() over a third-party stream or user
```
I am using openvidu-browser-js as client side.
I have set a user with MODERATOR role and got every connections to the session. But was unable to find any method to disconnect other non MODERATOR user.

I found dispose() method in connection object but it doen't seem to disconnect other non MODERATOR user.

Is there any way to do so as it seems possible according to the docs.

**Comment by pabloFuente** [comment]
OpenVidu 2.3.0 now offers MODERATOR role.
