### ISSUE TITLE
Set audio to speaker Android

### ISSUE THREAD

**Issue by dverrastro** [OpenVidu/openvidu#421]
Hi, 
I followed the android tutorial project to implement openvidu in my app but when i start the call sound comes out from the earpiece (like during a call) and not from the speaker. Home can I fix It?

**Comment by sadeghtkd** [comment]
I have the same problem.
Please help me.

**Comment by micaelgallego** [comment]
Is is out of the scope of OpenVidu selecting device to play sound. You should investigate on how to do that natively with Android.

If you found how to, please share your findings here to rest of the users.

**Comment by dverrastro** [comment]
Hi, I found a solution, even if I don't if it's the right way to do it. I used MediaPlayer component in this way: 
`

    private MediaPlayer mediaPlayer;

    private void reproduceSound() {
        mediaPlayer = new MediaPlayer();
        mediaPlayer = MediaPlayer.create(this, R.raw.customcsound);
        mediaPlayer.setAudioStreamType(AudioManager.STREAM_MUSIC);
        mediaPlayer.setLooping(true);
        mediaPlayer.start();
    }

    private void stopSound() {
        if(mediaPlayer != null) {
            //mediaPlayer.stop();
            mediaPlayer.release();
        }
    }`

Remember to call stopSound when you close the call. I hope it's useful.

**Comment by dverrastro** [comment]
Hi, I found a solution, even if I don't if it's the right way to do it. I used MediaPlayer component in this way: 
`

    private void enableSpeaker() {
        AudioManager audioManager = (AudioManager) this.getSystemService(Context.AUDIO_SERVICE);
        if(audioManager != null) {
            if(!audioManager.isSpeakerphoneOn()) {
                audioManager.setSpeakerphoneOn(true);
                audioManager.setMode(AudioManager.MODE_IN_COMMUNICATION);
            }
        }
    }

    private void disableSpeaker() {
        AudioManager audioManager = (AudioManager) this.getSystemService(Context.AUDIO_SERVICE);
        if(audioManager != null) {
            if(audioManager.isSpeakerphoneOn()) {
                audioManager.setSpeakerphoneOn(false);
                audioManager.setMode(AudioManager.MODE_NORMAL);
            }
        }
    }`

Remember to call stopSound when you close the call. I hope it's useful.

**Comment by dverrastro** [comment]
Hi, I found a solution, even if I don't if it's the right way to do it. I used AudioManager component in this way: 
`

    private void enableSpeaker() {
        AudioManager audioManager = (AudioManager) this.getSystemService(Context.AUDIO_SERVICE);
        if(audioManager != null) {
            if(!audioManager.isSpeakerphoneOn()) {
                audioManager.setSpeakerphoneOn(true);
                audioManager.setMode(AudioManager.MODE_IN_COMMUNICATION);
            }
        }
    }

    private void disableSpeaker() {
        AudioManager audioManager = (AudioManager) this.getSystemService(Context.AUDIO_SERVICE);
        if(audioManager != null) {
            if(audioManager.isSpeakerphoneOn()) {
                audioManager.setSpeakerphoneOn(false);
                audioManager.setMode(AudioManager.MODE_NORMAL);
            }
        }
    }`

Remember to call disableSpeaker when you close the call. I hope it's useful.
