### ISSUE TITLE
Missing publisher field from the subscriber object.

### ISSUE THREAD

**Issue by marcsello** [OpenVidu/openvidu#422]
**Describe the bug**
It seems like, that the REST API documentation is inconsistent with the actual server implementation as one of the fields in the REST api is missing. 

**Expected behavior**
According to the documentation at https://docs.openvidu.io/en/2.12.0/reference-docs/REST-API/#get-apisessionsltsession_idgt there should be a `publisher` field in the subscriber object which identifies the publisher this connection is "subscribed to". 

connections.content[]:
```json
      "subscribers": [{
        "createdAt": 1586189031647,
        "streamId": "str_CAM_GYn9_con_OE21BmiEBL",
        "publisher" : "con_OE21BmiEBL"
      }, {
        "createdAt": 1586188426911,
        "streamId": "str_CAM_LQyP_con_M26r9luFL2",
        "publisher" : "con_M26r9luFL2"
      }]
```

**Wrong current behavior**
Requesting a session's informations either by /api/sessions or /api/sessions/<SESSION_ID> The field connections.content[].subscribers[].publisher field is missing. 

connections.content[]:
```json
      "subscribers": [{
        "createdAt": 1586189031647,
        "streamId": "str_CAM_GYn9_con_OE21BmiEBL"
      }, {
        "createdAt": 1586188426911,
        "streamId": "str_CAM_LQyP_con_M26r9luFL2"
      }]
```

**OpenVidu tutorial where to replicate the error**
1. Use public OpenVidu demo server
2. Connect to it with at least two clients so subscriptions will be made
3. `curl --user OPENVIDUAPP:MY_SECRET https://demos.openvidu.io:4443/api/sessions`
4. Find the session with at least two connections
5. In the connections.content[].subscribers[] there will be no publisher field.

**OpenVidu deployment info**
Self-hosted deployment in a Ubuntu 18.04.4 VM. Running Kurento 6.13.0-0kurento1.18.04. Without coturn.

The issue is present on the public demo server as well. https://demos.openvidu.io/

**Additional context**
I'm trying to implement this API as a Python3 library. My ipmplementation fails, because it expects that value to be there. https://github.com/marcsello/pyopenvidu/issues/3

**Comment by pabloFuente** [comment]
Yes, you are right. But actually the one thing wrong is the documentation. It is outdated. No `publishe` field is necessary, because the `streamId` property of the subscriber identifies its associated publisher.
In other words: property `streamId` of a specific publisher and property `streamId` of each subscriber subscribe to it wil be the same.

I'm updating the documentation right now.

Thanks for reporting.
