### ISSUE TITLE
Use IP Camera but video is no playing

### ISSUE THREAD

**Issue by zw12579** [OpenVidu/openvidu#423]
![image](https://user-images.githubusercontent.com/33717789/78639363-632b2200-78e0-11ea-9392-f8dc18d8f9ef.png)

Must the RTSP stream be a public address? 

Browser console output content

`
Subscribing to ipc_IPCAM_rtsp_ALKR_admin_bimcc123@192_168_2_172_554_h264_ch1_main_av_stream
`

`IceConnectionState of RTCPeerConnection 7d077914-f952-4541-afd6-1b5c9ebd9955 (str_IPC_G7C8_ipc_IPCAM_rtsp_ALKR_admin_bimcc123@192_168_2_172_554_h264_ch1_main_av_stream) change to "checking"`

`'Subscriber' (str_IPC_G7C8_ipc_IPCAM_rtsp_ALKR_admin_bimcc123@192_168_2_172_554_h264_ch1_main_av_stream) successfully subscribed`

`Subscribed correctly to ipc_IPCAM_rtsp_ALKR_admin_bimcc123@192_168_2_172_554_h264_ch1_main_av_stream`

`IceConnectionState of RTCPeerConnection 7d077914-f952-4541-afd6-1b5c9ebd9955 (str_IPC_G7C8_ipc_IPCAM_rtsp_ALKR_admin_bimcc123@192_168_2_172_554_h264_ch1_main_av_stream) change to "connected"`

**Comment by GioGallo** [comment]
hi do you have any updates regarding this problem?

**Comment by dhavalsolankislk** [comment]
@zw12579  How did you find solution of this problem
