### ISSUE TITLE
app.js:192 POST https://<ip-address>:5000/api-sessions/get-token net::ERR_CONNECTION_TIMED_OUT

### ISSUE THREAD

**Issue by neeldebnath** [OpenVidu/openvidu#425]
Every time I click the "Join" button to join a session, a error generate, app.js:192 POST https://<ip-address>:5000/api-sessions/get-token net::ERR_CONNECTION_TIMED_OUT.
Why the server is taking too long ? I have set the server up as per the documentation.
What I am doing wrong? please help.

**Comment by pabloFuente** [comment]
GitHub issues is not available for support. It is for bugs and code issues. To ask for help use OpenVidu forum: https://openvidu.discourse.group/
