### ISSUE TITLE
How to deploy Openvidu server in cluster mode ?

### ISSUE THREAD

**Issue by kinserlin** [OpenVidu/openvidu#429]
hi .In case of the Openvidu server in single node mode shutdown . I want to deploy openvidu server in cluster mode . According to the code of openvidu/openvidu I found that the sessions and the participants are in the memory. How can i share the sessions and the participants in multi nodes ?

**Comment by pabloFuente** [comment]
For support questions use OpenVidu forum: https://openvidu.discourse.group/
GitHub issue tracker is for tracking issues.
