### ISSUE TITLE
Custom screen sharing chrome extension using

### ISSUE THREAD

**Issue by AntonMatiushin** [OpenVidu/openvidu#43]
Hello!

I try to use my own chrome extension for screen sharing. I look here: [https://github.com/OpenVidu/openvidu-screen-sharing-chrome-extension](https://github.com/OpenVidu/openvidu-screen-sharing-chrome-extension)

and see that I have to specify my extension as parameter of OV.setAdvancedConfiguration function.

But there is no such function in openvidu-browser  (I npm installed last version - 1.9.0)

> AppComponent_Host.ngfactory.js? [sm]:1 ERROR TypeError: this.OV.setAdvancedConfiguration is not a function

Is docs correct, or I have to act other way?

**Comment by pabloFuente** [comment]
Hi Breedibf,

This will be available in version 2.0.0, which will be released this week.

Stay tunned!

**Comment by pabloFuente** [comment]
This is now available with OpenVidu 2.0.0
