### ISSUE TITLE
There is no Chat feature in android like it is in web application

### ISSUE THREAD

**Issue by sravan41-elorce** [OpenVidu/openvidu#435]
Working with Openvidu Android.. I see there is no chat feature for android application, But it is in web application. We would like to get some help regarding group Chat.

**Comment by micaelgallego** [comment]
This is a request for enhancement for the android-tutorial. Please fill the issue in https://github.com/OpenVidu/openvidu-tutorials repository. 

If you want help, use the community forum: https://openvidu.discourse.group
