### ISSUE TITLE
openvidu-server in docker: different behavior on different computers

### ISSUE THREAD

**Issue by creimers** [OpenVidu/openvidu#436]
**Describe the bug**

I am evaluating openvidu to stream IP cameras via webRTC to a react browser application. In the meantime, I'm observing peculiar phenomena that I can't quite make sense of.

I have two MacBooks, one from 2015 with macOS 10.14, and one from 2019 with macOS 10.15. Both run docker 19.03.

When I run the openvidu media servers on the 2015 MacBook in a docker container, the webRTC streams play perfectly fine in whatever browser/computer I connect with on my LAN.

When running the media servers on the 2019 MacBook in the same docker container, however, the streams don't work, regardless of which computer or browser I'm using on my LAN. Signaling always fails.

Here is an `about:webrtc` screenshot from the **working** connection in Firefox 75:

<img width="1464" alt="Bildschirmfoto 2020-04-17 um 11 42 10" src="https://user-images.githubusercontent.com/6090492/79567192-0daafe00-80b4-11ea-8532-f309e4e7d7b1.png">

Here's another screenshot from the **failing** connection:

<img width="1453" alt="Bildschirmfoto 2020-04-17 um 14 04 28" src="https://user-images.githubusercontent.com/6090492/79567364-61b5e280-80b4-11ea-837d-8a99dd832cdc.png">

In addition, it says

```
🚨 IceConnectionState of RTCPeerConnection e9e17b72-6173-4b39-b79b-c3fd877418a2 (str_IPC_QQev_ipc_IPCAM_rtsp_ZSD6_192_168_1_106_8554_unicast) to "failed"

🚨 ICE failed, add a TURN server and see about:webrtc for more details
```

in the console. Any thoughts why this might be happening?

**Expected behavior**

I'd expect to be able to play the webRTC stream in all browsers and on all computers in my LAN, regardless of which computer I run the media server on.

**Wrong current behavior**
I can't get the stream to work in any browser on any computer in my LAN when I'm running the media server on my 2019 MacBook in docker.

**OpenVidu tutorial where to replicate the error**

I have created a [lightweight repository](https://github.com/creimers/openvidu-kms) that contains a docker-compose.yml file to spin up the media server and a frontend application that can be started with yarn/npm. The repo contains [detailed instructions](https://github.com/creimers/openvidu-kms/blob/master/README.md).

The setup very closely resembles the [IP cameras tutorial](https://github.com/OpenVidu/openvidu-tutorials/tree/master/openvidu-ipcameras). 

**OpenVidu deployment info**

- Docker container [openvidu-server-kms](https://github.com/OpenVidu/openvidu/tree/master/openvidu-server/docker/openvidu-server-kms) with docker compose (`docker-compose up`) on either macOS 10.14 or macOS 10.15.

**Comment by micaelgallego** [comment]
WebRTC is very sensible to network conditions. It seems that networking in your two computers are different in some way. 

openvidu/openvidu-server-kms:2.12.0 docker image is provided for local development.

For production, we do not support Mac OS (for things like this issue). 

If you manage to solve your issue, please comment here to let others know.
