### ISSUE TITLE
Add property to set composite resolution when always recording

### ISSUE THREAD

**Issue by rafaelrenanpacheco** [OpenVidu/openvidu#439]
Hello!

Since the combination COMPOSITE + ALWAYS doesn't allow for customization when creating a session, would be possible to add a server property to set the default COMPOSITE resolution when ALWAYS recording? In our case we don't need 1080p composite videos, and we prefer to always record instead of starting it from the API (which allows for resolution customization).

I think the resolution property would be [used here](https://github.com/OpenVidu/openvidu/blob/master/openvidu-server/src/main/java/io/openvidu/server/kurento/core/KurentoSessionManager.java#L409). I did a hardcode test using the 854x480 resolution and the .mp4 video was recorded just fine in that resolution. I didn't started a PR because I was unable to get the docker recorder working. It just recorded a "Welcome" OpenVidu screen, not the session. But at least that "Welcome" screen had the 480p resolution.

The property could be named like `OPENVIDU_RECORDING_COMPOSITE_RESOLUTION`, and 1080p would be the default value.

**Comment by micaelgallego** [comment]
Thank you for suggestion. We will add it in the following weeks.

**Comment by pabloFuente** [comment]
By the way, when donde this won't be a configuration property of openvidu-server such as these: https://docs.openvidu.io/en/2.13.0/reference-docs/openvidu-config/

But instead will be simply a new configuration parameter when initializing the Session: https://docs.openvidu.io/en/2.13.0/reference-docs/REST-API/#post-apisessions
The same way you can set the `defaultRecordingLayout` for a session, you will be able to set the `defaultRecordingResolution`

**Comment by rafaelrenanpacheco** [comment]
Way better! :+1:

**Comment by pabloFuente** [comment]
Hi,

Release 2.18.0 allows setting default values when initializing Sessions for all existing recording properties: https://openvidu.medium.com/openvidu-2-18-0-improved-recordings-client-sdk-reconnection-capabilites-and-much-more-5aad3e3c57cc
