### ISSUE TITLE
enableProdMode should not disable all logging in browser

### ISSUE THREAD

**Issue by doomsower** [OpenVidu/openvidu#440]
**Describe the bug**
When using `enableProdMode`, console statements from other parts of my code are no longer visible

**Expected behavior**
OpenVidu debug logging is disabled, but everywhere else console works

**Wrong current behavior**
Currently, `enableProdMode` in `openvidu-browser` [overrides](https://github.com/OpenVidu/openvidu/blob/9aee3eaf4460fe7a6365a30ea93c6f6947044a7b/openvidu-browser/src/OpenVidu/OpenVidu.ts#L642) console methods, effectively disabling console for any other debugging. This problem can be solved by implementing custom (replaceable) logger.

**Additional context**
"openvidu-browser": "2.12.0"

**Comment by pabloFuente** [comment]
Sure, we will take a look to this. Proper solution would be "wrapping" openvidu-bowser logs with another function that would be disabled when calling `enableProdMode`.

Stay tuned.

**Comment by pabloFuente** [comment]
Probably the best way to go is using a third-party well-established JavaScript logging library that may be deactivated without overriding global `console.[LOGGING_METHOD]` mehtods, such as [loglevel](https://github.com/pimterry/loglevel)

**Comment by AbdallahAbdedaiem** [comment]
I'm facing same issue! does openvidu provide a way to disable only its logs and not all console logs? Did anyone you found out how to do it??

**Comment by micaelgallego** [comment]
It is already implemented in master. It will be ready in 2.15 version (to be published in a few weeks)

**Comment by CSantosM** [comment]
In fact , this was added to openvidu-browser 2.14.0 version.
