### ISSUE TITLE
how to config recording folder format /recording/yyy-mm-dd/hashcode/file video

### ISSUE THREAD

**Issue by toanlv92** [OpenVidu/openvidu#442]
how to config recording folder format /recordings/yyy-mm-dd/hashcode/file video

**Comment by micaelgallego** [comment]
Right now recording path is not configurable in this way you suggested. 

As a work around you can put your app in front of recording with this mapping. 

We will take this RFE in our roadmap for consideration.

**Comment by pabloFuente** [comment]
Closing this now. We'll consider your suggestion.
