### ISSUE TITLE
GST_DEBUG issue with latest docker container

### ISSUE THREAD

**Issue by spyang** [OpenVidu/openvidu#446]
Using a Google cloud Ubuntu 18.04 instance, I followed the deployment directions here:
https://docs.openvidu.io/en/2.13.0/deployment/deploying-on-premises/
 
Installation worked mostly fine, starting with this:
curl https://s3-eu-west-1.amazonaws.com/aws.openvidu.io/install_openvidu_latest.sh | bash 

I edited /opt/openvidu/.env and configured it for my domain name with letsencrypt.

As root, ran ./openvidu start

Got an error, had to hack docker-compose.yml like this:
```
<             - GST_DEBUG=0
---
>             - GST_DEBUG=${KMS_DEBUG_LEVEL:-}
```

Ran `./openvidu start`

**Comment by micaelgallego** [comment]
Can you describe the error you obtained to change GST_DEBUG in docker-compose.yml file? 

I've just test installation and work fine for me.

**Comment by spyang** [comment]
Here's the error:
```root@upoll:/opt/openvidu# ./openvidu start
ERROR: Invalid interpolation format for "environment" option in service "kms": "GST_DEBUG=${KMS_DEBUG_LEVEL:-}"
ERROR: Invalid interpolation format for "environment" option in service "kms": "GST_DEBUG=${KMS_DEBUG_LEVEL:-}"```

**Comment by spyang** [comment]
the 2.12 version issue I had previously was a caching problem with a previous version (fixed on hard page reload), so I have corrected my bug report to only be about the GST_DEBUG problem.

**Comment by spyang** [comment]
Actually, even though the browser works, even after doing a hard reload, the browser still claims to be for version 2.12.

**Comment by OscarSotoSanchez** [comment]
Hi,

```
ERROR: Invalid interpolation format for "environment" option in service "kms": "GST_DEBUG=${KMS_DEBUG_LEVEL:-}"
ERROR: Invalid interpolation format for "environment" option in service "kms": "GST_DEBUG=${KMS_DEBUG_LEVEL:-}
```

This is an error due to the version you are using of docker-compose. Could you tell me which one you have? With the latest version 1.25.4 it's working fine. You can see how to install the latest version here [Install Docker Compose](https://docs.docker.com/compose/install/)

**Comment by spyang** [comment]
> Install Docker Compose

Interesting.  I had simply done `sudo apt install docker-compose`,
which gives me version 1.17.1-2 (Ubuntu 18.04).
I'll upgrade and try it out.

**Comment by pabloFuente** [comment]
We have already updated all installations scripts to check the installed version and throw a descriptive error if it does not meet the minimum supported version, inviting the admin to install a newer version.

Thank you opening the issue.

**Comment by spyang** [comment]
Thanks for being so responsive!  I can verify that upgrading docker-compose fixed my issue.  As for my other issue, the client still reports itself as version 2.12.0 as seen on the top right corner of the screen whenever I visit the default page.

**Comment by pabloFuente** [comment]
Yes. Release 2.13.0 didn't bring a new release for OpenVidu Call application. It is fine, it will work without a problem.

We will release 2.13.0 version of OpenVidu Call probably next week with tons of improvements. To upgrade it it will be just a matter of updating the tag of its container at docker-compose.override.yml file. Stay tuned!
