### ISSUE TITLE
Getting blank video streams in production.

### ISSUE THREAD

**Issue by Wrufesh** [OpenVidu/openvidu#45]
I deployed Openvidu-server over ubuntu 16.4 and used this guide : [Openvidu server deployment over ubuntu](http://openvidu.io/docs/deployment/deploying-ubuntu/)

I was able to join session and can detect `connectionCreated `event and `streamCreated` event but cannot get a video (it is blank).

I have setup coturn server as described in deployment guide.
 I also have conformed that required ports are not blocked by firewall.

My server computer is on Global Protect VPN. Similarly I can test my application on my local network and it is working fine.

I also came to know that some VPN blocks STUN or TURN protocal. But couldn't verify whether its working or not. The systemctl status of coturn.service is running.

What might have causing this issue?
[stackoverflow question](https://stackoverflow.com/questions/50072530/openvidu-webrtc-openvidu-browser-streamcreated-event-is-triggered-but-didnt-ge)

**Comment by pabloFuente** [comment]
Please, check if your COTURN works fine here: [Trickle ICE](https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/). To do so, remove the default Google server and add your own:

- STUN or TURN URI > turn:`YOUR_TURN_IP`:`YOUR_TURN_PORT`
- TURN username > `TURN_USERNAME`
- TURN password > `TURN_PASSWORD`

Click on "Add Server" and finally "Gather candidates" (this of course in a browser outside the VPN). Please, paste the ouput here when you are done. It will say if your COTURN server is reachable and working OK or not

**Comment by micaelgallego** [comment]
Also, it is possible you need configure TURN server on the browser side. OpenVidu doesn't currently support that, but that feature will be included in version 2.1.0.

**Comment by Wrufesh** [comment]
![screenshot from 2018-04-28 15-46-16](https://user-images.githubusercontent.com/4590723/39395202-6f6dc898-4afb-11e8-9aca-ccedd7e31b5f.png)

Above is the output of tricke-ice.

**Comment by Wrufesh** [comment]
I cannot fix this issue yet.
Will this be fixed only in release 2.1.0? 
Or hosting openvidu-server over other server not on VPN with no firewall active will solve this.
@pabloFuente @micaelgallego

**Comment by micaelgallego** [comment]
It is better to host openvidu-server and KMS in a network without restrictions. We recommend to install it in AWS with our provided Cloudformation. It is tested and it works well in the majority of scenarios.

The ability to configure TURN server on browser will be available on version 2.1.0.

**Comment by Wrufesh** [comment]
I was able to get video streaming when I disabled firewall.
Still want to deploy with firewall enabled.

**Comment by micaelgallego** [comment]
Possible you will have to deploy TURN server without firewall.

**Comment by Wrufesh** [comment]
I just deployed TURN server without firewall and openvidu-server with firewall.
The result was negetive. It was not working that way.
May be firewall interfere with docker. If it is so running openvidu-server.jar might work.

**Comment by micaelgallego** [comment]
It is possible. It is very difficult to say something without knowing your
exact network topology.

In any case, remember that you need to install Kurento Media Server along
openvidu-server.jar.

Please review our installation instructions.

**Comment by Wrufesh** [comment]
Using jar file is also giving same result.
I have opened desired port in a firewall.
But cannot get the video.

Again if firewall is disabled it works great.
What is being blocked?
I cannot deploy it without firewall because of security issue of the company.
Neither I am able to find the solution.

Kindly suggest me further way if there any. :(

[https://stackoverflow.com/questions/50114379/webrtc-app-only-works-when-firewall-is-disabled](url)

**Comment by micaelgallego** [comment]
Please describe carefuly what network topology you have when OpenVidu is
working and when OpenVidu is not working.

Please describe where browsers are located, where KMS is located, where
openvidu-server is located, what ports are open in your firewall, where
coturn is installed, etc...

With that information maybe we can help you to solve your issues.

Regards

**Comment by micaelgallego** [comment]
What are the candidates generated with
https://webrtc.github.io/samples/src/content/peerconnection/trickle-ice/ in
both cases (with and without firewall?)

It seems that with this topology TURN server must me configured in the
browser. And that feature is not yet available in OpenVidu.

**Comment by Wrufesh** [comment]
Firewall Disabled: Candidates Generated
![nfirewall](https://user-images.githubusercontent.com/4590723/39480808-146fae94-4d89-11e8-92ad-2c481d2ab3a7.png)

Firewall Enabled: Candidates Generated
![yfirewall](https://user-images.githubusercontent.com/4590723/39480821-1d22f898-4d89-11e8-9299-6d048388beb2.png)

**Comment by Wrufesh** [comment]
Hi I was trying to debug with [chrome://webrtc-internals/](url).
I found the following facts:
**When firewall is disabled(When peer connection is successfull):**
Active connection uses reflex type candidate from from local side.

**When firewall is enabled(When peer connection fails):**
No possible peer uses reflex type candidate from local side. It uses host type candidate. Although reflex type candidates are gathered.

Here is the dump from Chrome Webrtc Internals
[firewall_disabled_webrtc_internals_dump.txt](https://github.com/OpenVidu/openvidu/files/1966614/firewall_disabled_webrtc_internals_dump.txt)
[firewall_enabled_webrtc_internals_dump.txt](https://github.com/OpenVidu/openvidu/files/1966615/firewall_enabled_webrtc_internals_dump.txt)

Can you please give me little insight on why it might be behaving like that?

**Comment by pabloFuente** [comment]
Glad to hear it. Sure, v2.0.0 now allow devs to configure custom STUN and TURN servers in OpenVidu Browser. Check out this method: https://openvidu.io/api/openvidu-browser/classes/openvidu.html#setadvancedconfiguration

**Comment by pabloFuente** [comment]
Be sure to update your code following the [v2.0.0 breaking changes list](https://github.com/OpenVidu/openvidu/releases).
