### ISSUE TITLE
In OpenVidu 2.13.0 https://openvidu-server-uri/dashboard|inspector etc is world-accessable

### ISSUE THREAD

**Issue by SiJux** [OpenVidu/openvidu#450]
Hello OpenVidu-Team,

thank you for your great work on OpenVidu!
Yesterday I've deployed the new Version 2.13.0 with Docker. Now openvidu is accessable on port 443, which is great for restrictive firewalls. Now port 4443 is not needed anymore, but https://openvidu-server-uri/dashboard|inspector etc. is world-accessable.
I think it would be great if this will be configurable  via .env or any other config. In any case i would be great if such ressources are only accessable from specific ip addresses or protected via htaccess. Or are there any reasons why they should be world-accessable?

Thank you.

Regards
Simon

**Comment by micaelgallego** [comment]
Good idea. We will provide this feature in the next version.

**Comment by pabloFuente** [comment]
Already available in version 2.14.0
