### ISSUE TITLE
Browser Chrome Mobile (version 81.0.4044.124) for iOS is not supported in OpenVidu (V2.12)

### ISSUE THREAD

**Issue by ohager** [OpenVidu/openvidu#451]
**Describe the bug**
We just got this exception:
```
BROWSER_NOT_SUPPORTED: Browser Chrome Mobile (version 81.0.4044.124) for iOS is not supported in OpenVidu
```
**Expected behavior**
Modern versions of Chrome should work even on iOS ;)

**Wrong current behavior**
Most recent major version of Chrome Mobile does not work

**Additional context**
Current Version: OpenVidu Pro 2.12

**Comment by pabloFuente** [comment]
Chrome and Firefox do not have WebRTC stack in iOS. Apple decided that only Safari would have WebRTC capabilities. 
https://stackoverflow.com/questions/59190472/webrtc-in-chrome-ios
Apple likes doing this kind of things ;)

**Comment by Flamenco** [comment]
Apple started allowing Chrome to use WebKit in their last iOS release.
