### ISSUE TITLE
Does Openvidu support unzip the record file right after the session ends in INVIDUAL mode?

### ISSUE THREAD

**Issue by nptt2920** [OpenVidu/openvidu#452]
I made the session record in INVIDUAL mode. After the stop recording, on my KMS I received a zip file containing the new video record and the json file. I need to use them right after the record ends. Now I have the solution of using crontab to extract them, but I need a more efficient solution. Does OpenVidu provide a solution to this problem?
Thanks for all the help!

**Comment by pabloFuente** [comment]
OpenVidu issue tracker is not meant to be used like this. This is not a bug, and besides there already is a very recent entry in OpenVidu forum with the exact same question (https://openvidu.discourse.group/t/is-there-a-way-to-unzip-right-after-the-session-ends-with-individual-mode/590/2?u=pablofuente) already answered. Please, respect the community rules.
