### ISSUE TITLE
Openvidu doesn't work in firefox

### ISSUE THREAD

**Issue by pocce90** [OpenVidu/openvidu#454]
Following the instructions in https://docs.openvidu.io/en/2.12.0/deployment/deploying-ubuntu/ I've installed the openvidu 2.12 server in an Ubuntu Bionic 18.04 machine (on azure). Everything works fine in chrome based browsers (also in safari on mac) using the test page of browser (https://ip-of-my-machine:4443), but if I try to test it with Firefox the page remains like attached image
![immagine](https://user-images.githubusercontent.com/6673842/80617737-c2450800-8a42-11ea-89d8-8a625c14cb4e.png)

**Comment by micaelgallego** [comment]
Please update to OpenVidu 2.13 following these instructions:

https://docs.openvidu.io/en/2.13.0/deployment/deploying-on-premises/

Report back if problem is still there.

**Comment by pocce90** [comment]
> Please update to OpenVidu 2.13 following these instructions:
> 
> https://docs.openvidu.io/en/2.13.0/deployment/deploying-on-premises/
> 
> Report back if problem is still there.

Same problem, I've followed your guide but openvidu test page works with all browsers except firefox

**Comment by micaelgallego** [comment]
Ok, please share with us Firefox console and OpenVidu logs. 

Also, please share with us the same test with Chrome, to see the differences.

**Comment by LoicMoerman** [comment]
Hello, I had the same issue and I resolved it by opening this ports: 
- 40000 - 57000 TCP+UDP: used by Kurento Media Server to establish media connections.
- 57001 - 65535 TCP+UDP: used by TURN server to establish relayed media connections.

Because on chrome it work without opening ports.

**Comment by pabloFuente** [comment]
Well, of course. We are always assuming that the Prerequisites of the deployment instructions are properly fulfilled. @pocce90 plaase check that the required ports are opened.

**Comment by pocce90** [comment]
> Well, of course. We are always assuming that the Prerequisites of the deployment instructions are properly fulfilled. @pocce90 plaase check that the required ports are opened.

Yes, of course I opened all ports. I followed instrunctions slavishly. On Monday I'll post all logs

**Comment by pocce90** [comment]
> Please update to OpenVidu 2.13 following these instructions:
> 
> https://docs.openvidu.io/en/2.13.0/deployment/deploying-on-premises/
> 
> Report back if problem is still there.

Sorry guys, I've mede new tests and I've found the problem, i'm working wrong with certificates, now firefox works with openvidu 2.13, but not openvidu 2.12 (for openvidu 2.13 I have recreated certificates from the .jks passed in openvidu 2.12)
