### ISSUE TITLE
openvidu-browser: incorrect handling of pre-acquired videoSource and audioSource

### ISSUE THREAD

**Issue by robymus** [OpenVidu/openvidu#456]
**Describe the bug**
openvidu-browser does not use passed videoSource and audioSource parameters with Publisher constructed through initPublisher, when these parameters are MediaStreamTracks, 

**Expected behavior**
getUserMedia is not getting called and passed MediaStreamTracks are used.

**Wrong current behavior**
Even though MediaStreamTracks are passed for videoSource and audioSource, new instances are still created according to passed or default constraints.

**OpenVidu deployment info**
N/A

**Client device info (if applicable)**
N/A

**Screenshots**
N/A

**Additional context**
When Publisher.ts in the constructor checks if the MediaStreamTracks are provided, it checks if the constraints returned by openvidu.generateMediaConstraints is undefined, however that's never the case, it's reported through audioTrack / videoTrack fields being filled. Other parts of the browser code handle this correctly.
```
                    if (myConstraints.constraints === undefined) {
                        // No need to call getUserMedia at all. MediaStreamTracks already provided
```
[openvidu-browser/src/OpenVidu/Publisher.ts:613](https://github.com/OpenVidu/openvidu/blob/2976ecc4435b1c37687625680a396d5f915ec474/openvidu-browser/src/OpenVidu/Publisher.ts#L613)

I will submit a pull request fixing this shortly.

**Comment by pabloFuente** [comment]
Thank you for reporting and the PR. Already merged to master.
