### ISSUE TITLE
streaming not showing in iOS device

### ISSUE THREAD

**Issue by saisatya525** [OpenVidu/openvidu#458]
Hi Team, im using 2.11 to create video stream using ionic tutorial,How ever i can able to share and see streaming in browser with ionic serve, but when i do build for iOS device, i cant see the local and streamed video in device and no errors in the console as well, at the same time streamed video from device is showing in browser.

Im loading adapater and rtc plugins properly for device and and i can see the video tags in DOM.
 Let me know if you need more imformation.

**Comment by pabloFuente** [comment]
Use the forum for this kind of support questions: https://openvidu.discourse.group/
