### ISSUE TITLE
Can't add existing ICE candidates to null WebRtcEndpoint

### ISSUE THREAD

**Issue by zzzykf** [OpenVidu/openvidu#46]
I am modifying openvidu-android-app to allow the user to unpublish  and publish the video again without leaving the room.  
The problem that occurs to me is the user unable to publish the video again after unpublish, and OpenVidu Server shows the error "Can't add existing ICE candidates to null WebRtcEndpoint".

What I did to unpublish the video in the Android App is only sending the message "unpublishVideo" to OpenVidu Server. 
Is there anything I've did wrong or I've missed any process to correctly unpublish the video?

**Comment by pabloFuente** [comment]
Hi

Can you test this behaviour in our test application?

```
docker run -p 8443:8443 openvidu/testapp
```

You can join two users to the same session and press a button to stop the publishing and to republish again, as many times as you want. 

![selection_179](https://user-images.githubusercontent.com/15049534/39816167-b35b244a-539a-11e8-96a1-bfef5bf99ae3.png)


I guess this is the behaviour you want in your application.

You can use then if you want the source code of [openvidu/openvidu-testapp](https://github.com/OpenVidu/openvidu/tree/master/openvidu-testapp) to see how it is done at the client-side and adapt it to your needs.

**Comment by zzzykf** [comment]
Thank you, much appreciate for the reply.
