### ISSUE TITLE
Error stopping big recordings, method getSizeInBytes() overflows int max value

### ISSUE THREAD

**Issue by techcouncilbox** [OpenVidu/openvidu#464]
**Describe the bug**
Openvidu 2.13

With long recordings int precision is not enough to represent data in bytes in method getSizeInBytes().

**Expected behavior**
RecordingInfoUtils -> getSizeInBytes() should return a double or long

**Wrong current behavior**
A clear and concise description of what is actually happening instead of the expected behavior.

**OpenVidu deployment info**
- Docker container as explained in on Premises

**Client device info (if applicable)**
Not applicable

**Screenshots**
![image](https://user-images.githubusercontent.com/17164419/81005490-50a7f800-8e4e-11ea-9682-4564edba0d43.png)

**Comment by pabloFuente** [comment]
Is this related to this forum entry? https://openvidu.discourse.group/t/recording-download-error-large-recordings/678?u=pablofuente

**Comment by pabloFuente** [comment]
And yes, this can be absolutely a problem. Max int in Java only goes to 2147483647, so 3,XXX,XXX,XXX will fail to parse to Integer. I will taje a look in the following days and propose a fix for the next release, coming very soon.

**Comment by techcouncilbox** [comment]
This error occurs at the end of recording when OV is setting metadata for file. I think is not related to downloading proccess.

**Comment by pabloFuente** [comment]
This commit add3ee56033965bfa817d55b338eec817563b0e5 should take care of this issue. Already in master branch. Available in next release.

Thanks for reporting.
