### ISSUE TITLE
Parent POM of openvidu-java-client 2.13.0 does not specify version.gson and version.slf4j

### ISSUE THREAD

**Issue by christophehamal** [OpenVidu/openvidu#465]
**Describe the bug**
Build on CircleCI fails because dependencies for ${version.gson} and ${version.slf4j} cannot be resolved

**Expected behavior**
Properties get resolved in the parent POM (2.0.0)

**Wrong current behavior**
Build fails with the following messages:
[WARNING] The POM for com.google.code.gson:gson:jar:${version.gson} is missing, no dependency information available
[WARNING] The POM for org.slf4j:slf4j-api:jar:${version.slf4j} is missing, no dependency information available
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.1.2:go-offline (default-cli) on project xxx: org.eclipse.aether.resolution.DependencyResolutionException: The following artifacts could not be resolved: com.google.code.gson:gson:jar:${version.gson}, org.slf4j:slf4j-api:jar:${version.slf4j}: Could not find artifact com.google.code.gson:gson:jar:${version.gson} in central (https://repo.maven.apache.org/maven2) -> [Help 1]

**OpenVidu tutorial where to replicate the error**
openvidu-mvc-java

**OpenVidu deployment info**
Maven build on CircleCI

> **IMPORTANT NOTE**: please, if you think the bug might be related to OpenVidu Server side, specify here if you are also getting the error by using OpenVidu Server Demos instance. This instance is publicly available (use it only for this test, because it is not secure!!!): **URL**: `https://demos.openvidu.io:4443`, **SECRET**: `MY_SECRET`

**Client device info (if applicable)**
N/A

**Screenshots**
N/A

**Additional context**
N/A

**Comment by pabloFuente** [comment]
Please, describe exactly what are you trying to do. What fails to be built? What commands are you executing?

**Comment by christophehamal** [comment]
I'm integrating openvidu in a Spring Boot 5 MVC project. I included the dependency in the project POM as in the tutorial. I have no issue in dev environment, but when the build goes through the CircleCI build pipeline, it fails when maven tries to download the dependencies (i.e. go-offline step).

From what I can see, the POM in the package "openvidu-java-client-2.13.0.jar" contains a dependency on "com.google.code.gson:gson" with a parametrized version "${version.gson}". The  POM indicates "openvidu-parent", version 2.0.0 as its parent. However, the parameter "${version.gson}" does not seem to be set in [openvidu-parent](https://repo1.maven.org/maven2/io/openvidu/openvidu-parent/2.0.0/openvidu-parent-2.0.0.pom). This seems to throw off the build pipeline as it cannot resolve the version. Same for the dependency on "org.slf4j:slf4j-api".

Maybe I'm missing something, though. :-)

Thanks for your help anyway!

**Comment by pabloFuente** [comment]
Well, on a totally clean Ubuntu installation, on which only Git and Maven have been installed, this commands work just fine out-of-the-box. You can test it with a single line command like this:

```
docker run --rm ubuntu:18.04 /bin/bash -c "apt-get update && apt-get install -y maven git && git clone https://github.com/OpenVidu/openvidu-tutorials.git && cd openvidu-tutorials/openvidu-mvc-java && mvn compile package"
```

openvidu-java-client is a completely self-contained dependency, so I don't know what CircleCI is trying to do. I'm sorry, but this is out of scope of OpenVidu.

**Comment by in-fke** [comment]
Same Bug for version.gson 2.19.0 which references https://search.maven.org/artifact/io.openvidu/openvidu-parent/2.0.0/pom and version.gson is apparently not defined anywhere.
