### ISSUE TITLE
Node Basic Tutorial/Test is not working with latest versions

### ISSUE THREAD

**Issue by devcarlos** [OpenVidu/openvidu#467]
**Describe the bug**
I cannot JOIN a call setting up the latest OpenVidu/Kurrento Server from Docker (latest which means 2.13.0)

Tutorial
https://docs.openvidu.io/en/2.12.0/tutorials/openvidu-js-node/

**Expected behavior**
JOIN the Video Stream as showcased on the tutorial

**Wrong current behavior**
I get an error 401 on the node server response:

```
Error: 401
    at /Users/charles/Documents/DEVELOPER/WORKSPACE/OPENVIDU/openvidu-tutorials/openvidu-js-node/node_modules/openvidu-node-client/lib/Session.js:413:32
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**OpenVidu tutorial where to replicate the error**
This is an EXTREMELY IMPORTANT STEP. If we are able to replicate the error in any of the official [OpenVidu Tutorials](https://github.com/OpenVidu/openvidu-tutorials) or [OpenVidu Demos](https://github.com/OpenVidu), then we will be able to quickly fix it. If you are getting the error in your own application, please try to add the necessary changes to the most similar tutorial so it fails with the same error (try to keep those changes as contained as possible, so that the original tutorial maintains its integrity). Once you have an application to replicate the error, explain in detail the steps to get it like this:
1. Clone repository [
git clone https://github.com/OpenVidu/openvidu-tutorials.git
]
2. Compile the application like this 
3. Run OpenVidu Server like this [
docker run -p 4443:4443 --rm -e openvidu.secret=test123123 openvidu/openvidu-server-kms:latest
]
4. Run the application like this [
cd openvidu-tutorials/openvidu-js-node
npm install
node server.js https://localhost:4443 test123123
]
5. Join 1 user... Publish a video stream [
Go to browser on https://localhost:5000/
Login with:
user: publisher1
pass: pass

]
6. See error:
On console:

```
Logging in | {user, pass}={publisher1, pass}
'publisher1' has logged in
Getting a token | {sessionName}={Session 3}
New session Session 3
Error: 401
    at /Users/charles/Documents/DEVELOPER/WORKSPACE/OPENVIDU/openvidu-tutorials/openvidu-js-node/node_modules/openvidu-node-client/lib/Session.js:413:32
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**OpenVidu deployment info**
How is your OpenVidu Server instance deployed when you get the bug. A couple of possible examples are listed below:
- Docker container as explained in OpenVidu tutorials, run with command 
`docker run -p 4443:4443 --rm -e openvidu.secret=test123123 openvidu/openvidu-server-kms:latest`
on macOS Catalina 10.15.1

**Client device info (if applicable)**
- Chrome Version 81.0.4044.129 (Official Build) (64-bit) on MacOS Catalina 10.15.4
- Firefox 75.0 (64-bit) on MacOS Catalina 10.15.4

**Screenshots**

<img width="1680" alt="Screen Shot 2020-05-09 at 18 23 26" src="https://user-images.githubusercontent.com/646364/81487562-54f85a80-922c-11ea-8ccc-8890cb1ee8b8.png">
<img width="1680" alt="Screen Shot 2020-05-09 at 18 37 08" src="https://user-images.githubusercontent.com/646364/81487566-59247800-922c-11ea-979b-e5a7aa371f4b.png">
<img width="1680" alt="Screen Shot 2020-05-09 at 18 37 32" src="https://user-images.githubusercontent.com/646364/81487567-59bd0e80-922c-11ea-8bfd-004b48e3fe9c.png">
<img width="1680" alt="Screen Shot 2020-05-09 at 18 39 05" src="https://user-images.githubusercontent.com/646364/81487569-5aee3b80-922c-11ea-8655-5fe224bba9f1.png">

**Additional context**
Add any other context about the problem here. For example, attach any useful logs related to the issue.

**Comment by devcarlos** [comment]
After debug the code in `server.js` a little bit I have found it is crashing here:

<img width="1680" alt="Screen Shot 2020-05-09 at 19 56 02" src="https://user-images.githubusercontent.com/646364/81487809-3ba4dd80-922f-11ea-991c-9ee018b87b70.png">

**Comment by devcarlos** [comment]
Changing docker to v2.12.0 and I get this:

<img width="1680" alt="Screen Shot 2020-05-09 at 20 04 37" src="https://user-images.githubusercontent.com/646364/81487958-3183de80-9231-11ea-955d-17f99e1a9105.png">
<img width="1680" alt="Screen Shot 2020-05-09 at 20 04 45" src="https://user-images.githubusercontent.com/646364/81487960-35affc00-9231-11ea-916b-813461e24c32.png">
<img width="1680" alt="Screen Shot 2020-05-09 at 20 09 31" src="https://user-images.githubusercontent.com/646364/81487963-36489280-9231-11ea-97e3-2f9cce6cc4c6.png">

So it seems a problem of versions between OpenVido from Docker with `2.12.0` and `2.13.0 (latest)`

Also on browser we can see a problem between versions, so I will try to use `2.12.0` on `package.json` to see if the errors persist

**Comment by devcarlos** [comment]
UPDATE: 

After downgrade to `2.12.0` I was able to connect and get the token without the browser error complaining, but now I get this error:

> Firefox can’t establish a connection to the server at wss://localhost:4443/openvidu.

Any thoughts ?

<img width="1680" alt="Screen Shot 2020-05-09 at 20 34 32" src="https://user-images.githubusercontent.com/646364/81488284-da800880-9234-11ea-8f4a-f727da1e98af.png">

**Comment by devcarlos** [comment]
UPDATE2:

After test on Chrome I was able to see the Video Session:

<img width="1680" alt="Screen Shot 2020-05-09 at 20 49 06" src="https://user-images.githubusercontent.com/646364/81488425-9d1c7a80-9236-11ea-9f67-5835dbb5a017.png">

So it seems the wss protocol issue is related to Firefox only, will keep looking for a workaround for that browser.

**Comment by micaelgallego** [comment]
Have you connected to `https://localhost:4443` in Firefox and accepted the certificate warning?

**Comment by devcarlos** [comment]
@micaelgallego yes and it worked 👍
