### ISSUE TITLE
Open-vidu V-2.14.0 not working

### ISSUE THREAD

**Issue by rvigneshw** [OpenVidu/openvidu#470]
**Describe the bug**
After upgrading to openvidu 2.14 ,i tried to access my public IP the browser says page could not be loaded

**Expected behavior**
To show a open-vidu call app home page

**Wrong current behavior**
the  brwser says "This site can’t be reached"

**OpenVidu tutorial where to replicate the error**
https://docs.openvidu.io/en/2.14.0/deployment/upgrading/

steps to get it like this:
sudo su
cd /opt/openvidu
./openvidu start

**OpenVidu deployment info**
On Google Cloud platform using open-vidu on premises deployment tutorial
[V2.13.0 works fine for me]

**Comment by OscarSotoSanchez** [comment]
Hi @rvigneshw,

you can show me the logs of Openvidu and NGINX, to do so follow these steps:

1.- Login with root `sudo su`
2.- Go to Openvidu folder `cd /opt/openvidu`
3.- Getting Openvidu logs `docker-compose logs openvidu-server
4.- Getting NGINX logs `docker-compose logs nginx`

**Comment by dennysq** [comment]
Hi, If you followed the upgrade process from 2.13 to 2.14, keep in mind that DOMAIN_OR_PUBLIC_IP is the new property in the latest version, OPENVIDU_DOMAIN_OR_PUBLIC_IP has been deprecated. I noticed that in the log, however, this is missing in the upgrade documentation

**Comment by pabloFuente** [comment]
OPENVIDU_DOMAIN_OR_PUBLIC_IP is deprecated, but is still accepted by OpenVidu Server. It will first try to get the value from DOMAIN_OR_PUBLIC_IP, and if it does not exist, will try from OPENVIDU_DOMAIN_OR_PUBLIC_IP. If this doesn't exist either, then OpenVidu server will throw an error.

This won't be this way forever, and will be removed in a future version of OpenVidu

**Comment by rvigneshw** [comment]
Thanks for the information.
