### ISSUE TITLE
Mute and Unmute Audio and Video Programatically in openvidu-library-angular v2.14.0

### ISSUE THREAD

**Issue by jebatalent** [OpenVidu/openvidu#474]
Mute and Unmute Audio and Video Programatically in openvidu-library-angular v2.14.0. I follow the tutorial openvidu docs and used that method but i cant able to change it.

**Comment by pabloFuente** [comment]
Please, don't delete the issue template. Fill it properly so we are able to replicate and fix the error if it exists.

**Comment by micaelgallego** [comment]
If you have a question, open an entry in https://openvidu.discourse.group
