### ISSUE TITLE
iOS App i am unable to render the remotevideo stream

### ISSUE THREAD

**Issue by MunnaMnm** [OpenVidu/openvidu#478]
Hi ,

I have downloaded from the below link

https://github.com/OpenVidu/openvidu-ios-app 
When i was running the code, i created roomname and participant name. later i open safari brower and  enter the https://demos.openvidu.io, click on 
open viducall and enter the same room which i created. Now the remote partipant name is coming and but remote video is not streaming/rendering in my iPhone.
func remoteVideoRenderingMethod(){
guard let videoTrack = self.peersManager?.remoteStreams.first?.videoTracks.first else {
            return
        }
        self.remoteVideoTrack = videoTrack
        self.remoteVideoTrack?.isEnabled = true
            #if arch(arm64)
               let renderer = RTCMTLVideoView(frame: self.remoteVideoView.bounds)
           #else
               let renderer = RTCEAGLVideoView(frame: self.remoteVideoView.bounds)
           #endif
            renderer.contentMode = .scaleAspectFit
            self.remoteVideoTrack!.add(renderer)
            self.remoteVideoView.addSubview(renderer)
}

Please check the issue.

Tools using Xcode : 11.4.1
iPhone os : 13.4.1

**Comment by pabloFuente** [comment]
Didn't you see the warnings in the project?

![Selection_617](https://user-images.githubusercontent.com/15049534/82429483-457adc00-9a8c-11ea-946f-a71ca6244847.png)

![Selection_618](https://user-images.githubusercontent.com/15049534/82429496-4a3f9000-9a8c-11ea-8515-26011d03c9ac.png)

This application is provided as it is. It is not officially supported and cannot be guaranteed to work fine right now. What I can tell you is that it worked some time in the past, but it has work to be done and probably only developers with WebRTC and iOS skills would be able to make it work in its current status. You can use Ionic (open-source and free) or React Native (paid feature, contac us through [Commercial](https://openvidu.io/support#commercial) page to ask for further information) to build your mobile app, both for Android and iOS at the same time.

Regards

**Comment by MunnaMnm** [comment]
Hi,

I already saw the warning.. I am iOS Developer for past 6 years.. In the
project i have only issue with remote rendering issue.

I changed a lot of code in the openVidu code of ios source to make it work.
To me i am getting the video from the delegate method of peer

 *func* peerConnection(*_* peerConnection: RTCPeerConnection, didAdd
stream: RTCMediaStream) {

        *if* peerConnection == *self*.localPeer {

            print("local peerConnection did add stream")

        } *else* {

            print("remote peerConnection did add stream")



            *if* (stream.audioTracks.count > 1 || stream.videoTracks.count >
1) {

                print("Weird looking stream")

            }

            remoteStreams.append(stream)

        }

 }

but when i passed this video stream to below method Video is not getting
rendering and i could see the participant name also ... Please let me know
the issue how can i resolve it

 *func* renderRemoteVideoStream() {

        *guard* *let* videoTrack = *self*.peersManager?.remoteStreams.first
?.videoTracks.first *else* {

            *return*

        }

        *self*.remoteVideoTrack = videoTrack

        *self*.remoteVideoTrack?.isEnabled = *true*

        DispatchQueue.main.async {

            *let* renderer = RTCEAGLVideoView(frame: *self*.remoteVideoView.
bounds)

            renderer.contentMode = .scaleAspectFill

            renderer.delegate = *self*

            renderer.renderFrame(*nil*)

            *self*.remoteVideoView.addSubview(renderer)

            *self*.remoteVideoTrack!.add(renderer)

            *self*.remoteName.text = *self*.peersManager?.remoteParticipant
?.participantName ?? "No name"

        }

    }
