### ISSUE TITLE
No event for session disconnect is recived on openvidu browser when Chrome app is closed

### ISSUE THREAD

**Issue by AlexStreaming** [OpenVidu/openvidu#482]
**Describe the bug**
I don't get disconnect event from android device when Chrome app closes

**Expected behavior**
A disconnect event should arrive in order to kick the participant out of the session, otherwise their thumbnail doesn't disappear

**Wrong current behavior**
What happens is that a participant accesses a room from an android device, and to exit what he does is close the Chrome application, this I have seen is detected in the openvidu-server log but there is no event towards client (openvidu-browser) to be able to remove the participant

I add an openvidu-server log of what happens in this case:

```
2020-05-21 08:53:37,319 DEBG 'openvidu-server' stdout output:
[ERROR] 2020-05-21 08:53:37,319 [0.0-4443-exec-7] io.openvidu.server.rpc.RpcHandler - Transport exception for WebSocket session: fo6nr3i19r9ljbgik61cun7a3t - Exception: Unable to unwrap data, invalid status [CLOSED]

2020-05-21 08:53:38,476 DEBG 'openvidu-server' stdout output:
[INFO] 2020-05-21 08:53:38,476 [ventExec-e2-t41] io.openvidu.server.kurento.core.KurentoParticipantEndpointConfig - KMS event [MediaFlowInStateChange] -> endpoint: con_FK89to8yiU_str_CAM_RjOt_con_LIYJsRFzD0 (subscriber) | state: NOT_FLOWING | pad: default | mediaType: VIDEO | timestamp: 1590051218475

2020-05-21 08:53:38,592 DEBG 'openvidu-server' stdout output:
[INFO] 2020-05-21 08:53:38,591 [0.0-4443-exec-3] io.openvidu.server.rest.SessionRestController - REST API: GET /api/sessions

2020-05-21 08:53:39,686 DEBG 'openvidu-server' stdout output:
[INFO] 2020-05-21 08:53:39,685 [ventExec-e2-t43] io.openvidu.server.kurento.core.KurentoParticipantEndpointConfig - KMS event [MediaFlowOutStateChange] -> endpoint: str_CAM_RjOt_con_LIYJsRFzD0 (publisher) | state: NOT_FLOWING | pad: default | mediaType: VIDEO | timestamp: 1590051219684
[INFO] 2020-05-21 08:53:39,686 [ventExec-e2-t41] io.openvidu.server.kurento.core.KurentoParticipantEndpointConfig - KMS event [MediaFlowOutStateChange] -> endpoint: str_CAM_RjOt_con_LIYJsRFzD0 (publisher) | state: NOT_FLOWING | pad: default | mediaType: AUDIO | timestamp: 1590051219684

2020-05-21 08:53:40,477 DEBG 'openvidu-server' stdout output:
[INFO] 2020-05-21 08:53:40,476 [ventExec-e2-t41] io.openvidu.server.kurento.core.KurentoParticipantEndpointConfig - KMS event [MediaFlowInStateChange] -> endpoint: con_FK89to8yiU_str_CAM_RjOt_con_LIYJsRFzD0 (subscriber) | state: NOT_FLOWING | pad: default | mediaType: AUDIO | timestamp: 1590051220475

2020-05-21 08:53:44,620 DEBG 'openvidu-server' stdout output:
[INFO] 2020-05-21 08:53:44,619 [0.0-4443-exec-9] io.openvidu.server.rest.SessionRestController - REST API: GET /api/sessions

2020-05-21 08:53:47,320 DEBG 'openvidu-server' stdout output:
[INFO] 2020-05-21 08:53:47,320 [TaskScheduler-1] io.openvidu.server.rpc.RpcHandler - After connection closed for WebSocket session: fo6nr3i19r9ljbgik61cun7a3t - Status: Unable to unwrap data, invalid status [CLOSED]

2020-05-21 08:53:50,584 DEBG 'openvidu-server' stdout output:
[INFO] 2020-05-21 08:53:50,584 [0.0-4443-exec-3] io.openvidu.server.rest.SessionRestController - REST API: GET /api/sessions

2020-05-21 08:53:56,568 DEBG 'openvidu-server' stdout output:
[INFO] 2020-05-21 08:53:56,568 [0.0-4443-exec-7] io.openvidu.server.rest.SessionRestController - REST API: GET /api/sessions

2020-05-21 08:54:02,613 DEBG 'openvidu-server' stdout output:
[INFO] 2020-05-21 08:54:02,612 [.0-4443-exec-10] io.openvidu.server.rest.SessionRestController - REST API: GET /api/sessions

2020-05-21 08:54:02,719 DEBG 'openvidu-server' stdout output:
[INFO] 2020-05-21 08:54:02,719 [ventExec-e2-t41] io.openvidu.server.kurento.core.KurentoParticipantEndpointConfig - KMS event [MediaStateChangedEvent]: -> endpoint: con_LIYJsRFzD0_str_CAM_YG3h_con_FK89to8yiU (subscriber) | oldState: CONNECTED | newState: DISCONNECTED | timestamp: 1590051242718

2020-05-21 08:54:03,482 DEBG 'openvidu-server' stdout output:
[INFO] 2020-05-21 08:54:03,481 [ventExec-e2-t41] io.openvidu.server.kurento.core.KurentoParticipantEndpointConfig - KMS event [MediaStateChangedEvent]: -> endpoint: str_CAM_RjOt_con_LIYJsRFzD0 (publisher) | oldState: CONNECTED | newState: DISCONNECTED | timestamp: 1590051243480
```

**Comment by pabloFuente** [comment]
I cannot reproduce the error. Try on https://demos.openvidu.io/openvidu-call/ 
- Connect a desktop Chrome to a session
- Connect a mobile Android Chrome to the same session
- Both users see each other
- Direclty close the Chrome application in Android
- After the required time for the ping-pong mechanism to be aware of the mobile user having left (~10 seconds), a streamDestroyed a connectionDestroyed events with reaason "networkDisconnect" will be received by the desktop user, and the stream will be removed from the view.

It takes a little bit because forcing the close up of the application doesn't allow communicating openvidu-server that the user is leaving the session. So it must be openvidu-server itself the one warning other users that someone has not sent the required ping messages in the allowed time frame, so it has been evicted from the session.

**Comment by buzeandrei** [comment]
Any update on this? I get the same issue with 2 web clients on Chrome. If I refresh the page while broadcasting - the connected user does not get the update event that the stream is offline.

**Comment by mateatslc** [comment]
same here, no `streamDestroyed` is triggering

**Comment by pabloFuente** [comment]
`streamDestroyed` and `connectionDestroyed` events are triggered once the websocket connection of the parcitipant is closed.
If it is gracefully closed, they will happen immediately. If not (for example forcibly closing the application), then it will take some time for openvidu-server to finally decide to close the connection (between 8-12 seconds).
If events never happen, then it simply means the websocket connection is never broken. Be aware that for example in a mobile device, setting the app in the background does not mean the connection is closed.

**Comment by mateatslc** [comment]
@pabloFuente, thanks for your reply
just to clarify: graceful disconnect works fine. linked OV demo works fine too. my problem is similar of what @buzeandrei is describing. refreshing (or even closing) a _desktop_ browser (aka websocket connection is gone) won't cause the `streamDestroyed` event fire on the other end.
also, this was working reliably in the past and still works sporadically.
