### ISSUE TITLE
CDR does not work

### ISSUE THREAD

**Issue by gomez34** [OpenVidu/openvidu#483]
**Describe the bug**
Do not create any file with the log even though cdr is enabled and pointing to the path / opt / openvidu / cdr and the folder if it is created

**Expected behavior**
Create a file with the different events because the cdr is enabled

**Wrong current behavior**
Do not create any file with the different events.

**OpenVidu tutorial where to replicate the error**
Anyone

**OpenVidu deployment info**
- Java and docker, Openvidu v. 2.13.0
- Ubuntu Server 18.04

**Client device info (if applicable)**
- Chrome 81  on Windows 10 (1903).

Thanks.

**Comment by pabloFuente** [comment]
What do you mean with "Java and docker, Openvidu v. 2.13.0" ? What kind of deployment is that?

**Comment by gomez34** [comment]
I have tried both docker and the old deployment method with java, openvidu version 2.13.0

**Comment by pabloFuente** [comment]
Since release 2.13.0, the only supported deployments are these ones:
https://docs.openvidu.io/en/2.14.0/deployment/

Try any of those and enable CDR. It should work just fine out-of-the-box.

**Comment by gomez34** [comment]
CDR does not work with this deployment method, https://docs.openvidu.io/en/2.14.0/deployment/deploying-on-premises/

**Comment by pabloFuente** [comment]
Yes it does.

**Comment by pabloFuente** [comment]
You must set [configuration property](https://docs.openvidu.io/en/2.14.0/reference-docs/openvidu-config/) **OPENVIDU_CDR=true**
That's all.

**Comment by gomez34** [comment]
I have it in true but it doesn't work for me, also in console I have traces like: [INFO] 2020-05-22 12:04:43,492 [m0tv5u2j-e16-t0] io.openvidu.server.cdr.CDRLoggerFile - {"webrtcConnectionCreated":{"sessionId":"166","timestamp":1590149083446,"streamId":"str_CAM_LRQm_con_Qxs5led1Ld","participantId":"con_Qxs5led1Ld","connection":"OUTBOUND","videoSource":"CAMERA","videoFramerate":11,"videoDimensions":"{\"width\":960,\"height\":540}","audioEnabled":true,"videoEnabled":true}}

**Comment by pabloFuente** [comment]
Show the logs of your OpenVidu Server on startup (the first 200 lines when running the service)

**Comment by pabloFuente** [comment]
(Be careful with any secret or IP you don't wanna show)

**Comment by gomez34** [comment]
[INFO] 2020-05-22 14:59:09,962 [main] io.openvidu.server.OpenViduServer - Starting OpenViduServer on PC with PID 61998 (/home/test/***.jar started by root in /home/test)
[INFO] 2020-05-22 14:59:09,983 [main] io.openvidu.server.OpenViduServer - No active profile set, falling back to default profiles: default
[ERROR] 2020-05-22 14:59:10,305 [main] io.openvidu.server.config.OpenviduConfig - .env file not found at /home/test/Videos/.env
[INFO] 2020-05-22 14:59:10,506 [main] io.openvidu.server.OpenViduServer - Started OpenViduServer in 2.423 seconds (JVM running for 3.399)
[INFO] 2020-05-22 14:59:10,522 [main] io.openvidu.server.OpenViduServer - 


   Configuration properties
   ------------------------

   * CERTIFICATE_TYPE=selfsigned
   * OPENVIDU_CDR=true
   * OPENVIDU_CDR_PATH=/opt/openvidu/cdr
   * OPENVIDU_DOMAIN_OR_PUBLIC_IP=
   * OPENVIDU_PUBLICURL=****
   * OPENVIDU_RECORDING=true
   * OPENVIDU_RECORDING_AUTOSTOP_TIMEOUT=30
   * OPENVIDU_RECORDING_COMPOSED_URL=
   * OPENVIDU_RECORDING_CUSTOM_LAYOUT=/opt/openvidu/custom-layout
   * OPENVIDU_RECORDING_NOTIFICATION=publisher_moderator
   * OPENVIDU_RECORDING_PATH=/home/test/Videos
   * OPENVIDU_RECORDING_PUBLIC_ACCESS=true
   * OPENVIDU_RECORDING_VERSION=2.9.0
   * OPENVIDU_SECRET=*****
   * OPENVIDU_SESSIONS_GARBAGE_INTERVAL=900
   * OPENVIDU_SESSIONS_GARBAGE_THRESHOLD=3600
   * OPENVIDU_STREAMS_VIDEO_MAX_RECV_BANDWIDTH=0
   * OPENVIDU_STREAMS_VIDEO_MAX_SEND_BANDWIDTH=0
   * OPENVIDU_STREAMS_VIDEO_MIN_RECV_BANDWIDTH=300
   * OPENVIDU_STREAMS_VIDEO_MIN_SEND_BANDWIDTH=300
   * OPENVIDU_WEBHOOK=false
   * OPENVIDU_WEBHOOK_ENDPOINT=
   * OPENVIDU_WEBHOOK_EVENTS=["sessionCreated","sessionDestroyed","participantJoined","participantLeft","webrtcConnectionCreated","webrtcConnectionDestroyed","recordingStatusChanged","filterEventDispatched","mediaNodeStatusChanged"]
   * OPENVIDU_WEBHOOK_HEADERS=[]



[INFO] 2020-05-22 14:59:10,524 [main] io.openvidu.server.OpenViduServer - Using /dev/urandom for secure random generation
[INFO] 2020-05-22 14:59:10,667 [main] io.openvidu.server.OpenViduServer - Starting OpenViduServer on PC with PID 61998 (/home/test/***.jar started by root in /home/test)
[INFO] 2020-05-22 14:59:10,668 [main] io.openvidu.server.OpenViduServer - No active profile set, falling back to default profiles: default
[ERROR] 2020-05-22 14:59:12,329 [main] io.openvidu.server.config.OpenviduConfig - .env file not found at /home/test/Videos/.env
[INFO] 2020-05-22 14:59:12,787 [main] org.springframework.boot.web.embedded.tomcat.TomcatWebServer - Tomcat initialized with port(s): 443 (https)
[INFO] 2020-05-22 14:59:12,803 [main] org.apache.coyote.http11.Http11NioProtocol - Initializing ProtocolHandler ["https-jsse-nio-0.0.0.0-443"]
[INFO] 2020-05-22 14:59:12,804 [main] org.apache.catalina.core.StandardService - Starting service [Tomcat]
[INFO] 2020-05-22 14:59:12,804 [main] org.apache.catalina.core.StandardEngine - Starting Servlet engine: [Apache Tomcat/9.0.30]
[INFO] 2020-05-22 14:59:12,906 [main] org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/] - Initializing Spring embedded WebApplicationContext
[INFO] 2020-05-22 14:59:12,906 [main] org.springframework.web.context.ContextLoader - Root WebApplicationContext: initialization completed in 2162 ms
[INFO] 2020-05-22 14:59:13,486 [main] io.openvidu.server.OpenViduServer - OpenVidu CDR service is enabled
[INFO] 2020-05-22 14:59:13,487 [main] io.openvidu.server.OpenViduServer - OpenVidu Webhook service is disabled (may be enabled with 'OPENVIDU_WEBHOOK=true')
[INFO] 2020-05-22 14:59:13,505 [main] io.openvidu.server.OpenViduServer - OpenVidu Server using one KMS: ws://localhost:8888/kurento
[INFO] 2020-05-22 14:59:13,568 [rbeatExec-e1-t0] org.kurento.jsonrpc.client.JsonRpcClientNettyWebSocket - [KurentoClient]  Connecting native client
[INFO] 2020-05-22 14:59:13,569 [rbeatExec-e1-t0] org.kurento.jsonrpc.client.JsonRpcClientNettyWebSocket - [KurentoClient]  Creating new NioEventLoopGroup
[INFO] 2020-05-22 14:59:13,884 [ntLoopGroup-2-1] org.kurento.jsonrpc.client.JsonRpcClientNettyWebSocket - [KurentoClient]  Initiating new Netty channel. Will create new handler too!
[INFO] 2020-05-22 14:59:14,049 [main] io.openvidu.server.recording.service.RecordingManager - OpenVidu recording service is enabled
[INFO] 2020-05-22 14:59:14,376 [main] io.openvidu.server.recording.service.RecordingManager - Recording module required: Downloading openvidu/openvidu-recording:2.9.0 Docker image (350MB aprox)
[INFO] 2020-05-22 14:59:14,376 [main] io.openvidu.server.recording.service.RecordingManager - Initializing recording paths
[INFO] 2020-05-22 14:59:14,378 [main] io.openvidu.server.recording.service.RecordingManager - OpenVidu Server has write permissions on recording path: /home/test/Videos
[INFO] 2020-05-22 14:59:14,990 [main] io.openvidu.server.recording.service.RecordingManager - Kurento Media Server has write permissions on recording path: /home/test/Videos
[INFO] 2020-05-22 14:59:14,997 [main] io.openvidu.server.recording.service.RecordingManager - OpenVidu Server has write permissions over files created by Kurento Media Server
[INFO] 2020-05-22 14:59:14,997 [main] io.openvidu.server.recording.service.RecordingManager - Recording path successfully initialized at /home/test/Videos
[WARN] 2020-05-22 14:59:15,012 [main] io.openvidu.server.coturn.CoturnCredentialsService - No COTURN server is installed in the host machine. Response: /bin/sh: 1: turnadmin: not found
[ERROR] 2020-05-22 14:59:15,012 [main] io.openvidu.server.coturn.CoturnCredentialsService - No COTURN server will be automatically configured for clients
[INFO] 2020-05-22 14:59:15,047 [main] io.openvidu.server.core.SessionManager - Garbage collector for non active sessions initialized. Running every 900 seconds and cleaning up non active Sessions more than 3600 seconds old
[INFO] 2020-05-22 14:59:15,124 [main] org.springframework.scheduling.concurrent.ThreadPoolTaskScheduler - Initializing ExecutorService 'jsonrpcTaskScheduler'
[INFO] 2020-05-22 14:59:15,405 [main] org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor - Initializing ExecutorService 'applicationTaskExecutor'
[INFO] 2020-05-22 14:59:15,618 [main] org.springframework.boot.autoconfigure.web.servlet.WelcomePageHandlerMapping - Adding welcome page: class path resource [static/index.html]
[INFO] 2020-05-22 14:59:15,982 [main] org.springframework.security.web.DefaultSecurityFilterChain - Creating filter chain: any request, [org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter@2053d869, org.springframework.security.web.context.SecurityContextPersistenceFilter@10163d6, org.springframework.security.web.header.HeaderWriterFilter@306f16f3, org.springframework.web.filter.CorsFilter@6dc17b83, org.springframework.security.web.authentication.logout.LogoutFilter@223aa2f7, org.springframework.security.web.authentication.www.BasicAuthenticationFilter@2b48a640, org.springframework.security.web.savedrequest.RequestCacheAwareFilter@15bbf42f, org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter@247d8ae, org.springframework.security.web.authentication.AnonymousAuthenticationFilter@7a419da4, org.springframework.security.web.session.SessionManagementFilter@22e357dc, org.springframework.security.web.access.ExceptionTranslationFilter@1a4013, org.springframework.security.web.access.intercept.FilterSecurityInterceptor@3fb1549b]
[INFO] 2020-05-22 14:59:16,099 [main] org.apache.coyote.http11.Http11NioProtocol - Starting ProtocolHandler ["https-jsse-nio-0.0.0.0-443"]
[INFO] 2020-05-22 14:59:16,880 [main] org.springframework.boot.web.embedded.tomcat.TomcatWebServer - Tomcat started on port(s): 443 (https) with context path ''
[INFO] 2020-05-22 14:59:16,882 [main] io.openvidu.server.OpenViduServer - Started OpenViduServer in 6.3 seconds (JVM running for 9.776)
[INFO] 2020-05-22 14:59:16,883 [main] io.openvidu.server.OpenViduServer - 

----------------------------------------------------

   OpenVidu is ready!

**Comment by pabloFuente** [comment]
That's not 2.14.0, is it?

**Comment by gomez34** [comment]
It is 2.13.0

**Comment by pabloFuente** [comment]
Also, you are not following the official instructions, as I see that the port Tomcat is listenting to is 443, and in any official OpenVidu deployment that port is different. Also, I see you are trying to deploy in a different path than the recommended one /opt/openvidu, which may more difficult to manage in any future administration procedure.

Until you deploy following the official instructions I'm afraid I won't be able to help you. I think it could be simplu a permission problem. Try giving more permissions to opt/openvidu/cdr folder
