### ISSUE TITLE
How to disable tls 1.0 and tls 1.1 with OpenVidu

### ISSUE THREAD

**Issue by AustinRSellers** [OpenVidu/openvidu#486]
How to disable tls 1.0 and tls 1.1 with OpenVidu? Ive tried in the jdk java.security file with no luck.

Thx guys

**Comment by micaelgallego** [comment]
Can you describe what are you trying to do? Just use http instead of https?

**Comment by AustinRSellers** [comment]
I need to disable TLS Protocol versions 1.0 and 1.1.
Im using this resource to test the status: https://www.cdn77.com/tls-test
and this is my openvidu installation: "https://subdomain.domain.com:4443".

I was able to disable it in my front end openvidu: "https://subdomain.domain.com" with apache2 with this resource: https://www.digitalocean.com/community/questions/disable-old-tls-versions-1-0-1-1-for-apache-nginx-on-ubuntu-18-04-or-centos-7

The purpose is to make it compliant with my security compliance report for vulnerabilities.
If you want my actual installation(domain for openvidu) i can email it to you. 

Im not sure if i explained that well enough so let me know if you need anything.

Thanks, Austin

**Comment by micaelgallego** [comment]
I understand now.

OpenVidu Server is a SpringBoot application using Tomcat under the hood. You should take a look to how to disable it with those technologies.

**Comment by AustinRSellers** [comment]
Okay, i will look into this and let you know if i find anything

**Comment by AustinRSellers** [comment]
Okay, found it: 
server.ssl.enabled-protocols=TLSv1.2

Here is the option to add when executing the jar file: -Dserver.ssl.enabled-protocols=TLSv1.1,TLSv1.2
