### ISSUE TITLE
2.14 Deployment Issue On Premise Deployment

### ISSUE THREAD

**Issue by praveen732** [OpenVidu/openvidu#487]
Hi Team,

With the latest 2.14 release we were able to see remote videos of users with in network

But media of users outside the network are not getting displayed

We provided public IP(NAT) to our server and opened all required ports on our firewall

Token is getting released to external users but media is not transmitted

Kindly help us in this regard

**Comment by pabloFuente** [comment]
GitHub issues is not for support question. Use the public forum for that: https://openvidu.discourse.group/
