### ISSUE TITLE
Getting OpeningHandshakeException while using OpenVidu 2.0.0

### ISSUE THREAD

**Issue by zzzykf** [OpenVidu/openvidu#49]
The status code of the opening handshake response is not '101 Switching Protocols'. The status line is: HTTP/1.1 404 

I'm using openvidu-android-app to access the OpenVidu Server 2.0.0, I've changed the port to 4443 in the android app but it shows that error.
It works fine by using OpenVidu Server 1.9.0 (port 8443).

Is there any other configurations need to be changed in the android app other than the port number?

**Comment by zzzykf** [comment]
What I did was to clone the latest release repository, run mvn install and run openvidu-server with mvn compile exec:java

For the app, I'm using openvidu-android-app and only changed the port number from 8443 to 4443. 
Do I need to change anything else in the openvidu-android-app in order to use 2.0.0 OpenVidu Server?

**Comment by pabloFuente** [comment]
Yeah, thinking about it there's one more change for your particular case. Change `/room` for `/openvidu` in every websocket url of your app. That may be the problem

**Comment by zzzykf** [comment]
Thank you very much, that issue has been solved :+1: 

But there is another issue now, the two participants unable to receive each other's video.
I think this issue is that i need to make so some changes to the app. I'll try to figure it out first. Thank you :)
