### ISSUE TITLE
400 error on signal of chat implementation openvidu

### ISSUE THREAD

**Issue by designerprasan007** [OpenVidu/openvidu#492]
**Describe the bug**
A few words describing what the bug is.
POST https://dev.conitor.in:4443/api/signal 400
getting error of 400 when trying to make signaling 
**Expected behavior**
Want to implemet the chat feature of openvidu
**Wrong current behavior**
A clear and concise description of what is actually happening instead of the expected behavior.
as i followed the openvidu docs of rest api https://docs.openvidu.io/en/2.12.0/reference-docs/REST-API/ i found some usefull thing about chatting system so tried to implement that but getting 400 error
**OpenVidu tutorial where to replicate the error**
This is an EXTREMELY IMPORTANT STEP. If we are able to replicate the error in any of the official [OpenVidu Tutorials](https://github.com/OpenVidu/openvidu-tutorials) or [OpenVidu Demos](https://github.com/OpenVidu), then we will be able to quickly fix it. If you are getting the error in your own application, please try to add the necessary changes to the most similar tutorial so it fails with the same error (try to keep those changes as contained as possible, so that the original tutorial maintains its integrity). Once you have an application to replicate the error, explain in detail the steps to get it like this:
1. Clone repository [...]
2. Compile the application like this [...]
3. Run OpenVidu Server like this [...]
4. Run the application like this [...]
5. Join 1 user... Publish a video stream [...]
6. See error

**OpenVidu deployment info**
How is your OpenVidu Server instance deployed when you get the bug. A couple of possible examples are listed below:
- Docker container as explained in OpenVidu tutorials, run with command `docker run ...` on macOS Catalina 10.15.1
- AWS deployment as explained in OpenVidu Docs (https://docs.openvidu.io/en/stable/deployment/deploying-aws/)

> **IMPORTANT NOTE**: please, if you think the bug might be related to OpenVidu Server side, specify here if you are also getting the error by using OpenVidu Server Demos instance. This instance is publicly available (use it only for this test, because it is not secure!!!): **URL**: `https://demos.openvidu.io:4443`, **SECRET**: `MY_SECRET`

**Client device info (if applicable)**
Describe the client device(s) or platform(s) where you are able to replicate the error. For example:
- Chrome 78.0.3904.97 (Official Build) (64-bit) on Windows 10 (1903).
- Firefox Mobile 68.2.0 running on OnePlus 6 with Android 9.

**Screenshots**

**Additional context**
Add any other context about the problem here. For example, attach any useful logs related to the issue.

here i'm attaching my code of signaling
` signal(sessionId).then(token => {
		session.connect(token)
		.then(() => {
			var path = (location.pathname.slice(-1) == "/" ? location.pathname : location.pathname + "/");
			window.history.pushState("", "", path + '#' + sessionId);
			session.signal({
						session : Session,
			      data: 'My custom message',  // Any string (optional)
			      to: [],                     // Array of Connection objects (optional. Broadcast to everyone if empty)
			      type: 'my-chat'             // The type of message (optional)
			    })
			    .then(() => {
			        console.log('Message successfully sent');
			        alert('Message successfully sent');
			    })
			    .catch(error => {
			        console.error(error);
			    });

			  	session.on('signal:my-chat', (event) => {
		    console.log(event.data); // Message
		    console.log(event.from); // Connection object of the sender
		    console.log(event.type); // The type of message ("my-chat")
		});  
			});
	})`

and here is my ajax call to the server

`function signal(sId){
	return new Promise((resolve, reject) => {
		console.log(sId, "this is sid from signal");
		console.log(session, "this is sid from signal");
		$.ajax({
			type: "POST",
			url: OPENVIDU_SERVER_URL + "/api/signal",
			data: JSON.stringify({ customSessionId: sId }),
			headers: {
				"Authorization": "Basic " + btoa("OPENVIDUAPP:" + OPENVIDU_SERVER_SECRET),
				"Content-Type": "application/json"
			},
			success: response => resolve(response.id, 'seresadasdasdasd'),
			error: (error) => {
				if (error.status === 409) {
					resolve(sId);
				} else {
					console.warn('No connection to OpenVidu Server. This may be a certificate error at ' + OPENVIDU_SERVER_URL);
					if (window.confirm('No connection to OpenVidu Server. This may be a certificate error at \"' + OPENVIDU_SERVER_URL + '\"\n\nClick OK to navigate and accept it. ' +
						'If no certificate warning is shown, then check that your OpenVidu Server is up and running at "' + OPENVIDU_SERVER_URL + '"')) {
						location.assign(OPENVIDU_SERVER_URL + '/accept-certificate');
					}
				}
			}
		});
	})
}
`

waiting for response thank you.

**Comment by MrCrayon** [comment]
Error 400 suggests you are not sending the right parameters.
Your code is quite hard to read but it looks like you are sending only  `data` that is an optional parameter.
Have a look at the documentation you linked above.

I also hope this is just a test because you shouldn't be using REST API client side.

**Comment by pabloFuente** [comment]
Thank you for your response, @MrCrayon 
Yes, check the documentation, as it clearly says that a `400` status response in POST /api/signal is a problem with some body parameter: https://docs.openvidu.io/en/2.14.0/reference-docs/REST-API/#post-apisignal

**Comment by designerprasan007** [comment]
hi OpenVidu/openvidu i saw that
https://docs.openvidu.io/en/2.14.0/reference-docs/REST-API/#post-apisignal and
written as it is only as i shown in my code at github issue. i'm bit
confused about for what part i'm getting 400 error. i had passed
"type","to","session", and "data" too. but still why 400?

**Comment by designerprasan007** [comment]
can u please provide any ajax call of chat message. i understood where the
mistake is but not sure about ajax call function for chat.

**Comment by MrCrayon** [comment]
I think this is not the right place to ask for support, you should go to https://openvidu.discourse.group/

Anyway you do NOT use or even need REST API for client side calls that's only if you want to send a signal from your server.

It's all in docs:
https://docs.openvidu.io/en/2.14.0/cheatsheet/send-messages/
