### ISSUE TITLE
OpenVidu kurento server OpenVidu 2.12.0

### ISSUE THREAD

**Issue by matrad4307** [OpenVidu/openvidu#493]
Hi,
at fews days I have problem with my OpenVidu application. I gen many erros. I nothing changed. Please look at te screenshot.

I can connect but I can't see any person connected to the same session

<img width="1252" alt="Zrzut ekranu 2020-06-4 o 22 08 08" src="https://user-images.githubusercontent.com/18301195/83805304-ec2bc300-a6af-11ea-86a3-8f2fb01f15b9.png">
<img width="1247" alt="Zrzut ekranu 2020-06-4 o 22 08 00" src="https://user-images.githubusercontent.com/18301195/83805315-f057e080-a6af-11ea-847c-cb540656a502.png">
<img width="588" alt="Zrzut ekranu 2020-06-4 o 22 07 53" src="https://user-images.githubusercontent.com/18301195/83805318-f0f07700-a6af-11ea-9462-4ce7e197f0fe.png">
<img width="1231" alt="Zrzut ekranu 2020-06-4 o 22 07 43" src="https://user-images.githubusercontent.com/18301195/83805319-f1890d80-a6af-11ea-9c8f-cb6754f9054e.png">

**Comment by micaelgallego** [comment]
Please update to latest 2.14 version as some bugs have been fixed.

Please reopen if you found the problem again
