### ISSUE TITLE
Automatic stop is not cancelled after user returns to a session

### ISSUE THREAD

**Issue by TBorgert** [OpenVidu/openvidu#496]
**Describe the bug**
Automatic stop is not cancelled after user returns to the session.

**Expected behavior**

 If a user publishes within the timeout,  the automatic stop of the recording is cancelled

**Wrong current behavior**

Im using 120 seconds timeout = OPENVIDU_RECORDING_AUTOSTOP_TIMEOUT=120

Two participantes entered at session "sessionId":"Sala201", at 16:59:06, the countdown to stop record has started:

 openvidu-server_1  | [INFO] 2020-06-08 16:59:06,370 [SessionHandler-9r1j9ilel0s0mcqftjb9jfi0vb-e4-t0] io.openvidu.server.kurento.core.KurentoSessionManager - Last participant left. Starting 120 seconds countdown for stopping recording of session Sala201

The participant joined again publishing video at 16:59:30:

openvidu-server_1  | [INFO] 2020-06-08 16:59:30,032 [SessionHandler-32rs7f2cfuh1hogo4jd1ogefe-e10-t0] io.openvidu.server.cdr.CDRLoggerFile - {"participantJoined":{"sessionId":"Sala201","timestamp":1591635570032,"participantId":"con_RRFkqJCN0i","location":"unknown","platform":"Chrome 83.0.4103.97 on Windows 10 64-bit","clientData":"{\"nome\":\"Nome Alterado\",\"interno\":true,\"participanteId\":\"8\",\"salaParticipanteId\":433,\"moderador\":true,\"apresentador\":true,\"justScreenShare\":false,\"acessoLink\":false}","serverData":""}}
openvidu-server_1  | [INFO] 2020-06-08 16:59:30,198 [SessionHandler-32rs7f2cfuh1hogo4jd1ogefe-e10-t0] io.openvidu.server.rpc.RpcHandler - Participant con_RRFkqJCN0i is calling method 'publish' in session Sala201
openvidu-server_1  | [INFO] 2020-06-08 16:59:30,211 [SessionHandler-32rs7f2cfuh1hogo4jd1ogefe-e10-t0] io.openvidu.server.kurento.core.KurentoParticipant - PARTICIPANT con_RRFkqJCN0i: Request to publish video in room Sala201 (sdp type OFFER)
openvidu-server_1  | [INFO] 2020-06-08 16:59:30,218 [SessionHandler-32rs7f2cfuh1hogo4jd1ogefe-e10-t0] io.openvidu.server.kurento.core.KurentoParticipant - PARTICIPANT con_RRFkqJCN0i: Is now publishing video in room Sala201

At 17:01:06, session is stopped automatically (even though I returned to the session and broadcasting video):

openvidu-server_1  | [INFO] 2020-06-08 17:01:06,371 [pool-1-thread-1] io.openvidu.server.recording.service.RecordingManager - Stopping recording Sala201 after 120 seconds wait (no publisher published before timeout)
openvidu-server_1  | [INFO] 2020-06-08 17:01:06,372 [pool-1-thread-1] io.openvidu.server.recording.service.RecordingManager - Automatic stopping recording Sala201. There are users connected to session Sala201, but no one is publishing

**OpenVidu deployment info**
Aws deploy Openvidu 2.14

**Additional context**
[Openvidu-server-logs-autostop-rec.txt](https://github.com/OpenVidu/openvidu/files/4747540/Openvidu-server-logs-autostop-rec.txt)

**Comment by pabloFuente** [comment]
Hi,

I see your session is configured with recording mode ALWAYS. We've detected a bug that makes the automatic stop cancelation only occur for MANUAL recording mode. This commit should take care of it: https://github.com/OpenVidu/openvidu/commit/d5b3b9dde7690a4444ac5dac24e0bc7224cc16d2

The fix will be available in the next release.

Thanks for reporting.
