### ISSUE TITLE
ReferenceError: cordova is not defined on Xiaomi MiUi browser. OV 2.14.0

### ISSUE THREAD

**Issue by wardhanster** [OpenVidu/openvidu#498]
**Describe the bug**
**ReferenceError** cordova is not defined on Xiaomi MiUi browser.

**Expected behavior**
Cordova & ionic check should not happen on a mobile browser, and even if it does it should factor in right failing mechanisms.

**Wrong current behavior**
It throws an exception when trying to access calls using Xiaomi MiUi browser

**OpenVidu deployment info**
openvidu-browser version: 2.11.0

**Client device info (if applicable)**
- MiuiBrowser 10.9.8 Running on Android 9

**Screenshots**
![Screenshot 2020-06-12 at 1 54 15 PM](https://user-images.githubusercontent.com/845209/84482526-8ba31400-acb5-11ea-91d3-61bb3bc73c87.png)

**Comment by micaelgallego** [comment]
Please update to 2.14 to check if problem still applies.

**Comment by wardhanster** [comment]
@micaelgallego confirmed it is still present in 2.14

**Comment by micaelgallego** [comment]
It seems WebRTC is not supported in Mi Browser: 

https://github.com/webrtc/samples/issues/1253

**Comment by wardhanster** [comment]
@micaelgallego that's true, what I was hopeing was for OV to fail gracefully since we rely on its internal method of checkSystemRequirements.
Although, I will check for possible loopholes on our code side.

**Comment by wardhanster** [comment]
It seems like `platform['isIonicAndroid'] ` is returning true for the MI browser on android leading to false positive of checkSystemRequirements. Because Cordova does not exist in the global scope.

**Comment by wardhanster** [comment]
`window.cordova={}` before initializing OV helped; I also ended up adding another layer of device compatibility test since the results of the original `checkSystemRequirements` is unreliable.
