### ISSUE TITLE
Cannot install Openvidu for development

### ISSUE THREAD

**Issue by mgochoa** [OpenVidu/openvidu#5]
When I get to the step where I have to make `/openvidu mvn compile -DskipTests=true`

I get the next error: 

> [INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for io.openvidu:openvidu:1.0.0-beta.1: Could not find artifact org.kurento:kurento-parent-pom:pom:6.6.1-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 5, column 10
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project io.openvidu:openvidu:1.0.0-beta.1 (/home/ubuntu/java/openvidu/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for io.openvidu:openvidu:1.0.0-beta.1: Could not find artifact org.kurento:kurento-parent-pom:pom:6.6.1-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 5, column 10 -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

I look for the package in Maven Central and erase the word _-SNAPSHOT_ in the pom, but I don't know if it is good idea.

**Comment by mgochoa** [comment]
I'm closing this issue. I was not taking in account this part of the docs [Adding kurento parent pom](https://github.com/OpenVidu/openvidu.io-docs/blob/master/docs/developing/index.md#adding-kurento-parent-pom-to-your-local-respository) on the openvidu.io-docs.

I think it should be specified in the actual README.md for this repository

**Comment by pabloFuente** [comment]
We are currently developing a web for OpenVidu platform. In the near future a complete, well ordered documentation will be available at openvidu.io.
