### ISSUE TITLE
OpenVidu Voice or Video not Showing

### ISSUE THREAD

**Issue by naveedaziz** [OpenVidu/openvidu#500]
I am using openvidu on AWS server and recently deployed. Sometimes voice/video wont show on either end. It mostly happens on IOS devices like iphone X or iphone XI. When we connect doctor and patient sometimes patient wont get video/audio and some times doctor wont get. Please guide as i am suffering from webrtc from last 3 months and at last i have landed over openvidu feeling that things will work smooth.

My demo server is https://v-3.bewell.pk and live one is https://m.bewell.pk

**Comment by pabloFuente** [comment]
Hi,

I'm sorry, but this is not the place to ask for support. GitHub Issues is designed to post possible bugs and detailed problems for us to fix.
I get you are having trouble, but the nature of your problems is not a right fit for the issue tracker. We don't have any detail of your deployment and more importantly, about your application and your user's networking.

You can open an entry in OpenVidu forum: https://www.google.com/url?sa=t&source=web&rct=j&url=https://openvidu.discourse.group/&ved=2ahUKEwj89ZOVppbqAhWQC2MBHXPcBSUQFjAAegQIBRAD&usg=AOvVaw0X6qhdG4t8d8aXG4ISccM6

Or if you are a Pro user and want to keep any details private, you can write us to pro.support@openvidu.io

Best regards.
