### ISSUE TITLE
OpenVidu Insecure ReactJS not working in In-App WebView

### ISSUE THREAD

**Issue by hazhayder** [OpenVidu/openvidu#503]
Hello,
We have been trying to implement just receive the streams from OpenVidu server on a webpage. This webpage is then wrapped in a React Native application in a WebView. The intended tasks works fine on Google Chrome but once joined from ReactNative Webviews we are not able to see any remote stream.

While app is running in WebView it is able to make a connection to server but doesn't subscribes to published streams.

**Comment by micaelgallego** [comment]
WebView in iOS doesn't have WebRTC support. 

To use OpenVidu in a react-native app, you will have to purchase commercial react-native support. Please contact with commercial@openvidu.io.

Regards
