### ISSUE TITLE
User agent on samsung devices closes the call 

### ISSUE THREAD

**Issue by pocce90** [OpenVidu/openvidu#504]
**Describe the bug**
A few words describing what the bug is.
Openvidu 2.14 is able now to work on samsung browser. This is partially true: if you use samsung browser on samsung device you will receive a notify (in openvidu dashboard) that says something like internet samsung (version 12) is not supported by openvidu. The same browser installed on my xiaomi device works well... **If i manually change user agent on samsung browser on samsung device it works!**

**Expected behavior**
using openvidu dashboard on samsung browser on samsung device will works good

**Wrong current behavior**
using openvidu dashboard on samsung browser on samsung device launch "Browser samsung internet (version 12.0) for android is not supported in openvidu

**OpenVidu tutorial where to replicate the error**
This is an EXTREMELY IMPORTANT STEP. If we are able to replicate the error in any of the official [OpenVidu Tutorials](https://github.com/OpenVidu/openvidu-tutorials) or [OpenVidu Demos](https://github.com/OpenVidu), then we will be able to quickly fix it. If you are getting the error in your own application, please try to add the necessary changes to the most similar tutorial so it fails with the same error (try to keep those changes as contained as possible, so that the original tutorial maintains its integrity). Once you have an application to replicate the error, explain in detail the steps to get it like this:
1. Clone repository [...]
2. Compile the application like this [...]
3. Run OpenVidu Server like this [...]
4. Run the application like this [...]
5. Join 1 user... Publish a video stream [...]
6. See error

1 Run OpenVidu Server Demo (https://demos.openvidu.io:4443) using samsung device with samsung browser
2 Try it
3 See error

**OpenVidu deployment info**
How is your OpenVidu Server instance deployed when you get the bug. A couple of possible examples are listed below:
- Docker container as explained in OpenVidu tutorials, run with command `docker run ...` on macOS Catalina 10.15.1
- AWS deployment as explained in OpenVidu Docs (https://docs.openvidu.io/en/stable/deployment/deploying-aws/)
- Docker container as explained in OpenVidu tutorials, run with command `docker run ...` on Ubuntu 16.04

> **IMPORTANT NOTE**: please, if you think the bug might be related to OpenVidu Server side, specify here if you are also getting the error by using OpenVidu Server Demos instance. This instance is publicly available (use it only for this test, because it is not secure!!!): **URL**: `https://demos.openvidu.io:4443`, **SECRET**: `MY_SECRET`

**Client device info (if applicable)**
Describe the client device(s) or platform(s) where you are able to replicate the error. For example:
- Chrome 78.0.3904.97 (Official Build) (64-bit) on Windows 10 (1903).
- Firefox Mobile 68.2.0 running on OnePlus 6 with Android 9.
Mozilla/5.0 (Linux; Android 9; SAMSUNG) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/12.0 Chrome/79.0.3945.136 Mobile Safari/537.36
**Screenshots**

**Additional context**
Add any other context about the problem here. For example, attach any useful logs related to the issue.

**Comment by CSantosM** [comment]
Check this post https://openvidu.discourse.group/t/samsung-web-browser-11-2-is-not-supported/1037/6

This will be solved on 2.15.0 release.
