### ISSUE TITLE
Error in iOS ionic app video display

### ISSUE THREAD

**Issue by anupzone** [OpenVidu/openvidu#505]
**iosrtc version - 6.0.11
iOS deployment target - 13.5
xcode version - 11.5
openvidu version in app - 2.14.0
openvidu version in backend - 2.13.0
platform - ionic 5
checking device - iPhone 11 pro max** 

**Error:**
Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKitCore/UIView.h> may also be helpful.
2020-07-08 15:54:54.287656+0530 PatientMD[5181:2197869] [LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
	(Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSAutoresizingMaskLayoutConstraint:0x2810f5220 h=--& v=--& UIView:0x106c6ae40.minY == 950   (active, names: '|':WKWebView:0x107823000'Doctor Dashboard' )>",
    "<NSLayoutConstraint:0x2810f4dc0 UIView:0x106c6ae40.top == UILayoutGuide:0x280a8e220'UIViewSafeAreaLayoutGuide'.top   (active)>",
    "<NSLayoutConstraint:0x2810d34d0 'UIViewSafeAreaLayoutGuide-top' V:|-(44)-[UILayoutGuide:0x280a8e220'UIViewSafeAreaLayoutGuide']   (active, names: '|':WKWebView:0x107823000'Doctor Dashboard' )>"
)

**getting blank screen in app. but subscriber can hear and view video of publisher. means camera and audio working properly. means streaming working properly from app but getting blank screen in app. even can not see subscribers video in app. I saw this issue in iosrtc latest bug. so you can confirm if you are also getting this issue or not.** 

https://github.com/cordova-rtc/cordova-plugin-iosrtc/issues/422

**working fine in safari browser in iPhone but not in app.**

**Comment by CSantosM** [comment]
Hi, 

First of all, 
We need that you test our [openvidu-ionic](https://docs.openvidu.io/en/2.15.0/tutorials/openvidu-ionic/) pointing to our environment development 

URL = https://demos.openvidu.io 
SECRET = MY_SECRET

We need to know if the bug is in your side or in ours.

I hope your feedback. 

Thanks

**Comment by anupzone** [comment]
Hi CSantosM,

I checked your demo app. it's working. but getting error in my app. Is this because of version mismatch or what?

Thanks

**Comment by CSantosM** [comment]
Thnak you. 

I don't know how you app is developed. 

Try update iosrtc to **6.0.12** and update  the OpenVidu stack (server and browser) to the last version **2.15.0**. **It's highly recommend to use the same client and server version.**

**Comment by hthetiot** [comment]
This error have no impact but would be nice if someone could help resolving them
- cordova-rtc/cordova-plugin-iosrtc#422
