### ISSUE TITLE
"sessionDisconnected" event loop

### ISSUE THREAD

**Issue by rfazi** [OpenVidu/openvidu#506]
**Describe the bug**
**sessionDisconnected** event is called in loop if inside the event handler the **session.disconnect**() method is called.

**Expected behavior**
I suggest that **sessionDisconnected** event is not fired if the event was already fired.

**Wrong current behavior**
If by mistake the **session.disconnect()** method is called inside the **sessionDisconnected** event handler, the **sessionDisconnected** event is fired every time and a loop started even though the event has already been fired. This causes a browser crash.

**OpenVidu tutorial where to replicate the error**
On browser, js code:
```
session.on('sessionDisconnected', (event) => {
	session.disconnect();
});
```

**Comment by CSantosM** [comment]
Hi @rfazi ,

I underestand your issue but the `sessionDisconnected` event is fired when a local user has lefft the session. 
**Invoking to session.disconnect method inside of this event lifecycle don't really make sense.** 

I don't think this is an openvidu issue.

**Comment by pabloFuente** [comment]
You are probably right about the idea that OpenVidu should avoid any kind of possible infinite loop. But what @CSantosM says is also true: calling `session.disconnect()` as result of receiving `sessionDisconnected` event is just a senseless paradox. In no situation you should do that.
