### ISSUE TITLE
Camera not closed on session disconnect

### ISSUE THREAD

**Issue by dhavalsolankislk** [OpenVidu/openvidu#511]
Hello,
We are using open vidu in our application. We are facing issue that when we are closing or stopping the call camera is not remains open.
We are using open vidu version 14
On disconnection of call we have written the below code
    if(this.session) {
      this.session.disconnect();
    }
    
    delete this.publisher;
    delete this.session;
    delete this.OV;

Our camera gets closed only if we close the browser or browser tab

**Comment by dhavalsolankislk** [comment]
Any update

**Comment by sreedharbukya** [comment]
@dhavalsolankislk , I guess client should triggering event to close the camera in this case.

**Comment by CSantosM** [comment]
Hello, test if this happens in any of our demos please

**Comment by dhavalsolankislk** [comment]
Hello  @CSantosM 
I tested in you demo. It is working properly in your demo

**Comment by CSantosM** [comment]
Ok, so it is not a openvidu bug. It looks like that the bug is in your side. 

Please, read the all related post in OpenVidu forum and post your question or problem if you don’t find the solution before. 

You will have an extra media stream track opened in your code. 

Cheers
