### ISSUE TITLE
How to auto renew the ssl of aws cloudformation

### ISSUE THREAD

**Issue by maxifjaved** [OpenVidu/openvidu#52]
My SSL is expired after a period how do i renew this automatically

![screenshot from 2018-05-16 19-41-14](https://user-images.githubusercontent.com/17304812/40125001-3978c19c-5943-11e8-8857-cf1b2afba717.png)

**Comment by maxifjaved** [comment]
I manually sorted out this by running the following commands but it should be automated.

```
sudo add-apt-repository ppa:certbot/certbot
sudo apt-get update
sudo apt-get install python-certbot-nginx
sudo certbot --nginx -d YOUR_DOMAIN_NAME
```

**Comment by nordri** [comment]
Hi @maxifjaved 
To renew the certificate just log into the instance and run
`$ sudo /usr/bin/letsencrypt renew`
If you want to automatically renew, run
`$ sudo crontab -e`
which will open an editor, and add the following line
`0 0 * * * /usr/bin/letsencrypt renew `

We've added the crontab stanza now.

Thanks for let us know this issue!
Cheers
