### ISSUE TITLE
Webhook not working if configured as empty array.

### ISSUE THREAD

**Issue by TBorgert** [OpenVidu/openvidu#521]
**Describe the bug**
Webhook not working if setted as this: 

**# List of events that will be sent by OpenVidu Webhook service**
**# Leave blank if all events.**
OPENVIDU_WEBHOOK_EVENTS=[]

**Expected behavior**
Webhook working if configured like OPENVIDU_WEBHOOK_HEADERS=[], By default this property is an empty array (no headers).

**Wrong current behavior**
OPENVIDU_WEBHOOK_EVENTS=[] **(that way is not working)**

OPENVIDU_WEBHOOK_EVENTS=sessionCreated,sessionDestroyed,participantJoined,participantLeft,webrtcConnectionCreated,webrtcConnectionDestroyed,recordingStatusChanged,filterEventDispatched,mediaNodeStatusChanged] **(that way is working)**

**OpenVidu deployment info**
Ubuntu 20.04 - On premisses at AWS - OV 2.15

**Comment by pabloFuente** [comment]
Well, this might simply be a bad choice of words for commentary

`# Leave blank if all events.`

This does not mean that the array is left empty, but that the default value is not changed. As you can see in openvidu docs, default value is all available events: https://docs.openvidu.io/en/latest/reference-docs/openvidu-config/

We will change that commentary to make it clearer.
