### ISSUE TITLE
Getting 401 Error when using STOP rest api in 2.14

### ISSUE THREAD

**Issue by surya5353** [OpenVidu/openvidu#523]
Hi Team,
Same issue in 2.14 also.
Getting 401 Error when using STOP rest api, its happening only in 2.14.0 and 2.13.0 version only. When i rollback to 2.11.0 its working fine.

![image](https://user-images.githubusercontent.com/6995567/80272081-fc7d7500-86e3-11ea-9d7c-11026436e9c6.png)

Used API.
https://docs.openvidu.io/en/2.13.0/reference-docs/REST-API/#post-apirecordingsstopltrecording_idgt

Cans please share the stop api custom function in github.

see my code below
**recStop(recStage) {
        this.concludeType = recStage;
        this.concludemeeting = true;
        const options = {
            headers: new HttpHeaders({
                Authorization:
                    "Basic " +
                    btoa("OPENVIDUAPP:" + environment.OPENVIDU_SERVER_SECRET),
                "Content-Type": "application/x-www-form-urlencoded"
            })
        };
        let stopSessionId = this.concludeType == 1 ? this.mySessionId : this.mySessionId + "-1";
        return this.httpClient
            .post(
                environment.OPENVIDU_SERVER_URL +
                "recordings/stop/" + stopSessionId, options
            )
            .subscribe(
                response => {
                    if (this.concludeType == 1) {
                        this.recStart(2);
                        //this.onMuteAll();
                    } else {
                        this.concludeType = recStage;
                        this.gs.onEndMeeting(this.gs.ovSessionDetails.mDetails).subscribe(
                            (res: any) => {
                                if (!res.error) {
                                    this.ts.success(custommessage.mommessage);
                                    this.leaveSession();
                                    setTimeout(() => {
                                        //this.router.navigate(['/meetings']);
                                        location.reload();
                                    }, appConfig.time4s);
                                }
                            },
                            error => {
                                console.error(error.error);
                            }
                        );
                    }
                },
                () => { }
            );
	}**

**Comment by CSantosM** [comment]
Reopen this issue If you still have the problem
