### ISSUE TITLE
IP camera video not loading 

### ISSUE THREAD

**Issue by dhavalsolankislk** [OpenVidu/openvidu#524]
Hello,

We are using open vidu in our application. Our open vidu version is 2.14.0. IP camera gets added to the session and also subuscribed but video is not playing. The rtsp link we are passing is working perfectly in vlc player. But not working in browser

**Comment by CSantosM** [comment]
Please,

1. Update your OpenVidu stack to the laste version (2.15.0 rigth now)
2. Check OpenVidu Forum for problems developing your own app requiremens. The issue tracker is only for OpenVidu bugs.
2. If you think that is an OpenVidu bug, reopen the issue by filling in all the fields described in the issue template if you still have the problem.
