### ISSUE TITLE
Browser Safari (version 8+) for iOS is not supported in OpenVidu

### ISSUE THREAD

**Issue by pradeepmdk** [OpenVidu/openvidu#526]
ios not working on OpenVidu

**Comment by pabloFuente** [comment]
iOS is working in OpenVidu.
Do not delete the issue template. If you want to report a proper issue, fill all of the template details for us to replicate the error.
Detail the exact iOS device, iOS version and Safari version in which you are experiencing the issue.
Explain in which demo of demos.openvidu.io you can see the problem. We need more information to know if there is a problem and if so, to fix it.

**Comment by JimmyKing18** [comment]
I am having the same issue. I had it working fine yesterday.

**Comment by CSantosM** [comment]
Which version are you using?

**Comment by JimmyKing18** [comment]
> Which version are you using? Are you testing the 2.15.1-alpha2 ?

Correct. I found the issue pertains to the iOS device. I was using an older iPod with < Safari 13.0 causing the issue
