### ISSUE TITLE
gitter.im chat for developers

### ISSUE THREAD

**Issue by sandeep048** [OpenVidu/openvidu#53]
Kindly create a room for openvidu developers in [gitter.im](https://gitter.im) which will encourage discussion among community and improve the software. There is no necessity for the core developers to be present but people who are familiar with the API can provide quick help.

**Comment by talentedandrew** [comment]
+1

**Comment by pabloFuente** [comment]
Done. Here you have the gitter.im community for OpenVidu:

https://gitter.im/OpenVidu-WebRTC
