### ISSUE TITLE
`getLocalStreams` deprecated in firefox

### ISSUE THREAD

**Issue by m-alexander** [OpenVidu/openvidu#54]
I get the following warning when running this library in firefox when use `publisher.publishAudio`:

```
RTCPeerConnection.getLocalStreams/getRemoteStreams are deprecated.
Use RTCPeerConnection.getSenders/getReceivers instead.
```
And `publisher.publishAudio` stops working when I try to remove/add tracks to mediastream

**Comment by pabloFuente** [comment]
We are aware of the Firefox deprecation warning about RTCPeerConnection API. Working on it. 

Regarding dynamic addition and removal of MediaStream objects, OpenVidu doesn't officially support this kind of behaviour (Kurento Media Server may be in trouble). You can try it on your own, but we only officialy support the [API](https://openvidu.io/api/openvidu-browser/) operations.

**Comment by romandragan** [comment]
+1

**Comment by pabloFuente** [comment]
Already fixed in development 'master' branch of OpenVidu/openvidu (openvidu-browser folder) with commit e456b5e3503cbe3be1105ab79e238f8c4a98223e
