### ISSUE TITLE
Documentation improvement: OPENVIDU_SECRET

### ISSUE THREAD

**Issue by rfazi** [OpenVidu/openvidu#541]
In documentation we found that: 

OPENVIDU_SECRET | Secret used to connect to OpenVidu Server. This value is required when using the REST API or any server client (openvidu-java-client, openvidu-node-client), as well as when connecting to openvidu-server dashboard
-- | --

Well, we set the secret by inserting special characters such as the question mark and all works well.
Later we decided to implement the registration and here the problems started because on the test server it worked but it didn't work on the production server. The only difference was in the secret key which has no special characters on the test server.
We understood that the recording to work simulates a browser by calling an openvidu API GET and in the same API the credentials for the openvidu dashboard are entered and here the problem arises: the question mark breaks the url and openvidu records what you can see in the attachment.
![2020-09-21_15_08_20](https://user-images.githubusercontent.com/9641390/93813803-eaccd900-fc53-11ea-8a50-2992d32bcc30.gif)
Please specify better in the documentation that the secret key must not contain these special characters or at least if you can encode the key in url it would be better. Thank you

**Comment by banagale** [comment]
This should probably be filed [here](https://github.com/OpenVidu/openvidu.io-docs/issues).

**Comment by pabloFuente** [comment]
We'll be addressing this problem for the next release. Actually the recording container is not the only service that can be affected by special characters in OpenVidu Secret, but also other services may fail. We will make very clear in the documentation what chars are allowed in OPENVIDU_SECRET, and also check the property in the server to directly fail in launch time if the format is not fulfilled.

**Comment by pabloFuente** [comment]
A fix is already commited into master branch 99cd6d2f9ce7120547fb9aa9afa18c68b79f34a9
