### ISSUE TITLE
Stream to OpenVidu & Kurento from prog by RTP, WebRTC

### ISSUE THREAD

**Issue by Monkheim** [OpenVidu/openvidu#543]
Good afternoon, guys!

We have some problems and didn't know that to do. Learned all information from site but no result. 
By the way, we develop a program (C/C++) that can get linux video device and stream it on Kurento through OpenVidu in some session. What subscribers can view in the web by browser. We done this task but with errors. When we push or pull stream from/to ov kurento, the picture shows with artefacts (grey, green or others). First of all, we use rtp to deliver video (artefacts). Then we rebuild all and use native webrtc to communicate with OV, same result. If we use only browsers, all is ok. no problem.  

Next step was to use alternative soft, janus as webrtc gateway. We stream to janus and from it by webrtc stream to kurento. And same way back. But same result. But! When we use only janus, stream from our soft to janus, and get it back to linux as loopback all is ok! But we want to use your software. Please, help us with it. We can give you all additional information. 
We read all info from your sites of OV & Kurento...

We use:
ov - 2.15
kurento - 6.14
ubuntu 18.04.4
All installed native without docker.

It will be great if you can help us. Maybe some ifo or advices how to debug it and understand where problem.

**Comment by mihailj** [comment]
Hello,

What you are describing above is not an issue with OpenVidu server, please use the https://openvidu.discourse.group/ forum. We can discuss there in detail, I've successfully published video with RTSP (IPCAM) to OpenVidu. Had some issues with artifacts also using UDP, solved by changing the RTSP server to TCP. :wink: 

Regards,
Mihail

**Comment by Monkheim** [comment]
Mihail, thank you a lot! 
I'll try to create new ticket there. I have no problem with publication ipcam to openvidu too. 
Hope, somebody help me. Want to use your soft
