### ISSUE TITLE
Stream is stopped after sometime

### ISSUE THREAD

**Issue by abhi021** [OpenVidu/openvidu#547]
Getting following message on openvidu-server: 

[INFO] 2020-10-01 11:11:53,845 [Timer-1319] io.openvidu.server.kurento.core.KurentoSession - Resetting process: closing media pipeline for active session 65e46f4b-63ea-48bb-a227-b647627d6da4
[INFO] 2020-10-01 11:11:53,883 [tExec-e2-t14578] io.openvidu.server.kurento.core.KurentoSession - Resetting process: media pipeline closed for active session 65e46f4b-63ea-48bb-a227-b647627d6da4
[INFO] 2020-10-01 11:11:53,883 [tExec-e2-t14578] io.openvidu.server.kurento.core.KurentoSession - SESSION 65e46f4b-63ea-48bb-a227-b647627d6da4: Creating MediaPipeline
[INFO] 2020-10-01 11:11:53,982 [tExec-e2-t14578] io.openvidu.server.kurento.core.KurentoParticipant - Resetting publisher endpoint for participant con_CQ6wHxRioW
[INFO] 2020-10-01 11:11:53,982 [tExec-e2-t14578] io.openvidu.server.kurento.core.KurentoSession - Resetting process: media pipeline created and publisher endpoints reseted for active session 65e46f4b-63ea-48bb-a227-b647627d6da4

because of which video stream goes blank.

**Comment by pabloFuente** [comment]
Please, do not delete the issue template. It is there make everything easier. Without it it is much more complicated to help foxing possible issues.

Please, edit your previous post to include the default template.
