### ISSUE TITLE
Error in wss:// url handling

### ISSUE THREAD

**Issue by rwdim** [OpenVidu/openvidu#549]
File: /src/main/java/io/openvidu/server/config/OpenviduConfig.java:878
`
			if (!uri.startsWith("ws://") || uri.startsWith("wss://")) {
`
Should be:
`
			if (!uri.startsWith("ws://") && !uri.startsWith("wss://")) {
`
Code a few lines below clearly shows wss:// is a valid prefix, and the line above stops it from being able to be used.

**Comment by pabloFuente** [comment]
You are right, nothing happened because OpenVidu is prepared to connect to Kurento throuhg plain WS, so the second part of the condition never came into play. But that is already fixed in https://github.com/OpenVidu/openvidu/issues/549
