### ISSUE TITLE
How to proxy OpenVidu from Nginx correctly?

### ISSUE THREAD

**Issue by sandeep048** [OpenVidu/openvidu#55]
This is my nginx config which is acting as a websocket proxy to openvidu using url rewriting.

Majority users in our setup are under corporate firewall and can only access port 443 and 80. They cannot connect to websocket port 4443 hence need the proxy redirection. 

My first question is can we run openvidu without SSL since nginx is terminating ssl anyway? -> I suspect this configuration will be slightly faster.

Secondly can we use a config similar to the following? I don't have it working. Getting HTTP 409 error. 

proxy_pass https://127.0.0.1:4443; 
OR 
proxy_pass https://webrtc.vu2vu.org:4443;

```
server {
  server_name webrtc.vu2vu.org;
  root /srv/openvidu-tutorials/openvidu-insecure-js/web;

  location /mediaserver {
    rewrite /mediaserver(.*) /$1 break;
    proxy_pass https://webrtc.vu2vu.org:4443;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
  }

  listen 443 ssl;
  ssl_certificate /root/fullchain.pem;
  ssl_certificate_key /root/privkey.pem;
}

server {
  if ($host = webrtc.vu2vu.org) {
    return 301 https://$host$request_uri;
  }

  listen 80;
  server_name webrtc.vu2vu.org;
  return 404;
}
```

![image](https://user-images.githubusercontent.com/500899/40236391-07394a88-5acb-11e8-9e52-05b6ce004444.png)

**Comment by sandeep048** [comment]
app.js is modified appropriately for insecure-js demo as follows
`url: "https://webrtc.vu2vu.org/mediaserver/api/sessions"`

**Comment by pabloFuente** [comment]
409 error in `/api/sessions` simply means that you already have a session "vu2vu" initialized in your OpenVidu Server, as documented [here](https://openvidu.io/docs/reference-docs/REST-API#post-apisessions) in "HTTP Responses" section. But you have succesfully connected to your OpenVidu Server.

You can run openvidu-server without ssl very easily. Just add this configuration parameter on your launching command: 

`server.ssl.enabled=false`

If you want to change the port it is as easy as adding

`server.port=8888`

**Comment by sandeep048** [comment]
Is my nginx proxy config correct?

**Comment by sandeep048** [comment]
Running on another port like 8888 is also not feasible since users under firewall can only access port 80 and 443 of the media server.

**Comment by sandeep048** [comment]
Do we have any architectural diagram of openvidu? All the media streams flow from browser through openvidu to kurento media server?

**Comment by pabloFuente** [comment]
All media streams flow [ from clients to Kurento Media Server / from Kurento Media Server to clients ]

**Comment by Dem0n3D** [comment]
@pabloFuente why option `server.ssl.enabled=false` isn't documented?
