### ISSUE TITLE
Video filters not working

### ISSUE THREAD

**Issue by sabrimev** [OpenVidu/openvidu#551]
Trying to make a video filter on my React Native stream but receiving error on server side. Here is the error I receive from server;

**"Error on publishVideo: {\"code\":406,\"message\":\"'filter' parameter wrong:Not a JSON Object: \\\"videoflip method=vertical-flip\\\". Code: 406\",\"requestTime\":1603916885097}"**

When I check the kurento code I see my error line appears here and its trying to read my command as JSON. You can see how it reads **options** from kurento code.

![image](https://user-images.githubusercontent.com/4224210/97536369-14ed8580-19ce-11eb-94c3-a8057b902cd2.png)

Also in openVidu documentation it indicates this is how I should use

https://docs.openvidu.io/en/2.15.0/advanced-features/filters/

`
const publisher = await this.OV.initPublisherAsync(undefined,
                        {
                            filter: {
                                type: "GStreamerFilter",
                                options: "videoflip method=vertical-flip"
                            }}
                        );
`

I am already receving token with filters enabled. Here is how my post request is;

![image](https://user-images.githubusercontent.com/4224210/97536879-e1f7c180-19ce-11eb-86cb-5643de78786b.png)

Any idea how I can overcome with this? Thank you

Device: Mobile Emulator - React Native
React Native Adapter - 2.15.2

**Comment by micaelgallego** [comment]
You should use this format
```
var OV = new OpenVidu();
var publisher = OV.initPublisher(
    targetElement,
    filter: {
        type: "GStreamerFilter",
        options: {
            command: "videoflip method=vertical-flip"
        }
    }
);
```
