### ISSUE TITLE
Getting ERRCONNRESET when hosting on Digital Ocean

### ISSUE THREAD

**Issue by ajay01994** [OpenVidu/openvidu#56]
I am using the openvidu-js-node tutorial. When I run it locally everything works fine even with the ssl certificates. But when I host it on digital ocean I am able to login the users publisher1,publisher2 and subscriber but after that when I try to start video session nothing happens and I get ERRCONNRESET on my node server at digital ocean.

**Comment by pabloFuente** [comment]
I don't have any experince with Digital Ocean. That error is certainly something outside OpenVidu scope. I'm afraid I cannot help you, at least with the level of detail of the error you provided.
