### ISSUE TITLE
Error when saving the recordings 

### ISSUE THREAD

**Issue by pradeepmdk** [OpenVidu/openvidu#564]
**Describe the bug**
Hi,

I tried to record but when I saved the videos the only thing saved was a black screen

![ses_A5ONcJWg3H](https://user-images.githubusercontent.com/16595846/99671509-22ab9d80-2a98-11eb-88ea-090d12e6681e.jpg)

my config:
docker run -p 4443:4443 --rm \
    -e OPENVIDU_PUBLICURL=https://192.168.43.111:4443 \
    -e  DOMAIN_OR_PUBLIC_IP=192.168.43.111\
    -e OPENVIDU_SECRET=MY_SECRET \
    -e OPENVIDU_RECORDING=true \
    -e OPENVIDU_RECORDING_PATH=/Users/Documents/media \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /Users/Documents/media:/Users/Documents/media \
openvidu/openvidu-server-kms:2.16.0

**Comment by pabloFuente** [comment]
Do not delete the issue template. To get support use OpenVidu public forum: https://openvidu.discourse.group/
