### ISSUE TITLE
stream.videoDimensions is undefined - OpenVidu Browser 2.16

### ISSUE THREAD

**Issue by melanef** [OpenVidu/openvidu#569]
**Describe the bug**
Firefox fails with an uncaught error in a promise. `stream.videoDimensions is undefined`. This happens whenever a user tries to start publishing `Session.publish()` on Firefox without a webcam available, regardless of the video options set. This is also reproducible on the current version of OpenVidu Call. Although the frontend seems to behave nicely after the error is seen on console, no audio is sent from this publisher.

**Expected behavior**
Does OpenVidu Server 2.16 require that the client browser always send the video data? If not, then OpenVidu Browser 2.16 should not send the video data when there's no webcam available. But if OpenVidu Server 2.16 requires it always, then there may be some fallback data to send when no webcam is available. Should the dimensions be 0?

**Wrong current behavior**
Currently it's trying to obtain the dimensions from the Stream object, but this object doesn't have them if it was initialized without a webcam. Although the TypeScript class predicts there will be `videoDimensions`, the compiled JavaScript version (the one actually used by the browser) only sets that if a video source is available, in which case it will then submit the initialization property `hasVideo` as true.

**OpenVidu tutorial where to replicate the error**
1. Open OpenViduCall (https://demos.openvidu.io/openvidu-call/) on Firefox on any computer without a webcam available.
2. Join the room (any room).
3. Grant access to the media devices when the browser requests it (in this case, it will be only the audio input device).
4. Click on Join
5. Watch the console logs after a few seconds.

**Client device info (if applicable)**
Describe the client device(s) or platform(s) where you are able to replicate the error. For example:
- Mozilla Firefox 83.0 (Official Build) (64bit) on Windows 10 (2004).
- Mozilla Firefox 83.0 (Official Build) (64bit) on Linux Mint 19.

**Screenshots**
https://i.imgur.com/TZpnvh9.png

**Comment by melanef** [comment]
Upon further investigation and experimenting with the compiled `Session.js`, I was able to verify that OpenVidu Server 2.16 DOES REQUIRE the parameters to be sent on that payload.

**Comment by CSantosM** [comment]
Thank you for your report @melanef . 
We have just reproduced the issue and we will fix it as soon as possible.

**Comment by melanef** [comment]
@CSantosM thank you very much, I'm experimenting here to see if it can be trivial to fix, and if that's the case, could I create a PR?

**Comment by CSantosM** [comment]
Sure, I would bet for this lines https://github.com/OpenVidu/openvidu/blob/49d15ffdd5de852f26df8d436a8b64a53dc00fdf/openvidu-browser/src/OpenVidu/Session.ts#L1209-L1212. 

Maybe the stream is undefined with the webcam disabled this would be the reason for the null pointer.

**Comment by melanef** [comment]
@CSantosM exactly what I've been experimenting with. I'm just checking that the audio actually works fine under these circumstances, if it's alright I'll submit a PR. Once again, thank you for your help here.

**Comment by melanef** [comment]
Submitted #570 to address this.

**Comment by melanef** [comment]
@CSantosM sorry for bothering, but do you have an estimation on when NPM package may be updated?
