### ISSUE TITLE
Question about the possibility of a scenario

### ISSUE THREAD

**Issue by danionescu2007** [OpenVidu/openvidu#57]
Hello and thank you for developing this awesome piece of software.
I have the following scenario. I have a teacher and the students. I need the teacher to see everyone (video and audio). I need the students to be able to choose if they want not to be visible to the other students (aka only to the teacher) or to everyone. Is this possible in any way with the openvidu software?
SImpler put: the teacher can see everyone, everyone can see only teacher.
Thank you in advance!

**Comment by micaelgallego** [comment]
Yes, in the current version of OpenVidu you can implement such logic.
Simply, in the student client side, you have to know if other student can
be seen or not. That can be implemented, for example, asking to backend
with a REST API.

On thing you have to have in mind. Right now, if a student hack your client
side JavaScript code, could circunvent such protection by simply not asking
to backend if that student can be seen for other students.

We plan to implement a feature in the future versions to avoid that this
hack can be performed. We plan to implement in such a way that backend app
is always queried by OpenVidu server when a user video is subscribed.

Regards

**Comment by danionescu2007** [comment]
Are there any ready to use implementations open or closed source, based on openvidu, which can work as described? Or is there a list maintained with available front ends which make use of openvidu?
Thank you!

**Comment by micaelgallego** [comment]
You can take a look to OpenVidu tutorials and adapt them to your needs.
There are several front ends with several use cases.

If you prefer, OpenVidu dev team offers professional services around
OpenVidu. One of the services is implement custom apps over the platform.
