### ISSUE TITLE
Remote Video not working

### ISSUE THREAD

**Issue by neosoft-jaykantj** [OpenVidu/openvidu#571]
I am trying to setup Openvidu on AWS.
I followed this [URL](https://docs.openvidu.io/en/2.16.0/deployment/deploying-aws/) 
On OpenVidu Server dashboard I made a quick test of deployment then i got issues mentioned below
![image](https://user-images.githubusercontent.com/60260227/100381947-2f079b80-3040-11eb-9963-3a837d1baeb4.png)

Did I miss something.

Hosted URL: https://ec2-13-127-154-30.ap-south-1.compute.amazonaws.com/dashboard/#/
Username: OPENVIDUAPP
Password: secret1234

It would be great if I can get to know what I missed.

**Comment by neosoft-jaykantj** [comment]
when tried to test on [main screen](https://ec2-13-127-154-30.ap-south-1.compute.amazonaws.com/#/jayk)
The remote video is not loaded , while chat and video stop are working fine but remote video is not working,
There is no error log in console
![image](https://user-images.githubusercontent.com/60260227/100382593-af7acc00-3041-11eb-9a56-a99aa3a694a1.png)

**Comment by CSantosM** [comment]
Please, use the[ OpenVidu Forum](https://openvidu.discourse.group/) for community support. 
This is just for OpenVidu related bugs
