### ISSUE TITLE
The issue for putting the correct certificate

### ISSUE THREAD

**Issue by fullstackdev96** [OpenVidu/openvidu#575]
Hello Everyone. 
Glad to post my question here.

I'm trying to start openvidu server 2.16.0 with the JAR file in my VPS. So I've tried to run the openvidu server using this command.

_```java -jar -Dopenvidu.secret=MY_SECRET -Dserver.ssl.key-store=store.jks -Dserver.ssl.key-store-password=XXX -Dserver.ssl.key-alias=XXX -Dopenvidu.recording=true -Dopenvidu.recording.autostop-timeout=10 -Dopenvidu.recording.path=/record -Dopenvidu.recording.public-access=true -Dopenvidu.publicurl=https://mydomain.com:4443  openvidu-server-2.16.0.jar```_

This command worked perfectly in 2.12.0 version. But getting error for certificate now.

Hopefully to get a correct answer quickly.

**Comment by pabloFuente** [comment]
I'm sorry, but:
1. This is not the place to open a support question like this.
2. OpenVidu team cannot provide support if not using the official deployment procedure based on Docker.

**Comment by fullstackdev96** [comment]
Thanks for answering!
Then can you provide me your answer on how to configure the SSL certificate set when I use the docker for openvidu? Also, I want to know how to set the recording options for enabling and custom layout.

Looking forward to hearing good news from your team.

Thank you!
