### ISSUE TITLE
Problem with  Microsoft Edge version 87.0.664.66

### ISSUE THREAD

**Issue by DevAly** [OpenVidu/openvidu#578]
**Describe the bug**
You can't participate to a meeting in Microsoft Edge version 87.0.664.66
a message show up "Browser Microsoft Edge (version 87.0.664.66) for Windows is not supported in OpenVidu"

**Expected behavior**
Join the meeting normaly without any messages problems
**Wrong current behavior**
A message showing saying 

"There was an error connecting to the session:
Browser Microsoft Edge (version 87.0.664.66) for Windows is not supported in OpenVidu"

**OpenVidu tutorial where to replicate the error**
This is an EXTREMELY IMPORTANT STEP. If we are able to replicate the error in any of the official [OpenVidu Tutorials](https://github.com/OpenVidu/openvidu-tutorials) or [OpenVidu Demos](https://github.com/OpenVidu), then we will be able to quickly fix it. If you are getting the error in your own application, please try to add the necessary changes to the most similar tutorial so it fails with the same error (try to keep those changes as contained as possible, so that the original tutorial maintains its integrity). Once you have an application to replicate the error, explain in detail the steps to get it like this:
1. Clone repository [...]
2. Compile the application like this [...]
3. Run OpenVidu Server like this [...]
4. Run the application like this [...]
5. Join 1 user... Publish a video stream [...]
6. See error

**OpenVidu deployment info**
How is your OpenVidu Server instance deployed when you get the bug. A couple of possible examples are listed below:
- Docker container as explained in OpenVidu tutorials, run with command `docker run ...` on macOS Catalina 10.15.1
- AWS deployment as explained in OpenVidu Docs (https://docs.openvidu.io/en/stable/deployment/deploying-aws/)

> **IMPORTANT NOTE**: please, if you think the bug might be related to OpenVidu Server side, specify here if you are also getting the error by using OpenVidu Server Demos instance. This instance is publicly available (use it only for this test, because it is not secure!!!): **URL**: `https://demos.openvidu.io:4443`, **SECRET**: `MY_SECRET`

**Client device info (if applicable)**
Describe the client device(s) or platform(s) where you are able to replicate the error. For example:
- Microsoft Edge (version 87.0.664.66) for Windows

**Screenshots**
![image](https://user-images.githubusercontent.com/45365762/102714853-ddb29b00-42d1-11eb-8f52-5b601c0f36a9.png)

**Additional context**

**Comment by micaelgallego** [comment]
The problem is solved in openvidu-browser 2.16.2 version.
