### ISSUE TITLE
OpenVidu destroys HTTP session

### ISSUE THREAD

**Issue by d01010101** [OpenVidu/openvidu#586]
**Describe the bug**
Somewhere when a video connection is done to the WebRTC client, OpenVidu invalidates the whole HTTP session and starts a new one.

**Expected behavior**
Due to the separation of concerns, OpenVidu does not invalidate what does not belong to it. Thanks to this, it can make part of different multi-purpose web applications.

**Wrong current behavior**
Destroying the state of a whole web application just because its WebRTC-related part created a video connection.

**OpenVidu tutorial where to replicate the error**
openvidu-mvc-java
remove all `HttpSession.invalidate()` methods from its source, they can be found in `LoginController.java`
add `System.out.println("sessionId=" + httpSession.getId());` at the beginning of `SessionController.joinSession()`
do not connect your camera
go to https://localhost:5000/session, enter `publisher1`, `pass`, press `Log in`, then `Join`.
the app prints a HTTP session id
go to https://localhost:5000/session in another tab, enter `publisher1`, `pass`, press `Log in`, then `Join`.
the app prints a new HTTP session id, the previous session is gone

**Comment by micaelgallego** [comment]
Please report your suggestion about tutorials in the openvidu-tutorials repository.

**Comment by d01010101** [comment]
This has nothing to do with the tutorial. I wrote about the tutorial only to show a test case. As seen in the report, all `HttpSession.invalidate()` have been deleted from the tutorial's source. Despite that, OpenVidu closes somewhere the session.

**Comment by micaelgallego** [comment]
Sorry, I miss read your issue.

But... What session is closed? OpenVidu can manage its session whatever it needs without affecting the applications session, right?

**Comment by d01010101** [comment]
Thanks, Micael. I appreciate the simplicity of OpenVidu's API and hope to resolve the problem.

I know that OpenVidu has its own session and that my web application has a HTTP sessions, and that these are different things. The problem here is that OpenVidu probably invalidates my app's HTTP session when it closes its own video session. I suppose that it is so because I recreated the problem using the tutorial example. It is despite that I removed all attempts to invalidate the session by the tutorial itself. So, unless I am missing something, HTTP session invalidation happens somewhere in OpenVidu sources.

If you wish, I can send you the modified tutorial source or do some debugging.

**Comment by d01010101** [comment]
It looks like the old session is not invalidated, but the browser produces a lot of new HTTP sessions. New tab = new HTTP session. It is not a problem with my browser, because other web apps work correctly and it only happens when OpenVidu recycles its own video session. If this part of the application is commented out, a new tab has the same HTTP session id as the previous one, as expected.

**Comment by d01010101** [comment]
The OpenVidu tutorial (and in effect, my app) had session timeouts set to 300 seconds. I am sorry, I did not know Spring at the time.
