### ISSUE TITLE
v2.16 missing server data

### ISSUE THREAD

**Issue by sachin-sinngh** [OpenVidu/openvidu#594]
In 2.16 version, the Connection.connectionProperties does not contain the "data" parameter passed to it in Session.createConnection. Previously this data was accessible in serverData property of Connection.

Below is the output of Session.activeConnections, here connectionProperties is missing the "data" field, the data is accessible at client side (browser) from Connection.data but not at server side.
[
  {
    "publishers": [],
    "subscribers": [],
    "connectionId": "con_EESibzJSps",
    "status": "active",
    "createdAt": 1610301263129,
    "activeAt": 1610301263888,
    "location": "unknown",
    "platform": "Chrome 83.0.4103.116 on Linux 64-bit",
    "clientData": "",
    "token": "wss://ovdev.uxarmylabs.com?sessionId=2mS4qe7LT&token=tok_YTSnX1tQmUlvFAW1&role=MODERATOR&version=2.16.0&coturnIp=18.141.229.230&turnUsername=KUVUFR&turnCredential=ejyloz",
    "connectionProperties": {
      "type": "WEBRTC",
      "record": true,
      "role": "MODERATOR",
      "kurentoOptions": null,
      "rtspUri": null,
      "adaptativeBitrate": null,
      "onlyPlayWithSubscribers": null,
      "networkCache": null
    },
    "role": "MODERATOR"
  }
]

**Comment by semmel** [comment]
Seems to be a bug in openvidu-node-client.

Until fixed one could fallback on the [REST API](https://docs.openvidu.io/en/2.16.0/reference-docs/REST-API/#get-openviduapisessionsltsession_idgtconnectionltconnection_idgt). Here (v.2.16) the field `serverData` is populated properly:
```json
{
         "id":"con_WICz8jyP3M",
         "object":"connection",
         "status":"pending",
         "connectionId":"con_WICz8jyP3M",
         "sessionId":"de2evisisoft2edummy2eapp2123001",
         "createdAt":1610388764574,
         "type":"WEBRTC",
         "record":true,
         "role":"PUBLISHER",
         "kurentoOptions":null,
         "rtspUri":null,
         "adaptativeBitrate":null,
         "onlyPlayWithSubscribers":null,
         "networkCache":null,
         "serverData":"{\"isForScreenSharing\":true,\"peerId\":\"de.visisoft.dummy.app!#001!5ff9e41d562c4\",\"customAuthorisationData\":\"Kjeld/Chrome\"}",
         "token":"wss://webrtc.blabla.de?sessionId=de2evisisoft2edummy2eapp2123001&token=tok_QeSM2Noll4lgsUnd&role=PUBLISHER&version=2.16.0&coturnIp=webrtc.blabla.de&turnUsername=JW0QLD&turnCredential=sglfpl",
         "activeAt":null,
         "location":null,
         "platform":null,
         "clientData":null,
         "publishers":null,
         "subscribers":null
      }
```

Is openvidu-browser [Connection.data](https://docs.openvidu.io/en/2.16.0/api/openvidu-browser/classes/connection.html#data) also affected?

**Comment by sachin-sinngh** [comment]
No, in browser, Connection.data is populated correctly

**Comment by pabloFuente** [comment]
Hello. This is a bug in openvidu-node-client, which is currently fixed in the master branch. You can compile this version with these simple commands:

```
git clone https://github.com/OpenVidu/openvidu.git
cd openvidu/openvidu-node-client
npm install
npm run build
```

To then install it in your local NPM repository: `npm link`
After installed, to use it in your Node app, run this comand in the project's root folder: `npm link openvidu-node-client`

**Comment by semmel** [comment]
@pabloFuente Thanks a lot! 
New version works fine! 🍾
