### ISSUE TITLE
how to capture session.publish error 

### ISSUE THREAD

**Issue by chinarui-na** [OpenVidu/openvidu#597]
## how to capture session.publish error 
```
session.publish(publisher).then(res=>{}).catch(err=>{})
```
catch can not capture, when ice failure

**Comment by pabloFuente** [comment]
Briefly answering your question, ICE failures are currently not considered a direct error of method `Session.publish`. You can still handle them accessing the interal RTCPeerConnection object of Stream: https://docs.openvidu.io/en/latest/api/openvidu-browser/classes/stream.html#getrtcpeerconnection
