### ISSUE TITLE
Publishing screenshare and camera stream in the same session

### ISSUE THREAD

**Issue by dustgrinder** [OpenVidu/openvidu#60]
I need, as a Publisher, to publish both a camera video and a screensharing video at the same time.

Here is what I have tried:
```
let publisher = OV.initPublisher('video-container');
session.publish(publisher);

let screenPublisher = OV.initPublisher('video-container', {
    videoSource: 'screen'
});
session.publish(screenPublisher);
```

If I only try to publish **one** of the them, they both work normally (individually). Otherwise, I get error like these:

```
TypeError: "stream.getWebRtcPeer(...) is undefined"
recvIceCandidatehttp://localhost:9000/assets/javascripts/openvidu-browser-2.0.0.js:7247:13
```
```
uncaught exception: Error on publishVideo: {"code":-1,"message":"org.kurento.client.internal.server.KurentoServerException:Endpoint already negotiated (Code:40208, Type:null, Data: {\"type\":\"SDP_END_POINT_ALREADY_NEGOTIATED\"})","data":"org.kurento.client.internal.server.KurentoServerException: Endpoint already negotiated (Code:40208, Type:null, Data: {\"type\":\"SDP_END_POINT_ALREADY_NEGOTIATED\"})\n\tat org.kurento.client.internal.transport.jsonrpc.RomClientJsonRpcClient.sendRequest(RomClientJsonRpcClient.java:264)\n\tat org.kurento.client.internal.transport.jsonrpc.RomClientJsonRpcClient.invoke(RomClientJsonRpcClient.java:117)\n\tat org.kurento.client.internal.transport.jsonrpc.RomClientJsonRpcClient.invoke(RomClientJsonRpcClient.java:99)\n\tat org.kurento.client.internal.client.RomManager.invoke(RomManager.java:157)\n\tat org.kurento.client.internal.client.RemoteObject.invoke(RemoteObject.java:186)\n\tat org.kurento.client.internal.client.RemoteObjectInvocationHandler.invoke(RemoteObjectInvocationHandler.java:160)\n\tat org.kurento.client.internal.client.RemoteObjectInvocationHandler.internalInvoke(RemoteObjectInvocationHandler.java:129)\n\tat org.kurento.client.internal.client.DefaultInvocationHandler.invoke(DefaultInvocationHandler.java:39)\n\tat com.sun.proxy.$Proxy103.processOffer(Unknown Source)\n\tat io.openvidu.server.kurento.endpoint.MediaEndpoint.processOffer(MediaEndpoint.java:354)\n\tat io.openvidu.server.kurento.endpoint.PublisherEndpoint.publish(PublisherEndpoint.java:124)\n\tat io.openvidu.server.kurento.core.KurentoParticipant.publishToRoom(KurentoParticipant.java:212)\n\tat io.openvidu.server.kurento.core.KurentoSessionManager.publishVideo(KurentoSessionManager.java:239)\n\tat io.openvidu.server.rpc.RpcHandler.publishVideo(RpcHandler.java:219)\n\tat io.openvidu.server.rpc.RpcHandler.handleRequest(RpcHandler.java:107)\n\tat org.kurento.jsonrpc.internal.JsonRpcHandlerManager.handleRequest(JsonRpcHandlerManager.java:128)\n\tat org.kurento.jsonrpc.internal.server.ProtocolManager$3.run(ProtocolManager.java:218)\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\n\tat java.lang.Thread.run(Thread.java:748)\n","requestTime":1527132575001}
```

How should I do this instead? Thank you!

**Comment by micaelgallego** [comment]
OpenVidu currently doesn't support publishing multiple streams per user. 

There is a ugly hack that you can use until it is available. You can have two OpenVidu connections to the same session in the same browser and publish with both of them. In that way, you simulate two users in the session publishing two streams. It is not the better solution, but it works.

Please vote here if you are interested in #61

**Comment by dustgrinder** [comment]
@micaelgallego I am deeply sorry for the trouble, but would you mind clarifying the hack you mentioned a little for me? I'm not very knowledgeable of OpenVidu yet, so the terminologies escape me. I tried these way...

```
//get two tokens token1 and token2 from the Java back-end

let session1 = OV.initSession();
session1.connect(token1, data1)
.then(() => {
    let publisher1 = OV.initPublisher(...);
    session1.publish(publisher1);
});

let session2 = OV.initSession();
session2.connect(token2, data2)
.then(() => {
    let publisher2 = OV.initPublisher(...); // the one with videoSource: 'screen'
    session2.publish(publisher2);
});
```
But then I get an error like this:
```
InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable
```
How should I be implementing what you recommended? Thank you very much for your patience.

**Comment by micaelgallego** [comment]
Try this

```
//get two tokens token1 and token2 from the Java back-end

let OV1 = new OpenVidu();
let session1 = OV1.initSession();
session1.connect(token1, data1)
.then(() => {
    let publisher1 = OV1.initPublisher(...);
    session1.publish(publisher1);
});

let OV2 = new OpenVidu();
let session2 = OV2.initSession();
session2.connect(token2, data2)
.then(() => {
    let publisher2 = OV2.initPublisher(...); // the one with videoSource: 'screen'
    session2.publish(publisher2);
});
```

**Comment by t3mnikov** [comment]
I found this [example code](http://jsfiddle.net/oyabqd0j/) to switch between the camera or screen (checked it in Firefox). But I do not know how to apply it in conjunction with [openvidu-browser](https://github.com/OpenVidu/openvidu/tree/master/openvidu-browser/static/js).

**Comment by pabloFuente** [comment]
Regarding this last message from @t3mnikov , you can easily change between publishers for the same user wothout leaving the session like this:

```typescript
// You have an 'oldPublisher' publishing to the session and want to change it for a new one with different properties
var newPublisher = OV.initPublisher(
    'my-div-where-to-insert-the-video-element',
    myNewPublisherProperties,
);
newPublisher.once('accessAllowed', () => {
    // Here you already now that the user has given any necessary permissions.
    // You can proceed to unpublish the old publisher and publish the new one.
    // This way, for example, if a user is publishing the webcam and calls this method to change it for a screen-share, 
    // the rest of users will still see his webcam until the user selects the desired window to share, which
    // usually will take a few seconds. This way no ugly black video will be received by the subscribers while
    // the screen stream is sent to everybody
    session.unpublish(oldPublisher);
    session.publish(newPublisher);
});
```

**Comment by t3mnikov** [comment]
Hurrah! It is working! Thanks a lot.

**Comment by t3mnikov** [comment]
OK!
It does work in FireFox, but I don't see a window with the choice of the window to broadcast in Chrome.
Part of my code based on @pabloFuente code :
```

    var OV;
    var session;
    var publisher;
    var localRecorder;

    OV = new OpenVidu();
    OV.setAdvancedConfiguration({
        screenShareChromeExtension: "https://chrome.google.com/webstore/detail/not_relevant/cbphanggbafoobneklcoekioolbijejh"

    });
    session = OV.initSession();
...


    var myNewPublisherProperties = {
        videoSource: 'screen',
        mirror: false,
    };

    var newPublisher = OV.initPublisher(
        'screen2',
        myNewPublisherProperties,
        function(error) {
            if (error.name == 'SCREEN_EXTENSION_NOT_INSTALLED') {
                //showWarning(error.message);
                console.log('not installed...');

                // showWarning could show a button with href 'error.message',
                // so the user can navigate to install the extension.
                // A browser refresh is also needed after installation

            } else if (error.name == 'SCREEN_SHARING_NOT_SUPPORTED') {
                alert('Your browser does not support screen sharing');
            } else if (error.name == 'SCREEN_EXTENSION_DISABLED') {
                alert('You need to enable screen sharing extension');
            } else if (error.name == 'SCREEN_CAPTURE_DENIED') {
                alert('You need to choose a window or application to share');
            }
        }
    );
....

 $('.switch-w').on('click', function () {


        newPublisher.once('accessAllowed', () => {
            // Here you already now that the user has given any necessary permissions.
            // You can proceed to unpublish the old publisher and publish the new one.
            // This way, for example, if a user is publishing the webcam and calls this method to change it for a screen-share,
            // the rest of users will still see his webcam until the user selects the desired window to share, which
            // usually will take a few seconds. This way we minimize the time the subscribers will receive no video
            // until the screen stream is sent to everybody
            session.unpublish(publisher);
            session.publish(newPublisher);

        });
    });
```
![image](https://user-images.githubusercontent.com/11781965/43700403-1fec4610-995b-11e8-99fc-e329c14d8ccf.png)

manifest.json
![image](https://user-images.githubusercontent.com/11781965/43700545-b2b5ceee-995b-11e8-840e-de104ee52711.png)


When loading a page in FireFox, a window appears indicating the window that will be broadcast. Chrome doesn't have that. No errors there.I have an SSL certificate configured on the test domain. And Chrome trusts me.
What am I doing wrong?

**Comment by t3mnikov** [comment]
My "brilliant" solution - set variable "publisher" with videoSource property 'screen' and newPublisher is 'camera'. It's work!

**Comment by Shion093** [comment]
How to handle the streams on the subscribers' side? How to know if one if for the screen and the other for the camera?

**Comment by micaelgallego** [comment]
Every stream is like a different connections. Simply use "user1-camera" and "user1-screen" for connection id.

**Comment by Shion093** [comment]
Sorry to bother you, but how can I accomplish that? just a little sample of code would be enough

**Comment by micaelgallego** [comment]
Take a look to this section in the doc:

https://openvidu.io/docs/how-do-i/share-data/

**Comment by AngeSohone** [comment]
Hi need to stream canvas but local video for remote user append on canvas instead of stream of canvas element. below code that i used (PS: whiteboard element is not a video element)

               var FRAME_RATE = 10
                var iframe = document.getElementById("iframe")
                var doc = iframe.contentDocument || iframe.contentWindow.document
                var canvas = doc.getElementById('canvas')

                OV.getUserMedia({
                audioSource: false,
                videoSource: undefined,
                resolution: '931.5x780',
                frameRate: FRAME_RATE
                })
                .then(mediaStream => {

                var videoTrack = mediaStream.getVideoTracks()[0]
                var video = doc.getElementById('whiteboard')
                video.srcObject = new MediaStream([videoTrack])
                video.loop = true
                video.muted = true

                var ctx = canvas.getContext('2d')
             
                video.addEventListener('play', () => {
                    var loop = () => {
                    if (!video.paused && !video.ended) {
                        ctx.drawImage(video, 0, 0, 300, 170);
                        setTimeout(loop, 1000/ FRAME_RATE); // Drawing at 10 fps
                    }
                    };
                    loop();
                });

                video.play()

                var whiteBoard = canvas.captureStream(FRAME_RATE).getVideoTracks()[0]
                var publisherWhiteboard = OV.initPublisher(
                "stream-whiteboard",
                {
                    audioSource: false,
                    videoSource: whiteBoard
                });
                    sessionWhiteboard.publish(publisherWhiteboard)
                    console.log('Start Stream of Whiteboard')
                })

**Comment by Flamenco** [comment]
> Take a look to this section in the doc:
> 
> https://openvidu.io/docs/how-do-i/share-data/

This link is broken.

**Comment by micaelgallego** [comment]
Here is its new home:

https://docs.openvidu.io/en/2.16.0/cheatsheet/share-data/
