### ISSUE TITLE
Add a way to update connection data property

### ISSUE THREAD

**Issue by alecpl** [OpenVidu/openvidu#601]
I know this is not really a bug, but this is a lack of an important feature.

When initializing a connection I can set `data` property. However, I don't see a way to update it afterwards. I think this is essential.

Let's consider I want to store a nickname for the user in there (the documentation mentions this use-case, but this could be any metadata). After a while user is changing his nickname. Other users that connected to the session after it happened will not see the change (they will get the initial value).

A solution I'm looking for is an additional `data` parameter in the REST API's connection modification request.

Of course, preferably this would be available in the free version.

**Comment by pabloFuente** [comment]
Hi,

Currently there's no way of updating the `data` property of Conneciton objects. Nonetheless the method you are referring to already exists in the Pro tier: [Modify a Connection](https://docs.openvidu.io/en/2.16.0/reference-docs/REST-API/#patch-openviduapisessionsltsession_idgtconnectionltconnection_idgt), but it does not allow updating `data` property yet.

**Comment by alecpl** [comment]
Just want to note that your browser app has the same issue I was talking about. I didn't use it recently, but I remember it was something like:

1. Set a nickname when joining the room to "Test Name"
2. In the room change the nickname to "Real Name"
3. Join as another user and see the other connection is described as "Test Name".

So, imho your own app could make use of this missing API.

**Comment by pabloFuente** [comment]
Which browser app are you refering to? 

Regards.

**Comment by alecpl** [comment]
OpenVidu-call. I see that in the recent version it's fixed with use of `signal:nicknameChanged` signal. I'd say it is a workaround.
