### ISSUE TITLE
204 No media Nodes available yet a token can still be created

### ISSUE THREAD

**Issue by GarvanD** [OpenVidu/openvidu#602]
**Describe the bug**
A few words describing what the bug is.

When requesting a token to a session sometimes under high use scenarios a token is returned but when attempting to join using the token a 204: No media nodes error is returned

**Expected behavior**

When no media nodes are available a token should not be able to be generated

**Wrong current behavior**
A clear and concise description of what is actually happening instead of the expected behavior.

A token is produced to the session but is useless as the session returns a 204

**OpenVidu tutorial where to replicate the error**
This is an EXTREMELY IMPORTANT STEP. If we are able to replicate the error in any of the official [OpenVidu Tutorials](https://github.com/OpenVidu/openvidu-tutorials) or [OpenVidu Demos](https://github.com/OpenVidu), then we will be able to quickly fix it. If you are getting the error in your own application, please try to add the necessary changes to the most similar tutorial so it fails with the same error (try to keep those changes as contained as possible, so that the original tutorial maintains its integrity). Once you have an application to replicate the error, explain in detail the steps to get it like this:
1. Clone repository [...]
2. Compile the application like this [...]
3. Run OpenVidu Server like this [...]
4. Run the application like this [...]
5. Join 1 user... Publish a video stream [...]
6. See error

**OpenVidu deployment info**
How is your OpenVidu Server instance deployed when you get the bug. A couple of possible examples are listed below:
- Docker container as explained in OpenVidu tutorials, run with command `docker run ...` on macOS Catalina 10.15.1
- AWS deployment as explained in OpenVidu Docs (https://docs.openvidu.io/en/stable/deployment/deploying-aws/)

On Premise - OV version 2.16.0

> **IMPORTANT NOTE**: please, if you think the bug might be related to OpenVidu Server side, specify here if you are also getting the error by using OpenVidu Server Demos instance. This instance is publicly available (use it only for this test, because it is not secure!!!): **URL**: `https://demos.openvidu.io:4443`, **SECRET**: `MY_SECRET`

**Client device info (if applicable)**
Describe the client device(s) or platform(s) where you are able to replicate the error. For example:
- Chrome 78.0.3904.97 (Official Build) (64-bit) on Windows 10 (1903).
- Firefox Mobile 68.2.0 running on OnePlus 6 with Android 9.

Chrome (not OS dependent, can be recreated from POSTMAN given a broken OV)

**Screenshots**

**Additional context**
Add any other context about the problem here. For example, attach any useful logs related to the issue.

This only seems to happen when the CPU usage averages over 80% but there is no easy way to recreate this issue.

**Comment by pabloFuente** [comment]
Hello,

This is the current expected behavior. Session and tokens generation do not depend on the availablity of Media Nodes. They are mere logical operations that do not depend on the status of the cluster. This is a topic that is complex and could be discussed: if we must return a different response if there are no Media Nodes available, why not also warn about a high CPU load even if a Media Node is available? Why not warn if the expected size of the recently created Session is expected to grow until overflowing the Media Node capacity? This is why OpenVidu takes the simplest approach and that's the reason for decoupling the Session/Token logic from the Media Node availability.

Best regards.

**Comment by GarvanD** [comment]
Thanks for the explanation, that makes sense. I assume this information could be accessed directly at the Kurento level.
