### ISSUE TITLE
Microsoft Edge (version 88.0.705.62) for Windows is not supported in OpenVidu

### ISSUE THREAD

**Issue by Jayce53** [OpenVidu/openvidu#606]
**Describe the bug**
There was an error connecting to the session: undefined Browser Microsoft Edge (version 88.0.705.62) for Windows is not supported in OpenVidu

**Expected behavior**
I expected the latest version of Edge to be supported

**Wrong current behavior**
Console error: "There was an error connecting to the session: undefined Browser Microsoft Edge (version 88.0.705.62) for Windows is not supported in OpenVidu"

**OpenVidu tutorial where to replicate the error**
1. https://demos.openvidu.io/basic-videoconference/
2. Click "Join"
3. Look at console for error

**Comment by pabloFuente** [comment]
https://github.com/OpenVidu/openvidu/issues/578
