### ISSUE TITLE
[ov-browser] On some browsers, stream.getMediaStream() is not set for a moment.

### ISSUE THREAD

**Issue by Flamenco** [OpenVidu/openvidu#608]
**Describe the bug**
After subscribing to a publisher the mediaStream is not set for 1-2 seconds sometimes.  I am managing the video content myself.

It would be better to get an event from the subscriber object instead of polling as I do in the workaround posted at the end of this report.

**Expected behavior**
I expect the mediastream to be a valid object, or have a callback that will contain the object.

**Wrong current behavior**
The mediastream is null for 1-2 seconds, and I need to poll.

**OpenVidu tutorial where to replicate the error**
Intermittent issue....

**OpenVidu deployment info**
OpenVidu-Browser 2.16 and 2.17-beta

**Additional context**
Workaround. In this example, I do not emit my `created` event until the mediastream is available.

It would be better to get an event from the subscriber object.

```js
          let subscriber = await myOv.session.subscribe(stream, undefined) as any;

          // On ChromeBook, the mediaStream is not set for at least 1000 milliseconds
          let timer = setInterval(() => {
            if (subscriber.stream.getMediaStream()) {
              if (timer) {
                clearInterval(timer)
                timer = null
                this.$emit('created', {streamManager: subscriber})
              }
            }
            else{
              console.log('Waiting for media stream...')
            }
            // })
          }, 100)
```

**Comment by pabloFuente** [comment]
Use [Session#subscribeAsync](https://docs.openvidu.io/en/stable/api/openvidu-browser/classes/session.html#subscribeasync) instead
