### ISSUE TITLE
AWS Cloudformation stuck on WaitCondition

### ISSUE THREAD

**Issue by sn0lan-stardio** [OpenVidu/openvidu#611]
Every time I try to use cloud formation to deploy openVidu it gets stuck on the WaitCondition and fails. I have followed OpenVidu Docs and have tried several different instance types, but none seem to finish the deployment.

![image](https://user-images.githubusercontent.com/75323984/110214117-fecf6480-7e9a-11eb-9e7b-58ae81448f08.png)

eventually it bombs out to this: 
![image](https://user-images.githubusercontent.com/75323984/110214455-74880000-7e9c-11eb-85ff-3b21ac2fb846.png)

This is from the logs: 

![image](https://user-images.githubusercontent.com/75323984/110214652-828a5080-7e9d-11eb-8368-92d9378c02bc.png)
![image](https://user-images.githubusercontent.com/75323984/110214673-946bf380-7e9d-11eb-88c5-4da8f38a1068.png)

**Comment by pabloFuente** [comment]
GitHub issues is only for reporting bugs. To get support use OpenVidu public forum: https://openvidu.discourse.group/
