### ISSUE TITLE
Bug changing own certificates

### ISSUE THREAD

**Issue by VaporMontey** [OpenVidu/openvidu#620]
**Describe the bug**
Openvidu continues to use the old certificates even though they have been replaced.

**Expected behavior**

1. Stop Openvidu
2. Change the certificates in /opt/openvidu/owncert
3. Start Openvidu

or

1. Change the certificates in /opt/openvidu/owncert
2. Restart Openvidu

**Wrong current behavior**
I have to do this procedure to change the certificates every time:

1. Stop Openvidu
2. Edit .env and set `CERTIFICATE_TYPE` anything other that `owncert`, for example I usually set `selfsigned`
3. Start Openvidu
4. Stop Openvidu
5. Change the certificates in /opt/openvidu/owncert (In my case the have the same name as before)
6. Edit .env and set `CERTIFICATE_TYPE` as `owncert`
7. Start Openvidu

**OpenVidu tutorial where to replicate the error**
Starting with Openvidu already configured to use owncert:

1. Stop Openvidu
2. Change the certificates in /opt/openvidu/owncert
3. Start Openvidu

You can now see the cerficates were not changed.

**OpenVidu deployment info**
Openvidu deployed on premises using the installation script

Openvidu 2.17.0
Kurento 6.16.0

**Client device info (if applicable)**
-

**Screenshots**
-

**Additional context**
As I remember this bug is present from version 2.15.0 of Openvidu.

**Comment by micaelgallego** [comment]
Thank you for reporting. 

We will take a look to your issue.

**Comment by cruizba** [comment]
If you remove /opt/openvidu/certificates, all the certificates living in /opt/openvidu/owncert will be copied. In this way you don't need to change anything in the .env file.

Do you consider a better solution if the certificates are replaced all the times the nginx container starts?

**Comment by VaporMontey** [comment]
Hi,

Thanks for the responses.

> Do you consider a better solution if the certificates are replaced all the times the nginx container starts?

I think it would be a nice improvement in certificates changing process.

**Comment by maxaptus** [comment]
Any workaround for someone like us who are still running same version due to certain requirements?
