### ISSUE TITLE
error to display remote participant voice and video android app

### ISSUE THREAD

**Issue by aaaaaaaaaali** [OpenVidu/openvidu#622]
hi all.
i have an boring issue .
i have downloaded openvidu-android native android app from openvidu site and i have compiled and run into android studio.
every thing is good and it hasnt reports any error. and my server is "https://demos.openvidu.io". but in createing forexample a session between two android devices any device can captures its camera and sound and surfaceview for other participants 
 is created and participant name is shown. but they cant receiving participants video and sound. 
please guide me.
thank you.
![Capture](https://user-images.githubusercontent.com/83222384/116813944-aef3dd80-ab6b-11eb-939c-2fbbfc49f293.JPG)

**Comment by micaelgallego** [comment]
Have you tested the official android tutorial?

https://docs.openvidu.io/en/2.17.0/tutorials/openvidu-android/

**Comment by aaaaaaaaaali** [comment]
hello and thank u very much micaelgallego.
yes i have downloaded the openvidu-android from "https://github.com/OpenVidu/openvidu-tutorials.git" and tested it.
but unfortunatly it dosnt work. please help me.

**Comment by CSantosM** [comment]
Our fault @aaaaaaaaaali , 

The source code on master branch includes a refactoring for the new OpenVidu release and it won't work with the current 2.17.0 version. 

Please, check out the commit https://github.com/OpenVidu/openvidu-tutorials/tree/0752d4edcccc979d8c62b9b9fe4b86f70d6d7568 and test again. 

Sorry for the inconveniences.

**Comment by aaaaaaaaaali** [comment]
thank u Carlos Santos you have helped me very much and my have solved my
problem 🌷🌹🌺🌻🌸
