### ISSUE TITLE
videoTrack dosnt render anything on SurfaceViewRenderer Android App

### ISSUE THREAD

**Issue by aaaaaaaaaali** [OpenVidu/openvidu#626]
hi all
im using openvidu 2.17.0 media server and android app that deployed via openvido.io. 
when set server ip as "https://demos.openvidu.io" the application works fine and any problem occured.
but when set server ip as my server ip that runs  openvidu 2.17.0 the application works and onicecondidate and ontrack event is called but SurfaceViewRenderer dosnt show remote client voice and sound.
also i have installed openvidu 2.17.0 on ubuntu 18.04 bionic via "docker run -p 4443:4443 --rm -e OPENVIDU_SECRET=MY_SECRET -e DOMAIN_OR_PUBLIC_IP=YOUR_OPENVIDU_IP openvidu/openvidu-server-kms:2.17.0" command.
 please hep me.
thanku

![Capture](https://user-images.githubusercontent.com/83222384/117565279-9a609980-b0c5-11eb-9ac3-dc61f431da86.JPG)

**Comment by pabloFuente** [comment]
Closing for not complying with the issue template.
