### ISSUE TITLE
Browser Safari (version 14.1.1) for OS X is not supported in OpenVidu

### ISSUE THREAD

**Issue by robertvb** [OpenVidu/openvidu#636]
**Describe the bug**
Cannot join video session using custom device emulating Safari 14.1.4 on google chrome. a message show up "There was an error connecting to the session: Browser Safari (version 14.1.1) for OS X is not supported in OpenVidu"

**Expected behavior**
I was expecting Safari v14 to be supported

**Wrong current behavior**
After selecting participant name and session on openvidu-library-angular tutorial and clicking on "join!" button, it throws an error when user agent is something like: `Mozilla/5.0 (Macintosh; Intel Mac OS X 11_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15`

**OpenVidu tutorial where to replicate the error**
openvidu-library-angular tutorial and find below reproduction steps:

1. Clone repository 
2. Run OpenVidu Server like this: `docker run -p 4443:4443 --rm -e OPENVIDU_SECRET=MY_SECRET openvidu/openvidu-server-kms:2.18.0`
3. Run the application like this: `ng serve`
4. Using chrome, add a custom device config like this: `'width: 375, height: 812, device pixel ratio: 3 and user agent string: Mozilla/5.0 (Macintosh; Intel Mac OS X 11_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.1 Safari/605.1.15'`
5. Select previous device
6. reload page and click on "join!"

**OpenVidu deployment info**
How is your OpenVidu Server instance deployed when you get the bug:
- Docker container as explained in OpenVidu tutorials, run with command `docker run -p 4443:4443 --rm -e OPENVIDU_SECRET=MY_SECRET openvidu/openvidu-server-kms:2.18.0` on windows 10.

**Client device info (if applicable)**
- Version 91.0.4472.124 (Official Build) (64-bit) on windows 10 playing with different custom device confs.

**Screenshots**
![image](https://user-images.githubusercontent.com/16294067/123401374-011f1100-d5a7-11eb-89b8-f515d1f3c7d8.png)

**Additional context **
Openvidu version: 2.18.0 (according to docker image)
Tutorial version: 2.18.0 (according to github)

And this is not really related to the issue but I would like to know how can I customize openvidu web component. I.e: changing size, colors, etc. Is there any tutorial for this you can point me to?

Thank you 👍

**Comment by pabloFuente** [comment]
If you try a real Safari browser 14.1 you will see it works fine. Last successful verification happened with Safari 14.1.1 (15611.2.7.1.6, 15611)
Seems like adding custom fake devices in Chrome mixing platforms is can throw some errors. We cannot consider this a bug, as platform verification can only be based on real devices.

**Comment by robertvb** [comment]
Makes sense, thank you for your quick reply Pablo. I have just tested it on a real device and it's working as expected.

Related to my last question: 

_And this is not really related to the issue but I would like to know how can I customize openvidu web component. I.e: changing size, colors, etc. Is there any tutorial for this you can point me to?_

Would you mind to provide some guidance on this too? 

Thank you 👍

**Comment by pabloFuente** [comment]
Please, open an entry on the public forum to get support on application development: https://openvidu.discourse.group/
