### ISSUE TITLE
method error in file PublisherEndpoint.java:356:65 and KurentoSessionManager.java:1370:64

### ISSUE THREAD

**Issue by tjdznet** [OpenVidu/openvidu#638]
**Describe the bug**
1. java: method invoke in interface org.kurento.client.GenericMediaElement cannot be applied to given types;
  required: java.lang.String,org.kurento.jsonrpc.Props
  found: java.lang.String,org.kurento.jsonrpc.Props,java.lang.Class<com.google.gson.JsonElement>
  reason: actual and formal argument lists differ in length
2. java: method addEventListener in interface org.kurento.client.GenericMediaElement cannot be applied to given types;
  required: java.lang.String,org.kurento.client.EventListener<org.kurento.client.GenericMediaEvent>
  found: java.lang.String,(event)->{[...])); },java.lang.Class<org.kurento.client.GenericMediaEvent>
  reason: actual and formal argument lists differ in length

**Screenshots**
1.
![image](https://user-images.githubusercontent.com/20569692/124298609-0a077800-db8f-11eb-898b-c294c837081a.png)

![image](https://user-images.githubusercontent.com/20569692/124298042-60c08200-db8e-11eb-9b3a-1e2ec7298baa.png)

2.
![image](https://user-images.githubusercontent.com/20569692/124298407-cca2ea80-db8e-11eb-9f9f-3ae6d4537110.png)

**Comment by pabloFuente** [comment]
For the master version of openvidu-server to work, you will need at the moment the SNAPSHOT version of kurento Java libraries.
Add this to openvidu-server POM: https://doc-kurento.readthedocs.io/en/latest/user/installation_dev.html#kurento-java-client
And update `<property>` named `<version.kurento>` to `6.16.1-SNAPSHOT` in the [parent POM](https://github.com/OpenVidu/openvidu/blob/master/pom.xml#L45).
