### ISSUE TITLE
openvidu-angular jsnlog issue

### ISSUE THREAD

**Issue by VaporMontey** [OpenVidu/openvidu#639]
**Describe the bug**
After changing from screenshare to a normal webcam there is a continuos POST failing (405) to the address of openvidu server, like `http://server.com/jsnlog.logger`. Even if it fails it will continue to send it until the page is reloaded. (See picture)

I'm sure it's caused by openvidu-angular (openvidu-browser) as the previous version 2.17.0 didn't have a dependency on jsnlog and the issue wasn't present. (See [OPENVIDU_BROWSER_LOGS](https://docs.openvidu.io/en/2.18.0/reference-docs/openvidu-config/#configuration-parameters-for-openvidu-pro))

As wrote in the documentation shouldn't this log feature be only available on Openvidu Pro deployments? Currently the issue happens using Openvidu CE

**Expected behavior**
- No log is sent from the frontend to openvidu server on CE version

Or

- Cancel the request after some failed tries

**Wrong current behavior**
The POST is sent continuosly bloating the console until it won't fail anymore or the page is reloaded

**OpenVidu tutorial where to replicate the error**

- Publish a stream using openvidu-angular with a webcam
- Switch to screen sharing
   - Unpublish the previous stream
   - Publish the new stream
- Switch to a camera
   - Unpublish the previous stream
   - Publish the new stream
- The error should start to appear

**OpenVidu deployment info**
Openvidu deployed on premises using the installation script

- Openvidu CE 2.18.0
- openvidu-angular 2.18.0

**Client device info (if applicable)**
- Chrome 91.0.4472.124 (Official Build) (64-bit) on Windows 10 (21H1).

**Screenshots**
![jsonlogerr](https://user-images.githubusercontent.com/47629585/124602318-0282f000-de69-11eb-87d9-0eaa558bacfc.PNG)

**Additional context**
openvidu-angular (openvidu-browser) is the only package I'm using to have a dependency on jsnlog

**Comment by VaporMontey** [comment]
I've just seen that some days ago was released openvidu-browser 2.18.2 (a dependency of openvidu-angular, the one that has jsnlog), but openvidu-angular still uses openvidu-browser 2.18.0. Could that version have fixed this issue?

**Comment by micaelgallego** [comment]
Thank you for reporting the issue. 

We plan to release 2.19 version next week with this issue fixed. Sorry for inconveniences.

**Comment by VaporMontey** [comment]
Hi,

Thanks for the response.

After some more digging I've found issue #631 where @cruizba states the issue was fixed on openvidu-browser 2.18.1, however I'll wait for the next update.

**Comment by micaelgallego** [comment]
Yes... it is fixed in openvidu-browser 2.18.1, but there is not a version 2.18.1 of openvidu-angular (https://www.npmjs.com/package/openvidu-angular)

Regards

**Comment by pabloFuente** [comment]
If nonetheless you want to compile openvidu-angular 2.18.1 yourself, you can do it!
These are the steps to compile openvidu-angular from scratch: https://docs.openvidu.io/en/2.18.0/developing/#compiling-openvidu-angular-library

You just need to update openvidu-browser version used by openvidu-angular project to 2.18.2 before installing dependencies and compiling it.
