### ISSUE TITLE
Close openvidu session

### ISSUE THREAD

**Issue by smialex** [OpenVidu/openvidu#64]
Hi,
I want to close the openvidu session on the server side. Is it possible?
For example:
On clien-side browser was crashed and session.disconnect() not executed. And session did not disconnect.

How can I fix it?

Thank you

**Comment by pabloFuente** [comment]
Please, do not duplicate questions here and in OpenVidu Google group. This question is answered here: https://groups.google.com/forum/m/#!msg/openvidu/hyzKMS7IzrY/PJkbJ_fFAQAJ
