### ISSUE TITLE
"mvn clean compile package" BUILD FAILURE  on project openvidu-server

### ISSUE THREAD

**Issue by shanakaperera** [OpenVidu/openvidu#641]
**Describe the bug**
"mvn clean compile package" build failure 
Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile
/home/ubuntu/openvidu/openvidu-server/src/main/java/io/openvidu/server/kurento/endpoint/PublisherEndpoint.java:[356,73] method invoke in interface org.kurento.client.GenericMediaElement cannot be applied to given types;
[ERROR]   required: java.lang.String,org.kurento.jsonrpc.Props
[ERROR]   found: java.lang.String,org.kurento.jsonrpc.Props,java.lang.Class<com.google.gson.JsonElement>
[ERROR]   reason: actual and formal argument lists differ in length
[ERROR] /home/ubuntu/openvidu/openvidu-server/src/main/java/io/openvidu/server/kurento/core/KurentoSessionManager.java:[1370,80] method addEventListener in interface org.kurento.client.GenericMediaElement cannot be applied to given types;
[ERROR]   required: java.lang.String,org.kurento.client.EventListener<org.kurento.client.GenericMediaEvent>
[ERROR]   found: java.lang.String,(event)->{[...])); },java.lang.Class<org.kurento.client.GenericMediaEvent>
[ERROR]   reason: actual and formal argument lists differ in length

**Expected behavior**
Expecting to build the cloned project successfully

**Wrong current behavior**
"mvn clean compile package" build failure 

**OpenVidu deployment info**
Just trying to build the project before deployment

**Maven Version**
Apache Maven 3.6.0

**JDK Version**
openjdk version "11.0.11" 

**OS**
Ubuntu 18.04

**Comment by cruizba** [comment]
Hi @shanakaperera , our master branch is currently using the content of a non released kurento-client version in master branch.

You need to execute this in OpenVidu directory:

```
git clone https://github.com/Kurento/kurento-java.git
cd kurento-java && MVN_VERSION=$(mvn --batch-mode -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)
cd ../openvidu && mvn --batch-mode versions:set-property -Dproperty=version.kurento -DnewVersion=$MVN_VERSION
mvn dependency:get -DrepoUrl=https://maven.openvidu.io/repository/snapshots/ -Dartifact=org.kurento:kurento-client:$MVN_VERSION
mvn dependency:get -DrepoUrl=https://maven.openvidu.io/repository/snapshots/ -Dartifact=org.kurento:kurento-jsonrpc-client-jetty:$MVN_VERSION
mvn dependency:get -DrepoUrl=https://maven.openvidu.io/repository/snapshots/ -Dartifact=org.kurento:kurento-jsonrpc-server:$MVN_VERSION
mvn dependency:get -DrepoUrl=https://maven.openvidu.io/repository/snapshots/ -Dartifact=org.kurento:kurento-test:$MVN_VERSION
cd ..
```

**Comment by shanakaperera** [comment]
Okay. Thanks.

**Comment by cruizba** [comment]
See https://github.com/OpenVidu/openvidu/issues/677#issuecomment-1023229068 if you still facing issues on fetching SNAPSHOTS dependencies from maven.openvidu.io.
