### ISSUE TITLE
Publisher.replaceTrack(audioTrack) on Chrome unmutes audio for publisher 

### ISSUE THREAD

**Issue by unicornsoftwareinc** [OpenVidu/openvidu#642]
Calling Publisher.replaceTrack(audioTrack) seems to unmute the audio for the publisher with OpenVidu version 2.18.0 in Chrome.

**Expected behavior**
I'm implementing an audio input switcher for my software. When switching the audio source, I expect the audio input to change after calling Publisher.replaceTrack(audioTrack) and the audio for the publisher to remain muted. In other words, I should NOT be hearing myself when I talk into the microphone after switching the audio input. 

This looks similar to an older issue here which was previously closed because it was supposedly fixed in newer versions. Older, possibly same, issue which was previously closed: https://github.com/OpenVidu/openvidu/issues/449

**Wrong current behavior**
After switching the audio input using replaceTrack, the audio becomes unmuted for the publisher so I can hear myself through the microphone (essentially an echo effect).

**OpenVidu tutorial where to replicate the error**
Please note: Just like in the older linked issue, I'm only encountering this issue in Chrome. Doesn't seem to be an issue in Firefox (haven't tested other browsers)

Publish an audio/video stream. Mute the video so that the publisher isn't hearing himself while talking into microphone. Then call Publisher.replaceTrack(audioTrack). Note how you can hear yourself talking into the microphone (echo effect)

**OpenVidu deployment info**
AWS deployed OpenVidu, 2.18.0 across entire codebase including browser/server/AWS install.

**Client device info (if applicable)**
Describe the client device(s) or platform(s) where you are able to replicate the error. For example:
Chrome Version 91.0.4472.114 (Official Build) (x86_64) macOS

**Comment by plorenz-etes** [comment]
I just came across this issue and confirm that this is a real problem.

**Comment by pabloFuente** [comment]
This has been fixed with commit https://github.com/OpenVidu/openvidu/commit/17ff9105aaf05f435f6247c7fa4d7eaa39daf812
