### ISSUE TITLE
Selfie camera screen flashing on mobile of huawei p30 lite

### ISSUE THREAD

**Issue by DzungLT7610** [OpenVidu/openvidu#645]
I am developing a phone call application between pc and mobile, when the app is installed on my huawei p30 lite phone, it is flashing selfie camera screen, i have tried it installed on one and the phone of samsung, xiaomi .. it's not like that. A big thank you to anyone who can help me find the cause and how to fix it.

[https://drive.google.com/file/d/16NMNHlPR5UBnRxi6pQYmwnCQ0q5qBb0y/view?usp=sharing](url)

**Comment by pabloFuente** [comment]
This must be a problem with that specific phone model. Maybe you can confirm this theory trying other applications that provide access to the camera and show the selfie camera on screen. Unfortunately we don't have such model to perform some tests on our own. There is really no solution to this problem from OpenVidu's sourcecode point of view. The client side just access the camera with standard API, and there is no difference between one phone model and another. There is not much more we can do to help in this particular case, sorry.
