### ISSUE TITLE
Browser Chrome is not supported in OpenVidu

### ISSUE THREAD

**Issue by maxifjaved** [OpenVidu/openvidu#647]
**Describe the bug**
I am not able to start the video call [Here](https://demos.openvidu.io/openvidu-call/#/initial-silver-alpaca). The popup says browser not supported.

**Expected behavior**
Should start the video call.

**Wrong current behavior**
Doesn't start the call and says *Browser Chrome (version 92.0.4515.107) for OS X is not supported in OpenVidu*

**Steps to re-product**

1. Go to this [Link](https://demos.openvidu.io/openvidu-call/#/initial-silver-alpaca)
2. Open DevTools, set the browser to desktop(touch)
3. Start the call.

**Client device info (if applicable)**
 - Chrome (version 92.0.4515.107)

**Screenshots**
![image](https://user-images.githubusercontent.com/17304812/128124566-bad6ec8a-ff65-4e44-b9d7-f6f037f70a1a.png)

**Comment by pabloFuente** [comment]
Modifying the browser description on dev tools may result in this message. Chrome on OSX works perfectly fine using a regular browser.
