### ISSUE TITLE
wss considered not secure through ip address

### ISSUE THREAD

**Issue by valkalon** [OpenVidu/openvidu#65]
Hi,
I'm currently in the process of pushing OpenVidu to a pre-production server.
I used the "Deploying OpenVidu in Ubuntu" tutorial

App,OpenVidu and KMS are on the same server.

I switched to a Let's Encrypt certificate and I cannot get the wss connection to work correctly. I keep getting the insecure certificate notification.
![selection_007](https://user-images.githubusercontent.com/7339264/40794274-f823d14c-64fe-11e8-988a-9f00108e6009.jpg)

![selection_008](https://user-images.githubusercontent.com/7339264/40794295-0aa68864-64ff-11e8-9d5d-0204c045de7b.jpg)

This makes sense to me since the Let's Encrypt certificate is bound to a domain name not an ip address.

How do you bypass this problem or what am I doing wrong?

Your help will be much appreciated.
Valkalon

**Comment by pabloFuente** [comment]
Hi:

You simply have to indicate OpenVidu Server which URL should your client-side use to connect to it. You make that with configuration property `openvidu.publicurl=https://your.domain.com`

So, when launching your OpenVidu Server, just pass that property.

Regards.

**Comment by valkalon** [comment]
Dear Pablo, thanks a lot for your quick return.

I followed your advice and updated the configuration property. It solves the security certificate issue indeed but as I feared I now face the "Everything looks alright, but I cannot see any remote video" as described in your documentation

https://openvidu.io/docs/troubleshooting/

![selection_009](https://user-images.githubusercontent.com/7339264/40802438-e5dc682a-6515-11e8-8162-9c1071d5feb5.jpg)

According to the documentation, openvidu.publicurl must be an ip address. 

![selection_010](https://user-images.githubusercontent.com/7339264/40802474-fcc544f8-6515-11e8-97fe-5a191dea1b2d.jpg)

Can you point to what I'm missing?

If it can help: I'm using Ubuntu 16.04 on a digitalocean droplet. Turn server is working as tested using trickeICE and if I bypass the security warning (when using ip based configuration) video is shared correctly.

Kind regards,
Aurélien Vabre

**Comment by pabloFuente** [comment]
If you are sure that your KMS is properly configured (and ready to use your COTURN server), this problem might be caused by any of this situations:
- Network requirements in your server side: https://openvidu.io/docs/deployment/deploying-ubuntu/#server-network-requirements
- Firewalls or NATs in your client side: if your browser is behind a complex network, you may need to configure OpenVidu Browser to use your COTURN server. Check `iceServers` property in method [OpenVidu.setAdvancedConfiguration](https://openvidu.io/api/openvidu-browser/classes/openvidu.html#setadvancedconfiguration)

**Comment by valkalon** [comment]
Dear Pablo,

thank you for your help. Based on your suggestion I found the solution.

To have it work I switched from the "openvidu-server Docker container" to the "openvidu-server executable" on the droplet using Java 1.8 and openvidu-server-2.0.0.jar.

Video is now shared correctly.

If I may make a recommendation, I got confused by the documentation saying that you "must" put an ip address for the openvidu.publicurl parameter.

Again thank you for your responsiveness. Looking forward to having OpenVidu into production!

**Comment by pabloFuente** [comment]
I will review that section of the documentation.
I'm glad your deployment worked. Please, can you tell us a little bit more about your first attempt with openvidu-server Docker container? This info would be very helpful for us:

- Name and tag of the Docker container you used
- The full `docker run ...` command you used to launch it

Thanks for the help

**Comment by valkalon** [comment]
Sure, I'm glad if I can help.

Docker image used (no tag specified): openvidu/openvidu-server-kms

full docker run command: (using domain.com as replacement from real domain)

docker run -d -p 4443:4443 --rm -v /etc/letsencrypt/live/domain.com/domain_keystore.jks:/etc/letsencrypt/live/domain.com/domain_keystore.jks:ro -e openvidu.secret=MY_SECRET -e openvidu.publicurl=https://domain.com -e server.ssl.key-store=/etc/letsencrypt/live/domain.com/domain_keystore.jks -e server.ssl.key-store-password=the_password -e server.ssl.key-alias=my_cert openvidu/openvidu-server-kms

With this command video sharing does not work. It you replace the publicurl with an IP address everything works as excepted (need to accept untrusted certificate manually of course). 

If you need further information feel free to ask. If you'd like to check the vps where everything is installed it can also be arranged, just let me know.
