### ISSUE TITLE
OPENVIDU_STREAMS_FORCED_VIDEO_CODEC=H264 doesn't work

### ISSUE THREAD

**Issue by micaelgallego** [OpenVidu/openvidu#653]
**Describe the bug**
OPENVIDU_STREAMS_FORCED_VIDEO_CODEC=H264 doesn't work. VP8 is always selected.

**Expected behavior**
OPENVIDU_STREAMS_FORCED_VIDEO_CODEC=H264 selected.

**Wrong current behavior**
OPENVIDU_STREAMS_FORCED_VIDEO_CODEC=H264 doesn't work. VP8 is always selected.

**OpenVidu tutorial where to replicate the error**
Configure OPENVIDU_STREAMS_FORCED_VIDEO_CODEC=H264 and test how VP8 is negotiated. If VP8 is disabled in KMS with 
```
"videoCodecs": [
        { "///name": "VP8/90000" },
        { "name": "H264/90000" }
    ]
```
then the app crashes because the setRemoteDescription method returns an invalid SDP.

**OpenVidu deployment info**
It is no relevant.

**Comment by j1elo** [comment]
So far, I'm not able to see the issue. tested with several combinations of web browsers and ForceCodec settings, and in all cases the SDP Offer messages are always mangled appropriately as needed, which causes the right selection of video codec.

## Chrome (on Linux)

### OPENVIDU_STREAMS_FORCED_VIDEO_CODEC=NONE

OK: Selects the codec as per the default preference order given by the web browser.

SDP Offer from browser

    m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 102 121 127 120 125 107 108 109 35 36 124 119 123
    a=rtpmap:96 VP8/90000
    a=rtpmap:98 VP9/90000
    a=rtpmap:100 VP9/90000
    a=rtpmap:102 H264/90000
    a=rtpmap:127 H264/90000
    a=rtpmap:125 H264/90000
    a=rtpmap:108 H264/90000
    a=rtpmap:35 AV1X/90000

SDP Answer from Kurento

    m=video 1 UDP/TLS/RTP/SAVPF 96 102 127 125 108
    a=rtpmap:96 VP8/90000
    a=rtpmap:102 H264/90000
    a=rtpmap:127 H264/90000
    a=rtpmap:125 H264/90000
    a=rtpmap:108 H264/90000



### OPENVIDU_STREAMS_FORCED_VIDEO_CODEC=H264

OK: Filters the SDP Offer, leaving only the desired codec.

SDP Offer from browser

    m=video 9 UDP/TLS/RTP/SAVPF 96 97
    a=rtpmap:96 VP8/90000

SDP Answer from Kurento

    m=video 1 UDP/TLS/RTP/SAVPF 96
    a=rtpmap:96 VP8/90000



### OPENVIDU_STREAMS_FORCED_VIDEO_CODEC=VP8

OK: Filters the SDP Offer, leaving only the desired codec.

SDP Offer from browser

    m=video 9 UDP/TLS/RTP/SAVPF 100 101
    a=rtpmap:100 VP8/90000
    
SDP Answer from Kurento

    m=video 1 UDP/TLS/RTP/SAVPF 100
    a=rtpmap:100 VP8/90000



## Safari (on MacOS)

### OPENVIDU_STREAMS_FORCED_VIDEO_CODEC=NONE

OK: Selects the codec as per the default preference order given by the web browser.

SDP Offer from browser

    m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 127 125 104
    a=rtpmap:96 H264/90000
    a=rtpmap:98 H264/90000
    a=rtpmap:100 VP8/90000

SDP Answer from Kurento

    m=video 1 UDP/TLS/RTP/SAVPF 96 98 100
    a=rtpmap:96 H264/90000
    a=rtpmap:98 H264/90000
    a=rtpmap:100 VP8/90000



### OPENVIDU_STREAMS_FORCED_VIDEO_CODEC=H264

OK: Filters the SDP Offer, leaving only the desired codec.

SDP Offer from browser

    m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99
    a=rtpmap:96 H264/90000
    a=rtpmap:98 H264/90000

SDP Answer from Kurento

    m=video 1 UDP/TLS/RTP/SAVPF 96 98
    a=rtpmap:96 H264/90000
    a=rtpmap:98 H264/90000



### OPENVIDU_STREAMS_FORCED_VIDEO_CODEC=VP8

OK: Filters the SDP Offer, leaving only the desired codec.

SDP Offer from browser

    m=video 9 UDP/TLS/RTP/SAVPF 100 101
    a=rtpmap:100 VP8/90000

SDP Answer from Kurento

    m=video 1 UDP/TLS/RTP/SAVPF 100
    a=rtpmap:100 VP8/90000



## Safari (on iOS 14)

### OPENVIDU_STREAMS_FORCED_VIDEO_CODEC=NONE

OK: Selects the codec as per the default preference order given by the web browser.

SDP Offer from browser

    m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99 100 101 127 125 104
    a=rtpmap:96 H264/90000
    a=rtpmap:98 H264/90000
    a=rtpmap:100 VP8/90000

SDP Answer from Kurento

    m=video 1 UDP/TLS/RTP/SAVPF 96 98 100
    a=rtpmap:96 H264/90000
    a=rtpmap:98 H264/90000
    a=rtpmap:100 VP8/90000



### OPENVIDU_STREAMS_FORCED_VIDEO_CODEC=H264

OK: Filters the SDP Offer, leaving only the desired codec.

SDP Offer from browser

    m=video 9 UDP/TLS/RTP/SAVPF 96 97 98 99
    a=rtpmap:96 H264/90000
    a=rtpmap:98 H264/90000

SDP Answer from Kurento

    m=video 1 UDP/TLS/RTP/SAVPF 96 98
    a=rtpmap:96 H264/90000
    a=rtpmap:98 H264/90000



### OPENVIDU_STREAMS_FORCED_VIDEO_CODEC=VP8

OK: Filters the SDP Offer, leaving only the desired codec.

SDP Offer from browser

    m=video 9 UDP/TLS/RTP/SAVPF 100 101
    a=rtpmap:100 VP8/90000
    
SDP Answer from Kurento

    m=video 1 UDP/TLS/RTP/SAVPF 100
    a=rtpmap:100 VP8/90000

**Comment by j1elo** [comment]
I just updated the test results (https://github.com/OpenVidu/openvidu/issues/653#issuecomment-919021096) with also successful tests done with a Swift native application.

In all cases so far, OpenVidu Server is correctly parsing and removing unwanted codecs from the incoming SDP Offer from the application.

**Comment by micaelgallego** [comment]
Yes, please close it pointing to the commit fixing the issue.
