### ISSUE TITLE
OpenVidu server jar compilation

### ISSUE THREAD

**Issue by rfazi** [OpenVidu/openvidu#654]
**Describe the bug**
Compiling openvidu-server JAR goes to error

**Expected behavior**
JAR file compiled without errors

**Wrong current behavior**
Creating the Jar file of the Openvidu-server part this error appears: 
**Error: Could not find or load main class Main Caused by: java.lang.ClassNotFoundException: Main.** 
The MANIFEST.MF file is created and configured with everything you need, including the reference to the main class. How can this error be solved?
[MANIFEST.MF.txt](https://github.com/OpenVidu/openvidu/files/7197045/MANIFEST.MF.txt)

**Comment by micaelgallego** [comment]
Have you followed official instructions?

https://github.com/OpenVidu/openvidu/issues/654

**Comment by rfazi** [comment]
Yes, we did it all over again by downloading the repo again and now it worked. Thanks anyway
