### ISSUE TITLE
Error when create multiple connections concurrently using openvidu-node-client

### ISSUE THREAD

**Issue by gr8den** [OpenVidu/openvidu#659]
**Describe the bug**
Unable create multiple connections concurrently using `openvidu-node-client`

**Expected behavior**
I can create multiple connections concurrently without errors

**Wrong current behavior**
When I try create multiple connections concurrently I get error

**OpenVidu tutorial where to replicate the error**
1. docker run -p 4443:4443 --rm -e OPENVIDU_SECRET=MY_SECRET openvidu/openvidu-server-kms:2.20.0
1. clone repo https://github.com/gr8den/openvidu_concurrent_error
1. yarn && yarn start

**Client device info (if applicable)**
* OS: macOS Big Sur 11.6, Intel CPU
* Docker version 20.10.8, build 3967b7d
* Node: v14.17.6
* OpenVidu: 2.20.0

**Logs from Node and Docker with error**
```

> start
> docker --version && node --version && node src/index.js

Docker version 20.10.8, build 3967b7d
v14.17.6
script started
Creating OV

Creating session...
(node:22263) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
Session created

Try create single connection...
Connection created

Creating connections...
Wait promises...
(node:22263) UnhandledPromiseRejectionWarning: Error: [object Object]
    at Session.handleError (/Users/gr8/sandbox/openvidu_bug/node_modules/openvidu-node-client/lib/Session.js:598:20)
    at /Users/gr8/sandbox/openvidu_bug/node_modules/openvidu-node-client/lib/Session.js:152:23
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(node:22263) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:22263) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

[Node](https://github.com/gr8den/openvidu_concurrent_error/blob/master/logs/node.log)
[Docker](https://github.com/gr8den/openvidu_concurrent_error/blob/master/logs/docker.log)

**Comment by cruizba** [comment]
Hello @gr8den 

Well, first, thank you very much for giving a repository to replicate the error.

I've researched this, and I see the error which is being in place:
```
Client network socket disconnected before secure TLS connection was established
```

This is because of the self-signed certificate used in the development image `openvidu/openvidu-server-kms`. This should not happen to you in production.

By playing around with some TLS parameters, these parameters should solve your issue:
```
const tls = require('tls');
tls.DEFAULT_MIN_VERSION = "TLSv1.2";
tls.DEFAULT_MAX_VERSION = "TLSv1.2";
```

In fact, this error can be replicated always by using:
```
const tls = require('tls');
tls.DEFAULT_MIN_VERSION = "TLSv1.3";
tls.DEFAULT_MAX_VERSION = "TLSv1.3";
```

Maybe the certificate in the image `openvidu/openvidu-server-kms` needs to be updated.
