### ISSUE TITLE
How do I know the number of subscribers in one session?

### ISSUE THREAD

**Issue by t3mnikov** [OpenVidu/openvidu#66]
Question on title. Thanks

**Comment by pabloFuente** [comment]
Hi,

Right now OpenVidu Server API REST doesn't offer a method for getting such information. In your clients users will receive every participant connected to the session (`connectionCreated` event) and every publisher in the session (`streamCreated` event). If you need the number of subscribers, you will have to implement this logic on your own in your application (for every user that successfully calls `Session.subscribe`  you will have one subscriber).

Supporting the retrieval of session information from OpenVidu Server is planned in enhancement issue #69

**Comment by t3mnikov** [comment]
Wow! However, as an option, I can try to count subscribers on the client side.
 For example: 
```
var subscribers = 0;
subscribers++;
```
But I don't like this option ;)

**Comment by pabloFuente** [comment]
OpenVidu 2.3.0 now offers in its REST API methods `GET /api/sessions` and `GET /api/sessions/<SESSION_ID>` to get information about an active session
