### ISSUE TITLE
Missing property in the answer to RPC join room message

### ISSUE THREAD

**Issue by Holograc** [OpenVidu/openvidu#662]
**Describe the bug**
When I send a RPC message to join a room, I can't access the record property in the answer to that message. 

**Expected behavior**
I expect to have access to the record property in the answer to the join room rpc message.

**Wrong current behavior**
When I use the body provided in [the documentation](https://docs.openvidu.io/en/stable/developing/rpc/#joinroom) in my rpc join room message, regardless of whether I set the recorder property in the body to true, false or if I omit it entirely, I can't get the record property in the answer. There is however some peculiar behaviour when I set the recorder property to true : the finalUserId property is no longer accessible in the answer and the result id becomes "RECORDER".

**OpenVidu deployment info**
My OpenVidu Server instance is deployed as a docker container on Ubuntu 18.04.
The bug is also present when using the OpenVidu Server Demos instance.

**Client device info (if applicable)**
Firefox 93.0 running on Windows 10.

**Additional context**
Here is the answer from the join room message in all three cases. I would appreciate if you could shed some light on what exactly is happening here.

recorder property set to false
"{\"id\":1,\"result\":{\"id\":\"con_PM0uATiB1g\",\"finalUserId\":\"543EE6F4FF03E1F0\",\"createdAt\":1633944516705,\"metadata\":\"{clientData: TestClient}\",\"value\":[],\"session\":\"TestWebcam\",\"version\":\"2.20.0\",\"mediaServer\":\"kurento\",\"coturnIp\":\"23.97.238.17\",\"turnUsername\":\"116EEN\",\"turnCredential\":\"7vi9qz\",\"sessionId\":\"d7mil4j42mod8drslaalla8rqg\"},\"jsonrpc\":\"2.0\"}"

recorder property set to true
"{\"id\":1,\"result\":{\"id\":\"RECORDER\",\"createdAt\":1633944584685,\"metadata\":\"{clientData: TestClient}\",\"value\":[],\"session\":\"TestWebcam\",\"version\":\"2.20.0\",\"mediaServer\":\"kurento\",\"coturnIp\":\"23.97.238.17\",\"turnUsername\":\"XVMZAV\",\"turnCredential\":\"n8ibbh\",\"sessionId\":\"b74d5vqthk009e04u8oblv31un\"},\"jsonrpc\":\"2.0\"}"

recorder omitted
"{\"id\":1,\"result\":{\"id\":\"con_GjU4Qvt5wP\",\"finalUserId\":\"841338B244F4364B\",\"createdAt\":1633944737104,\"metadata\":\"{clientData: TestClient}\",\"value\":[],\"session\":\"TestWebcam\",\"version\":\"2.20.0\",\"mediaServer\":\"kurento\",\"coturnIp\":\"23.97.238.17\",\"turnUsername\":\"2TRHFL\",\"turnCredential\":\"rqstya\",\"sessionId\":\"knkh2cgkp66g8gvqkejkhjob\"},\"jsonrpc\":\"2.0\"}"

**Comment by pabloFuente** [comment]
Property `record` is present in the joinRoom RPC response message.
This is a screenshot of the response using demos.openvidu.io: 

![image](https://user-images.githubusercontent.com/15049534/151211162-3ae1efab-74e6-48dd-a5dc-9acdd553a702.png)
