### ISSUE TITLE
IPCam with rtsps url: rtspUri parameter is not a valid rtsp uri

### ISSUE THREAD

**Issue by Siedlerchr** [OpenVidu/openvidu#668]
**Describe the bug**
I am trying to publish an IP camera with an rtsp**s** (notice the addtional s) URL, but it fails (Tested both node-client and REST API)

**Describe the bug**
A few words describing what the bug is.

The connection is successfully established.

**Wrong current behavior**
I receive an error:
```
The response:
{

    "timestamp": 1636734658300,
    "status": 400,
    "error": "Bad Request",
    "message": "\"rtspUri\" parameter is not a valid rtsp uri",
    "path": "/openvidu/api/sessions/office/connection"
}
```
using both the node and the REST API client.

```
curl --location --request POST 'https://video.example.com/openvidu/api/sessions/office/connection' \
--header 'Authorization: Basic  base64==' \
--header 'Content-Type: application/json' \
--data-raw '{
   "type": "IPCAM",
   "data": "Office security camera",
   "record": true,
   "rtspUri": "rtsps://video-rtsp-secure.example.com:8555/mystream",
   "adaptativeBitrate": true,
   "onlyPlayWithSubscribers": true,
   "networkCache": 2000
}'
```

The rtsps stream is working fine. I verified this using ffplay:
`ffplay rtsps://video-rtsp-secure.example.com:8555/mystream`

**OpenVidu tutorial where to replicate the error**
https://docs.openvidu.io/en/stable/advanced-features/ip-cameras/

To publish an rtsps stream:
`fmpeg -re -stream_loop -1 -i movie.mp4 -c copy -f rtsp rtsps://video-rtsp-secure.example.com:8555/mystream  `

**OpenVidu deployment info**

Docker as explained in the tutorials.
Tried to test it with the demo.openvidu.

**Client device info (if applicable)**
Not relevant. Firefox latest on mac.

**Screenshots**

**Additional context**
Add any other context about the problem here. For example, attach any useful logs related to the issue.

**Comment by pabloFuente** [comment]
The problem might be that rtsp SSL (rtsps) is not supported.
Let me provide to you a beta version of openvidu-server that supports it. I will post it here when it's ready.

**Comment by pabloFuente** [comment]
You can try **`openvidu-server:2.21.0-beta2`**

**Comment by Siedlerchr** [comment]
Thanks for the quick fix, I will test it and report back

**Comment by Siedlerchr** [comment]
Sorry for the delay. I can confirm that it works now in the beta!.
