### ISSUE TITLE
IOS - Microphone not works when we play other video in screen.

### ISSUE THREAD

**Issue by mayander30** [OpenVidu/openvidu#670]
I am testing in IOS.

The microphone stops working when we play another video for example from youtube, it is a bug from openvidu. I do not know if there is another way to make it works, I am trying to play the video in parallel with the live one for the users, but when we unmute the video, the openvidu does not capture the audio from the microphone .

**Comment by pabloFuente** [comment]
Please, properly fill the bug template as required or we won't be able to help you.

**Comment by mayander30** [comment]
the bug is simples, you can replicate it playing some video..
