### ISSUE TITLE
http://maven.openvidu.io/ appears to be down

### ISSUE THREAD

**Issue by kavanpuranik** [OpenVidu/openvidu#676]
**Describe the bug**
http://maven.openvidu.io/ appears to be down

**Expected behavior**
expected to be not down.

**Comment by CSantosM** [comment]
Thanks for your alert @kavanpuranik 
We're working on it.

**Comment by cruizba** [comment]
Hello @kavanpuranik , this is a SNAPSHOT repository of openvidu and kurento. If you are using in your pom.xml any SNAPSHOT, we recommend you to use a release version instead. We're currently making some maintenance, and it could be down some days.

**Comment by j1elo** [comment]
As mentioned in #677, we can suggest using the `--no-snapshot-updates` or `-nsu` flags for Maven, which disables the checking of latest snapshot versions.

Still, there is an actual unsolved issue here, which is that [Kurento packages are adding the Kurento snapshots server](https://github.com/Kurento/kurento-java/blob/6.16.2/kurento-parent-pom/pom.xml#L1478-L1480) to the Maven configuration. Even though this server was disabled for non-snapshot builds, the fact remains that Maven still needs to download the public manifest from the repo, thus causing a network failure error now that the repo has been taken down.

I believe the solution is that Kurento packages don't include any snapshot repository URL, and instead users should be left to add it when needed. [Kurento docs have been updated](https://doc-kurento.readthedocs.io/en/latest/user/installation_dev.html#kurento-java-client).

Unless there is some idiomatic and more correct way to include snapshots repo information in the pom.xml of a project? Then I'd like to learn about it.

But if there is none, then this looks like the way to go. It might break stuff that relied on the snapshot servers being included by default, though. But I think it's a good thing to break them and bring attention to the issue wherever is needed (such as some of our CI jobs...)

**Comment by j1elo** [comment]
Kurento Java packages v6.16.3 have been released, with the mentioned fixes. Once OpenVidu starts depending on this version, there won't be any accesses to snapshot repositories.

This doesn't solve the issue for previous versions of OpenVidu, though. I'm not sure how valuable it is that we worry about that. I think the workaround of using `mvn -nsu` is good enough until a new OpenVidu version get published.

**Comment by cruizba** [comment]
See https://github.com/OpenVidu/openvidu/issues/677#issuecomment-1023229068 if you still facing issues on fetching SNAPSHOTS dependencies from maven.openvidu.io OpenVidu < 2.18.0
