### ISSUE TITLE
events library is not added as a dependency for openvidu-browser

### ISSUE THREAD

**Issue by OrkhanAlikhanov** [OpenVidu/openvidu#679]
**Describe the bug**
openvidu-browser depends on [events](https://www.npmjs.com/package/events) npm package but it is not added as a dependency.
https://github.com/OpenVidu/openvidu/blob/4c6e388cabec87caf90aaa05e303445a72317953/openvidu-browser/src/OpenViduInternal/KurentoUtils/kurento-jsonrpc/index.js#L55

**Expected behavior**
It should be in the dependency list

**Wrong current behavior**
It's not specified as a dependency

**Additional context**
This caused the following error.
```
index.js:199 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'call')
    at new RpcBuilder (index.js:199)
    at new JsonRpcClient (jsonrpcclient.js:144)
    at OpenVidu2.startWs (OpenVidu.ts:776)
    at Session.ts:1363
    at new Promise (<anonymous>)
    at Session2.connectAux (Session.ts:1362)
    at Session.ts:183
    at new Promise (<anonymous>)
    at Session2.connect (Session.ts:172)
```

Fix is to run `npm install events`.

This won't happen in the environments where `events` library is already in `node_modules` folder (because it was required by another module). `npm list events` to find out it if that's the case. 

I am using vitejs if you ask

**Comment by pabloFuente** [comment]
This commit includes the missing packages: https://github.com/OpenVidu/openvidu/commit/0010ac11573f8a0dcf532ba6817be3e0f380cc5a

Thanks for reporting
