### ISSUE TITLE
Poor quality video recording on the server side

### ISSUE THREAD

**Issue by t3mnikov** [OpenVidu/openvidu#68]
Hello dears! 
I was able to start the video recording as an [tutorial](https://github.com/OpenVidu/openvidu-tutorials/tree/master/openvidu-recording-node)  . But the video quality is very poor. How to fix?
 I tried to do it at my laptop: i3-6006, 12Gb RAM, 240 SSD

**Comment by t3mnikov** [comment]
Thanks for your reply. Yes, I compared with the quality of the video in real time.
Soon I will try to recording on a more powerful machine.

**Comment by ggn06awu** [comment]
@pabloFuente is there any chance of upgrading from 480p at any point? It's been a long running flaw of Kurento that it couldn't be improved (i even tried breaking out my very rusty C at one point to try to influence it but the code held a deep learning curve). I also appreciate the Kurento approach historically was the mixing of streams into a file as they arrive, creating significant overheads. I've always thought perhaps capturing the streams individually and running a post processing job to combine them might have been a better architecture (less real time load, and we could even offload the job of merging and compositing the end result to another server). FWIW I'm reasonably sure that's how Opentok do things.

**Comment by micaelgallego** [comment]
You can improve the video quality with the OpenVidu API. Can you describe
more precisely what are the problems with the video quality?

Regarding to recording, it is planned to allow recording individually each
stream to be composed offline.

Best regards.

Micael Gallego
ElasTest Project Technical Coordinator - http://elastest.io
Profesor en la Escuela Técnica Superior de Ingeniería Informática URJC

**Comment by pabloFuente** [comment]
OpenVidu 2.8.0 now supports individual stream recording: https://openvidu.io/docs/advanced-features/recording/
