### ISSUE TITLE
openvidu-browser LocalRecorder crashes the Chrome tab on long recordings

### ISSUE THREAD

**Issue by lierdakil** [OpenVidu/openvidu#686]
**Describe the bug**

LocalRecorder crashes the Chrome tab on recordings lasting (in my limited testing) for 1.5 hours or longer. I can't really get many specifics, but this happens during the construction of the final blob from chunks.

**Expected behavior**

The blob is successfully constructed regardless of the length of the recording (within reason)

**Wrong current behavior**

The tab crashes.

**OpenVidu tutorial where to replicate the error**

Okay, I will eschew this part for time. Let me know if you're prepared to waste several hours in testing. The basic idea is this:

1. Prepare a publisher
2. Start local recording
3. Wait for an hour or two
4. Stop local recording
5. Wait for several minutes while the tab hangs
6. See the crashed tab

**OpenVidu deployment info**

Server-side is irrelevant. openvidu-browser v2.20.0.

**Client device info (if applicable)**

I've tested on Google Chrome Version 96.0.4664.110 (Official Build) (64-bit) on Linux.

Doesn't seem to be platform-specific, since initially this was reported by application users on Windows 10.

**Screenshots**

Unfortunately, I forgot to take any.

**Additional context**

As far as I understand, the issue happens because LocalRecorder creates a chunk every 10 ms, which after 1.5 hours ends up being more than half a million chunks, which doesn't sound very reasonable. Perhaps just increasing the chunk length to something more manageable, like 10 seconds, would improve the situation dramatically.

But to be honest, I don't understand the need to make chunks to begin with, if those will immediately be glued back together anyway. It seems more efficient to let MediaRecorder make a single chunk right away by setting chunk length to `undefined`, i.e. calling `start()` with no arguments.

I've reimplemented the local recording logic using MediaRecorder directly, without bothering with chunks, and the crash doesn't happen after 2 hours, so I'd say this is pretty strong evidence my hunch about chunks being the issue here is correct.

**Comment by pabloFuente** [comment]
Hello,
This commit should fix the issue: https://github.com/OpenVidu/openvidu/commit/4ca3839821c26c6d6552c6ea0227f75f4fbdfd2d
Could you try updating openvidu-browser to master and testing the fix in your application?
Cheers.

**Comment by pabloFuente** [comment]
I'm not an expert on the MediaRecorder object of Web API, but I think that the `timeslice` property allows storing the video in different chunks (of duration `timeslice` milliseconds) on disk, instead of having it stored in memory. This technically provides a way of never running out of memory, even for extremely long videos that could take up GiB.

**Comment by Sed9yDataBank** [comment]
Understood, thank you for the explanation ⭐
