### ISSUE TITLE
How to record local and remote videos?

### ISSUE THREAD

**Issue by githubuser05** [OpenVidu/openvidu#7]
Hi,

I'm new to OpenVidu and would like to record local and remote videos to separate files on my server where Kurento is installed.

Is this possible using OpenVidu?

Thanks in advance!

**Comment by pabloFuente** [comment]
Hi:
Right now it is not possible, but session recording is one of the scheduled features to be implemented in the following weeks. Stay tunned for incoming releases.

**Comment by pabloFuente** [comment]
Our first recording service prototype is available now under release 1.7.0. Check our updated Docs to learn more: [http://openvidu.io/docs/advanced-features/recording/](http://openvidu.io/docs/advanced-features/recording/)
