### ISSUE TITLE
Why openvidu is leaking users IP information along with all the users session to everyone?

### ISSUE THREAD

**Issue by josephmiller2000** [OpenVidu/openvidu#712]
**Describe the bug**
Openvidu is leaking all the users IP address to everyone who connect to the cams

**Expected behavior**
It should send the other events rather than sending everyone's information to everyone who joined the video broadcast in the chat room, this will cause too much load on the server and application

**Wrong current behavior**
I have a public chat room, where users broadcast their cams in a room, the cams will be visible to viewer who view any broadcasters cam. For example if 20 people are broadcasting in cam. And when we open(view) only one users cam, im getting everyone's session including ip address and information in the socket information.

**OpenVidu tutorial where to replicate the error**
1. Im, using docker for my production, i did follow your documentation to install the setup " https://docs.openvidu.io/en/stable/deployment/ce/on-premises/ "

**OpenVidu deployment info**
Docker ( ubuntu 21.04 ) version.

**Screenshots**
![Snap_Shot_03279](https://user-images.githubusercontent.com/24210340/161395537-4e773518-51f0-4603-8fad-d738024cd76e.png)

**Other Info**

OPENVIDU_WEBHOOK_EVENTS=[sessionCreated,sessionDestroyed,participantJoined,participantLeft]

**Comment by pabloFuente** [comment]
There is no leak of clients IPs. You must understand how WebRTC and ICE protocol works.
Final users won't receive the IP of other users when using OpenVidu. That's one of the consequences of using a [SFU](https://webrtcglossary.com/sfu/). The ICE candidates sent and receive by the clients will contain its own IP (of all of its networl interfaces, that's how WebRTC works) and you will also see the IP of your OpenVidu deployment (the media server is the other endpoint of the WebRTC communication). The 192.168.8.104 IP you pointed in the attached image is one of the IPs of the device running the browser, probably a local one (that's a `local` type ICE candidate).
So no, unless you are using P2P connections without a media server, your clients won't receive the public IPs of other clients.
If you want further information, the web is full of it: https://developer.mozilla.org/es/docs/Web/API/WebRTC_API/Protocols
