### ISSUE TITLE
Apply OpenVidu Filters (CE) on Android Native 

### ISSUE THREAD

**Issue by saponteindra** [OpenVidu/openvidu#728]
**Describe the bug**
I try to use the filters in android app using the example that your have in openvidu-tutorials, i want to know how can i send that because i need to use the FaceOverlay. The openVidu Server work fine and the KMS too. I tested  the filter with the openvidu-filter and this work fine too. But i don't see anything about how can send a request to apply filter in android native. 

**Expected behavior**
That the video in the android native app and the openvidu server take the faceoverlay filter. 

**Wrong current behavior**
N/A

**Comment by pabloFuente** [comment]
You must implement the RPC method in the application yourself: https://docs.openvidu.io/en/2.22.0/developing/rpc/#applyfilter

Android and iOS do not have an official OpenVidu SDK, so these applications consume the RPC protocol directly. To use the Kurento filters, you must simply implement the RPC filter methods.

**Comment by saponteindra** [comment]
> But do you have a example (java code) for user de RPC Protocol ?
