### ISSUE TITLE
How to play music from publisher to subscribers?

### ISSUE THREAD

**Issue by t3mnikov** [OpenVidu/openvidu#74]
Hello dears! 
I'm developing a system for webinars. Can you tell me how to play music before the webinar?
Thanks!

**Comment by micaelgallego** [comment]
You can use browser APIs to play music before connecting to a webinar.

Take a look to audio tag: https://www.w3schools.com/tags/tag_audio.asp

**Comment by t3mnikov** [comment]
@micaelgallego Thank you! That's a good idea.
