### ISSUE TITLE
Chrome extension not installed even after installed

### ISSUE THREAD

**Issue by maxifjaved** [OpenVidu/openvidu#75]
I have deployed my [Custom screen share chrome extenion](https://chrome.google.com/webstore/detail/contribute-cloud/gbmlmheknojbpmagkgfcjlalpmeiflko) sucessfully. I added that to my chrome browser and on screen share it ask for install the extension. My chrome extension version is 1.1.0.

**Comment by pabloFuente** [comment]
How is that "it asks for install the extension"? That depends on your JavaScript code. How are you configuring OpenVidu Browser to use your custom extension? How are you initializing your Publisher object?

Can you post your client side code, please? That way we may help you.

**Comment by maxifjaved** [comment]
Here is the client side code:

``` 
   this.OV = new OpenVidu();
   this.OV.setAdvancedConfiguration({ screenShareChromeExtension: "https://chrome.google.com/webstore/detail/contribute-cast/gbmlmheknojbpmagkgfcjlalpmeiflko" });
  ......
  ......
   let self = this;
   let lectureRecoding = self.OV.initPublisher('video-container', {
        audioSource: undefined, // The source of audio. If undefined default microphone
        videoSource: 'screen', // The source of video. If undefined default webcam
        publishAudio: true,  	// Whether you want to start publishing with your audio unmuted or not
        publishVideo: true,  	// Whether you want to start publishing with your video enabled or not
        resolution: '640x480',  // The resolution of your video
        frameRate: 30,			// The frame rate of your video
        // insertMode: 'APPEND',	// How the video is inserted in the target element 'video-container'
        mirror: false,       	// Whether to mirror your local video or not
        screen: true
      }, function (error) {
        if (error) {
          if (error.name == 'SCREEN_EXTENSION_NOT_INSTALLED') {
            alert(error.message);
          } else if (error.name == 'SCREEN_SHARING_NOT_SUPPORTED') {
            alert('Your browser does not support screen sharing');
          } else if (error.name == 'SCREEN_EXTENSION_DISABLED') {
            alert('You need to enable screen sharing extension');
          } else if (error.name == 'SCREEN_CAPTURE_DENIED') {
            alert('You need to choose a window or application to share');
          }
        } else {
          //on success logic goes here!!
        }
      });
```

It always throw an error for `SCREEN_EXTENSION_NOT_INSTALLED` and return the extension link.

**Comment by pabloFuente** [comment]
I'll look into it

**Comment by maxifjaved** [comment]
Any update on this issue?

**Comment by pabloFuente** [comment]
Well, one of the latest Chrome updates has broken this feature. [Muaz Khan extension](https://github.com/muaz-khan/Chrome-Extensions/tree/master/desktopCapture), which is the one OpenVidu extension is based on, has been updated these past weeks.

We will try to fix this ASAP. Stay tunned

**Comment by pabloFuente** [comment]
We have refactored Screen Sharing capabilities for next release (probably launching today). I have tried to use your extension, but of course it won't work and the error triggered is `SCREEN_EXTENSION_NOT_INSTALLED`.

But of course this is because property `content-scripts.matches` in your `manifest.json` file probably does not match with the URL I am using to serve my testing application: https://github.com/OpenVidu/openvidu-screen-sharing-chrome-extension/blob/master/extension/manifest.json#L17

Please, make sure this is not what is happening  to you with your extension. Make sure you accept every origin where you plan to use it. As explained **[here](https://github.com/OpenVidu/openvidu-screen-sharing-chrome-extension#how-to-test-your-extension)** you can extend that array when developing your app to allow the use of the extension in other contexts.

**Comment by pabloFuente** [comment]
Give v2.2.0 a try. We have updated Chrome Extension feature.

**Comment by Shion093** [comment]
Still doesn't work

**Comment by pabloFuente** [comment]
Let me see your `manifest.json` file of your custom Chrome extension, please.

**Comment by Shion093** [comment]
Hi man, I got it working with the extension example provided by OpenVidu, I was trying with the one I had for kurento, they are different. 

All good know, thanks!

**Comment by robin3317** [comment]
I didn't install openvidu extension in my chrome browser. But i can share all applications along with browser tab & entire screen ! 
Is Openvidu updated version doesn't need any extension ? 
And in initPulisher, callback function as third parameter return error only if i cancel from the screen share prompt.
Is there any way to detect - is extension installed before initializing publisher ? @pabloFuente

**Comment by micaelgallego** [comment]
Browser extension is not needed to share your screen using OpenVidu with recent Chrome versions
