### ISSUE TITLE
White recording on China server

### ISSUE THREAD

**Issue by vnapastiuk** [OpenVidu/openvidu#753]
Description of the issue

When we start a video recording on a server in China, the first 30 seconds of the recorded video display a white-screen. After this first 30 seconds, the recording is correct.
On another solutions with the same configuration we do not experience this issue; this happens only on a server in China.

If we empty the RAM cache, the first recording we make does not have the 30-seconds white screen; the recordings thereafter present the issue once more.

The Openvidu version is 2.20.0; Openvidu recordings version is 2.19.0-custom.

Additionally, when we start a video recording on the server in China, we have the following system error (not present in other solutions we have):
`
Sep 27 21:30:20 localhost systemd[1]: docker-e08b6cebaa9942903914158f520c8c9d0d9bdbc6a370298629272b0d875a42d3.scope: Consumed 4.082s CPU time. Sep 27 21:30:20 localhost containerd[1234147]: time="2022-09-27T21:30:20.276672410+08:00" level=info msg="shim disconnected" id=e08b6cebaa9942903914158f520c8c9d0d9bdbc6a370298629272b0d875a42d3 Sep 27 21:30:20 localhost dockerd[594949]: time="2022-09-27T21:30:20.276765144+08:00" level=info msg="ignoring event" container=e08b6cebaa9942903914158f520c8c9d0d9bdbc6a370298629272b0d875a42d3 module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete" Sep 27 21:30:20 localhost containerd[1234147]: time="2022-09-27T21:30:20.277642671+08:00" level=error msg="copy shim log" error="read /proc/self/fd/36: file already closed"
`

In the container of the video recording we have the following warning (this happens on other servers as well):
![ErrDocker-Thread](https://user-images.githubusercontent.com/62963524/192568112-1878d85b-1c1c-48a8-a8b8-c426c701b37c.png)

Here are the datas of the server in use:
![df-h](https://user-images.githubusercontent.com/62963524/192568147-d98d1970-1992-48bc-b8e4-0a9b7c9b02bf.png)

This is the RAM usage at the start of the video recording:

![free-h](https://user-images.githubusercontent.com/62963524/192568170-8f8590c1-ae08-4caa-921f-d204ffa15d95.png)

**Comment by vnapastiuk** [comment]
Any update on this? Could the problem be related to a  resource consumption problem?

**Comment by vnapastiuk** [comment]
The issue was with a request to google fonts cdn our custom layout was doing, that was causing a connection timeout

**Comment by cruizba** [comment]
Solved [here]: https://openvidu.discourse.group/t/white-screen-on-recording-china-server/4211/22
