### ISSUE TITLE
Ghost sessions in basic-videoconference

### ISSUE THREAD

**Issue by relivvius** [OpenVidu/openvidu#756]
**Describe the bug**
Ghost session stays open forever

**Expected behavior**
Opening https://demos.openvidu.io/basic-videoconference/ should not have any inactive session

**Wrong current behavior**
Ghost session are there forever https://demos.openvidu.io/basic-videoconference/ 

**OpenVidu tutorial where to replicate the error**
1. Open https://demos.openvidu.io/basic-videoconference/ 
2. See the ghosts 

**OpenVidu deployment info**
no deployement needed

**Client device info (if applicable)**
no applicable

**Screenshots**
<img width="1195" alt="image" src="https://user-images.githubusercontent.com/65466667/198320961-b881dc60-0e19-47d3-a4a9-a4accb1e2cd5.png">

**Additional context**

**Comment by pabloFuente** [comment]
Ghost participant issue has been fixed in 2.29.0
