### ISSUE TITLE
How to build my recording server in a physical machine not a docker?

### ISSUE THREAD

**Issue by yinjiaoyuan** [OpenVidu/openvidu#76]
How to build my recording server in a physical machine not a docker? Thanks!

**Comment by pabloFuente** [comment]
You cannot, at least for now. Current version of recording endpoint for OpenVidu Server requires Docker in order to run. We have planned in our roadmap extending the recording capabilities, so users can choose to record streams individually. (this will not require Docker).

Regards

**Comment by yinjiaoyuan** [comment]
How to do it about "so users can choose to record streams individually. (this will not require Docker)." ?Thanks!
