### ISSUE TITLE
Openvidu-browser gave an error when building with vite

### ISSUE THREAD

**Issue by InSooBae** [OpenVidu/openvidu#768]
**Describe the bug**

I am using openvidu-browser 2.24.0 with ```vue 3.2.37 + vite 2.9.14```.<br/>
There is some problem when it build by ```vite```. <br/>
(Works fine when run locally)

![image](https://user-images.githubusercontent.com/48831854/230866672-d06e797b-7a85-44d1-b818-a418bbfdf968.png)

**Expected behavior**

I guess ```vite```is always build ```strict-mode```, so some files(in ```KurentoUtils/**```) are giving errors.

It seems difficult to solve the problem with vite.
Because Vite cannot handle and does not support code that only runs on non-strict mode (sloppy mode). This is because Vite uses ESM and it is always strict mode inside ESM.

![image](https://user-images.githubusercontent.com/48831854/230866344-8f2f5104-ab6c-482b-aca0-3dac9b303416.png)

So I think we should make openvidu-browser build without problems in strict mode.

**before build**

![image](https://user-images.githubusercontent.com/48831854/230866584-d161f141-6175-4924-9e89-5cd0c937c716.png)

**after build**

![image](https://user-images.githubusercontent.com/48831854/230866619-2dbe72f8-963d-4709-a430-145b53cfedff.png)

The reason for the error is that there is a problem with the [default binding](https://gist.github.com/zcaceres/2a4ac91f9f42ec0ef9cd0d18e4e71262) in ```strict-mode```.

If you don't think you can solve this error, you should specify that it conflicts with vite.

**Comment by jrmi** [comment]
Since I've switched to vitejs I'm not able to use openvidu neither, I have a similar error:

![image](https://user-images.githubusercontent.com/571533/235371736-60445aa6-740e-4f80-a0ec-88919836d4bd.png)

while in dev it's working perfectly...

Do you plan to make your openvidu-browser compatible with vitejs?

**Comment by jrmi** [comment]
If someone experience the same problem I have solved it by not bundling the openvidu library with vite but I include it from a CDN and it works.

**Comment by InSooBae** [comment]
> If someone experience the same problem I have solved it by not bundling the openvidu library with vite but I include it from a CDN and it works.

Alternatively, try "npm run build --no-strict" to avoid "strict mode"
https://rollupjs.org/configuration-options/#output-strict

**Comment by CSantosM** [comment]
Hi, could you please give me access to a Vue + Vite sample project for trying to solve this issue ?

**Comment by jrmi** [comment]
By updating the vitejs framework the the latest version (from 2.2.x->4.3.x), it also solves the problem, may be it's not worth to try to solve it for old vite version...

**Comment by bum19** [comment]
> If someone experience the same problem I have solved it by not bundling the openvidu library with vite but I include it from a CDN and it works.

how can i get openvidu-cdn url?

**Comment by jrmi** [comment]
> > If someone experience the same problem I have solved it by not bundling the openvidu library with vite but I include it from a CDN and it works.
> 
> how can i get openvidu-cdn url?

Last time I searched "Openvidu cdn" with my search engine. You can found something like: https://www.jsdelivr.com/package/npm/openvidu-browser
