### ISSUE TITLE
No video and only audio when run recording docker image.

### ISSUE THREAD

**Issue by yinjiaoyuan** [OpenVidu/openvidu#77]
I clone openvidu and compile it, and go to openvidu-server/target and run the command:
java -jar \
    -Dopenvidu.recording=true \
    -Dopenvidu.recording.path=/home/yinjiaoyuan/openvidu/video \
    -Dopenvidu.recording.public-access=true \
openvidu-server-2.1.0.jar
to download the openvidu/openvidu-recording docker image and run it.
I run https://github.com/sergiopaniego/WebRTCapp for a few minutes. When I stop WebRTCapp and play the record file, it has only audio and no video.
My docker image info:
REPOSITORY                     TAG                 IMAGE ID            CREATED             SIZE
openvidu/openvidu-recording    2.1.0               c98f1db33a18        2 weeks ago         879MB

**Comment by yinjiaoyuan** [comment]
My ubuntu is 14.04 and install in MacBook Pro's VM.

**Comment by pabloFuente** [comment]
Ok, let me see if I've got your scenario right: you are running an Android app in an emulator on Android Studio in your MacBook Pro and connecting it to an Ubuntu VM running in the same machine and serving a JAR of OpenVidu Server.

And the application works OK in the emulator (you can see both video and audio in a local and a remote stream), but the recording has only audio?

**Comment by yinjiaoyuan** [comment]
I test it in the set top box (android 4.4.2, Hi3796m v100), now I test it in the android phone and the video and the audio are ok. Why no video in the set top box? Thanks.

**Comment by micaelgallego** [comment]
Maybe set top box is lacking some codecs?

Have you tried to use some standard webrtc demos with this set top box?

**Comment by yinjiaoyuan** [comment]
Yes, I get the webrtc's source from google site and build the webrtc to run is ok in the set top box. I run https://github.com/sergiopaniego/WebRTCapp sample in the set top box and the video is ok, but the   record file in the server has no video.

**Comment by yinjiaoyuan** [comment]
Today I test it on the set top box and it's ok. I'll continue to test it.Thanks.

**Comment by pabloFuente** [comment]
Closing this issue for now
