### ISSUE TITLE
/openvidu/api/recordings/start

### ISSUE THREAD

**Issue by bobby-8084** [OpenVidu/openvidu#783]
1.Recordings Api not working

https://xxxxx.com/openvidu/recordings/start

I added Authorization Headers (Basic Auth)

username:xxxxx
password:xxxxxx

and
 body is {
"session":"xxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx",
"name": "MyRecording",
"hasAudio": true,
"hasVideo": true,
"outputMode": "COMPOSED",
"recordingLayout": "CUSTOM",
"customLayout": "mySimpleLayout",
"resolution": "1280x720",
"frameRate": 25,
"shmSize": 536870912,
"ignoreFailedStreams": false,
"mediaNode": {
"id": "media_i-0c58bcdd26l11d0sd"
}
}

show this error of response
{
"timestamp": "2023-01-20T07:20:26.177+00:00",
"status": 401,
"error": "Unauthorized",
"message": "",
"path": "/openvidu/api/recordings/start"
}
Can anyone help on this plz @CSantosM @nordri @robymus @ramiel @Flamenco

**Comment by CSantosM** [comment]
No duplicate issues please
