### ISSUE TITLE
No Redis Container Installed or Started

### ISSUE THREAD

**Issue by JEAholding** [OpenVidu/openvidu#785]
**Describe the bug**
While the dashboard and login works with default admin + openvidu_secret ... When I ./openvidu starts only 5 containers installing/started, the redis-1 container is not installing or accessible. Is this normal? In one of the original installation I did in another server the redis container was accessible (at one point). CE version and on Debian 11 OS. Reason why I want to have redis is to try adding users manually by connecting to the DB that manages access. I am trying to do this to avoid compiling a new openvidu-call instance from deployment docker file.

On the coturn log I see below: 

`openvidu-coturn-1  | 0: : SQLite DB connection success: /var/lib/coturn/turndb`
`openvidu-coturn-1  | 0: : SQLite DB connection success: /var/lib/coturn/turndb`
`openvidu-coturn-1  | 0: : ERROR: `
`openvidu-coturn-1  | Could not start Prometheus collector!`
`openvidu-coturn-1  | 0: : ERROR: `
`openvidu-coturn-1  | Could not start Prometheus collector!`

 What can I do to manage users or add users on the default app that comes with deployment outside of the default admin user?

**Expected behavior**
Redis container should install and start with the stack based on the documentation 2.25, is this not the case anymore? In the Docker yaml file I do not see any information for the Redis container is this normal?  Using Basic Authentication....

**Wrong current behavior**
Redis-1 container is not starting, the docker compose logs -f redis not showing any logs. The .env has CALL_PRIVATE_ACCESS=ENABLED / Default and the openvidu file does not have any information on the logs. Again was this container remove on 2.25 ? 
 

**OpenVidu tutorial where to replicate the error**
Not able to replicate the error outside of 2 VM that current both face the same issue. Redis container like shown in the deployment documentation not loading, I am able to login with default admin user even though no Redis DB container. 

**OpenVidu deployment info**
Debian 11 both OS.
Download via `curl https://s3-eu-west-1.amazonaws.com/aws.openvidu.io/install_openvidu_latest.sh | bash`

I reinstall by deleting docker rmi and same results.

**Client device info (if applicable)**
No viewable issues with client side I am able to login with default admin user and /dashboard

**Comment by cruizba** [comment]
This is not a bug. Redis is longer needed in OpenVidu. It was removed in favor of implementing https://datatracker.ietf.org/doc/html/draft-uberti-behave-turn-rest-00

Turn credentials are unique per connection and expires after 24 hours.
