### ISSUE TITLE
openvidu-node-client large amount of console.log calls

### ISSUE THREAD

**Issue by skgith1** [OpenVidu/openvidu#791]
When running openvidu-node-client under normal operation and calling forceDisconnect() the function makes entries such as `Connection 'con_NFoHEAcyBn' closed` every time the connection is ended. Since we have many users and call this often this can generate over 10,000 console.log() lines every day. It would be nice if this could be muted. Thank you.

**Comment by pabloFuente** [comment]
We will add a method similar to [`OpenVidu.enableProdMode`](https://docs.openvidu.io/en/2.25.0/api/openvidu-browser/classes/OpenVidu.html#enableProdMode) of openvidu-browser SDK to disable all logs except error/warn level.

**Comment by skgith1** [comment]
@pabloFuente Excellent Thank you!
