### ISSUE TITLE
ScreenSharing in Chrome 69

### ISSUE THREAD

**Issue by t3mnikov** [OpenVidu/openvidu#80]
As I understand Google Chrome has banned the screen sharing through third-party applications. But there will be native support for screen display in Chrome 69. Here is [article](https://webrtchacks.com/chrome-screensharing-getdisplaymedia/). While you can use the display screen in FireFox without problems.

**Comment by pabloFuente** [comment]
We are aware of this situation, and will be great in the near future to support native screen sharing in Chrome. But right now it still needs the use of an extension.

OpenVidu Browser, while used in desktop Chrome, offers by default an extension that works on any domain. And any developer can customize it by cloning repository https://github.com/OpenVidu/openvidu-screen-sharing-chrome-extension

**Comment by t3mnikov** [comment]
@pabloFuente Thank you!
