### ISSUE TITLE
Failed to record the Rtsp video stream using INDIVIDUAL mode

### ISSUE THREAD

**Issue by eanfs** [OpenVidu/openvidu#807]
**Describe the bug**
Failed to record the Rtsp video stream using INDIVIDUAL mode

**Expected behavior**
Can use the INDIVIDUAL mode to record RTSP streams from network cameras.

**Wrong current behavior**
A clear and concise description of what is actually happening instead of the expected behavior.

**OpenVidu tutorial where to replicate the error**

1. Clone repository [git clone https://github.com/OpenVidu/openvidu-tutorials.git -b v2.27.0]
2. Add Recording source code
`
RecordingProperties properties = new RecordingProperties.Builder()
			.outputMode(Recording.OutputMode.INDIVIDUAL)
			.hasAudio(false)
			.hasVideo(true)
			.ignoreFailedStreams(true)
			.resolution("1920x1080").build();
		OV.startRecording(this.session.getSessionId(), properties);
`
3. Run the application
4. Debug OpenVidu Server code , Participant' token is always null;
<img width="1214" alt="image" src="https://github.com/OpenVidu/openvidu/assets/5432110/5c9b4924-4dea-4185-b946-b246dcf6941c">

**Comment by pabloFuente** [comment]
INDIVIDUAL recordings of RTSP IP cameras is working fine. Try this:

Run OpenVidu with recording mode enabled:

```bash
docker run -p 4443:4443 --rm -e OPENVIDU_RECORDING=true -e OPENVIDU_RECORDING_PATH=/opt/openvidu/recordings -v /var/run/docker.sock:/var/run/docker.sock -v /opt/openvidu/recordings:/opt/openvidu/recordings openvidu/openvidu-dev:2.27.0
```

Clone openvidu-ipcameras tutorial:

```bash
git clone https://github.com/OpenVidu/openvidu-tutorials.git -b v2.27.0
cd openvidu-tutorials/openvidu-ipcameras
```

Modify the openvidu-ipcameras tutorial adding these lines to `MyRestController.java` file just before **[line 144](https://github.com/OpenVidu/openvidu-tutorials/blob/master/openvidu-ipcameras/src/main/java/io/openvidu/ipcameras/MyRestController.java#L144)**:

```java
RecordingProperties properties = new RecordingProperties.Builder().outputMode(Recording.OutputMode.INDIVIDUAL).hasAudio(false).hasVideo(true).ignoreFailedStreams(true).resolution("1920x1080").build();
OV.startRecording(this.session.getSessionId(), properties);
```

Run the openvidu-ipcameras tutorial:

```bash
mvn package exec:java
```

Go to `https://localhost:8080/` and subscribe to the IP cameras. After they are visible in the browser, the recording will start. You can stop the Recording or close the Session with REST API. You will find at path `/opt/openvidu/recordings/` the ZIP file of the INDIVIDUAL recording with the 3 webm files of the 3 IP cameras of the app.
