### ISSUE TITLE
Specifying STUN servers for Kurento

### ISSUE THREAD

**Issue by tyranron** [OpenVidu/openvidu#81]
In the latest [installation instructions](https://openvidu.io/docs/deployment/deploying-ubuntu/) there is a step:

> 4. File `/etc/kurento/modules/kurento/WebRtcEndpoint.conf.ini`
> ```
> stunServerAddress=YOUR_MACHINE_PUBLIC_IP
> stunServerPort=3478
> ```

The question is:  
If Kurento and Coturn are deployed on the same machine, why Kurento can't talk to Coturn via `127.0.0.1`?
```
stunServerAddress=127.0.0.1
stunServerPort=3478
```

Is there any actual restrictions or problems with that?

**Comment by tyranron** [comment]
I suppose because Coturn should read packet address from __external interface__, not loopback. Am I right?

**Comment by t3mnikov** [comment]
Hi!
I think you need to specify the public ip

**Comment by tyranron** [comment]
@t3mnikov nope, the [installation instruction](https://openvidu.io/docs/deployment/deploying-ubuntu) is given for 1, 2 [architectures](https://openvidu.io/docs/deployment/deploying-ubuntu/#architectures). The doc is clear about that.

**Comment by tyranron** [comment]
Additional question is: why `fingerprint` was removed from Coturn settings?

> 5. File /etc/turnserver.conf
> ```
> external-ip=YOUR_MACHINE_PUBLIC_IP
> listening-port=3478
> lt-cred-mech
> max-port=65535
> min-port=49152
> pidfile="/var/run/turnserver.pid"
> realm=openvidu
> simple-log
> redis-userdb="ip=127.0.0.1 dbname=0 password=turn connect_timeout=30"
> verbose
> ```

The Coturn server config [recommends it for WebRTC](https://github.com/coturn/coturn/wiki/turnserver#webrtc-usage).

**Comment by pabloFuente** [comment]
We have performed some tests and when configuring KMS with a local IP, sometimes WebRTC connections couldn't be established. Setting it to the public IP always results in successful connections. But if you think it will behave okey in your expected user scenarios, give localhost IP a try.

Regarding [installation instructions](https://openvidu.io/docs/deployment/deploying-ubuntu/#architectures) docs, take into account that such diagram does not include a COTURN instance (it probably needs an update).

And about `fingerprint` option, yes, you are probably right. COTURN docs recommend it. Will be added again in the next release, thanks.

**Comment by tyranron** [comment]
@pabloFuente thank you. You've confirmed my doubts.

**Comment by pabloFuente** [comment]
`fingerprint` option is already added to docs.
