### ISSUE TITLE
[OV 2.28.0] OpenVidu/dashboard it is giving 404 error

### ISSUE THREAD

**Issue by ingeorgepaul** [OpenVidu/openvidu#813]
**Describe the bug**
We are trying to upgrade from OpenVidu 2.22.0 to version 2.28.0. After downloading we can successfully start the OV server. We are trying to access OpenVidu/dashboard but it is giving 404 error. It is pointing to http protocol instead of https. Same was not the case for OpenVidu 2.22.0. 

**These are the logs generated by OpenVidu 2.28.0:**

2023-07-14 07:10:09,478 DEBG 'openvidu-server' stdout output:
[INFO] 2023-07-14 07:10:09,478 [main] org.springframework.boot.web.embedded.tomcat.TomcatWebServer - Tomcat initialized with port(s): 4443 (http)
 
2023-07-14 07:10:09,499 DEBG 'openvidu-server' stdout output:
[INFO] 2023-07-14 07:10:09,498 [main] org.apache.coyote.http11.Http11NioProtocol - Initializing ProtocolHandler ["http-nio-0.0.0.0-4443"]

----------------------------------------------------
   OpenVidu is ready!
   ---------------------------
   * OpenVidu Server URL: **http:**//localhost:4443/
   * OpenVidu Dashboard: **http:**//localhost:4443/dashboard

**These are the logs for OpenVidu 2.22.0:**

2023-07-14 07:12:48,341 DEBG 'openvidu-server' stdout output:
[INFO] 2023-07-14 07:12:48,341 [main] org.springframework.boot.web.embedded.tomcat.TomcatWebServer - Tomcat initialized with port(s): 4443 (https)

2023-07-14 07:12:48,362 DEBG 'openvidu-server' stdout output:
[INFO] 2023-07-14 07:12:48,361 [main] org.apache.coyote.http11.Http11NioProtocol - Initializing ProtocolHandler ["https-jsse-nio-0.0.0.0-4443"]

----------------------------------------------------
   OpenVidu is ready!
   ---------------------------
   * OpenVidu Server URL: **https:**//localhost:4443/
   * OpenVidu Dashboard: **https:**//localhost:4443/dashboard
----------------------------------------------------

**Expected behavior**
OpenVidu server should point to https:// protocol.

**Wrong current behavior**
Server is pointing to http protocol.

**OpenVidu deployment info**
We are using docker image for OV deployment as prescribed on OV portal.

@pabloFuente @cruizba

**Comment by cruizba** [comment]
I've tested `openvidu-server-dev` and the official [OpenVidu CE deployment](https://docs.openvidu.io/en/stable/deployment/ce/on-premises/), and everything is working fine.

Are you on windows? bind port 4443 so the host can reach it. 

I'll close the issue because I see no problems.
![image](https://github.com/OpenVidu/openvidu/assets/7049047/24031906-bf5c-46c3-a083-4d58e6415cbd)
