### ISSUE TITLE
How can I implement following HA model, No documentation available also no reply from support team

### ISSUE THREAD

**Issue by Leepian** [OpenVidu/openvidu#814]
I have purchased the OpenVidu Enterprise license and purchased 3 AWS instances. How can I implement the following High Availability Openvidu Enterprise cluster with 3 Nodes? There is No documentation available in OpenVidu docs except a basic model. Also I am getting no reply from support team and its been more than a week I have email to the pro team support.

![image](https://github.com/OpenVidu/openvidu/assets/79126050/fa8af48d-5a13-43fc-aec8-476258c0e93b)

**Comment by pabloFuente** [comment]
Of course there is documentation available: 
- In AWS (using CloudFormation): https://docs.openvidu.io/en/2.28.0/deployment/enterprise/aws/#high-availability-deployment
- On Premises (wherever you want, including raw AWS EC2 instances if you want): https://docs.openvidu.io/en/2.28.0/deployment/enterprise/on-premises/#high-availability-deployment

**Comment by Leepian** [comment]
Thank you for your email. I am specifically interested in on premises deployment and in the documentation link you provided has an example of reduced version, as it states

![image](https://github.com/OpenVidu/openvidu/assets/79126050/5e17c2a1-e5c6-443d-a9c8-b6483da8e4f1)


But I need exact implementation of the following HA modal on premises: 

![image](https://github.com/OpenVidu/openvidu/assets/79126050/3027955b-0885-48ff-a381-e6815db8317e)


Waiting for your detailed reply.
