### ISSUE TITLE
Always getting Connection refused: /127.0.0.1:5443 error

### ISSUE THREAD

**Issue by Leepian** [OpenVidu/openvidu#815]
Always getting Connection refused: /127.0.0.1:5443 error on OpenVidu enterprise HA node deploying on permises. After configuring all the stuff as per documentation when I start OpenVidu Enterprise Nodes using .`/openvidu start ` this error occurs. Base service is working perfectly on other aws server instance that I have also deployed on premises. I tried installing enterprise node on different server instances but getting the same issue.

**Comment by cruizba** [comment]
This is because OpenVidu Server PRO is not being able to run, check the logs of your `openvidu-server`. Maybe there is a misconfiguration somewhere.

**Comment by cruizba** [comment]
The enterprise environment is working correctly, so I am going to close the issue.

Please reach us again or open an issue more specific with openvidu server logs if you need more help.
