### ISSUE TITLE
OV 2.29: server build instructions no longer work

### ISSUE THREAD

**Issue by juhaszp-uhu** [OpenVidu/openvidu#822]
**Describe the bug**
The instructions to build openvidu-server at https://docs.openvidu.io/en/stable/developing/#compiling-openvidu-server no longer work, there is an error about a missing dependency.

**Expected behavior**
Compiles successfully and creates the .jar

**Wrong current behavior**
There is an error at the `mvn -DskipTests=true clean install` step:
```[ERROR] Failed to execute goal on project openvidu-client: Could not resolve dependencies for project io.openvidu:openvidu-client:jar:1.1.0: The following artifacts could not be resolved: org.kurento:kurento-jsonrpc-client:jar:7.0.1-SNAPSHOT, org.kurento:kurento-jsonrpc-client-jetty:jar:7.0.1-SNAPSHOT: Could not find artifact org.kurento:kurento-jsonrpc-client:jar:7.0.1-SNAPSHOT```

**Additional context**
Looking at the build scripts in the repo, I need extra step to enable or get the snapshot version of these Kurento packages, but in the end, there is a KURENTO_SNAPSHOTS_URL variable, whose value I don't know.

So is this just an omission in the documentation, or is building from source no longer supported?

**Comment by juhaszp-uhu** [comment]
I might have found the URL at https://doc-kurento.readthedocs.io/en/latest/user/installation_dev.html , after copying ci-scripts/kurento-snapshots.xml to $HOME/.m2/settings.xml and substituting KURENTO_SNAPSHOTS_URL with the URL from that document, I was able to build openvidu-server.

Could you please confirm that this is at least approximately correct?

**Comment by pabloFuente** [comment]
Yes, 2.29.0 is actually using a snapshot version of a Kurento dependency, and for that reason the building process requires configuring **.m2** folder with this configuration: https://doc-kurento.readthedocs.io/en/latest/user/installation_dev.html#per-user-config. We will update the documentation or release a new kurento-java version ASAP to avoid this problem.
