### ISSUE TITLE
v2.2.0, Coturn, and iOS 11.4

### ISSUE THREAD

**Issue by OTTStreamingVideo** [OpenVidu/openvidu#83]
Hello,

v2.2.0 was installed with openvidu-browser-2.2.0.js using the REST API.

On an Ubuntu 16.04 server it was necessary to run an external Coturn service in addition to the latest docker openvidu-server-kms (06-28-2018) with the embedded Coturn. Perhaps I did not completely understand the instructions on https://medium.com/@openvidu/openvidu-2-2-0-turn-made-easy-9d7e145f8905, but I made sure the JavaScript code matched the form described. When the external Coturn service was stopped an ICE error displayed.
    
    Is an external STUN/TURN server required even with the docker embedded Coturn instance?

    Does the command line to start the docker container need to be changed from v2.1.0? (I tried stopping the external Coturn service and omitting the "-e KMS_STUN_IP=MYIP -e KMS_STUN_PORT=3478 -e KMS_TURN_URL=MYUSER:MYPASS@MYIP:3478" parameters with no success.)

 I do not wish to use public STUN/TURN servers, but it is not a problem to run a private instance of Coturn. However, the TURN credentials tied to a token would be preferred.

Firefox v60.0.2 on Ubuntu 16.04 worked with v2.2.0.

Firefox v61.0 on Windows 8 worked with v2.2.0.

Firefox v60.0.1 on Android v5.1.1 worked with v2.2.0.

Firefox v60.0.2 on Android v7.0 worked with v2.2.0.

Chrome v67.0.3396.87 on Ubuntu 16.04 worked with v2.2.0 and the new OpenVidu ScreenSharing extension.

Chrome v67.0.3396.99 on Windows 8 worked with v2.2.0 and the new OpenVidu ScreenSharing extension.

Chrome v67.0.3396.87 on Android v5.1.1 worked with v2.2.0.

Chrome v67.0.3396.87 on Android v7.0 worked with v2.2.0.

iOS 11.4 did not work:
    local camera video tag is not created in div
    remote video tag is created in div, but does not display
Please provide an update on iOS compatibility schedule.

Thanks,
Dean

**Comment by micaelgallego** [comment]
Hi Dean, 
We are going to focus again in Safari support the next week. Please stay tuned.

**Comment by pabloFuente** [comment]
By the way, COTURN integration into OpenVidu platform is not supported for Docker containers of OpenVidu Server, at least for now. Official support is granted for [Cloud Formation deployment](https://openvidu.io/docs/deployment/deploying-aws/) and [Ubuntu deployment](https://openvidu.io/docs/deployment/deploying-ubuntu/), only as stated in the docs.

Regards

**Comment by alexlapa** [comment]
@pabloFuente ,

Are you planning to add this functionality in next release? 
Have you configured ways to implement this? Perhaps, putting explicit turnadmin to openvidu-server container, or creating JDBC client for Coturn's Redis?

**Comment by pabloFuente** [comment]
We are planning to support a fully dockerized setup of OpenVidu platform. This will include a Docker container for COTURN server and a Docker container with a Redis database. The idea is that both will work along the dockerized versions of OpenVidu Server and Kurento Media Server.

We cannot schedule a release date for this architecture right now. It is for sure something we want to support, but there are some other features that require our attention for now.

Regards.

**Comment by OTTStreamingVideo** [comment]
Hello,

Is there an updated status on iOS compatibility and specific status information page to check?

Thanks,

Dean

**Comment by pabloFuente** [comment]
iOS is now supported through Ionic framewrok in OpenVidu 2.7.0 (https://openvidu.io/docs/tutorials/openvidu-ionic/)
