### ISSUE TITLE
Bandwidth control of WebRTC clients

### ISSUE THREAD

**Issue by olzzon** [OpenVidu/openvidu#86]
Hi,
Thanks for a great API - and the Cloudformation script for creating a KMS - WebRTC with STUN&TURN makes everything so easy, it´s really great.

I have a question:
Is it possible to set - setMaxVideoSendBandwidth and setMinVideoSendBandwidth in properties somewhere.
The logical place would be in the .initPublisher, where you already can set framerate and resolution.
But a general setting in KMS would also be fine for now.

**Comment by pabloFuente** [comment]
Hi olzzon,

Next release will bring the possibility of globally configuring the max and min bandwith managed by OpenVidu Server for each Stream. In future iterations we will study the possibility of configuring each publisher individually, and maybe bring this bandwidth control to the client side in OpenVidu Browser (this will depend on how Kurento Media Server takes dynamic variations in bandwidth for incoming WebRTC streams).

Stay tuned!

**Comment by olzzon** [comment]
That sounds great 👍 
Until then I will try and recompile the openvidu-server and set the parameters in MediaEndpoint.java

Are there anything to be aware of when doing a "mvn build" (regarding authoring the .jar on the server etc.)

**Comment by pabloFuente** [comment]
As long as you change MediaEndpoint.java with your preferred values, nothing should be change in the compilation process.

Just run `mvn clean compile package` and the generated JAR under target folder will include your changes.

**Comment by olzzon** [comment]
Thanks a lot.
I have some version problems compiling the openvidu-server-2.2.0.jar file.
In the pom.xml file it says 2.2.0 but when I compile it and upload to the server, I get a 409 error.

It´s the same error as if I do a wget with latest: 
http://builds.openvidu.io/openvidu/nightly/latest/openvidu-server-latest.jar
Everything works if I take 2.2.0 from GitHub:
https://github.com/OpenVidu/openvidu/releases/download/v2.2.0/openvidu-server-2.2.0.jar

Do you have a clue of which parameters I need to change. I have changed the "MY_SECRET" but no luck with that.

**Comment by pabloFuente** [comment]
Do you get a 409 error when calling `POST /api/sessions`?

If that is the case, it is not a problem at all. You can see [here](https://openvidu.io/docs/reference-docs/REST-API/#post-apisessions) in **HTTP responses** section that a 409 error is just simply saying that the session with `customSessionId` identifier already exists. You can call `POST /api/tokens` using that same customSessionId without any problem. It will be a valid token for the previously created `customSessionId` session.

**Comment by olzzon** [comment]
That was just the first error, below is the rest.
And the reason why I thought it had to do with the version number.

jsonrpcclient.js:172 ERROR:java.lang.RuntimeException:Request element 'hasAudio' is missing in method 'publishVideo'. CHECK THAT 'openvidu-server' AND 'openvidu-browser' SHARE THE SAME VERSION NUMBER in Request: method:publishVideo params:{"sdpOffer":"v=0\r\
_------------I removed this part of the Error, as it includes SHA keys etc. _
\r\n","doLoopback":false,"audioActive":true,"videoActive":true,"typeOfVideo":"CAMERA","frameRate":25} request:undefined
(anonymous) @ jsonrpcclient.js:172
dispatchCallback @ index.js:614
processResponse @ index.js:745
RpcBuilder.decode @ index.js:806
transportMessage @ index.js:225

**Comment by olzzon** [comment]
Yes I was using the master. I´ll check out as v2.2.0 and/or use the corresponding Openvidu-browser.

Thanks a lot for the help 👍

**Comment by olzzon** [comment]
That did the job 👍

**Comment by AngeSohone** [comment]
Hi Everyone, want to use openvidu to design one webrtc app, need to know a minimum requirement for  Server (stream and recording). want to deploy on ubuntu. and how many users can connect to session.
if someone can give me theses information, it will be great
Thanks

**Comment by t3mnikov** [comment]
Hi @AngeSohone !  I know two articles that address the performance of the  media server.
[1st](https://testrtc.com/sessions-kurento-server/) , [2nd](http://blob.tomerweller.com/free-live-streaming-in-two-hours)

**Comment by micaelgallego** [comment]
We are going to publish a new article just today with some performance
improvements we have made in OpenVidu recently. Please stay tuned to our
medium blog.
