### ISSUE TITLE
Custom messages

### ISSUE THREAD

**Issue by Stopka** [OpenVidu/openvidu#9]
I am trying to replace KurentoRooms by Openvidu in my app.  First: Nice work. It seems very promising. 
But:
1) I didn't find if and how I can send custom messages to clients over websocet connection. Is it possible? In kurento rooms there was event callback fot that purpose.
2) ooou, i am stupid and forgot the second question  during writing the first. :smile: I will ask when it comes back

**Comment by pabloFuente** [comment]
Concerning your first question, one of the following features we will add will be one method to send text messages on broadcast to all Participants in a Session, if that's what you are asking about. This will make a piece of cake implementing a chat or any custom 1-to-all message system. 
Stay tunned!

**Comment by Stopka** [comment]
Thanks. Yes, this is what i need. I need it to enable moderator switch all participant's main video window to a main speaker.
And the second question came :smile:, in kurento rooms there is event callback when participant starts speaking and when he stops. Will this be implemented. It is usefull for the same reason.

**Comment by pabloFuente** [comment]
Sure thing. This will be available in OpenVidu as well.

**Comment by Stopka** [comment]
Another questions came when implementing openvidu to our app. 
1) We wanted to add turn server to openvidu browser, but there seems to be no other way to do it without modifying the hardcoded list of stun/turn servers in included freeice module. Or is there better way?
2) During our tests clients are freezing out. Accourding to our research it seems it could happen when client is using some kind of unstable network connection, like LTE. When the client disconnects even for a second, the media stream freezes. The problem is, that I don't get any notification from video element or openvidu about this incident. The websocket connection is going on, but video is frozen. And I can't react to this by reconnecting back, becaouse I am not notified about it. Is there any chance to detect that the media stream is broken?
Gladly thank you for all patient answers.

**Comment by micaelgallego** [comment]
Please create two new separate issues in GitHub labeled as "enhancement" with that two questions as they are not available in OpenVidu right now.

**Comment by pabloFuente** [comment]
Release 1.2.0 now supports sending messages in a Session. Check [How di I?](http://openvidu.io/docs/how-do-i/send-messages/) section to learn how.

**Comment by pabloFuente** [comment]
And speaking events for Publishers are now available on release 1.3.0 (`publisherStartSpeaking` and `publisherStopSpeaking`).  It is explained on "Events" table of Session object [here](http://openvidu.io/docs/reference-docs/openvidu-browser/#session).

**Comment by Stopka** [comment]
Thanks. I will try to implement it to our app in next few days.

**Comment by kishoreas** [comment]
how to intigrate chat application in openvidu-getaroom .

**Comment by pabloFuente** [comment]
Not the place to ask. Use public forum.
