### ISSUE TITLE
The problem with the connection to the server OpenVidu

### ISSUE THREAD

**Issue by t3mnikov** [OpenVidu/openvidu#91]
Hi!
An error occurs when connecting.

My domain (e. g. **domain.site**) has Let's Encrypt certificate.

![error](https://user-images.githubusercontent.com/11781965/42637023-cfc2d9ae-85f2-11e8-847f-d671fc717da6.jpg)

I using latest version OpenVidu server: ver. 2.3.0
Here is the command I run the server on the remote machine:

`docker run -d -p 4443:4443 -e openvidu.secret=MY_SECRET -e openvidu.publicurl=https://IP-remote-server:4443 -e server.port=4443 openvidu/openvidu-server-kms`

Can you point to what I'm missing?

**Comment by pabloFuente** [comment]
Your certificate is not valid, at least from the URL you are connecting from:

ERR_CERT_AUTHORITY_INVALID usually means that the URL in the browser and the domain granted by the certificate do not match.

Try connecting to `https://YOUR_DOMAIN:4443/`. If a message appears warning about your cert, then it is not valid.

**Comment by pabloFuente** [comment]
Okey, looking at the command you used to launch openvidu-server in docker, you have not provided a valid certificate for it.

You need to pass a valid certificate to openvidu-server or every browser will complain about it. Here in the docs you have how to start openvidu-server with your certificate: https://openvidu.io/docs/deployment/custom-certificate/

**Comment by t3mnikov** [comment]
Dear Pablo, thanks a lot for your quick answer.
Did I understand correctly?
I have to take the Let's Encrypt  certificate and make it a KEYSTORE.jks?

**Comment by pabloFuente** [comment]
Exactly. Generate a JKS with your Let'sEncrypt certificate and pass it to openvidu-server on launch as explained in the docs.

**Comment by t3mnikov** [comment]
Well, I'll try and answer as will result

**Comment by t3mnikov** [comment]
You are great! It's works!

**Comment by pabloFuente** [comment]
Glad it worked. Closing this issue now
