### ISSUE TITLE
Bandwidth somehow limited to 300-400kb/s even with new max and min arguments.

### ISSUE THREAD

**Issue by olzzon** [OpenVidu/openvidu#92]
Could there be some issues regarding the bandwith parameters. Somehow the server (KMS?) limits the bandwidth?

This is the Server settings (in /usr/local/bin/openvidu-server.sh):
_java -jar -Dopenvidu.secret="xxxxxxxxxxxxxx" -Dopenvidu.recording=true -Dopenvidu.recording.public-access=False -Dopenvidu.publicurl=https://${PUBLIC_HOSTNAME}:4443 -Dserver.port=5443 -DMY_UID=$(id -u $USER) -Dopenvidu.streams.video.max-recv-bandwidth=0 -Dopenvidu.streams.video.max-send-bandwidth=0 -Dopenvidu.streams.video.min-recv-bandwidth=600 -Dopenvidu.streams.video.min-send-bandwidth=600 /opt/openvidu/openvidu-server.jar_

This is what the one end transmits: (around 1.8mb/s)
<img width="240" alt="image" src="https://user-images.githubusercontent.com/29782499/42708200-d833f2ae-86dc-11e8-892d-c1f8da365cd2.png">
And this is what the other end receives: (around 300kb/s)
<img width="631" alt="image" src="https://user-images.githubusercontent.com/29782499/42708216-eb11446c-86dc-11e8-984d-afe5dd5c9218.png">
Both machines are on 1gb/s internetconnections, with all the headroom they need.
I have also tried to set the max values to 2000 but with same result.

**Comment by pabloFuente** [comment]
I have just tested (locally, I must say) one publisher and one subscriber and my results are the following:

**PUBLISHER**
![selection_262](https://user-images.githubusercontent.com/15049534/42709252-27360da8-86e0-11e8-93ee-8bb13e467f06.png)

**SUBSCRIBER**
![selection_263](https://user-images.githubusercontent.com/15049534/42709258-2babc440-86e0-11e8-8fa7-7b41a23b849d.png)

This for the following configuration:

![selection_261](https://user-images.githubusercontent.com/15049534/42709168-ea28fd08-86df-11e8-8f0e-168f2fed3532.png)

So yeah, approximately 1.8 MB/s, both the sender and the receiver.

---

When changing the values of the properties to these ones:

![selection_266](https://user-images.githubusercontent.com/15049534/42709427-cf5b20f4-86e0-11e8-8359-68c8ed7c8c0f.png)

The bits sents and received per second change accordingly:

**PUBLISHER**
![selection_264](https://user-images.githubusercontent.com/15049534/42709449-dcbf7ae2-86e0-11e8-8613-beba408445c7.png)

**SUBSCRIBER**
![selection_265](https://user-images.githubusercontent.com/15049534/42709453-df672d12-86e0-11e8-8502-e03dd8ff72c8.png)

I will perform some more tests in depth in a real scenario on the cloud next week, but these results are pretty consistent. Let me know if you figure out something else. Have you tried your scenario in your local machine? If it behaves in a different way, then we'd have to do a little research there.

**Comment by olzzon** [comment]
I have only tried with the server on AWS

**Comment by olzzon** [comment]
Before you spend more time, I’ll double test my “Server upgrade” maybe I forgot something.
I’ll try to spin a new one up and test on that one.

**Comment by olzzon** [comment]
Have just spinned up a new Cloudformation instance, it´s still limited to 300-400kb/s.

**Comment by olzzon** [comment]
I think it could be this in the kms-core.
In kms_base_sdp_endpoint_init_sdp_handlers these 2 calls is done:
First:
kms_base_sdp_endpoint_add_handler (self, sess, "audio", gid,
            self->priv->max_audio_recv_bw))
And after that:
kms_base_sdp_endpoint_add_handler (self, sess, "video", gid,
            self->priv->max_video_recv_bw))

And in:
kms_base_sdp_endpoint_add_handler (KmsBaseSdpEndpoint * self,
    KmsSdpSession * sess, const gchar * media, gint bundle_group_id,
    guint max_recv_bw)

It calls:
if (max_recv_bw > 0) {
    kms_sdp_media_handler_add_bandwidth (handler, "AS", max_recv_bw);
  }

But kms_sdp_media_handler_add_bandwidth only sets the bandwidth, it doesn't sum it.
And as first call is Audio and after that Video, it won´t initialize Video as its Zero. (maxVideoRecvBandwidth=0)
So the overall receive bandwidth becomes max_audio_recv_bw

I´m not that much into Kurento yet, so the chances that I´m wrong is quite possible.

Best regards :)

**Comment by olzzon** [comment]
Did you try it on AWS?

**Comment by olzzon** [comment]
Did you try it on AWS.
I just pinned up the Tutorial/Demo: https://s3-eu-west-1.amazonaws.com/aws.openvidu.io/CF-OpenVidu-Demos-latest.json
And using the getaroom demo I experienced the same bandwidthlimit no matter what I set max receive and send to.

I could do something wrong. This is what I´ve changed:
In: /usr/local/bin/openvidu-server.sh
I changed the Java line to:
_java -jar -Dopenvidu.secret="MY_SECRET" -Dopenvidu.recording=true -Dopenvidu.recording.public-access=False -Dserver.ssl.enabled=false -Dopenvidu.publicurl=https://${PUBLIC_HOSTNAME}:4443 -Dserver.port=5443 -DMY_UID=$(id -u $USER) **-Dopenvidu.streams.video.max-recv-bandwidth=0 -Dopenvidu.streams.video.max-send-bandwidth=0 -Dopenvidu.streams.video.min-recv-bandwidth=600 -Dopenvidu.streams.video.min-send-bandwidth=600** /opt/openvidu/openvidu-server.jar_

**Comment by olzzon** [comment]
Looked into latest Demo/toturial, and I was still ver 2.2.0 
Compiled openvido (mvn clean compile package)
and the openvidu-browser (npm run-script browserify)
and changed the index.html "openvidu-browser" version to 2.3.0

The receive bandwidth is still limited to around 300-400kb/s.

**Comment by pabloFuente** [comment]
Hi olzzon,

We have located a bug in AWS CloufFormation template that was preventing this options to properly work. Please, can you try deploying like this [https://openvidu.io/docs/deployment/deploying-aws/](https://openvidu.io/docs/deployment/deploying-aws/) and confirm that you can in fact modify the bandwidth of your media streams?

I have also tested native deployment in Ubuntu like this [https://openvidu.io/docs/deployment/deploying-ubuntu/](https://openvidu.io/docs/deployment/deploying-ubuntu/) setting different bandwidths on ***openvidu-server-2.3.0.jar*** startup, and everything seems to work just fine.

 Looking forward to hearing from you.

**Comment by olzzon** [comment]
I still have that receive limit:
<img width="586" alt="image" src="https://user-images.githubusercontent.com/29782499/42935011-dcdff94a-8b48-11e8-8d3a-28bbe92a23be.png">

Deployed with https://openvidu.io/docs/deployment/deploying-ubuntu 
using:
https://s3-eu-west-1.amazonaws.com/aws.openvidu.io/CF-OpenVidu-latest.json

I used this one for the Client:
https://github.com/OpenVidu/openvidu/raw/master/openvidu-browser/static/js/openvidu-browser-2.3.0.js

The /usr/local/bin/openvidu-server.sh looks like this:
_#!/bin/bash

# This script will launch OpenVidu Server on your machine

PUBLIC_HOSTNAME=kaoltest1.public.tv2net.dk

OPENVIDU_OPTIONS="-Dopenvidu.secret=openviduTV2danmark "
OPENVIDU_OPTIONS+="-Dopenvidu.recording=true "
OPENVIDU_OPTIONS+="-Dopenvidu.recording.public-access=False "
OPENVIDU_OPTIONS+="-Dserver.ssl.enabled=false "
OPENVIDU_OPTIONS+="-Dopenvidu.publicurl=https://${PUBLIC_HOSTNAME}:4443 "
OPENVIDU_OPTIONS+="-Dserver.port=5443 "
OPENVIDU_OPTIONS+="-DMY_UID=$(id -u $USER) "
OPENVIDU_OPTIONS+="-Dopenvidu.recording.notification=publisher_moderator "
OPENVIDU_OPTIONS+="-Dopenvidu.streams.video.max-recv-bandwidth=0 "
OPENVIDU_OPTIONS+="-Dopenvidu.streams.video.min-recv-bandwidth=200 "
OPENVIDU_OPTIONS+="-Dopenvidu.streams.video.max-send-bandwidth=0 "
OPENVIDU_OPTIONS+="-Dopenvidu.streams.video.min-send-bandwidth=200 "

java -jar ${OPENVIDU_OPTIONS} /opt/openvidu/openvidu-server.jar_

**Comment by olzzon** [comment]
I’ll do a manual deployment of a server later today.

**Comment by pabloFuente** [comment]
If you are completely sure you're using ***openvidu-server-2.3.0.jar*** ([`wget https://github.com/OpenVidu/openvidu/releases/download/v2.3.0/openvidu-server-2.3.0.jar`](https://github.com/OpenVidu/openvidu/releases/download/v2.3.0/openvidu-server-2.3.0.jar)), then there must be something wrong with the final command launching openvidu-server.

Can you post here the exact command you are using in the end to launch openvidu-server-2.3.0.jar? You can get it by listing the running process with `ps ax | grep openvidu` once you run it. You will get the exact command finally used.

By the way, if you are making use of openvidu-server JAR, there's no need to pass property `-DMY_UID=$(id -u $USER)`

**Comment by olzzon** [comment]
I haven´t changed anything in the https://s3-eu-west-1.amazonaws.com/aws.openvidu.io/CF-OpenVidu-latest.json

29917 ?        S      0:00 /bin/bash /usr/local/bin/openvidu-server.sh
29919 ?        Sl     0:28 java -jar -Dopenvidu.secret=openviduTV2danmark -Dopenvidu.recording=true -Dopenvidu.recording.public-access=False -Dserver.ssl.enabled=false -Dopenvidu.publicurl=https://kaoltest1.public.tv2net.dk:4443 -Dserver.port=5443 -DMY_UID=0 -Dopenvidu.recording.notification=publisher_moderator -Dopenvidu.streams.video.max-recv-bandwidth=0 -Dopenvidu.streams.video.min-recv-bandwidth=200 -Dopenvidu.streams.video.max-send-bandwidth=0 -Dopenvidu.streams.video.min-send-bandwidth=200 /opt/openvidu/openvidu-server.jar
30527 pts/1    S+     0:00 grep --color=auto openvidu

**Comment by olzzon** [comment]
I haven´t changed anything in the link from s3 (https://s3-eu-west-1.amazonaws.com/aws.openvidu.io/CF-OpenVidu-latest.json)

As you can see in the previous post the /usr/local/bin/openvidu-server.sh is not changed.
I have just checked the openvidu-server.jar and done a "diff" between the one in /opt/openvidu and this one https://github.com/OpenVidu/openvidu/releases/download/v2.3.0/openvidu-server-2.3.0.jar and there´s no difference (they have also same size and same date)

The -DMY_UID=$(id -u $USER) is added by the Cloudformation deployment.

Heres the command (ps ax | grep openvidu):
_29917 ? S 0:00 /bin/bash /usr/local/bin/openvidu-server.sh
29919 ? Sl 0:28 java -jar -Dopenvidu.secret=xxxxxxxxxxxxxx -Dopenvidu.recording=true -Dopenvidu.recording.public-access=False -Dserver.ssl.enabled=false -Dopenvidu.publicurl=https://kaoltest1.public.tv2net.dk:4443 -Dserver.port=5443 -DMY_UID=0 -Dopenvidu.recording.notification=publisher_moderator -Dopenvidu.streams.video.max-recv-bandwidth=0 -Dopenvidu.streams.video.min-recv-bandwidth=200 -Dopenvidu.streams.video.max-send-bandwidth=0 -Dopenvidu.streams.video.min-send-bandwidth=200 /opt/openvidu/openvidu-server.jar
30527 pts/1 S+ 0:00 grep --color=auto openvidu_

**Comment by pabloFuente** [comment]
I just deployed OpenVidU in an EC2 AWS server following [these guidelines](https://openvidu.io/docs/deployment/deploying-ubuntu/) and using your exact command (obviously changing the publicurl):

```
wget https://github.com/OpenVidu/openvidu/releases/download/v2.3.0/openvidu-server-2.3.0.jar

java -jar -Dopenvidu.secret=SECRET -Dopenvidu.publicurl=https://URL:5443 -Dserver.port=5443 -DMY_UID=0 -Dopenvidu.recording.notification=publisher_moderator -Dopenvidu.streams.video.max-recv-bandwidth=0 -Dopenvidu.streams.video.min-recv-bandwidth=200 -Dopenvidu.streams.video.max-send-bandwidth=0 -Dopenvidu.streams.video.min-send-bandwidth=200 openvidu-server-2.3.0.jar
```
It works okey, my outgoing and incoming bandwidth in the browser reaches 1.6~1.8 MB per second.

And I have deployed again in CloudFormation with our template following [these guidelines](https://openvidu.io/docs/deployment/deploying-aws/) and it also works as expected.

I cannot really understand what's happening to you. Do you say that following exactly the instructions for deploying with CloudFormation you don't see the bandwidth rules applied in the browser? That's not really possible, I've just confirmed it works OK. Maybe your client-side where you are testing is influencing the media connection somehow.

**Comment by olzzon** [comment]
Thanks a lot.
Yes, there´s something going on, on the client side. I have startet 2 new machines (Win10) and the receive bandwidth is around 2 Mb/s.
On my Mac however something is limiting it. Tomorrow I will start up a clean Mac (with no house security) and see if that one works.

Again, Thanks a lot for the help, I will report if I find a general problem on my Mac.

**Comment by pabloFuente** [comment]
Okey, perfect. I'm closing the issue for now. If you figure something out don't hesitate to open it again

**Comment by MinhDungDo** [comment]
Hi @pabloFuente and @olzzon ,

I don't know if it's the right place to ask questions. But after going through a lot of posts, I think this post is the closest to what I need.
I would like to view the android application's bandwidth, video framerate, and video dimensions (clients- subscribers or publishers). But from what I see, kibana elasticsearch can only display the information of the server, not the subscribers or publishers. 
I would like to ask if there are any other ways or methods to achieve this. How did you display the send and receive bandwidth like the images above?
