### ISSUE TITLE
User not authorized after update openvidu-browser from v2.2.0 to v2.3.0

### ISSUE THREAD

**Issue by miguelrcDEV** [OpenVidu/openvidu#94]
After update openvidu-browser version from 2.2.0 to 2.3.0, when session.connect is launched, always get this error. See screenshot attached:
![image](https://user-images.githubusercontent.com/17248343/42751194-41fd5efa-88ea-11e8-8f2d-1b9d98450d6a.png)

I simply updated the openvidu-server + kms docker image from 2.2.0 to 2.3.0, and updated openvidu-browser version. In openvidu-node-client I have the 2.2.0.

With 2.2.0v in all of this, its working ok.

**Comment by micaelgallego** [comment]
It seems that by default MODERATOR role is set for the user. But this role
is new in 2.3.0 version.

Maybe the issue is related to that. @pablofuente will take a look to that
in a momento.

**Comment by miguelrcDEV** [comment]
Yep, I use the role "Moderator" for the first user that join to a room. If you could check this I would be very appreciatted

**Comment by pabloFuente** [comment]
That error is launched whenever the token used to connect to a Session is not valid. For example: if you initialize a session and generate one token and use that token to connect one client to the session, but then try to connect a different user with that same token, this error will be returned.

Can you explain here how is the lifecycle of your sessions? I mean: how do you create the Session in OpenVidu Server, how do you generate a token for that session in OpenVidu Server and when do you call `Session.connect(token)` on your client-side.

By the way, PUBLISHER role is the default one when genearting a token.

**Comment by miguelrcDEV** [comment]
Lifecycle is next:
- From my client, I call an endpoint on my node server, that returns token generated with openvidu-node-client package. Token data is:
```
{
    data: `{"userName": "${userName}", "role": "${role}", "participantId": "${participantId}"}`,      
    role: role
};
```

- When token is returned to client, I make a session.connect with this token.

I'm sure that from client only one request it's thrown to get token, so it's imposible that the client is reusing this token, also I'm only connect with only one participant.

**Comment by pabloFuente** [comment]
Ok, so you are using openvidu-node-client library for managing sessions in your OpenVidu Server.

Token data is irrelevant regarding this problem. You could be passing no TokenOptions at all and the result shouldn't change. Do you mind restarting your OpenVidu Server and your application and trying the connection process from scratch? If the first time connecting a user to a newly created session with a new token fails with a 401 error, then something really weird is happening. If, for the contrary, this starts happening after connecting and disconnecting some users from your sessions, then probably there's some problem with the logic of your application (you might be storing and reusing sessions or tokens that are already closed or invalid from OpenVidu Server's point of view).

Let me know when you have more information, please.

Regards

**Comment by pabloFuente** [comment]
Can you post here the output of your OpenVidu Server docker image (from the very beginning, please)

**Comment by miguelrcDEV** [comment]
I found the error. Was my mistake Pablo, sorry. The problem was that I get the server sessions, calling /api/sessions endpoint of openvidu-server, and you make some changes in this endpoint, so the problem was on my logic, and the token was generated for only one session, throwing some errors. Sorry again.

**Comment by pabloFuente** [comment]
No breaking changes were supposed to be present in release 2.3.0 compared to 2.2.0. What changes have you done in order to fix this problem?

**Comment by miguelrcDEV** [comment]
Every time I create a session I check if It's created in openvidu-server making a request to /api/sessions. In v2.2.0 api/session return an object with {items:[]}, now, as you say in release notes this structure has changed, so when i try to get items in api/session response, it fails, triggering other errors that led to the problem that I told you at the beginning.

**Comment by pabloFuente** [comment]
Okey, so in fact there are breaking changes in REST method `GET /api/sessions`. That wasn't supposed to be changed till release 3.0.0, my mistake.

I will update Release Notes of 2.3.0 warning about this.

Regards.

**Comment by pabloFuente** [comment]
Ok, so in fact there's no "official" breaking change, as before release 2.3.0 REST method `GET /api/sessions` was not documented. I suppose you discovered it in the source code and decided to use on your own.

Regards.

**Comment by AngeSohone** [comment]
After many attempt to connect , i got this error and don't know the reason, someone can explain me ?
![capture](https://user-images.githubusercontent.com/16824856/50389621-06454000-075f-11e9-91cf-db196449a9f9.png)

**Comment by piranna** [comment]
That `[object Object]` is in fact the request object, that's being used as message of the returned `Error` instance. This is useless, because it don't provide any info. It would be by far better to create the `Error` instance with a meaningful message, and set the request as an attribute of it.

**Comment by micaelgallego** [comment]
Pull Requests welcomed @piranna ;)

**Comment by piranna** [comment]
They would be (minor) back breaks, so don't think they would pick a fast
trace, aren't they? ;-)
