### ISSUE TITLE
HOW to use Kurento functions 

### ISSUE THREAD

**Issue by ajay01994** [OpenVidu/openvidu#95]
HI , 
Nice work there team . i appreciate it a lot , however i have a query on how to use kurento's function like OPEN CV , AR etc in open vidu . kindly help me out .looking forward to hear from you 

Thanks

**Comment by micaelgallego** [comment]
Right now it is possible.

If you need this feature for your commercial use case, we offer
professional services around Kurento/OpenVidu.

Regards

**Comment by ajay01994** [comment]
Thank @micaelgallego as of now we don't have any commercial use case but were just wondering around to experiment since we successfully set up open vidu in our server , so a little guidance might help us  ;)

**Comment by micaelgallego** [comment]
We would help you if OpenVidu support a way to use artificial vision
algorithms on it. But it is not yet supported.

**Comment by ajay01994** [comment]
Sure thanks ;) i am closing this issue .
